### ISSUE TITLE
[功能请求]移除不负责任的上游来源

### ISSUE THREAD

**Issue by Mosney** [privacy-protection-tools/anti-AD#10]
`https://github.com/vokins/yhosts`  

使用臭名昭著/有过黑历史的上游可能会影响到您维护的列表的纯洁性，我相信您是出于负责任的态度尽可能多的取得更全面的广告追踪域名以提供更完整的列表，但是我也同时相信看到上游使用了yhosts之后毅然抛弃使用此列表的不止我一个。

此处引用自nfz在[neoHosts](https://hosts.nfz.moe)中的一句话
> 打着去广告 Hosts 的名义吸引用户使用，然而不断屏蔽与广告无关的地址，这样做和 GFW 又有什么区别？

**Comment by Mosney** [comment]
如果不知道我在说什么，请参考：
https://github.com/vokins/yhosts/wiki/%E9%83%A8%E5%88%86%E9%97%AE%E9%A2%98%E8%AF%B4%E6%98%8E

**Comment by gentlyxu** [comment]
每次看到这样的建议，我的内心都非常的感动。谢谢你，热心的朋友！

我特别希望大家各抒己见。`anti-AD是综合著名过滤列表的广告屏蔽、隐私保护工具`，所有上游源列表都**同等的并且持续的处于考察状态**，发现夹带私货并且anti-AD无法修正的情况时，将会剔除此上游列表，不管它有多么著名，多么权威。我始终相信总有一群人，愿意靠自己的力量，创造属于心中理想的完美乌托邦。而开源让这一切成为了可能！

关于yhosts这个列表。引入yhosts之前，是经过再三考察的，如果查看anti-AD的commit log可以发现，对于yhosts，中间是经过多次反复添加删除的。我也看过不少关于这个hosts的控诉和抨击，最后经过实际论证（不言而喻，anti-AD很长一段时间都是我自己一个人在用，当然不想受别人制约，莫名其妙的屏蔽不该屏蔽的东西），发现有可塑性，才又引入了进来。至于他们wiki链接中提到的海信、一号店、探探等，早已不存在于最终输出的hosts中。所以很抱歉，暂时不能答应你的请求，在没有明确的证据之前，yhosts先作为上游列表使用。

我对anti-AD设计了黑名单和白名单机制，完全有信心驾驭和驯服任何桀骜不驯的上游列表，像一个经验丰富的猎人一样。

目前的V4版本，仍然是以依赖上游列表的方式工作的，无论减少和增加哪一个上游列表，均不能降低工作的复杂度，因为我始终在关注误杀、漏杀、域名失效等纬度的问题。

后续的规划正在开脑洞，希望有一天能够做到降维打击。

**Comment by qpzr** [comment]
> 每次看到这样的建议，我的内心都非常的感动。谢谢你，热心的朋友！
> 
> 我特别希望大家各抒己见。`anti-AD是综合著名过滤列表的广告屏蔽、隐私保护工具`，所有上游源列表都**同等的并且持续的处于考察状态**，发现夹带私货并且anti-AD无法修正的情况时，将会剔除此上游列表，不管它有多么著名，多么权威。我始终相信总有一群人，愿意靠自己的力量，创造属于心中理想的完美乌托邦。而开源让这一切成为了可能！
> 
> 关于yhosts这个列表。引入yhosts之前，是经过再三考察的，如果查看anti-AD的commit log可以发现，对于yhosts，中间是经过多次反复添加删除的。我也看过不少关于这个hosts的控诉和抨击，最后经过实际论证（不言而喻，anti-AD很长一段时间都是我自己一个人在用，当然不想受别人制约，莫名其妙的屏蔽不该屏蔽的东西），发现有可塑性，才又引入了进来。至于他们wiki链接中提到的海信、一号店、探探等，早已不存在于最终输出的hosts中。所以很抱歉，暂时不能答应你的请求，在没有明确的证据之前，yhosts先作为上游列表使用。
> 
> 我对anti-AD设计了黑名单和白名单机制，完全有信心驾驭和驯服任何桀骜不驯的上游列表，像一个经验丰富的猎人一样。
> 
> 目前的V4版本，仍然是以依赖上游列表的方式工作的，无论减少和增加哪一个上游列表，均不能降低工作的复杂度，因为我始终在关注误杀、漏杀、域名失效等纬度的问题。
> 
> 后续的规划正在开脑洞，希望有一天能够做到降维打击。

建议添加[AdGuard Ad Filters]https://kb.adguard.com/en/general/adguard-ad-filters 中的
Mobile ads filter https://filters.adtidy.org/extension/chromium/filters/11.txt
Simplified domain names filter https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt 很有用呢
还有优化的组合
 中国过滤列表+隐私合集，https://github.com/523860169/list 合并自EasylistChina、EasylistLite、CJX'sAnnoyance EasyPrivacy
https://raw.githubusercontent.com/523860169/list/master/ad3.txt

Malware domains 恶意软件钓鱼网站
https://secure.fanboy.co.nz/malwaredomains_full.txt

NoCoin adblock list 屏蔽区域链加密货币挖矿 https://github.com/hoshsadiq/adblock-nocoin-list/

最后补一手 https://www.fanboy.co.nz/filters.html的Fanboy Ultimate列表（包括Easylist，Easyprivacy，Enhanced Trackers列表和Annoyances列表）
https://www.fanboy.co.nz/r/fanboy-ultimate.txt
差不多可以撒花了

**Comment by gentlyxu** [comment]
> 建议添加[AdGuard Ad Filters]https://kb.adguard.com/en/general/adguard-ad-filters 中的
> Mobile ads filter https://filters.adtidy.org/extension/chromium/filters/11.txt
> Simplified domain names filter https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt 很有用呢
> 还有优化的组合
> 中国过滤列表+隐私合集，https://github.com/523860169/list 合并自EasylistChina、EasylistLite、CJX'sAnnoyance EasyPrivacy
> https://raw.githubusercontent.com/523860169/list/master/ad3.txt
> 
> Malware domains 恶意软件钓鱼网站
> https://secure.fanboy.co.nz/malwaredomains_full.txt
> 
> NoCoin adblock list 屏蔽区域链加密货币挖矿 https://github.com/hoshsadiq/adblock-nocoin-list/
> 
> 最后补一手 [https://www.fanboy.co.nz/filters.html的Fanboy](https://www.fanboy.co.nz/filters.html%E7%9A%84Fanboy) Ultimate列表（包括Easylist，Easyprivacy，Enhanced Trackers列表和Annoyances列表）
> https://www.fanboy.co.nz/r/fanboy-ultimate.txt
> 差不多可以撒花了

兄台这么捧场的呀。
1. AdGuard的这些官方规则，针对国内域名的较少，好多俄罗斯大佬。。。；
2. 你中间说的这些anti-AD已经将他们作为上游源了；
3. 不使用二手源，这个整合anti-AD已经实现了；
