### ISSUE TITLE
据说有不少冗余和失效域名

### ISSUE THREAD

**Issue by xlighting2017** [privacy-protection-tools/anti-AD#100]
可以借鉴一下这个项目
https://github.com/felixonmars/dnsmasq-china-list

里面的 find_redundant.py  可以排除冗余
verify.py 可以排除失效

这样定期扫描一遍，应该可以精简不少?

**Comment by gentlyxu** [comment]
你来讨论我特别欢迎。感谢提供参考链接，我会仔细看的。但标题让我震惊了，这个据说是哪里据说的？冗余如果你说的是`anti-ad-domains.txt`, 这个是一个全域名列表，是故意为之的。其他的都做了最大化合并和去重，可以看看[版本历史](https://github.com/privacy-protection-tools/anti-AD/blob/master/changelog.md)啊（我的辛勤劳动你就当看不见吗？😂），另外无效域名现在引用的是notracking提供的一个列表，不尽如人意，但也去掉了不少无效域名，不然结果会更长。已经在规划这方面的[东西](https://github.com/privacy-protection-tools/dead-horse)，只是最近太忙。会进一步提升命中率的。
