### ISSUE TITLE
 游民星空的下载

### ISSUE THREAD

**Issue by qq5460168** [privacy-protection-tools/anti-AD#1005]
### 注意事项

- [X] 我做了简单验证，确定问题由 anti-AD 列表造成
- [ ] 我近期更新过 anti-AD 列表，当前版本仍存在问题
- [X] 我将提供清晰明确的问题描述

### 使用的规则

anti-ad-adguard.txt

### 使用的拦截工具

AdGuardHome

### 误杀域名

at.umtrack.com

### 问题描述

1. 问题发生时间：

2. 涉及的平台/软件/功能：

3. 误杀造成的影响：

4. 截图、附件等（如有）：

**Comment by qq5460168** [comment]
下载"游民星空"这个软件
需要访问这个域名

**Comment by ElementRef** [comment]
![14e598](https://github.com/user-attachments/assets/0402b7c9-537b-41a9-8b0a-d29399359006)

**Comment by qq5460168** [comment]
好的 谢谢大佬
