### ISSUE TITLE
smartdns关联conf文件重启后关联失效

### ISSUE THREAD

**Issue by laomao88** [privacy-protection-tools/anti-AD#101]
我用的openwrt，smartdns版本是“smartdns.1.2020.02.25-2212.arm-openwrt-all”，我把conf文件上传到/tmp/etc/smartdns/目录，然后修改smartdns.conf，在文件中添加“conf-file /etc/smartdns/anti-ad-smartdns.conf”，然后重启smartdns服务，但是重启后smartdns.conf文件中“conf-file /etc/smartdns/anti-ad-smartdns.conf”消失了，不知道smartdns中还有哪里要做配置？谢谢

**Comment by laomao88** [comment]
应该是关联完conf文件后，需要在smartdns里先保存配置，然后重启就不会丢了

**Comment by gentlyxu** [comment]
用AdGuardHome吧，smartdns配置太难了

**Comment by iLmessi** [comment]
![image](https://user-images.githubusercontent.com/41938155/79459536-ff160580-8025-11ea-9ed7-f5c481d2ec18.png)
openwrt的conf-file关联在这类设置，有luci界面的话。没有就去/etc/smartdns/custom.conf配置。

**Comment by Mosney** [comment]
op的smartdns配置文件是每次启动时由其luci配置文件生成出来的，不要直接修改它的配置文件，更改配置要么去luci界面加要么编辑/etc/config/smartdns

**Comment by laomao88** [comment]
谢谢各位，回家试试

**Comment by RebornL** [comment]
> ![image](https://user-images.githubusercontent.com/41938155/79459536-ff160580-8025-11ea-9ed7-f5c481d2ec18.png)
> openwrt的conf-file关联在这类设置，有luci界面的话。没有就去/etc/smartdns/custom.conf配置。

可以的，正确的配置方式
