### ISSUE TITLE
[新增拦截] 最近一些新增拦截 请核查

### ISSUE THREAD

**Issue by Mosney** [privacy-protection-tools/anti-AD#102]
<details><summary>NextDNS中暴露出的漏网之鱼</summary>

![image](https://user-images.githubusercontent.com/22477230/79357492-afc2cd00-7f72-11ea-9983-ef137a8582a8.png)
</details>

>  ### [notracking](https://github.com/notracking/hosts-blocklists):
>  
> client.wns.windows.com
> skydrive.wns.windows.com
> e6858.e19.s.tl88.net（存疑，与e6858.e19.s.tl88.net.0.1.cn.akamaiedge.net同时出现且域名所有者为网宿）
> vweixinthumb.tc.qq.com（存疑）
> 

> ### [WindowsSpyBlocker (Spy)](https://github.com/crazy-max/WindowsSpyBlocker)
> activity.windows.com

> ### [NoTrack Tracker Blocklist](https://gitlab.com/quidsup/notrack-blocklists)
> h5.sinaimg.cn

> ### Other：
> 1.`www.googleadservices.com`
> 被众多**过滤列表**列出但[被 AdGuardSDNSFilter 加白：](https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/290)
> <details><summary>过滤列表</summary>
> 
>  ![image](https://user-images.githubusercontent.com/22477230/79358343-a9812080-7f73-11ea-8013-2f11113ce1a7.png) 
> </details>

**Comment by gentlyxu** [comment]
稍晚点再逐个确认

**Comment by gentlyxu** [comment]
- `wns.windows.com` 是windows通知服务，加黑有安全风险
- `h5.sinaimg.cn` 微博移动版的一个主域名，不能屏
- `www.googleadservices.com` 早已在anti-AD过滤列表

已收录
- `activity.windows.com`

**Comment by Mosney** [comment]
感谢核查

**Comment by Mosney** [comment]
[误杀]activity.windows.com

https://github.com/privacy-protection-tools/anti-AD/issues/139

**Comment by muchqs** [comment]
> * `wns.windows.com` 是windows通知服务，加黑有安全风险
> * `h5.sinaimg.cn` 微博移动版的一个主域名，不能屏
> * `www.googleadservices.com` 早已在anti-AD过滤列表
> 
> 已收录
> 
> * `activity.windows.com`

对不起回复一个2020的贴，但是 “wns.windows.com” 这个域名还是被加黑了？
AdGuard Home 上用的列表里有 `||wns.windows.com^` 导致 `client.wns.windows.com` 被拦截。然后好像一些通知就收不到了。比如说 Windows 升级，Windows Defender 病毒库更新等。
