### ISSUE TITLE
误杀：https://www.gztv.com/list_two.html

### ISSUE THREAD

**Issue by snakwu** [privacy-protection-tools/anti-AD#103]
这是广州电视课堂的地址，给误杀了

**Comment by gentlyxu** [comment]
在anti-ad的所有屏蔽列表中都没有发现你提供的域名。

另外，请按issue模板提交误杀

**Comment by snakwu** [comment]
@gentlyxu 但我只要开启过滤，这个网址里的直播就打不开，关了过滤就正常

**Comment by Karmylr** [comment]
> @gentlyxu 但我只要开启过滤，这个网址里的直播就打不开，关了过滤就正常

在自定义规则里面加白试试
