### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by cecial** [privacy-protection-tools/anti-AD#105]
域名：腾讯视频
发生时间：2020年04月19日
使用的列表： anti-ad-for-dnsmasq.conf
问题描述：搭配SSRP里面的去广告，用的上面的列表，电视盒子开腾讯视频，视频列表可以看，但是播放的时候就会报，服务器异常。关闭去广告就可以播放，不知道是不是哪里误杀了还是怎么回事。

**Comment by gentlyxu** [comment]
具体是什么域名造成的呢？

**Comment by cecial** [comment]
> 具体是什么域名造成的呢？

目前我也不知道，有什么办法检查吗？一个个的试不太行吧

**Comment by gentlyxu** [comment]
查日志

**Comment by cecial** [comment]
> 查日志

用AdGuardHome查询，d.yoyi.tv，这个不过滤就可以看视频，但是广告去不了
