### ISSUE TITLE
[误杀]activity.windows.com

### ISSUE THREAD

**Issue by zeuswe** [privacy-protection-tools/anti-AD#106]
域名：activity.windows.com
发生时间：2020年4月19日
使用的列表： anti-ad-surge.txt
问题描述：CDPUserSvc进程（连接设备平台用户服务）长时间占用CPU，不停尝试连接该域名。

![批注 2020-04-19 200951](https://user-images.githubusercontent.com/28347178/79687475-10efe680-827a-11ea-8d40-5162b028d873.png)

**Comment by gentlyxu** [comment]
#102 你在确认一下？

**Comment by zeuswe** [comment]
今天傍晚手动更新了规则，结果发现连接日志在不停地刷新，任务管理器手动关掉占用CPU比较高、比较可疑的连接设备平台用户服务后，没有新的连接该域名的活动，而在该进程自动重启后，又有新的连接记录产生。日志显示该进程活动的14分钟内发起连接尝试近11万次……

**Comment by zeuswe** [comment]
它可能的确是一个用于用户数据搜集的域名，但个人感觉把它屏蔽掉得不偿失😅。

**Comment by gentlyxu** [comment]
在收录这条规则的时候，我是做了测试的。你的反馈我再次进行了确认，我的windows 10 专业版，一直开机1个小时，并没有出现你说的现象。所以你的所谓cpu高，没有其他排查过程，仅凭一张拦截次数很多的截图就确定是这个域名造成的，令人匪夷所思。。。

再者，按照你这套理论，一个域名连不上，cpu占用就高。那没有联网的windows岂不是完全不能用？

**Comment by zeuswe** [comment]
非常感谢您的反复排查。
我的系统是windows 10 1909 家庭中文版。在出现反复连接域名时，通过搜索，发现有人遇到过类似情况，他们的解决方法是直接修改注册表，禁止连接设备平台服务，而我通过删除 “DOMAIN-SUFFIX,activity.windows.com” 这条规则后便恰巧不会反复连接了，因而怀疑是这条规则引发的问题。情景复现不易，也许上报信息是不定时的，可能只有在系统联网，并已累积了一定的信息后，服务程序才会去尝试连接该域名。
但是，的确只有时间上的巧合，可能并没有关联，而是其他因素导致，是我轻率了。
在收到您的回复后，我又把那条规则加了回来，但过去了近半个小时，却仍一切正常。
再次感谢您的回复。
