### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by 1mogude1** [privacy-protection-tools/anti-AD#107]
域名：未知
发生时间：2020年4月19日
使用的列表： anti-ad-easylist.txt
问题描述：adguardhome开启这个规则以后，电视上的cibn微视听无法播放视频。

**Comment by gentlyxu** [comment]
adguardhome有个查询日志的功能，你把里面可疑的拦截规则“放行”，然后定位具体是哪条规则造成的，欢迎继续反馈

**Comment by 1mogude1** [comment]
> adguardhome有个查询日志的功能，你把里面可疑的拦截规则“放行”，然后定位具体是哪条规则造成的，欢迎继续反馈

放行了bkvv.play.cp81.ott.cibntv.net 之后，可以正常使用了
