### ISSUE TITLE
[误杀]同济大学

### ISSUE THREAD

**Issue by issac0521** [privacy-protection-tools/anti-AD#108]
域名：tongji.edu.cn
发生时间：2020年4月19日
使用的列表：easylist （具体的文件，例如/anti-ad-easylist.txt, /dist/anti-ad-surge-full.txt等等）
问题描述：
同济大学所有域名被规则:  /^(\\S+\\.)?tongji\\./   拦截

**Comment by gentlyxu** [comment]
好尴尬，我马上火速修复

**Comment by Mosney** [comment]
同济躺枪统计哈哈哈哈

**Comment by Xwg999** [comment]
太难了
