### ISSUE TITLE
[公告] 使用本项目存在一定的门槛

### ISSUE THREAD

**Issue by gentlyxu** [privacy-protection-tools/anti-AD#109]
近期的反馈越来越多，加上个人最近比较忙，积压的issue也越发的多了。

我更希望的社区环境是大家都动手排查排查，不要丢一个现象上来，就说是“误杀”了，这个很浪费我们彼此的时间。我是看到太多issue无法处理就会焦虑的人，你遇到的问题，不进行排查一番，提供更多的细节，我是没有办法进一步处理的，那样就很干着急。

同时这是一个社区，你遇到的问题，欢迎拿出来大家一起讨论。我曾经是有认真学习《[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)》的，也分享给你

以上，就是我要说的门槛

**Comment by chancat87** [comment]
希望作者你，能够控制好你的提交团队人员，什么样的地址该封，不要凭借个人喜好就提交规则进去，
在过去一年中，我一直在使用你们这个规则，知道最近几个月中，因为添加的新规则导致很多正常的网站应用等无法正常访问，比如facebook，我在过滤日志里查询到屏蔽的是几个ads的域名，你们是导致无法访问，手动添加允许就可以正常访问，其他的一些服务还有很多比如miui的域名被禁了几个域名导致小米金融app无法运行，直到现在我来发这条issues，是因为我发现ggplay商店无法下载应用，被屏蔽了几个gvt1.com的谷歌商店域名，在过去，碰到这种问题，我当然自己手动去放行或者加白名单里，像一般的网名不太懂得的朋友，碰到这种问题就会摸不到头绪，个人认为为了去广告而影响正常使用并不友好，目前在我们公司已经去掉使用anti的规则，
知道你们寻找并添加规则并保持更新辛苦，遇到这种情况向你们反馈到也挺乐意的。
但是在你们的qq群里有几个管理，暗示这规则爱用不用这种强势的话语，或者直接甩来一句提问的智慧等等之类，不可否认我之前就在你们qq群里呆着，一直没问题就潜水状态，有次我反应了一个被屏蔽的域名，我只是反馈而已，里面几个管理直接问，你想表达什么，又是小白总问这样的问题，我是在反馈信息，我能表达什么？责问你们为什么要屏蔽么？我见他们这样说根本就没有和他们争论，只是说我自己放行，接着他们又说你想被获取隐私就放行好了，我怎么做都不对咯？我需要用这个网站就必须放行，就这种态度，我直接选择放弃使用你们的规则，你们也不缺我这一个用户，反问作者你一句国内想有隐私？我说的事情已经快一个月了，根本不想提的，刚刚发现谷歌商店应用下载不了才想起这件事。qq群我也早就退了，如果还是群里反馈，又不知道他们是什么样的态度，令人反感。

**Comment by Leisuredpootle** [comment]
> 希望作者你，能够控制好你的提交团队人员，什么样的地址该封，不要凭借个人喜好就提交规则进去，
> 在过去一年中，我一直在使用你们这个规则，直到最近几个月中，因为添加的新规则导致很多正常的网站应用等无法正常访问，比如facebook，我在过滤日志里查询到屏蔽的是几个ads的域名，导致app端无法正常使用，数据被阻碍，手动放行就可以正常访问，其他的一些服务还有很多比如miui的域名被禁了几个域名导致小米金融app无法运行，直到现在我来发这条issues，是因为我发现ggplay商店无法下载应用，被屏蔽了几个gvt1.com的谷歌商店域名，在过去，碰到这种问题，我当然自己手动去放行或者加白名单里，如果是普通的网友不太懂得的朋友，碰到这种问题就会摸不到头绪，个人认为为了去广告而影响正常使用并不友好。
> 知道你们寻找并添加规则并保持更新辛苦，遇到这种情况向你们反馈到也挺乐意的。
> 但是在你们的qq群里有几个管理，暗示这规则爱用不用这种强势的话语，或者直接甩来一句提问的智慧等等之类，不可否认我之前就在你们qq群里呆着，一直没问题就潜水状态，有次我反应了一个被屏蔽的域名，我只是反馈而已，里面几个管理直接问，你想表达什么，又是小白总问这样的问题，我是在反馈信息，我能表达什么？责问你们为什么要屏蔽么？我见他们这样说根本就没有和他们争论，只是说我自己放行，接着他们又说你想被获取隐私就放行好了，我怎么做都不对咯？我需要用这个网站就必须放行，就这种态度，我直接选择放弃使用你们的规则，反问作者你一句国内想有隐私？我说的事情已经快一个月了，根本不想提的，刚刚发现谷歌商店应用下载不了才想起这件事。qq群我也早就退了，如果还是群里反馈，又不知道他们是什么样的态度，令人反感。

本人也想说两句（以下仅代表一些个人看法，如果有错麻烦指出，轻喷）：
1.facebook不能正常访问或者其他异常很多时候是上游的问题，正因如此才需要在我们这些使用者在使用过程中帮忙完善和加白；其次，普通网友的问题确实无解，个人希望是他们也能略微学习一下怎么查看是哪个域名导致的问题（仅仅是个人看法，轻喷）
2.QQ群内的一些管理的态度确实有一些问题，所以本人比较倾向于在GitHub提交issue，这个只能寄望于gentlyxu在百忙之中抽出一点时间去处理一下。

**Comment by gentlyxu** [comment]
> 希望作者你，能够控制好你的提交团队人员，什么样的地址该封，不要凭借个人喜好就提交规则进去，
> 在过去一年中，我一直在使用你们这个规则，直到最近几个月中，因为添加的新规则导致很多正常的网站应用等无法正常访问，比如facebook，我在过滤日志里查询到屏蔽的是几个ads的域名，导致app端无法正常使用，数据被阻碍，手动放行就可以正常访问，其他的一些服务还有很多比如miui的域名被禁了几个域名导致小米金融app无法运行，直到现在我来发这条issues，是因为我发现ggplay商店无法下载应用，被屏蔽了几个gvt1.com的谷歌商店域名，在过去，碰到这种问题，我当然自己手动去放行或者加白名单里，如果是普通的网友不太懂得的朋友，碰到这种问题就会摸不到头绪，个人认为为了去广告而影响正常使用并不友好。
> 知道你们寻找并添加规则并保持更新辛苦，遇到这种情况向你们反馈到也挺乐意的。
> 但是在你们的qq群里有几个管理，暗示这规则爱用不用这种强势的话语，或者直接甩来一句提问的智慧等等之类，不可否认我之前就在你们qq群里呆着，一直没问题就潜水状态，有次我反应了一个被屏蔽的域名，我只是反馈而已，里面几个管理直接问，你想表达什么，又是小白总问这样的问题，我是在反馈信息，我能表达什么？责问你们为什么要屏蔽么？我见他们这样说根本就没有和他们争论，只是说我自己放行，接着他们又说你想被获取隐私就放行好了，我怎么做都不对咯？我需要用这个网站就必须放行，就这种态度，我直接选择放弃使用你们的规则，反问作者你一句国内想有隐私？我说的事情已经快一个月了，根本不想提的，刚刚发现谷歌商店应用下载不了才想起这件事。qq群我也早就退了，如果还是群里反馈，又不知道他们是什么样的态度，令人反感。

看了这么一大段话，乍一看怀疑你走错项目了。哪里来什么“提交人员”？哪里来的“群管理”？什么是凭个人喜好？谁的个人喜好？你完全没有搞清楚anti-ad项目是怎么运行的。

**anti-ad的屏蔽规则全部来自上游，不存在个人喜好，随意封杀一说**。

有碰到误杀及时提issue上来，把问题描述清楚，我会抽时间解决的

关于qq群，目前就我一个群主，其他都是成员，没有管理员。群里是有几个积极发言者，他们的观点只能代表他们自己，代表不了任何其他人，你希望qq群是一言堂吗？只能我一个人说话？还是只能你一个人说话？我早都说了（甚至在qq群里挂了公告），反馈问题提issue，qq群里是及时沟通和了解问题细节，以及交流使用心得的地方

**Comment by gentlyxu** [comment]
@Leisuredpootle 说的非常好。反馈问题放心大胆的提issue就好，不用有任何顾虑，我倾向于构建的是开放的，包容的项目，不是独裁，不是一言堂，不是个人喜好。谢谢

**Comment by chancat87** [comment]
@gentlyxu @Leisuredpootle 统一回复两位
先谢谢回复，我发了那么长篇，也是醉了。。没有来抱怨和发泄的心态，包括我描述在群里的遭遇也没有上心的，这样的人很多，只是在想这么好的一个项目别被”影响“了，这种情况我觉得应该让作者能知道，仅此而已，再次谢谢回复。

**Comment by CalmLong** [comment]
> 希望作者你，能够控制好你的提交团队人员，什么样的地址该封，不要凭借个人喜好就提交规则进去，
> 在过去一年中，我一直在使用你们这个规则，直到最近几个月中，因为添加的新规则导致很多正常的网站应用等无法正常访问，比如facebook，我在过滤日志里查询到屏蔽的是几个ads的域名，导致app端无法正常使用，数据被阻碍，手动放行就可以正常访问，其他的一些服务还有很多比如miui的域名被禁了几个域名导致小米金融app无法运行，直到现在我来发这条issues，是因为我发现ggplay商店无法下载应用，被屏蔽了几个gvt1.com的谷歌商店域名，在过去，碰到这种问题，我当然自己手动去放行或者加白名单里，如果是普通的网友不太懂得的朋友，碰到这种问题就会摸不到头绪，个人认为为了去广告而影响正常使用并不友好。
> 知道你们寻找并添加规则并保持更新辛苦，遇到这种情况向你们反馈到也挺乐意的。
> 但是在你们的qq群里有几个管理，暗示这规则爱用不用这种强势的话语，或者直接甩来一句提问的智慧等等之类，不可否认我之前就在你们qq群里呆着，一直没问题就潜水状态，有次我反应了一个被屏蔽的域名，我只是反馈而已，里面几个管理直接问，你想表达什么，又是小白总问这样的问题，我是在反馈信息，我能表达什么？责问你们为什么要屏蔽么？我见他们这样说根本就没有和他们争论，只是说我自己放行，接着他们又说你想被获取隐私就放行好了，我怎么做都不对咯？我需要用这个网站就必须放行，就这种态度，我直接选择放弃使用你们的规则，反问作者你一句国内想有隐私？我说的事情已经快一个月了，根本不想提的，刚刚发现谷歌商店应用下载不了才想起这件事。qq群我也早就退了，如果还是群里反馈，又不知道他们是什么样的态度，令人反感。
> 

我觉得你这这样说就将所有的包袱都扔给作者了。

作为一个开源项目自己使用出了任何问题都和任何人无关。即使是作者也没有相应的责任和义务。

对于提问回答，这本来就是社区性质的，自然也会有各种各样的回答以及态度。你不能自己不高兴了就怪别人。既然选择提问起码得谦虚。总不能求别人办事自己还得当大哥吧。

如果每个作者都背负这么多那还有谁愿意去写项目呢

**Comment by gentlyxu** [comment]
> @gentlyxu @Leisuredpootle 统一回复两位
> 先谢谢回复，我发了那么长篇，也是醉了。。没有来抱怨和发泄的心态，包括我描述在群里的遭遇也没有上心的，这样的人很多，只是在想这么好的一个项目别被”影响“了，这种情况我觉得应该让作者能知道，仅此而已，再次谢谢回复。

你的思维真是跳脱，逻辑我也没看明白，就这样吧。anti-ad项目还是欢迎你使用，只是说话要组织一下语言先。我不需要你的肯定，但无端的毫无根据的乱指责，我不会放过的
