### ISSUE TITLE
[误杀]DOMAIN-SUFFIX,graph.facebook.com

### ISSUE THREAD

**Issue by xkerwin** [privacy-protection-tools/anti-AD#111]
域名：DOMAIN-SUFFIX,graph.facebook.com
发生时间：2020年04月23日
使用的列表： （具体的文件，例如/anti-ad-easylist.txt, /dist/anti-ad-surge-full.txt等等）
问题描述：
Facebook新版打不开

**Comment by gentlyxu** [comment]
参考一下这个 #94 ,你提到的域名并不会影响fb客户端使用。
