### ISSUE TITLE
[误杀]file.market.xiaomi.com

### ISSUE THREAD

**Issue by jzl2163** [privacy-protection-tools/anti-AD#113]
域名：http://file.market.xiaomi.com/mfc/thumbnail/webp/
发生时间：20年04月25日
使用的列表： /anti-ad-easylist.txt（具体的文件，例如/anti-ad-easylist.txt, /dist/anti-ad-surge-full.txt等等）

问题描述：
这个目录下一般存有MiPay的卡面图片，如：file.market.xiaomi.com/mfc/thumbnail/webp/w960h605q80/NextPay/0cce249fef750163338eccb6069eabd8e0843c2f5（建行储蓄卡）
拦截后，MiPay卡面图片无法加载

**Comment by gentlyxu** [comment]
anti-ad-easylist.txt当前版本 `20200425130544`，并不存在拦截你提供的域名，并且我测试你提供的url可以正常打开，请再次确认

**Comment by jzl2163** [comment]
老糊涂蛋了，又看错过滤器名称😂
给作者带来不便，请见谅
