### ISSUE TITLE
[新增拦截]youku?

### ISSUE THREAD

**Issue by ZuoYeZh** [privacy-protection-tools/anti-AD#114]
域名:https://v.youku.com/
出现场景：播放视频
补充说明：多种广告拦截器无效（ABP，乘风，uBlock，EasyList China+EasyList等等）

**Comment by Leisuredpootle** [comment]
建议您去帮忙探测一下广告域名，gentlyxu似乎比较忙。😘

**Comment by chancat87** [comment]
您认为优酷爱奇艺腾讯视频这种网站会被解广告么？不怕被告恶意竞争？

**Comment by gentlyxu** [comment]
这种提上来我也处理不了，请提供需要新增到过滤列表中具体的域名

**Comment by Leisuredpootle** [comment]
你可以考虑使用adguard（非home），自测adguard自带默认过滤器列表加easylist China可以过滤
