### ISSUE TITLE
[新增拦截]

### ISSUE THREAD

**Issue by LisonFan** [privacy-protection-tools/anti-AD#118]
域名: ulogs.umengcloud.com
出现场景：友盟 SDK
补充说明：

**Comment by gentlyxu** [comment]
经调查发现umengcloud.com已经存在过滤列表中，无需另外新增

**Comment by LisonFan** [comment]
> 经调查发现umengcloud.com已经存在过滤列表中，无需另外新增

https://github.com/privacy-protection-tools/anti-AD/blob/master/adblock-for-dnsmasq.conf

这里没有

**Comment by gentlyxu** [comment]
https://github.com/privacy-protection-tools/anti-AD/blob/35af4e5c42b01710c52d2a0639c6419046f145f8/adblock-for-dnsmasq.conf#L29829

**Comment by gentlyxu** [comment]
OK，下次反馈写清楚你用的哪个过滤列表

**Comment by LisonFan** [comment]
> OK，下次反馈写清楚你用的哪个过滤列表

好的好的，不好意思
