### ISSUE TITLE
[新增拦截]几个用于httpDNS的域

### ISSUE THREAD

**Issue by Mosney** [privacy-protection-tools/anti-AD#12]
域名:
httpdns.bcelive.com
umc.danuoyi.alicdn.com
httpdns.c.cdnhwc2.com
出现场景：局域网抓取
补充说明：
这种非标准DNS查询方式可能会导致拦截失效，因此建议一并加入规则

**Comment by gentlyxu** [comment]
你提交的三个域名，其中`httpdns.bcelive.com`不支持https，显然不能起到最好的保护用户的作用，已更新到黑名单。

请注意，httpdns是为了应对dns劫持而生的，其初衷出于保护用户不被侵犯。很多app都有相应策略，若httpdns不可用，会退化到传统dns，那么用户即存在被运营商dns劫持的风险。所以，anti-AD项目一定不会轻易屏蔽httpdns服务，除非确定它只为广告逃避封杀服务。

**Comment by gentlyxu** [comment]
非常感谢你的反馈，再接再厉哟
