### ISSUE TITLE
[误杀]小米金融的api被拦截

### ISSUE THREAD

**Issue by hue715** [privacy-protection-tools/anti-AD#121]
域名：api.jr.mi.com
发生时间：2020年05月03日
使用的列表： （具体的文件anti-ad-easylist.txt，例如/anti-ad-easylist.txt, /dist/anti-ad-surge-full.txt等等）
问题描述：
小米金融的api地址被拦截，相关APP无法使用。
### **Adguardhome的日志：**
![IMG_20200503_145601](https://user-images.githubusercontent.com/22958922/80908014-a09f9580-8d4e-11ea-943f-32f49b20c480.jpg)
### **被拦截后的小米金融的界面：**
![IMG_20200503_145624](https://user-images.githubusercontent.com/22958922/80908017-a8f7d080-8d4e-11ea-99e0-ca96c655dfcc.jpg)

**Comment by gentlyxu** [comment]
感谢反馈，我马上发个修复
