### ISSUE TITLE
[误杀]西门子中国下载中心被拦截

### ISSUE THREAD

**Issue by hue715** [privacy-protection-tools/anti-AD#122]
域名：www.ad.siemens.com.cn
发生时间：2020年05月04日
使用的列表： （具体的文件/anti-ad-easylist.txt，例如/anti-ad-easylist.txt, /dist/anti-ad-surge-full.txt等等）
问题描述：由于西门子中国的下载中心地址带有ad，被拦截🤣，建议加入白名单。
### **Adguardhome日志：**
![IMG_20200504_111524](https://user-images.githubusercontent.com/22958922/80934410-a357c480-8dfa-11ea-8cff-de11b68186e7.jpg)
### **下载中心首页图片：**
![IMG_20200504_111639](https://user-images.githubusercontent.com/22958922/80934426-b5d1fe00-8dfa-11ea-8d66-4a175bf2532a.jpg)

**Comment by gentlyxu** [comment]
感谢告知
