### ISSUE TITLE
[误杀]小米电视+niuza软件及主页+京东

### ISSUE THREAD

**Issue by zhaozhejun** [privacy-protection-tools/anti-AD#124]
域名：ppp.net
发生时间：xxx年xx月xx日
使用的列表： （具体的文件，例如/anti-ad-easylist.txt, /dist/anti-ad-surge-full.txt等等）
问题描述：[误杀]小米电视 主界面显示的影视或者电影综艺图片为空框，例外后可以正常显示，另niuza软件及主页彻底封了，例外后可正常进入。京东这个电脑端的有款试用软件，例外后也能正常登录并使用。
@@||image.box.xiaomi.com^$important
@@||www.niuza.com^$important
@@||app2.niuza.com^$important
@@||mercury.jd.com^$important

**Comment by zhaozhejun** [comment]
@@||www.niuza.com^$important
@@||app2.niuza.com^$important
例外之前添加的，现在新的是
@@||niuza.com^$important

**Comment by gentlyxu** [comment]
niuza.com是干啥的？能说明一下吗？

mercury.jd.com这个域名可以确定是用于埋点统计的，明确的数据收集功能，你的什么软件使用异常，希望说具体一点

**Comment by zhaozhejun** [comment]
京东那个再次测试 劫持到127.0.0.1 无问题了，应该是我自己的问题，打扰了。
牛杂那个就是淘宝的特价商品推荐网站，电脑端是www.niuza.com，手机端是app2.niuza.com，看上去电脑上跟手机端好像没什么广告，不知道拦截全域名的原因是什么。

**Comment by zhaozhejun** [comment]
![2020-5-7 19-20-3](https://user-images.githubusercontent.com/22097252/81288822-f26e5580-9097-11ea-8a77-f7d093054de4.png)
今天又测试了下，发现小米电视图片地址变了。之前反馈目前看可以关闭无需删除。后期再有问题再提出。
