### ISSUE TITLE
[误杀]dataflow.biliapi.com

### ISSUE THREAD

**Issue by tanglueyi** [privacy-protection-tools/anti-AD#125]
域名：dataflow.biliapi.com^
发生时间：没有明确的发生时间
使用的列表：anti-ad-easylist.txt等包含这条规则的
问题描述：
ADH版，Surge版均出现Dashboard中上述域名疯狂刷屏的现象，不知道是否误杀，比较担心是否影响某些功能正常使用。

**Comment by gentlyxu** [comment]
这个。。。杞人忧天了，不能因为他刷屏就放了他吧？多半是客户端做的太烂才会这样的
