### ISSUE TITLE
[误杀]微软新edge同步

### ISSUE THREAD

**Issue by THENEBYS** [privacy-protection-tools/anti-AD#126]
域名：vortex.data.microsoft.com
发生时间：2020年05月07日
使用的列表：anti-ad-for-dnsmasq
问题描述：软路由开启ssr+中的广告拦截后，新EDGE浏览器无法同步书签和设置等。开始找了半天原因，最终发现是广告拦截规则问题。未详细测试具体是Microsoft域名下的哪一条被误杀，但是在浏览器同步过程中抓包到vortex.data.microsoft.com，望修复，谢谢！

**Comment by gentlyxu** [comment]
这个判断不大严谨吧

**Comment by THENEBYS** [comment]
> 这个判断不大严谨吧

确实不太严谨，我测试了将上述网址删掉还是同步不了，空闲一点我再找找其他原因吧

**Comment by youngjumped** [comment]
我这也出现了edge同步误杀，用的Adgurad home，关闭Anti规则后接正常了。看了log不太清楚哪条造成了误杀，经过对比在同步期间以下三条域名被anti过滤，但感觉那V10和V20应该不是同步服务。。。
edge.activity.windows.com
v10.events.data.microsoft.com
v20.events.data.microsoft.com

**Comment by youngjumped** [comment]
我放行edge.activity.windows.com后正常了 你可以试一试 @THENEBYS
