### ISSUE TITLE
规则: /^tongji\\./[误杀]

### ISSUE THREAD

**Issue by qpzr** [privacy-protection-tools/anti-AD#13]
00:13:05
search.kuwo.cn
A
因响应的CNAME或IP被屏蔽 (规则: /^tongji\\./
过滤器: anti-ad-easylist.txt)
CNAME: tongji.kuwo.cn. (ttl=5)
A: 175.102.196.11 (ttl=5)

**Comment by gentlyxu** [comment]
这个看起来是一个AGH的bug，去查公共dns，search.kuwo.cn返回的只是A记录，并无CNAME，而去查询AGH，就会重现你的这个问题。现在先加白了tongji.kuwo.cn，细微之处回头再研究一下

```
dig search.kuwo.cn @223.5.5.5

; <<>> DiG 9.10.6 <<>> search.kuwo.cn @223.5.5.5
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10951
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;search.kuwo.cn.			IN	A

;; ANSWER SECTION:
search.kuwo.cn.		248	IN	A	175.102.196.12
search.kuwo.cn.		248	IN	A	175.102.196.11
```

**Comment by gentlyxu** [comment]
看起来是kuwo做了动态CDN，我去另一个地方查询，得到的结果里存在CNAME，呜呼！不是AGH的bug...

```
dig search.kuwo.cn @223.5.5.5

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> search.kuwo.cn @223.5.5.5
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60452
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;search.kuwo.cn.			IN	A

;; ANSWER SECTION:
search.kuwo.cn.		16	IN	CNAME	tongji.kuwo.cn.
tongji.kuwo.cn.		16	IN	A	175.102.178.52
tongji.kuwo.cn.		16	IN	A	175.102.178.53
```
@qpzr ,你更新一下anti-AD的过滤列表，已经修复该问题

**Comment by qpzr** [comment]
> 看起来是kuwo做了动态CDN，我去另一个地方查询，得到的结果里存在CNAME，呜呼！不是AGH的bug...
> 
> ```
> dig search.kuwo.cn @223.5.5.5
> 
> ; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> search.kuwo.cn @223.5.5.5
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60452
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0
> 
> ;; QUESTION SECTION:
> ;search.kuwo.cn.			IN	A
> 
> ;; ANSWER SECTION:
> search.kuwo.cn.		16	IN	CNAME	tongji.kuwo.cn.
> tongji.kuwo.cn.		16	IN	A	175.102.178.52
> tongji.kuwo.cn.		16	IN	A	175.102.178.53
> ```
> 
> @qpzr ,你更新一下anti-AD的过滤列表，已经修复该问题

其实还有很多这样的，查了之后返回cname的。比如log.阿里云百度云什么鬼大挪移.com都出来了。Adgurad Home我每次装不到几天就有惊喜，气的让你移除删掉，无力吐槽了。还是smartdns好使，格式还跟dnsmasq差不多 address /xx.yy/# 就能屏蔽主和子域名。我先拿那个for dnsmasq的转成smartdns格式安稳用几天，不想弄agh了免得上不得网又被骂哈哈哈，感谢你解答修复

**Comment by gentlyxu** [comment]
cname本来就是一种标准的dns解析方式呀

**Comment by gentlyxu** [comment]
cname本来就是标准的dns记录之一呀

**Comment by qpzr** [comment]
> cname本来就是标准的dns记录之一呀

我知道那些记录 返回soa的和谐效果更佳吗😀😂问题是Adgurad home坑呀，前晚上刚装，填上游服务器的时候，就发现了上流服务器这个神奇的东西😂然后我勾选了安全浏览和家长控制，随便打开一堆网站，网易首页就被家长控制天降大锅的给办了，我看记录理由是成人网站😂😂😂

**Comment by qpzr** [comment]
> cname本来就是标准的dns记录之一呀



00:17:07
artistpic.kwcdn.kuwo.cn
A
> 因响应的CNAME或IP被屏蔽（规则：/^tongji\./
> 过滤器：anti-ad-easylist.txt）
CNAME: tongji.kwcdn.kuwo.cn. (ttl=70)
A: 175.102.196.11 (ttl=5)

酷我音乐封面被干掉了  请+白

**Comment by kxdn3** [comment]
虾米音乐给干掉了。。
