### ISSUE TITLE
[误杀] simg.sinajs.cn

### ISSUE THREAD

**Issue by kkkidding** [privacy-protection-tools/anti-AD#133]
域名：blog.sina.com.cn
使用的列表： simg.sinajs.cn被拦截导致blog.sina.com.cn的样式和图片都无法加载
问题描述：

**Comment by gentlyxu** [comment]
使用的列表是哪个？anti-ad规则未检测到你提供的域名

**Comment by kkkidding** [comment]
阿,不好意思,和 https://gitlab.com/CHEF-KOCH/cks-filterlist/raw/master/hosts/Ads-tracker.txt 这个列表搞混了...
