### ISSUE TITLE
[误杀]有道云笔记无法同步笔记

### ISSUE THREAD

**Issue by htgy12** [privacy-protection-tools/anti-AD#137]
域名：wanproxy.127.net
发生时间：2020年05月19日
使用的列表： anti-ad-easylist.txt
问题描述：
有道云笔记同步需要访问这个域名，被拦截之后导致同步不成功
联系客服后确定，同步过程会访问 `http://wanproxy.127.net/lbs?version=1.0&bucketname=bucket-ynote-online` 这个网址

**Comment by gentlyxu** [comment]
感谢反馈。以及给你严谨的精神点赞！
