### ISSUE TITLE
[误杀]pingjs.qq.com（可能）

### ISSUE THREAD

**Issue by LisonFan** [privacy-protection-tools/anti-AD#143]
域名：pingjs.qq.com
发生时间：2020年5月27日
使用的列表： anti-ad-domains.txt
问题描述：通过支付宝打开兴业银行的商户二维码页面无法付款，通过抓包发现页面加载的所有请求中，只拦截了`pingjs.qq.com`，页面上请求的是`https://pingjs.qq.com/h5/stats.js?v2.0.4`
通过`Google`搜索到可知，这个`JS`是统计服务使用的，不知道为什么影响到了付款。。

**Comment by gentlyxu** [comment]
能不能提供下页面，我具体看看

**Comment by LisonFan** [comment]
> 能不能提供下页面，我具体看看

能否提供 Email？我发 Email 给你

**Comment by gentlyxu** [comment]
```
echo Z2VudGx5eHVAb3V0bG9vay5jb20K | base64 -d
```

**Comment by winduser** [comment]
另外再申报一个情况。

- 域名：pingjs.qq.com
- 发生时间：2020年5月27日
- 使用的列表： anti-ad-domains.txt

问题描述：在微信支付的「帮助中心」选择「管理名下账户」中的「查询名下账户」，如果屏蔽pingjs.qq.com，会导致下一步按钮无法点击。

![Screenshot of Surge](https://user-images.githubusercontent.com/5322700/82990579-0241df80-a02f-11ea-9d2e-a7ce7247a290.png)
![Help Page](https://user-images.githubusercontent.com/5322700/82990572-0110b280-a02f-11ea-83c0-66d79224db83.jpeg)
![Step 1](https://user-images.githubusercontent.com/5322700/82990582-03730c80-a02f-11ea-8c3c-b0024e8f4d0f.png)
![Step 2](https://user-images.githubusercontent.com/5322700/82990584-040ba300-a02f-11ea-86f1-2cb57d113615.png)

**Comment by gentlyxu** [comment]
> > 能不能提供下页面，我具体看看
> 
> 能否提供 Email？我发 Email 给你

实际抓包看了你提供的页面，没有发现`pingjs.qq.com`域名相关的请求，并且用微信成功支付了1毛钱。。。apple pay也能被正常唤起。我的环境是AdGuard Home，直接访问`pingjs.qq.com`是被屏蔽的。你说的情况我没有能够重现

**Comment by gentlyxu** [comment]
> 另外再申报一个情况。
> 
> * 域名：pingjs.qq.com
> * 发生时间：2020年5月27日
> * 使用的列表： anti-ad-domains.txt
> 
> 问题描述：在微信支付的「帮助中心」选择「管理名下账户」中的「查询名下账户」，如果屏蔽pingjs.qq.com，会导致下一步按钮无法点击。
> .....

你的这个我也实际测试了，是`bugly.qq.com`域名被拦截导致的

**Comment by winduser** [comment]
> > 另外再申报一个情况。
> > 
> > * 域名：pingjs.qq.com
> > * 发生时间：2020年5月27日
> > * 使用的列表： anti-ad-domains.txt
> > 
> > 问题描述：在微信支付的「帮助中心」选择「管理名下账户」中的「查询名下账户」，如果屏蔽pingjs.qq.com，会导致下一步按钮无法点击。
> > .....
> 
> 你的这个我也实际测试了，是`bugly.qq.com`域名被拦截导致的

感谢回复。

我使用Surge HTTP Capture抓了微信钱包里的操作。在这之中，我完成了一次提现操作，因此有银行icon。完成提现活动后，我再进入帮助中心，依旧无法点击「查询名下账户」的下一步。

![HTTP Capture Screenshot](https://user-images.githubusercontent.com/5322700/83051645-dfd8b200-a080-11ea-85a9-4a416cffee3a.png)

我抓包下来，并没有发现`bugly.qq.com` 这个域名。不确定是否有什么地方疏漏。我尝试把bugly.qq.com设置为直连，没有解决这个问题。

**Comment by LisonFan** [comment]
> > > 能不能提供下页面，我具体看看
> > 
> > 
> > 能否提供 Email？我发 Email 给你
> 
> 实际抓包看了你提供的页面，没有发现`pingjs.qq.com`域名相关的请求，并且用微信成功支付了1毛钱。。。apple pay也能被正常唤起。我的环境是AdGuard Home，直接访问`pingjs.qq.com`是被屏蔽的。你说的情况我没有能够重现

用支付宝扫码打开那个页面才有问题，微信打开好像没去请求`pingjs.qq.com`

**Comment by LisonFan** [comment]
> > 另外再申报一个情况。
> > 
> > * 域名：pingjs.qq.com
> > * 发生时间：2020年5月27日
> > * 使用的列表： anti-ad-domains.txt
> > 
> > 问题描述：在微信支付的「帮助中心」选择「管理名下账户」中的「查询名下账户」，如果屏蔽pingjs.qq.com，会导致下一步按钮无法点击。
> > .....
> 
> 你的这个我也实际测试了，是`bugly.qq.com`域名被拦截导致的

我也测了这个问题，也是`pingjs.qq.com`拦截造成的

**Comment by gentlyxu** [comment]
已经将 pingjs.qq.com 去除了，你们帮忙测试一下看看

**Comment by LisonFan** [comment]
> 已经将 pingjs.qq.com 去除了，你们帮忙测试一下看看

今早去买了包子，用支付宝能正常付款了

**Comment by gentlyxu** [comment]
那就先这样用着
