### ISSUE TITLE
anti-AD项目issue区规则

### ISSUE THREAD

**Issue by gentlyxu** [privacy-protection-tools/anti-AD#146]
本issue区主要用于anti-AD项目相关的技术交流，包括反馈误杀、新增拦截、广告屏蔽相关的建议，针对某些广告屏蔽相关疑难杂症的技术讨论。基于越来越复杂的外部环境，今制定以下规则，希望共同营造专注技术氛围的社区讨论环境。

## 本项目一如既往的欢迎
1. 明确的误杀反馈，有域名、有现象描述、有使用的列表，有出现时间，甚至有截图；
2. 任何的技术改进建议；
3. 经过代码审阅仍然对anti-ad存在技术疑问的任何内容；
4. 清晰的新增拦截内容；
5. 使用anti-ad中遇到的技术困惑，经过思考仍然找不到答案的；

## 以下几类issue可能会被直接关闭
1. 以“为什么屏蔽XXX”，“凭什么屏蔽X....”，“怎么连XXX都屏蔽了”等质问语气提交的issue，并且不说明目的的。这里解释一下：anti-AD的所有屏蔽规则均来自上游和网友提交，这些在代码和closed issues中均有记录；
2. 不说明具体被误杀的域名，也不提供具体APP名称，只有类似于“我的xx视频看不了”，“XX app打开又有广告了” 这类简单描述；
3. anti-AD的过滤列表从原理上就做不到的，例如基于ip地址的广告投放，网页中的元素广告，视频中的某些嵌入广告，已经拍摄进视频内的广告等；
4. 工具配置相关的，通过搜索引擎就能解决的；
5. 意图左右anti-AD屏蔽公平性而影响大多数人的，例如“我不喜欢xxx，建议屏蔽了它”，“我觉得xx视频里有点广告很好，建议加白”，等等

## 以下几类issue会被删除

1. 任何谩骂、侮辱或诽谤他人、冷嘲热讽、有人身攻击行为的；
2. 没有事实依据的无端质疑、道德绑架、指责；（*anti-AD项目的每一行代码早已面向全球互联网完全开源，视而不见上来就喷的请远离*）
3. 地域歧视、种族歧视、性别歧视、年龄歧视等歧视类内容；
4. 变相的商业宣传、广告信息；
5. 不利于促进技术交流、讨论的技术无关内容；
6. 声称付费解决广告屏蔽问题的；

注意！以上规则同样适用于在git代码中提交的评论。

**Comment by Mosney** [comment]
看了一下我[前两个被你删的issue](https://archive.vn/J4TKt)上面6条大概也就第5条强行解释能套上，然而实际上你私自往列表里面加料的行为就是利用技术替别人做选择，大概可以称为**技术不端**，还是技术相关

为了给你以前及以后的行为提供正义基础，建议在“以下几类issue会被删除”里加一条：
**7. @gentlyxu 不喜欢的内容** 
或者 
**8.本规定一切解释权归 @gentlyxu 所有**

**Comment by c2xusnpq6** [comment]
```
privacy-protection-tools deleted a comment from Mosney on 31 May 2020
```
???

**Comment by c2xusnpq6** [comment]
https://github.com/Mosney/anti-anti-AD/blob/master/OthersVoices.md ???

**Comment by gentlyxu** [comment]
惊！居然这个人专门做了项目来diss anti-AD，我是没有想到了。看了他的这个repo，这完全是此人在故意发泄。

我可能是不小心揭露了他是轮子的事实，引发了他的气急败坏，看他的截图就知道他后面骂人我才删除了issue的，其他的可以参考上面的issue区规则。

我在anti-AD的readme里补充过

> anti-AD在自我认知上始终是一个非主流的小众项目，受众群体较为狭窄。项目一直坚持每一行代码开源！anti-AD过滤列表的所有规则均来自上游列表和网友提交的issues，欢迎各界朋友审阅。在没有阅读代码或没有完全理解代码意图之前，本项目以及作者不再接受任何无端的质疑、猜忌，作者也不打算再浪费时间作出任何解释。

有任何疑问你看代码和提交记录啊，哪个是本作者故意为之的，你指出来嘛，几年来的所有提交记录都完整保存在这里，视而不见，非得在提交误杀issues里做文章，不是蠢就是坏！设置issues区是方便大家讨论和提交误杀的，按他那个说法，那我吃饱了撑的给自己找不痛快？

至于他在那个项目里毫无根据的尬黑，我就不多说了，明眼人一看就知道怎么回事。

我发现越不回应越有人觉得我有问题，那行啊，以后任何有必要的时候我都会回应的

就这样吧，本人还有好多事要忙，就不奉陪了

**Comment by 3136083906** [comment]
@@||analytics-api.smzdm.com^$important
这条规则真的是卡顿的根源。关键是adh还好说可以逐条放行。如果用别的过滤软件没有日志系统。就非常难办，比如lean固件里的广告屏蔽大师+，用dnsmasq规则，就不知道怎么放行

**Comment by xi-nan** [comment]
能否新增Shadowrocket Rules格式的规则文件，现在发布的几个不能直接用于Shadowrocket

**Comment by yikexiaoyao** [comment]
拦截失败倒是小事，后期补充就行了，然而很多页面被无故拦截就很难受，比如微信内部分链接打开的页面和抖音直播间小黄车，等等，有的时候这些拦截让人错不及防，希望能够改进

**Comment by Ra2-IFV** [comment]
> https://github.com/Mosney/anti-anti-AD/blob/master/OthersVoices.md ???

实在绷不住了，我寻思你不是可以自定义规则的吗？Fork然后自己改不也行？说得好像Anti-AD逼着你不准看什么东西一样，又不是GFW，脑子多少带点坑
