### ISSUE TITLE
dnsmasq 文件部分规则错误

### ISSUE THREAD

**Issue by Myer921** [privacy-protection-tools/anti-AD#149]
https://github.com/privacy-protection-tools/anti-AD/blob/73b590e4e915e99f31c9892be850a726b5ca5767/adblock-for-dnsmasq.conf#L5333

这里的规则会导致 dnsmasq 无法正确启动

错误信息
dnsmasq: error at line 5333 of /etc/dnsmasq.t/dnsmasq.d/adblock-for-dnsmasq.conf

如果这个域名整个都用于广告服务，建议直接合并成 address=/bcebos.com/

**Comment by gentlyxu** [comment]
感谢告知，php生成工具判断域名合法性上存在的bug，已修复，请更新到最新版本

**Comment by Myer921** [comment]
收到，我会进行测试(测试成功会编辑本回复)

**Comment by gentlyxu** [comment]
合并是已经做了最大限度的合并，没有屏蔽根域名的条目都是因为存在误杀。至于硬件性能，那就另外找办法解决了。减少过滤条目的做法肯定不行，降低了拦截效果啊
