### ISSUE TITLE
[误杀] api.ipify.org

### ISSUE THREAD

**Issue by hezhijie0327** [privacy-protection-tools/anti-AD#15]
域名：api.ipify.org api6.ipify.org www.ipify.org
发生时间：2020年01月21日
使用的列表：anti-ad-easylist.txt
问题描述：api.ipify.org 被  ||ipify.org^ 拦截，无法通过 api.ipify.org / api6.ipify.org 获得公网 IP，以及无法访问其官网(www.ipify.org)

**Comment by gentlyxu** [comment]
已加白

**Comment by gentlyxu** [comment]
查了一下，这条屏蔽规则来自easyprivacy，所以这个网址是涉及收集隐私的，不知道你的应用场景是什么，需要排除这条规则？ @hezhijie0327

**Comment by hezhijie0327** [comment]
通过 curl https://api.ipify.org 获取当前公网 IP。
我结合它反馈后的结果用于 DDNS

**Comment by hezhijie0327** [comment]
https://github.com/rdegges/ipify-api

**Comment by gentlyxu** [comment]
好的，明白了，谢谢告知
