### ISSUE TITLE
[误杀]easylist.txt的规则/^(\S+.)?widgets?./

### ISSUE THREAD

**Issue by lxk0301** [privacy-protection-tools/anti-AD#151]
域名：公司网站。不方便提供地址，见谅
发生时间：2020年06月12日
使用的列表： anti-ad-easylist.txt（https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt）
问题描述：上面文件的 拦截规则/^(\S+\.)?widgets?\./，会导致拦截我网站上面的jquery.ui.widget.js文件，导致网站部分功能出现问题。不知此规则目的是什么，能否剔除或者完善此规则呢？谢谢

<img width="1280" alt="Snipaste_2020-06-12_10-52-14" src="https://user-images.githubusercontent.com/21308593/84459764-d19eae80-ac9a-11ea-8e06-5ef7a63ad41f.png">

**Comment by gentlyxu** [comment]
你把anti-ad的规则用在浏览器插件上了？我们的规则只用于过滤域名部分

**Comment by lxk0301** [comment]
> 你把anti-ad的规则用在浏览器插件上了？我们的规则只用于过滤域名部分

对的，我用在了Windows的adguard上面了。我看你的anti-ad-easylist.txt适用于adguardHome。

**Comment by gentlyxu** [comment]
所以不是过滤规则的问题。你先搞清楚adguard和adguardhome不是一个东西

**Comment by lxk0301** [comment]
> 所以不是过滤规则的问题。你先搞清楚adguard和adguardhome不是一个东西

好， 那应该是我的问题，已经在adguard上删掉此规则了
