### ISSUE TITLE
[新增拦截]PicACG

### ISSUE THREAD

**Issue by Leisuredpootle** [privacy-protection-tools/anti-AD#154]
域名:ad-*.wikawika.xyz
出现场景：软件使用过程中展示的广告
补充说明：
广告域名为ad-channel.wikawika.xyz和ad-display.wikawika.xyz
可以考虑批量匹配，不会影响软件使用

**Comment by Leisuredpootle** [comment]
另附一个恶意跳转的域名

`https://js.bckrono.cn/safe/v6/index.html?9221592441112&pkg=35#37`

**Comment by gentlyxu** [comment]
> 另附一个恶意跳转的域名
> 
> `https://js.bckrono.cn/safe/v6/index.html?9221592441112&pkg=35#37`

这个域名会跳转到yemnn.cn，而`yemnn.cn`已经被上游规则屏蔽了，所以是否可以不用再添加了？

**Comment by gentlyxu** [comment]
> 域名:ad-*.wikawika.xyz
> 出现场景：软件使用过程中展示的广告
> 补充说明：
> 广告域名为ad-channel.wikawika.xyz和ad-display.wikawika.xyz
> 可以考虑批量匹配，不会影响软件使用

这个我无法验证副作用，暂不收录

**Comment by Leisuredpootle** [comment]
> > 另附一个恶意跳转的域名
> > `https://js.bckrono.cn/safe/v6/index.html?9221592441112&pkg=35#37`
> 
> 这个域名会跳转到yemnn.cn，而`yemnn.cn`已经被上游规则屏蔽了，所以是否可以不用再添加了？

根据本人测试，该域名会随机跳转，不限于yemnn.cn
例如，会跳转到s350.familytaste.cn/dapp/penhuol/v321.apk?p=35

**Comment by gentlyxu** [comment]
ok,收录了

**Comment by gentlyxu** [comment]
添加了一个`ad-*.wikawika.xyz` 到easylist里，若有误杀希望能告知本项目

**Comment by Leisuredpootle** [comment]
> 添加了一个`ad-*.wikawika.xyz` 到easylist里，若有误杀希望能告知本项目

本人在创建此issue之前测试了半个月左右，唯一出现的问题就是原本显示广告的地方会白屏，但并未影响正常使用，加入到easylist后可以考虑等待1-2个月，看看有没有人提交相关issue
