### ISSUE TITLE
建议：分离电视端广告过滤规则

### ISSUE THREAD

**Issue by leonwahy** [privacy-protection-tools/anti-AD#158]
因为电脑端及手机端广告过滤方式均较多，但电视端则相对麻烦，不知道是否可以分离一套电视端的广告过滤规则。
谢谢！

**Comment by Leisuredpootle** [comment]
这个适用于配置到路由器，如果路由器已经配置，那电视连接到WiFi即可，如果想追求更好的体验可以考虑电视使用adguard并搭配adgk规则，会有更上一层楼的体验

**Comment by leonwahy** [comment]
OK, Tks!
