### ISSUE TITLE
[误杀] 大量新聞網站被攔截 (新聞審查?)

### ISSUE THREAD

**Issue by kousyougi** [privacy-protection-tools/anti-AD#160]
用了幾個月才發現原來anti-AD還順便幫gfw做新聞審查。官方背景？熱心民眾？

address /soundofhope.org/#
address /renminbao.com/#
address /aboluowang.com/#
address /secretchina.com/#
address /minghui.com/#
address /minghui.org/#
address /epochtimes.com/#
address /epochtimes.org/#
address /dongtaiwang.com/#
address /dongtaiwang.org/#
address /ntdtv.com/#
address /ntdtv.org/#

**Comment by Leisuredpootle** [comment]
根据我的观察，这个应该是上游所添加进去的

**Comment by gentlyxu** [comment]
上来就质疑我啊？看看readme和issue区规则？

**Comment by kousyougi** [comment]
非常抱歉

**Comment by gentlyxu** [comment]
> 非常抱歉

哪里哪里，兄弟多一些耐心了解一下本项目，再提意见不迟，你提的这些之前也有人说到，只是口气一样觉得是我故意为之，索性不予理睬，刚刚已经把你提到的网站都做了处理。我近期在这个项目上的时间减少了很多，倒是有一些人觉得stars数多了，我开始飘了。实际完全不是这样，stars数多少，跟我并没有什么实际关系，我也过了需要靠一个项目获得一个好工作的阶段，当然远还没到财务自由的地步，也就没有那么多时间玩个人爱好，之前的很多质疑我也选择不解释，别人说就说了，与其浪费时间解释，不如干点实事。

起初，这个项目仅仅是我自己用的，发现可以共享出来，于是做了一些更新维护，并没有想过有多少的利益瓜葛或是从中捞点好处，这段时间下来，还真是不轻松呢，吼吼～

**Comment by c2xusnpq6** [comment]
`是上游把` ??? who?
