### ISSUE TITLE
发现一个可以安卓苹果两用的HOSTS源 iOSAdblockList

### ISSUE THREAD

**Issue by qpzr** [privacy-protection-tools/anti-AD#161]
大神得空研究一下加不加呗

项目地址 https://github.com/BlackJack8/iOSAdblockList

机翻的说明：
iOS广告拦截器的主机列表
截至2020年2月28日的重大更新：最近废弃的移动阻止列表已与iOSAdblockList合并。此列表主要针对iOS，可在Android设备上使用。

为了获得更新通知，请将我的存储库标记为“已监视”。

如果您发现广告，请提出问题或通过reddit u / neidhardterik与我联系。（请注意，由于主机格式，无法阻止Youtube，Messenger，Instagram和其他一些社交媒体平台上的广告。）

杂项是阻止假新闻，加密矿工和欺诈网站的列表。

对于新用户，我建议您使用Adguard Pro，因为它使您可以订阅列表，而无需手动更新列表。

**Comment by gentlyxu** [comment]
好的。晚点我看一看。另外，其实不用贴机翻

**Comment by gentlyxu** [comment]
加进来直接增加了12000多行，还基本都是国外网站，显然不符合咱“中文区”的定位，暂时不考虑添加此源了

**Comment by qpzr** [comment]
> 加进来直接增加了12000多行，还基本都是国外网站，显然不符合本项目“中文区”的定位，暂时不考虑添加此源了

选错列表了吧？没有一万二这么多这么夸张，我昨晚用ipv4hosts那个试的时候就多加了六千多行。bat三巨头的主域名分别输进去查找，也是有很多的

**Comment by gentlyxu** [comment]
运行后看 `anti-ad-domains.txt` 这还是去重后的，加进去这个列表是不是就废了？

**Comment by qpzr** [comment]
> 运行后看 `anti-ad-domains.txt` 这还是去重后的，加进去这个列表是不是就废了？

anti-ad-easylist.txt 我只用这个类型的列表 ，测试的时候也只生成了easylist.txt  其他没管  。目前发现的就是 www.baidu.com 和 www.wshifen.com 这两个误杀了 百度的搜索和搜索的结果

**Comment by gentlyxu** [comment]
没关系，有好的建议欢迎继续随时发出来

**Comment by qpzr** [comment]
> 没关系，有好的建议欢迎继续随时发出来

好吧 那我拿去自己玩

**Comment by qpzr** [comment]
> 加进来直接增加了12000多行，还基本都是国外网站，显然不符合本项目“中文区”的定位，暂时不考虑添加此源了

这里有疑问，所谓的中文区定位是不是有双重标准？
easylist=(
  "https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt" 中的easylist
  "https://easylist.to/easylist/fanboy-annoyance.txt"
这两条基本都是国外网站，那么是不是显然不符合本项目“中文区”的定位？那为什么他们又可以存在本项目？请明示
