### ISSUE TITLE
[误杀]v10.events.data.microsoft.com和v20.events.data.microsoft.com 

### ISSUE THREAD

**Issue by qpzr** [privacy-protection-tools/anti-AD#162]
01:59:04
v10.events.data.microsoft.com
A
被 anti-ad 过滤
状态： NXDOMAIN

2020/6/28 10:09
v20.events.data.microsoft.com
A
被 anti-ad 过滤
状态： NXDOMAIN

规则: ||events.data.microsoft.com^
列表: esaylist.txt

导致WIN10系统中的 WINDOWS更新不能使用，无法检查更新，安装更新

刚才放行了再试，居然检查更新成功了。难怪这几天干嘛都更新不了，总是失败 重试

详细的或许微软有更权威的解释 https://docs.microsoft.com/zh-cn/windows/privacy/configure-windows-diagnostic-data-in-your-organization

**Comment by sr093906** [comment]
Whether the domains harm privacy depends on which version of Windows 10 you use, and apparently not everyone uses enterprise edition…

Regarding v10.events.data.microsoft.com

You can search the domain on this page:

https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1903-non-enterprise-editions

In terms of v20.events.data.microsoft.com

https://github.com/crazy-max/WindowsSpyBlocker/issues/180

@gentlyxu Could you think it twice on the decision of removing the two from blacklists?

**Comment by gentlyxu** [comment]
@sr093906  many thanks.the current situation has also caused me some distress.on the one hand, more people want the "pages" to display perfectly, on the other, I want stricter protection of my privacy and blocking Advertising, so the plan is that in the future there will be two branches, one of which will be called "public edition" and the other "pro edition".
