### ISSUE TITLE
[新增拦截]国内主流APP广告

### ISSUE THREAD

**Issue by wchqybs** [privacy-protection-tools/anti-AD#164]
域名:见https://gitee.com/lhzgl6587/hosts/raw/master/myruler
出现场景：视频及APP

**Comment by gentlyxu** [comment]
有什么独到之处？

**Comment by wchqybs** [comment]
@gentlyxu 

> 有什么独到之处？

适合家里有智能电视的用户

**Comment by gentlyxu** [comment]
这个规则列表不清楚用于什么的。格式是错误的，anti-AD暂不考虑引入
