### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by 412026849** [privacy-protection-tools/anti-AD#165]
域名：@@||m.uczzd.cn^$important
发生时间：xxx年xx月xx日
使用的列表： （具体的文件，例如/anti-ad-easylist.txt, /dist/anti-ad-surge-full.txt等等）
问题描述：可以显示出uc（android）评论

**Comment by 412026849** [comment]
是UC推荐文章的评论

**Comment by gentlyxu** [comment]
经调查，广告众多。且放行后评论加载还有问题，请自行查询问题
