### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by hades002** [privacy-protection-tools/anti-AD#167]
域名：123.sogou.com和123.sogoucdn.com
发生时间：2020年7月2日
使用的列表：anti-ad-for-dnsmasq.conf
问题描述：

搜狗网址导航（ https://123.sogou.com/ ）无法打开 

搜狗影视（ http://kan.sogou.com/dianshiju/ ）图片加载异常

**Comment by gentlyxu** [comment]
网址导航站均涉及广告跳转和统计用户使用习惯，因此不属于误杀范围
