### ISSUE TITLE
[误杀]down.360safe.com

### ISSUE THREAD

**Issue by uniartisan** [privacy-protection-tools/anti-AD#169]
域名：down.360safe.com
发生时间：2020年07月05日
使用的列表： anti-ad-easylist.txt
问题描述：
Adguard Home 使用此列表会拦截360正常安装文件的下载。建议对360非广告域名放行，360仍然是国内查杀率最高、防护效果较好的安全软件。

**Comment by uniartisan** [comment]
同样非广告域名的有：
*softm.update.360safe.com
zip.update.360safe.com
ini.update.360safe.com
update.360safe.com*

意义不明的网址：
*s.360.cn* 疑似 360在线安全服务
建议对360safe.com采取白名单措施

**Comment by gentlyxu** [comment]
众所周知，360是收集隐私和用户行为跟踪的典型，这些上游规则不存在误杀行为。若对你造成使用不便，请酌情自行设置

**Comment by uniartisan** [comment]
个人已经放行更新必须的域名
**@@||down.360safe.com^
@@||update.360safe.com^**
