### ISSUE TITLE
[误杀] download.windowsupdate.com ||cedexis.net^

### ISSUE THREAD

**Issue by hezhijie0327** [privacy-protection-tools/anti-AD#17]
域名：download.windowsupdate.com / ||cedexis.net^
发生时间：2020年01月24日
使用的列表：anti-ad-easylist.txt
问题描述：
AdGuard Home
||cedexis.net^ 因响应的CNAME或IP被屏蔽
使得 Windows Update 无法使用

download.windowsupdate.com A 因响应的CNAME或IP被屏蔽
CNAME: 2-01-3cf7-0009.cdx.cedexis.net. (ttl=8)
CNAME: download.windowsupdate.com.bsgslb.cn. (ttl=8)
CNAME: u957.v.bsgslb.cn. (ttl=8)
A: 124.225.118.81 (ttl=8)
A: 124.225.118.88 (ttl=8)
A: 42.243.148.5 (ttl=8)
A: 116.53.36.73 (ttl=8)
A: 124.225.118.86 (ttl=8)
A: 42.243.148.11 (ttl=8)
A: 124.225.118.82 (ttl=8)
A: 124.225.118.89 (ttl=8)
A: 116.53.36.74 (ttl=8)
A: 124.225.118.83 (ttl=8)

**Comment by gentlyxu** [comment]
已加白
