### ISSUE TITLE
[误杀]app.adjust.com

### ISSUE THREAD

**Issue by Hades-001** [privacy-protection-tools/anti-AD#172]
域名：app.adjust.com
发生时间：2020年7月7日
使用的列表：anti-ad-for-dnsmasq.conf
问题描述：

屏蔽后会导致微软账户开启两步验证所需要的app无法下载。

app官方下载链接：https://go.microsoft.com/fwlink/?LinkId=869155

**Comment by gentlyxu** [comment]
可以确定的是`app.adjust.com` 一定是用户行为跟踪域名。如果你在app store里搜索"Microsoft Authenticator" 一样能下载，不知道为啥非得依赖他那个下载链接，况且那个链接最后跟的就是真正的app store地址

**Comment by Hades-001** [comment]
不能解析app.adjust.com的话根本不知道要装的app的名字。。。因为打不开那个跳转连接。

还有一个问题，使用anti-ad-for-dnsmasq.conf后Microsoft Authenticator无法添加用户账户，会在最后一步报错，连接失败，取消anti-ad-for-dnsmasq.conf后能正常添加账户。由于不会安卓抓包不知道是屏蔽了哪个域名导致此问题。

**Comment by gentlyxu** [comment]
这动手能力，建议提升一下水平再来使用？
