### ISSUE TITLE
又发现两个HOSTS源，应该符合要求

### ISSUE THREAD

**Issue by qpzr** [privacy-protection-tools/anti-AD#173]
有现成的去广告hosts为什么还弄多一个?
neohosts 没有我对应上的网站,我所以做了一些补充.主要针对小说网站,但不仅限于小说网站.
ilpl/ad-hosts    https://github.com/ilpl/ad-hosts

neohosts 中 JS Miner 挖矿 来自这个列表 https://gitlab.com/ZeroDot1/CoinBlockerLists/-/blob/master/hosts_browser

neohosts Full Hosts 和 CoinBlockerLists hosts_browser 对比

0.0.0.0 000.0x1f4b0.com
0.0.0.0 001.0x1f4b0.com
0.0.0.0 002.0x1f4b0.com
0.0.0.0 003.0x1f4b0.com
0.0.0.0 004.0x1f4b0.com
0.0.0.0 005.0x1f4b0.com
0.0.0.0 006.0x1f4b0.com
0.0.0.0 007.0x1f4b0.com
0.0.0.0 008.0x1f4b0.com
都是同样的开头，基本上可以确认无误了

**Comment by gentlyxu** [comment]
CoinBlockerLists 有点意思

**Comment by qpzr** [comment]
> CoinBlockerLists 有点意思
cloudflare.net
cdn77.org
要加白这两个CDN不然会误杀

**Comment by qpzr** [comment]
> CoinBlockerLists 有点意思

cloudflare.net
cdn77.org
要加白这两个CDN不然会误杀

**Comment by gentlyxu** [comment]
> > CoinBlockerLists 有点意思
> 
> cloudflare.net
> cdn77.org
> 要加白这两个CDN不然会出现大型车祸现场

添加上游源一定会遇到类似的问题，需要一段时间的调整，继续关注

**Comment by qpzr** [comment]
> > > CoinBlockerLists 有点意思
> > 
> > 
> > cloudflare.net
> > cdn77.org
> > 要加白这两个CDN不然会出现大型车祸现场
> 
> 添加上游源一定会遇到类似的问题，需要一段时间的调整，继续关注

addressMaker.class.php 我觉得应该是这个里面的机制，触发了某些域名不能完整写进最终列表，导致直接杀主域名，所以才会出现了误杀。得空更新一下，修正BUG吧

**Comment by gentlyxu** [comment]
不是的
