### ISSUE TITLE
[计划]anti-AD的下一步规划

### ISSUE THREAD

**Issue by gentlyxu** [privacy-protection-tools/anti-AD#175]
啊呀！反正都是忙碌，再更加忙碌一点又怎样，俗话不是说“虱子多了不痒”。

征求意见关于以下内容规划，欢迎大家一起讨论

1. 剔除已过期域名（之前有尝试实现过，效率较低，主要是方案问题。目前引用的是notracking的一个列表），怎么实现更好？
2. 计划分为“public版”和“pro版”，区别在于适用范围不同，public版侧重用网体验，去广告效果约等于目前，误杀较少，适用范围更广；而pro版更侧重隐私保护，会存在误杀，去广告效果更为激进，会导致一些app使用异常或网页显示被破坏。这两个区分是我的定位，大家有更好的建议么？

注：两个版本均无收费计划，会一直开源下去

**Comment by uniartisan** [comment]
**以下仅为个人看法**
1. 已过期域名可以尝试写一个通过海外 DNS 批量解析查看是否是 NXDOMAIN, 如果是的话表明是已过期域名，但不知道之前的方案是否是这样实现的。

 - 已经失效的域名自动写入一个新的文件，例如 *domain_doesnt_resist.txt*，再次批量解析可以跳过这些域名，生成规则的时候在最后生成文件的时候脚本自动剔除这些失效域名
- 对于已经失效的域名，一段时间可以重复解析，如果有重新生效的则移除黑名单

2.  非常支持 public 和 pro 版本，但个人认为 public 和 geek 更为合适，public 的更新缓慢而 geek 会尝试更多的上游源，等确认无误后再适当选择规则合入public， public尽可能做到不误杀， 拦截且只拦截广告和追踪域名，和public并列的还可以有beta， beta是geek和public的中间渠道，主要是为了使得合入public前可以得到较为广泛的测试。

**Comment by gentlyxu** [comment]
非常感谢。

> 已过期域名可以尝试写一个通过海外 DNS 批量解析查看是否是 NXDOMAIN, 如果是的话表明是已过期域名，但不知道之前的方案是否是这样实现的。

是这么实现的，但查的是国内dns server，这么选择的考虑是大家都在国内使用。同时还做了对返回nxdomain的主域名还会去查一次whois，除了效率不高外，还有结果不准确的问题。这条的实现上，原理应该就是这个了，还有实现上的细致建议就更好了

叫什么名字并不重要，引入beta版本是另一个话题了，public版本和pro版本同样都是release版本，不是拿来测试的，有误杀报告会根据不同侧重点来考量赦免

**Comment by Eccon** [comment]
可否增加用于 Clash 的列表？格式和 Surge 的差不多

官方文档格式

```
payload:
  - DOMAIN-SUFFIX,google.com
  - DOMAIN-KEYWORD,google
  - DOMAIN,ad.com
  - SRC-IP-CIDR,192.168.1.201/32
  - IP-CIDR,127.0.0.0/8
  - GEOIP,CN
  - DST-PORT,80
  - SRC-PORT,7777
  # MATCH is not necessary here
```

参考：
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Adobe.yaml

**Comment by gentlyxu** [comment]
> 可否增加用于 Clash 的列表？格式和 Surge 的差不多
> 
> 官方文档格式
> 
> ```
> payload:
>   - DOMAIN-SUFFIX,google.com
>   - DOMAIN-KEYWORD,google
>   - DOMAIN,ad.com
>   - SRC-IP-CIDR,192.168.1.201/32
>   - IP-CIDR,127.0.0.0/8
>   - GEOIP,CN
>   - DST-PORT,80
>   - SRC-PORT,7777
>   # MATCH is not necessary here
> ```
> 
> 参考：
> https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Adobe.yaml

暂无计划。因为每增加一种格式支持，就会有更多的人问怎么配置。anti-AD希望把更多的精力聚焦在去广告能力上

**Comment by sr093906** [comment]
1. https://github.com/funilrys/PyFunceble; https://github.com/dead-hosts. (Note: I have no experience with them.)
2. Off-topic. Could you assess the lists labeled with language tag 'zh' on filterlists.com to include some more sources related to China?

**Comment by gentlyxu** [comment]
OK, got it.I'll take a hard look at both addresses you provided.As for the second part,I took a quick look and have included the anti-AD...Many of those other ones are already included in the upstream sources of anti-AD, so let me take a closer look at how to make anti-AD better~

**Comment by nzm001** [comment]
给你一个减负的理由，剔除过期域名功能可以有，但没必要深入。剔除过期域名主要是为了性能，但是根据我在树莓派zero（极其孱弱的单核芯片，博通 BCM2835 芯片 1GHz ARM11 core，RaspberryPi OS Buster&AdGuard Home）上的使用，5万条规则与12万条规则的处理速度大概只差1ms，或许都没，cpu占用没涨多少。相对应，在树莓派zero上面加密DNS（例如dot用8.8.8.8:853），一个手机的DNS查询就可以让其宕机。所以即使有几万条无效域名过滤规则，也没有一个加密DNS的负载高。因此推测，即使对于手机来说soc性能较弱，减少无效域名带来的性能提升微乎其微？（不敢肯定，手机上没试过，DNS过滤都在软路由上，方便劫持53端口）

期待pro上线，误杀可以发现并改进，漏杀难以发现。只要知道怎么自定义放行规则，肯定是激进的好，漏杀需要提取全部DNS记录，一条一条核对，要命。更何况，有些人认为某域名是误杀，但是对于不需要这些服务的人来说是true positive。
