### ISSUE TITLE
[误杀] netlify.com

### ISSUE THREAD

**Issue by harryhpxs** [privacy-protection-tools/anti-AD#178]
域名：netlify.com
发生时间：2020年7月13日
使用的列表： anti-ad-easylist.txt
问题描述：
||netlify.com^
该规则通杀了netlify.com托管的所有域名，e.g., zh-hans.reactjs.org

**Comment by gentlyxu** [comment]
你这个eg我没有找到一个跟netlify.com相关的域名，有对应的具体的url么？相关页面更好

**Comment by harryhpxs** [comment]
> 
> 
> 你这个eg我没有找到一个跟netlify.com相关的域名，有对应的具体的url么？相关页面更好

![图片](https://user-images.githubusercontent.com/3590410/87326883-e7d3af00-c565-11ea-83fb-e577ffa7472c.png)
AdGuard Home的截图

**Comment by gentlyxu** [comment]
已修复。
