### ISSUE TITLE
[建议]增加adaway版的订阅链接

### ISSUE THREAD

**Issue by Leisuredpootle** [privacy-protection-tools/anti-AD#18]
希望可以增加形如yhost这种类型的安卓端adaway可用订阅链接
例子：
https://github.com/vokins/yhosts/blob/master/hosts

**Comment by gentlyxu** [comment]
感谢建议。首先，hosts格式是比较冗长的，例如屏蔽某个域名和它所有的子域名（假设有100个子域名），那么hosts规则至少是101条，而dnsmasq格式或者easylist格式一条规则就可以搞定，而且若新增子域名，hosts规则必须马上跟进才能保持有效。这也是本项目从hosts格式转换到dnsmasq格式的一个主要原因。

当然，我们上游的规则是有hosts格式的，anti-AD在使用时会生成一个中间结果，并且会经常更新，如果你需要，可以试试 https://github.com/privacy-protection-tools/anti-AD/raw/master/origin-files/base-src-hosts.txt ，这个文件仅合并去重了上游规则，未做其他任何修正

**Comment by Leisuredpootle** [comment]
> 感谢建议。首先，hosts格式是比较冗长的，例如屏蔽某个域名和它所有的子域名（假设有100个子域名），那么hosts规则至少是101条，而dnsmasq格式或者easylist格式一条规则就可以搞定，而且若新增子域名，hosts规则必须马上跟进才能保持有效。这也是本项目从hosts格式转换到dnsmasq格式的一个主要原因。
> 
> 当然，我们上游的规则是有hosts格式的，anti-AD在使用时会生成一个中间结果，并且会经常更新，如果你需要，可以试试 https://github.com/privacy-protection-tools/anti-AD/raw/master/origin-files/base-src-hosts.txt ，这个文件仅合并去重了上游规则，未做其他任何修正

好的，谢谢你
