### ISSUE TITLE
[新增拦截] yootoo6oocoo1oo.xyz

### ISSUE THREAD

**Issue by scomper** [privacy-protection-tools/anti-AD#180]
域名:yootoo6oocoo1oo.xyz
出现场景：局域网 AdGuard Home 监测到的异常访问
补充说明：疯狂访问一堆二级域名随机的地址。
<img width="914" alt="CleanShot 2020-07-14 at 15 19 23@2x" src="https://user-images.githubusercontent.com/13041847/87396581-9ec33f80-c5e5-11ea-9504-6f5097e2538e.png">

**Comment by scomper** [comment]
查到原因了，是部门同事使用的一个代理软件（ShadowsocksR-dotnet2.0.exe），只要打开代理软件，后台就不停的请求 N 多个域名。

**Comment by gentlyxu** [comment]
额。。。
