### ISSUE TITLE
[误杀] h-adashx.ut.taobao.com / retcode.taobao.com

### ISSUE THREAD

**Issue by luzhaohui** [privacy-protection-tools/anti-AD#181]
域名：h-adashx.ut.taobao.com / retcode.taobao.com
发生时间：每天
使用的列表： anti-ad-domains.txt / anti-ad-surge.txt
问题描述：钉钉会访问这个域名，不知道这个域名在干什么，反正被 REJECT 了，偶尔会导致钉钉无法正常运行。

**Comment by gentlyxu** [comment]
`h-adashx.ut.taobao.com` 基本上市面上的屏蔽列表都收录了，应该不是误杀吧。`

另外搜索到这个地址：
`http://retcode.taobao.com/r.png?uid=4e6642cf-3988-4931-b843-1b308f2930e6&userNick=&times=1&_t=-15698432473&tag=&api=articleDetailService&issucess=true&delay=437&msg=success&detail=&type=retcode&sampling=1&spm=a2700.8293689,alibaba.com` 

请自行决定放行与否

**Comment by luzhaohui** [comment]
再提这个问题：
1、h-adashx.ut.taobao.com，问题不大，杀掉也不影响使用。
2、retcode.taobao.com，这个真的影响使用，尤其是钉钉，一进入办公审批流程就卡住了；我觉得不应该只有我个人遇到了这个问题，虽然我自己是放行了，但还是觉得应该提出来。

**Comment by c2xusnpq6** [comment]
> 
> 
> `h-adashx.ut.taobao.com` 基本上市面上的屏蔽列表都收录了，应该不是误杀吧。`
> 
> 另外搜索到这个地址：
> `http://retcode.taobao.com/r.png?uid=4e6642cf-3988-4931-b843-1b308f2930e6&userNick=&times=1&_t=-15698432473&tag=&api=articleDetailService&issucess=true&delay=437&msg=success&detail=&type=retcode&sampling=1&spm=a2700.8293689,alibaba.com`
> 
> 请自行决定放行与否

基本上市面上的屏蔽列表都收录了???
