### ISSUE TITLE
[误杀] 腾讯翻译

### ISSUE THREAD

**Issue by inkss** [privacy-protection-tools/anti-AD#182]
域名：otheve.beacon.qq.com

主要是想问问这个域名是什么，在腾讯翻译 https://fanyi.qq.com/ 的页面，疯狂循环请求这个地址

**Comment by gentlyxu** [comment]
上报统计的，不属于误杀。自己决定是否加白。

**Comment by inkss** [comment]
好的，也是

**Comment by 0neday** [comment]
域名，otheve.beacon.qq.com，实测，与腾讯视频pc端，播放列表有关

**Comment by PlexPt** [comment]
beacon.qq.com
腾讯灯塔 收集隐私的

**Comment by magicdawn** [comment]
再提供一个来源 mac 搜狗输入法, block 这个域名后还继续疯狂请求...

**Comment by xiebaiyuan** [comment]
【误杀】

**Comment by josephgu41** [comment]
block后疯狂请求怎么办啊日志里看着好烦

**Comment by zongolia** [comment]
> block后疯狂请求怎么办啊日志里看着好烦

adguardhome的DNS设置里面，在"不允许的域名"功能中添加该域名,可以直接拒绝解析不记录日志。
