### ISSUE TITLE
[误杀] 新浪财经app

### ISSUE THREAD

**Issue by KyonCN** [privacy-protection-tools/anti-AD#183]
域名 d8.sina.com.cn
发生时间：2020年07月17日
使用的列表：https://cdn.jsdelivr.net/gh/privacy-protection-tools/anti-AD/anti-ad-easylist.txt
问题描述：新浪财经app 股票大盘k线信息等被拦截

手动放行
 d8.sina.com.cn 
d1.sina.com.cn
就可以正常显示

**Comment by gentlyxu** [comment]
你所提供的域名确实会被规则 `/^(\S+\.)?d[\d]+\.sina(img)?(\.com)?\.cn/` 拦截，我下载了新浪财经app，显示似乎正常。
![IMG_0864](https://user-images.githubusercontent.com/1243610/87848864-879e8d80-c916-11ea-993d-de8c62945183.PNG) ![IMG_0863](https://user-images.githubusercontent.com/1243610/87848869-9127f580-c916-11ea-917b-36b34841a8aa.PNG)
![IMG_0862](https://user-images.githubusercontent.com/1243610/87848873-971dd680-c916-11ea-8fa5-76f54d53f685.PNG)

你再确认一下看看，有问题欢迎继续交流

**Comment by KyonCN** [comment]
目前无法复现 访问这两个地址 
我等周一开盘再看一下 
确实是放行后实时数据才显示 可能目前不是实时数据 所以请求地址不同

**Comment by gentlyxu** [comment]
好的

**Comment by KyonCN** [comment]
目前还是无法复现 访问这两个地址  有点奇怪 issue我先关了吧
