### ISSUE TITLE
[误杀] 今日头条app的搜索功能

### ISSUE THREAD

**Issue by 82kg** [privacy-protection-tools/anti-AD#184]
域名：nativeapp.toutiao.com
发生时间：2020年07月19日
使用的列表： dns列表
问题描述：今日头条app里的 搜索框，无法搜索内容

**Comment by gentlyxu** [comment]
实测并未发现访问此域名的记录

**Comment by loyingEcu** [comment]
![1595695787217](https://user-images.githubusercontent.com/22834701/88461872-075dc680-ceda-11ea-8746-86477fcdadf7.jpg)
![1595695799408](https://user-images.githubusercontent.com/22834701/88461877-0d53a780-ceda-11ea-89f2-3fc98b6135e5.jpg)

is.snssdk.com这个会造成搜索框的内容加载失败
sf*-ttcdn-tos.pstatp.com这个会造成搜索的内容一些图片加载失败
