### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by hplee0120** [privacy-protection-tools/anti-AD#185]
域名：re.taobao.com
域名:gma.alicdn.com
域名:simba.taobao.com (click.mz.simba.taobao.com)
域名:show.1688.com
域名:dj.1688.com

发生时间：xxx年xx月xx日
使用的列表： adguard home过滤列表
问题描述：淘宝网页首页今日热卖和今日热卖网页的"发现喜欢滚动推荐“和1688首页的抢购和首页最瞩目的最大图片的那个滚动热点会场推荐

**Comment by hplee0120** [comment]
> 域名：re.taobao.com
> 域名:show.1688.com
> 域名:dj.1688.com
> 发生时间：xxx年xx月xx日
> 使用的列表： adguard home过滤列表
> 问题描述：淘宝网页首页今日热卖和1688首页的抢购和首页最瞩目的最大图片的那个滚动热点会场推荐

**Comment by gentlyxu** [comment]
那些所谓的热卖和 系统推荐、热点推荐 不属于广告么？

**Comment by hplee0120** [comment]
> 那些所谓的热卖和 系统推荐、热点推荐 不属于广告么？

那个发现热卖的确算是广告吧，但是实际过滤效果只去除了一部分，框架还在，看起来还不如让它显示出来。可能是我太多强迫症了。然后是那个show.1688.com和dj.1688.com的问题。1688首页最大的横幅（会场）dj.1688.com包括在他下方的两个抢购show.1688.com。这顶多算指南或者导航吧。实际过滤效果是直接将这两个图片导航跳转的二级网页show.1688.com和dj.1688.com全部干掉了。

**Comment by gentlyxu** [comment]
`show.1688.com` 和`re.taobao.com`并不是只用来加载图片的，很多投放广告使用了这个域名，请自行决定是否加白

**Comment by gentlyxu** [comment]
`gma.alicdn.com`相关的
http://gma.alicdn.com/simba/img/TB1_RMJJFXXXXaBXFXXSutbFXXX.jpg_q50.jpg

**Comment by hplee0120** [comment]
> `show.1688.com` 和`re.taobao.com`并不是只用来加载图片的，很多投放广告使用了这个域名，请自行决定是否加白

我猜你实际并没有使用电脑打开1688网页点击首页的推荐之类。。问题就是出在show.1688.com和re.taobao.com并不局限于某些图片链接，而是这两个域名是他们网站的某一个入口和站点，关键这个站点还是放在首页最醒目的位置。比如首页最大的图片推荐的家居节/数码电子会场/潮流服饰会场。点击进去后都是采用show.1688.com/xx/xx/或者dj.1688.com/xx/xx的域名。

**Comment by hplee0120** [comment]
感谢建议，个人已加白。个人想法是不太应当在去广告的前提下需要阉割正常服务内容

**Comment by gentlyxu** [comment]
感谢建议，一个广告过滤列表是没有办法满足所有人的不同需求的，会经过隐私保护和正常使用之间的权衡来决定是否放行。另外，anti-AD是不建议使用于办公网络环境的
