### ISSUE TITLE
[新增拦截]两个劫持跳转域名。

### ISSUE THREAD

**Issue by yuexiaduzhuo123** [privacy-protection-tools/anti-AD#187]
域名:
aa.shgansheng.cn
7202019monday.sgbbc.cn
出现场景：百度搜索，一条中关村在线的结果，点开强制跳转到了两个广告页面
https://7202019monday.sgbbc.cn/uc/llq_65/p4830z.html?f=1&i=1
https://aa.shgansheng.cn/safe/pot/iui/index.html?6101595245409&pkg=31
补充说明：

**Comment by gentlyxu** [comment]
已添加，同时其页面关联到的域名一并添加了黑名单
