### ISSUE TITLE
[误杀]淘宝桌面网站搜索结果无法点击

### ISSUE THREAD

**Issue by zhoubug** [privacy-protection-tools/anti-AD#188]
域名：click.simba.taobao.com 
发生时间：2020年07月21日
使用的列表： dns列表
问题描述：在淘宝网站搜索结果无法点击，click.simba.taobao.com  域名报错 
                 应该和列表文件anti-ad-for-dnsmasq.conf  里的simba.taobao.com 有关
                 手动删除simba.taobao.com这行后访问正常

**Comment by gentlyxu** [comment]
确认了一下，搜索结果中的“广告”，会点击这个域名，其他结果正常打开。既然是广告，就不加白了
