### ISSUE TITLE
adgk项目转移了仓库

### ISSUE THREAD

**Issue by Leisuredpootle** [privacy-protection-tools/anti-AD#189]
`https://github.com/banbendalao/ADgk`
![1ea3781ff08b05a3fca5191057774d8](https://user-images.githubusercontent.com/50063366/88023003-db051b80-cb62-11ea-9231-a713c858ec4d.jpg)
@gentlyxu

**Comment by gentlyxu** [comment]
感谢告知，我稍后更新adgk的源地址，并且也正在着手迁出gitee
