### ISSUE TITLE
[误杀] /^track(er|ing)?\\./ 毒性太大 误伤严重

### ISSUE THREAD

**Issue by Mosney** [privacy-protection-tools/anti-AD#19]
会将域名包含了`tracker`的BT tracker一起杀掉，误伤范围太大

**Comment by gentlyxu** [comment]
早在数天前已经修复，见 d4f2929f572dee270516590182b2836c2019b65f ，你可以更新规则试试

https://github.com/privacy-protection-tools/anti-AD/blob/d4f2929f572dee270516590182b2836c2019b65f/anti-ad-easylist.txt#L1568

**Comment by Mosney** [comment]
我给AGH设置的更新间隔是12小时，按理说早就应该覆盖掉了啊

**Comment by Mosney** [comment]
可能是我用的JSdeliver缓存导致的，还是用GitHub直链吧

**Comment by gentlyxu** [comment]
anti-ad-easylist.txt 文件头部有版本号的，你可以对比一下GitHub raw对应文件看看版本差多少

通过 Outlook<https://aka.ms/qtex0l> for iOS
________________________________
发件人: MosDos <notifications@github.com>
发送时间: Tuesday, January 28, 2020 8:11:21 PM
收件人: privacy-protection-tools/anti-AD <anti-AD@noreply.github.com>
抄送: gently <gently@live.cn>; Assign <assign@noreply.github.com>
主题: Re: [privacy-protection-tools/anti-AD] [误杀] /^track(er|ing)?\\./ 毒性太大 误伤严重 (#19)


可能是我用的JSdeliver缓存导致的，还是用GitHub直链吧

―

**Comment by Mosney** [comment]
的确是JSdeliver缓存导致的，这个加速链接还是只给访问GitHub有困难的用户用吧

**Comment by Mosney** [comment]
不过刚手动浏览器打开确认了一下加速链接的版本跟GitHub直链是一致的…那还有可能是AGH那边的问题？

**Comment by gentlyxu** [comment]
不太可能
