### ISSUE TITLE
建议将白名单也输出一份列表

### ISSUE THREAD

**Issue by CalmLong** [privacy-protection-tools/anti-AD#190]
感谢 `anti-AD` 提供的域名列表。

`anti-AD` 提供的国内广告域名算是很全面了，但实际应用中难免会有些域名不存在。因此通常会配合好几个列表一起使用。

但由于各个列表之间无关联，会出现 `anti-AD` 已经将域名 `A` 移除黑名单了，但是另一个列表中还存在域名 `A` 的情况，最后域名 `A` 还是会被拦截。

看到项目中存在 lib/white_domain_list.php 白名单文件，但是并不容易解析。

使用其他规则带来的问题不应该由 `anti-AD`  来处理，此 issue 的本意仅希望作者可以输出一份白名单，谢谢。

**Comment by gentlyxu** [comment]
放在这里了：
https://raw.githubusercontent.com/privacy-protection-tools/dead-horse/master/anti-ad-white-list.txt

（每3天自动同步更新一次txt）
