### ISSUE TITLE
[误杀]爱问知识人误杀

### ISSUE THREAD

**Issue by ShureCool** [privacy-protection-tools/anti-AD#194]
域名：iask.cn
iask.com.cn
发生时间：2020年7月26日
使用的列表： /anti-ad-smartdns.conf
问题描述：访问爱问知识人，界面不显示图片和背景，只有文字，用IE二次确认也一样，希望排查下

**Comment by gentlyxu** [comment]
这个域名挂载了很多广告，爱问网站的内容质量也非常差，没有必要放行
