### ISSUE TITLE
[新增拦截]i0.hdslb.com/bfs/sycp/creative_img/

### ISSUE THREAD

**Issue by JOJOforshaun** [privacy-protection-tools/anti-AD#195]
域名:i0.hdslb.com/bfs/sycp/creative_img/
出现场景：哔哩哔哩桌面网站播放视频的网页中
补充说明：
![image](https://user-images.githubusercontent.com/63553362/88481832-46e6ea00-cf90-11ea-8a34-0f75c3c024bb.png)

**Comment by gentlyxu** [comment]
这个域名不能封杀，影响正常显示
