### ISSUE TITLE
[误杀] cm.bilibili.com

### ISSUE THREAD

**Issue by Hades-001** [privacy-protection-tools/anti-AD#196]
域名：cm.bilibili.com
发生时间：2020年7月26日
使用的列表： adblock-for-dnsmasq.conf
问题描述：

哔哩哔哩主页图片无法加载

**Comment by gentlyxu** [comment]
没有遇到过。也没有抓到对应的包，来个被拦截的图片的URL吧

**Comment by Hades-001** [comment]
![捕获](https://user-images.githubusercontent.com/30254702/88483178-bc56b880-cf98-11ea-97c4-ac1867fd8948.PNG)

**Comment by gentlyxu** [comment]
肯定不是`cm.bilibili.com`这个域名，这个域名是用于行为统计的，你再检查一下吧

**Comment by Hades-001** [comment]
今天正常了。。。打扰了，实在抱歉。

**Comment by Karmylr** [comment]
cm.bilibili.com就是b站的广告域名啊 没有误杀

**Comment by EuropeanWithSSR** [comment]
![image](https://user-images.githubusercontent.com/39738950/161114654-742635df-673b-4cce-81c1-cafce7836e2d.png)
网页下愚人节活动链接的域名为cm.bilibili.com，访问后跳转至https://www.bilibili.com/blackboard/activity-3OfSTfVzwg.html?msource=search1

**Comment by itning** [comment]
这个轮播广告也需要杀掉吗？
![image](https://user-images.githubusercontent.com/19759891/179263187-6ffa2e6e-29a8-4bcc-8741-2111b6a8ede1.png)
