### ISSUE TITLE
[新增拦截]adim.pinduoduo.com

### ISSUE THREAD

**Issue by YH0426** [privacy-protection-tools/anti-AD#197]
域名:adim.pinduoduo.com
pangolin.snssdk.com
出现场景：
![image](https://user-images.githubusercontent.com/18507944/88496538-06b75400-cff0-11ea-84a5-74c737333d39.png)

补充说明：
出现在拼多多针对第三方应用投放的广告中

**Comment by gentlyxu** [comment]
已经被上游列表收录，issue我关闭了哈
