### ISSUE TITLE
[误杀]BT种子服务器 tracker.bittor.xyz 不幸中标

### ISSUE THREAD

**Issue by qpzr** [privacy-protection-tools/anti-AD#199]
22:32:09
2020/7/29
tracker.bittor.xyz
类型: A, 无加密DNS
按CNAME或IP拦截

响应细节
状态
按CNAME或IP拦截
DNS 服务器
127.0.0.1:6553
耗时
7 毫秒
响应代码
NXDOMAIN
过滤器
esaylist.txt
规则
||parkingcrew.net^
原始响应
CNAME: 467477.parkingcrew.net. (ttl=260)
A: 185.53.179.29 (ttl=84)

**Comment by gentlyxu** [comment]
不对，我发现`parkingcrew.net`是个域名停泊服务，而 `tracker.bittor.xyz` 指向`467477.parkingcrew.net`，已经不再是bt tracker服务了，只是停泊在那里赚广告流量

**Comment by gentlyxu** [comment]
所以这个域名不需要加白，根本是个无用的域名
