### ISSUE TITLE
[误杀] 今日头条 新资讯

### ISSUE THREAD

**Issue by niphor** [privacy-protection-tools/anti-AD#201]
域名：is.snssdk.com
发生时间：2020年07月30日
使用的列表： adblock-for-dnsmasq.conf
问题描述：今日头条 Google Play版 7.4.2 下拉更新时会请求此域名获取新的咨询，过滤后无法下拉更新

**Comment by gentlyxu** [comment]
https://www.jianshu.com/p/b668bbb0cc82

**Comment by gentlyxu** [comment]
特地去Google play上下载了你说的版本，使用正常

**Comment by niphor** [comment]
@gentlyxu 嗯 是的 它不是每次都无法请求，可能上午没问题，下午就无法请求
我在出问题的时候，用代理简单的抓了个日志，每次下拉是触发请求 `is.snssdk.com`,它可能会缓存域名IP结果或者更换别的域名尝试，我没有详细的去测试

**Comment by gentlyxu** [comment]
`is.snssdk.com`这个域名并不是关键入口，你再抓包看看有没有其他接口
