### ISSUE TITLE
[误杀]虎扑app使用异常

### ISSUE THREAD

**Issue by woboo110** [privacy-protection-tools/anti-AD#202]
域名：虎扑app
发生时间：2020年07月30日
使用的列表：anti-ad-easylist.txt
问题描述：赛事新闻板块无法加载，推荐板块加载慢，其他板块也比较卡顿

**Comment by gentlyxu** [comment]
具体是android版还是iOS，有具体域名吗？加载慢和卡顿是不是提醒你该换手机啦？这个现象通常跟去广告没有关系。我作为不称职的JRs，也会去上面逛，但一直没有发现有什么问题，包括刚刚

**Comment by woboo110** [comment]
> 具体是android版还是iOS，有具体域名吗？加载慢和卡顿是不是提醒你该换手机啦？这个现象通常跟去广告没有关系。我作为不称职的JRs，也会去上面逛，但一直没有发现有什么问题，包括刚刚

骁龙855问题不大吧，安卓，其他人没问题的话看来是我的问题，我再排查下网络，谢谢
