### ISSUE TITLE
gitee链接失效

### ISSUE THREAD

**Issue by leonwahy** [privacy-protection-tools/anti-AD#203]
您好！首先非常感谢您的分享，致敬！
26号开始Gitee的链接已经失效，以后是否连接这里的官网地址即可，今后会长期保留吧？
另外规则里面有个放行的网址“467477.parkingcrew.net”，不知这个是？

**Comment by gentlyxu** [comment]
关于删除gitee的镜像，我在adgh这里做了详细说明：https://github.com/AdguardTeam/AdGuardHome/issues/1903 , `anti-ad.net`的官网域名将一直保留，此处github的官方repo也会一直维护下去。

`467477.parkingcrew.net` 的放行域名是 issue #199 的误杀报告。

**Comment by leonwahy** [comment]
谢谢！！
