### ISSUE TITLE
[误杀]Geforce experience消息通知

### ISSUE THREAD

**Issue by sky96111** [privacy-protection-tools/anti-AD#205]
域名：events.gfe.nvidia.com
发生时间：2020年8月2日
使用的列表：anti-ad-easylist.txt
问题描述：此域名不产生广告推送，用于英伟达消息通知（可领取奖励），可在设置中关闭。并且屏蔽后会导致安装了Geforce Experience的电脑无限轮询尝试访问该域名，使Adguardhome产生大量干扰log

**Comment by gentlyxu** [comment]
这个域名会收集客户端标识，你可以参考 #97 ，是经过测试才加入的，市面上大多数过滤列表也都将此域名加入了屏蔽。如果你确实需要关注消息通知和领取奖励，请自行放行。

关于基于无限尝试产生大量log这个理由来放行。我必须纠正，一个笼子里关了猛兽，不能因为它成天大喊大叫就把它放出来害人吧？

**Comment by sky96111** [comment]
> 这个域名会收集客户端标识，你可以参考 #97 ，是经过测试才加入的，市面上大多数过滤列表也都将此域名加入了屏蔽。如果你确实需要关注消息通知和领取奖励，请自行放行。
> 
> 关于基于无限尝试产生大量log这个理由来放行。我必须纠正，一个笼子里关了猛兽，不能因为它成天大喊大叫就把它放出来害人吧？

确实，如果不是因为他在一天内轮询了5000次我也不会注意到他，但其实主要原因是我以为它只是用于获取通知，不知道他会上传用户标识
