### ISSUE TITLE
[误杀]DNS诊断工具whoami

### ISSUE THREAD

**Issue by sky96111** [privacy-protection-tools/anti-AD#208]
域名：whoami.akamai.net
发生时间：2020年8月2日
使用的列表： anti-ad-easylist.txt
问题描述：whoami是一款DNS工具，常用于诊断CDN，无广告推送行为

**Comment by gentlyxu** [comment]
实际监测发现的行为是某些app用这个收集客户端的真实IP，然后上报，你自己决定是否放行吧

**Comment by sky96111** [comment]
> 实际监测发现的行为是某些app用这个收集客户端的真实IP，然后上报，你自己决定是否放行吧

这就像某些国家有人是极端分子然后就禁止所有来自那个国家的人流入的做法，是不合理的。如果以后有人通过CDN投放广告，那么那个CDN也会被禁止吗?这么激进的做法，用在普遍使用的屏蔽列表中，会出大问题的

**Comment by gentlyxu** [comment]
感谢你的用心体验和宝贵意见。你稍微查看closed 的 issues列表，就知道屏蔽并不激进。

你的比喻偷换概念，首先屏蔽`whoami.akamai.net`不影响绝大多数用户正常上网，也不影响akamai CDN的正常使用，没有封锁哪家CDN。你可以搜索一下过滤列表中的`.cloudfront.net`，可以进一步佐证anti-AD不是激进的过滤列表

是这样的，anti-AD会将保护隐私、去广告放在首位，对于影响大多数人使用的规则，或者屏蔽域名中既是广告域名，同时又是正常链接也用到的域名，会加入白名单处理，而轻微影响的或者极个别的个性需求，官方推荐大家自行加白，毕竟每个人的需求千差万别，如果满足所有人，那anti-AD的将不能过滤任何域名

**Comment by gentlyxu** [comment]
我查看了官方介绍 https://developer.akamai.com/blog/2018/05/10/introducing-new-whoami-tool-dns-resolver-information

似乎这个域名也会退役了，推荐用`whoami.ds.akahelp.net` ?

**Comment by sky96111** [comment]
> 我查看了官方介绍 https://developer.akamai.com/blog/2018/05/10/introducing-new-whoami-tool-dns-resolver-information
> 
> 似乎这个域名也会退役了，推荐用`whoami.ds.akahelp.net` ?

所以你会把新域名..也屏蔽?回到举例，某个国家的人很少入境另一国，禁止那个国家的人流入不会影响到绝大多数人的出入境，这明显还是不合理的。我个人已经把他加进了白名单，不过考虑到普适性，这个域名是一个正常的域名，只不过是被某些人利用做了恶，禁掉源站不是合适的解决方案

**Comment by sky96111** [comment]
> 感谢你的用心体验和宝贵意见。你稍微查看closed 的 issues列表，就知道屏蔽并不激进。
> 
> 你的比喻偷换概念，首先屏蔽`whoami.akamai.net`不影响绝大多数用户正常上网，也不影响akamai CDN的正常使用，没有封锁哪家CDN。你可以搜索一下过滤列表中的`.cloudfront.net`，可以进一步佐证anti-AD不是激进的过滤列表
> 
> 是这样的，anti-AD会将保护隐私、去广告放在首位，对于影响大多数人使用的规则，或者屏蔽域名中既是广告域名，同时又是正常链接也用到的域名，会加入白名单处理，而轻微影响的或者极个别的个性需求，官方推荐大家自行加白，毕竟每个人的需求千差万别，如果满足所有人，那anti-AD的将不能过滤任何域名

我注意到你提及了 **或者屏蔽域名中既是广告域名，同时又是正常链接也用到的域名，会加入白名单处理** 只能说这比较小众吧。但如果只是获取IP的话，经常用来测试代理的cip.cc、ip.cn也是可以达到相应的效果，那我只需要curl cip.cc然后将结果发回我的服务器，我的服务器应该被加入禁止名单而不是cip.cc，他只是一个提供查询的工具啊

**Comment by gentlyxu** [comment]
真是个杠精。我上面说了监测到有app恶意利用此域名来获取用户的真实IP，你要扯到哪里去？什么cip.cc,ip.cn的，我是无言以对啊。你先定义anti-AD是激进的，我告诉你为什么他不是激进的。我说了`whoami.akamai.net`为什么被屏蔽，你说他是正常域名，我说**anti-AD会将保护隐私、去广告放在首位**，你给我扯其他的情况，这是什么理解能力啊？

> 我查看了官方介绍 https://developer.akamai.com/blog/2018/05/10/introducing-new-whoami-tool-dns-resolver-information
> 似乎这个域名也会退役了，推荐用whoami.ds.akahelp.net ?

我这个话的本意是提醒你切换到新域名，你给我理解成我要屏蔽这个域名。你自己看看anti-AD列表中的所有域名，哪一个是这么随意就给屏蔽了的？

就这样了，实在没有那么多精力陪你瞎扯。。。。

**Comment by sky96111** [comment]
因为它既不符合你所说的广告域名，同时也是正常链接用到的域名。而上传IP不是他的行为。
你非要屏蔽，也随便，对于个人加例外就是了。我没有觉得你会屏蔽掉新域名，只是玩笑。我一直在举例说明为什么不应该屏蔽这个域名，如果这也叫杠的话。命中率最高，不应该是误杀率最高
