### ISSUE TITLE
[新增拦截]ad.ettoday.net和yahoo.net

### ISSUE THREAD

**Issue by edentc** [privacy-protection-tools/anti-AD#21]
域名1:ad.ettoday.net
出现场景：m.ettoday.net
补充说明：
||msg.ettoday.net^
请修改成:
||ad.ettoday.net^

域名2:yahoo.net
出现场景：tw.mobi.yahoo.com
补充说明：相关的广告副服务器之一

**Comment by gentlyxu** [comment]
ad.ettoday.net 已经被 `/^ad([0-9]|m|s)?\./`规则合并，列表已经可以拦截该域名

yahoo.net 在您提供的页面中没有找到对应请求，经过搜索，yahoo.net亦不是广告所用域名，您是否可以提供更为详细的信息

**Comment by edentc** [comment]
你好:
https://tw.mobi.yahoo.com/news/%E6%89%8D%E8%AB%8B%E8%82%B2%E5%AC%B0%E5%81%87-%E6%97%A5%E6%9C%AC-%E6%9C%80%E5%B8%A5%E6%94%BF%E4%BA%8C%E4%BB%A3-%E4%B8%8D%E5%80%AB%E6%BF%95%E8%A8%8A%E6%9B%9D%E5%85%89-050821280.html
他算是这里的广告视频.
所以依你之見直接針對這條,是否比較恰當?
edgecast-vod.yahoo.net

**Comment by gentlyxu** [comment]
<img width="884" alt="2020-01-3023 09 33" src="https://user-images.githubusercontent.com/1243610/73461833-c6b34380-43b5-11ea-8b61-d70891d89412.png">

我打开此页面没有看到视频广告，yahoo.net加载的是一个正常视频哟

**Comment by gentlyxu** [comment]
![2020-01-3023 19 57](https://user-images.githubusercontent.com/1243610/73462870-658c6f80-43b7-11ea-87ae-d5b5b1aac2bf.png)
如果你说的是视频下方的广告图，它的url是 https://s.yimg.com/av/ads/1578018095365-8924.jpg ，这个不能通过屏蔽s.yimg.com来解决，因为s.yimg.com域名涉及太多正常资源了

**Comment by edentc** [comment]
ok,就這樣，他的太難弄了

**Comment by gentlyxu** [comment]
如果你使用Chrome浏览器，可以试试 uBlock Origin

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

它的拦截效果非常棒，能够拦截url path中带有广告的链接
