### ISSUE TITLE
你好anti-AD不能使用在Adblock Plus上吗?

### ISSUE THREAD

**Issue by LsnmxNB** [privacy-protection-tools/anti-AD#210]
提示  筛选器列表无效

**Comment by Leisuredpootle** [comment]
个人不建议订阅anti-AD到adblock上

**Comment by gentlyxu** [comment]
最好不要，因为Adblock Plus 起码是匹配整个URL的，也会匹配网页内容。而anti-AD仅针对域名进行过滤，一些模糊匹配和正则表达式会造成误杀，而无法单独为此修正

**Comment by SuTree** [comment]
目前使用uBlock Origin添加anti-ad-easylist.txt成功，使用效果不知道，等使用一段时间后再看看结果

**Comment by nzm001** [comment]
找个可以用的浏览器插件就行，如果发现误杀自己加白名单，宁可错杀一千不可放过一个
