### ISSUE TITLE
[误杀]pub.alimama.com

### ISSUE THREAD

**Issue by mjyhj** [privacy-protection-tools/anti-AD#214]
域名：pub.alimama.com
发生时间：2020年8月6日
使用的列表：https://anti-ad.net/anti-ad-for-dnsmasq.conf
问题描述：淘宝联盟用不了

**Comment by moxuanyuan** [comment]
直接屏蔽了alimama.com和alimama.cn

**Comment by mjyhj** [comment]
> 直接屏蔽了alimama.com和alimama.cn

所以不应该直接屏蔽这个顶级域名

**Comment by moxuanyuan** [comment]
> > 直接屏蔽了alimama.com和alimama.cn
> 
> 所以不应该直接屏蔽这个顶级域名

你说错了，是二级域名。。顶级域名是.com 和.cn
