### ISSUE TITLE
Remove Malwaredomainlist from the Source

### ISSUE THREAD

**Issue by sr093906** [privacy-protection-tools/anti-AD#218]
First, the list, a robust hosts file to block once-rampant malware/pup drive-by downloads back in early 2010s, remains unchanged since Jan.22 this year, and we don’t know whether the project has been abandoned for some reason (like the pandemic?). 

Second, of the total 1104 entries (http://www.malwaredomainlist.com/hostslist/hosts.txt), only 402 ones are still alive.(https://block.energized.pro/assets/sources/filter/malwaredomainlist.com.txt) Having a look at these active domains, you will notice many of them are ended with . de, .in, .br, . cz, . uk. I can reasonably assume not many of the netizens in China, the main user base of the list, will accidentally visit such domains in their daily life. 

Third, the list aims to block ad and tracking domains not the malware hosts. The most effective way to block such urls is to rely on a security software. Let us follow the Unix Philosophy: Make each program do one thing well.

**Comment by gentlyxu** [comment]
After a careful review, the usefulness of this list for Chinese regions is very low, it was too old. I'll remove it now. Thanks very much for your suggestion.

**Comment by sr093906** [comment]
Thanks for your reply. I'll close the issue now.
