### ISSUE TITLE
[误杀]淘宝粉丝福利购跳转失败

### ISSUE THREAD

**Issue by Leisuredpootle** [privacy-protection-tools/anti-AD#22]
域名：s.click.taobao.com
发生时间：2020年01月31日
使用的列表：anti-ad-easylist.txt,
问题描述：淘宝领卷后无法跳转，经检测被adguard home（仅使用该列表）屏蔽

**Comment by gentlyxu** [comment]
感谢反馈，已加白，jsdelivr有缓存，更新较慢，着急的话请使用raw链接
