### ISSUE TITLE
[误杀]迅雷手机端下载（具体域名不知道，不然像加白名单的）

### ISSUE THREAD

**Issue by shuaisle** [privacy-protection-tools/anti-AD#221]
域名：迅雷手机端下载（具体域名不知道，不然像加白名单的）
发生时间：2020年8月10日
使用的列表： （anti-ad-for-dnsmasq.conf）
问题描述：用的是路由器的去广告，adbyby plus+ 加载规则后效果很好，但是迅雷下载没速度了，去了规则之后下载就满速度。但是每次下载关去广告很麻烦，网上找了很久也没找到解决方法，麻烦作者大大看一下，谢谢

**Comment by gentlyxu** [comment]
我也好多年没有用过迅雷了，另外你说的插件我也不熟悉，刚刚我下载了手机迅雷，里面搜索了一个不知道啥电影，下载可以到50M/s（应该算有速度吧？就不截图了）。确实过滤了几个xunlei.com的子域名，但都不影响，由此基本上可以排查是误杀了。我的环境是adgh，我建议你再仔细排查一下，最简单方法是把xunlei.com的根域名加入白名单，如果还不行，就是工具设置的问题了

**Comment by shuaisle** [comment]
> 我也好多年没有用过迅雷了，另外你说的插件我也不熟悉，刚刚我下载了手机迅雷，里面搜索了一个不知道啥电影，下载可以到50M / s（应该算有速度吧？就不截图了）。确实过滤了几个xunlei.com的子域名，但都不影响，基本上可以排除是误杀了。我的环境是adgh，我建议你再仔细排查一下，最简单的方法是把xunlei.com的根域名加入白名单，如果还不行，就是工具设置的问题了

工具没问题，我之前用adguard home 也是一样的，速度不是完全没有，开规则只有一百多K/S，不开就正常，我下的是磁力种子，xunlei.com已近加过了，还是没用，排除以上，我怀疑是否是对BT下载有限制了，麻烦大佬有空看看，实在不行也没办法了，只能下载的时候关了去广告，不下再开了。不过有一说一，这个规则去广告真的好，家里的智能电视和开了会员一样，一点广告都没有

**Comment by gentlyxu** [comment]
我给issue关了，你才来回复，5天过去了，我以为没有问题了。。。

从迅雷拐到bt了，你的车能不能一直往前开？dns工具对bt下载协议是不会有影响的，两种可能：1.  你的网络硬件太烂，转发效率被影响了，从迅雷也被影响的现象来看，这个可能性比较大；2.  anti-AD屏蔽了你BT下载资源的tracker域名

**Comment by shuaisle** [comment]
> 我给issue关了，你才来回复，5天过去了，我以为没有问题了。。。
> 
> 从迅雷拐到bt了，你的车能不能一直往前开？dns工具对bt下载协议是不会有影响的，两种可能：1. 你的网络硬件太烂，转发效率被影响了，从迅雷也被影响的现象来看，这个可能性比较大；2. anti-AD屏蔽了你BT下载资源的tracker域名

真的很抱歉，我之前没注意，你把issue关了我才看到。网络硬件没问题，因为除了anti-ad，其他规则都不会限制迅雷下载（主要用于下载bt小电影）,但其他规则去广告效果不如anti-ad。那目前看来很有可能是第二种原因，tracker域名屏蔽了，这个有解决方案吗

**Comment by gentlyxu** [comment]
你说的是用手机迅雷下载磁力链，对吧？我以为是bt工具。把我说的两种可能排查一下，排查方法：下载一个热门资源，开广告屏蔽和不开，看看速度有没有区别；下载你要的资源，去域名拦截日志里查看所有可疑域名，加入白名单，再测试，一直到找到为止

**Comment by shuaisle** [comment]
> 你说的是用手机迅雷下载磁力链，对吧？我以为是bt工具。把我说的两种可能排查一下，排查方法：下载一个热门资源，开广告屏蔽和不开，看看速度有没有区别；下载你要的资源，去域名拦截日志里查看所有可疑域名，加入白名单，再测试，一直到找到为止

好的，麻烦你啦，谢谢。我去试试看
