### ISSUE TITLE
[误杀]miui的天气部分被拦截

### ISSUE THREAD

**Issue by zxp09** [privacy-protection-tools/anti-AD#222]
域名：不清楚
发生时间：2020年09月11日
使用的列表： （具体的文件，例如/anti-ad-easylist.txt）
问题描述：miui天气的最下面有一个是否适合洗车等建议的模块，然后是被拦截不能刷新。
好像不能发图片，我放到网盘上：http://caiyun.feixin.10086.cn/dl/0b5Csgrd89lcu  提取密码:pyeu

**Comment by gentlyxu** [comment]
没用过，也没有这个app，帮不了你啊

**Comment by zxp09** [comment]
如果需要的话我可以帮忙

**Comment by XMD0718** [comment]
相关域名：wtradv.market.xiaomi.com
@gentlyxu
