### ISSUE TITLE
您好！不知规则是否可以通用

### ISSUE THREAD

**Issue by leonwahy** [privacy-protection-tools/anti-AD#224]
比如是否支持koolproxy/adbyby/ssr？谢谢！

**Comment by gentlyxu** [comment]
这个需要你自己去尝试。`adblock-for-dnsmasq.conf` 是标准的支持dnsmasq的，`anti-ad-easylist.txt`是adblock风格的语法，有通配符和正则表达式，`anti-ad-domains.txt`是全域名过滤列表，每行一个域名，通常它的兼容性最好。

你提供的这些工具，有官方版和网友修改版，功能不尽相同，所以我也不确定是否兼容，要看看他们的支持哪些格式

**Comment by leonwahy** [comment]
谢谢！看了smartDNS、AGH规则好像有些不同，不知这几个规则有没有什么差别？分别的优缺点是什么？

**Comment by gentlyxu** [comment]
最大的不同是格式不一样，总体上来说对域名的屏蔽效果是差不多的。他们是从同样的源生成的结果

**Comment by leonwahy** [comment]
谢谢！
