### ISSUE TITLE
[误杀]quark.sm.cn

### ISSUE THREAD

**Issue by Nekomio** [privacy-protection-tools/anti-AD#225]
域名：quark.sm.cn
发生时间：2020年8月16日
使用的列表： anti-ad-easylist.txt
问题描述：
Adguard 中
||advert*.*^ 规则 误杀了 quark.sm.cn

**Comment by qpzr** [comment]
你应该说是夸克浏览器的ai搜索引擎整个报废了

**Comment by gentlyxu** [comment]
更新一下列表试试看

**Comment by Nekomio** [comment]
我这里正常了 谢谢
