### ISSUE TITLE
建议优化知乎去广告规则

### ISSUE THREAD

**Issue by XMD0718** [privacy-protection-tools/anti-AD#226]
目前在知乎的使用过程中，虽然没了开屏广告，使用体验有很大上升，但仍旧留存有一些问题。
针对这些问题，有酷基写了一篇教程介绍了一些针对性的规则。我希望能够把这些规则整合进anti-AD里，谢谢项目维护者了。
文章：https://www.coolapk.com/feed/19590470?shareKey=Mjg4NzlmMzFjZTc5NWYzYzkwZmI~&shareUid=1053243&shareFrom=com.coolapk.market_10.5

**Comment by gentlyxu** [comment]
感谢建议，这个要adguard层解密https才能做到。dns层的工具全都做不到。因此这些规则加进去也不会有效果
