### ISSUE TITLE
[误杀]虎牙

### ISSUE THREAD

**Issue by YeC1213** [privacy-protection-tools/anti-AD#228]
域名：bd.p2p.huya.com
发生时间：2020年8月**日
使用的列表：https://anti-ad.net/easylist.txt （具体的文件，例如/anti-ad-easylist.txt, /dist/anti-ad-surge-full.txt等等）
问题描述：
还杀了 statwup.huya.com，ylog.huya.com，tx2.p2p.huya.com不确定是哪一个，现象是会导致虎牙播放有频繁卡顿，网络是小带宽校园网(移动)

**Comment by gentlyxu** [comment]
同样的过滤列表，电信500M宽带，实测
https://www.huya.com/12323
半小时，没发现卡顿

**Comment by gentlyxu** [comment]
画质选的8M那个

你是否再重新测试一下？

**Comment by YeC1213** [comment]
没办法，只能手动放行

**Comment by gentlyxu** [comment]
首先说明一下，这条规则是从上游源继承过来的。查了一些资料和之前反馈的issues，这个p2p.huya.com应该是个p2p共享流量的东东，被屏蔽的最可能的原因是网友看不惯虎牙偷偷上传流量，不屏蔽可能会将上传带宽跑满和CPU居高不下（有相关讨论贴）。你的带宽略小，大概还是放行会体验更好。
