### ISSUE TITLE
[误杀]ip-api.com

### ISSUE THREAD

**Issue by NonCheng** [privacy-protection-tools/anti-AD#231]
域名：ip-api.com
发生时间：2020年8月xx日
使用的列表：anti-ad-domains.txt
问题描述：这个ip api挺好的  有些项目也在用  广告过滤不至于屏蔽api吧（？

**Comment by gentlyxu** [comment]
规则来自easyprivcy，这条规则收集用户ip地址，转换为归属地，经纬度等，涉及隐私泄漏，不属于误杀

**Comment by NonCheng** [comment]
好的 谢谢
