### ISSUE TITLE
[误杀]夸克浏览器自带的ai搜索

### ISSUE THREAD

**Issue by TianYaDY** [privacy-protection-tools/anti-AD#232]
域名：
发生时间：2020年8月25日
使用的列表：anti-ad-easylist.txt
问题描述：
使用手机上的夸克浏览器自带的ai搜索，会被拦截，确定是anti-ad规则拦截的。

**Comment by gentlyxu** [comment]
更新一下列表试试看

**Comment by TianYaDY** [comment]
> Thank you for opening your first issue in this repo. It’s people like you who make anti-AD better!

更新后情况复现。

**Comment by gentlyxu** [comment]
看这个 #225

**Comment by TianYaDY** [comment]
> 看这个 #225

事实上，有个怪事，前几天也误杀夸克，然后前两天好了，最后这几天又误杀了。难道又更新了？（ ￣O￣）ノノ

**Comment by TianYaDY** [comment]
> 看这个 #225

应该是更新后又误杀了。。。

**Comment by TianYaDY** [comment]
> 看这个 #225

谢谢！我找到原因了，antiad规则和雪花雨规则有冲突，单独订阅其中一种规则，夸克活得好好的，但两者一起，夸克就没了（搞不懂其中原理，但确实有这个现象）。

**Comment by gentlyxu** [comment]
> > 看这个 #225
> 
> 
> 
> 谢谢！我找到原因了，antiad规则和雪花雨规则有冲突，单独订阅其中一种规则，夸克活得好好的，但两者一起，夸克就没了（搞不懂其中原理，但确实有这个现象）。

你注意一开始你的描述，确定是anti-ad规则拦截的，把问题直接带到了错误的方向，若没有另一位朋友的报告，你这个问题会解决不了，订阅其他规则导致的冲突问题，本项目解决不了
