### ISSUE TITLE
[新增拦截]听云App性能监控

### ISSUE THREAD

**Issue by nzm001** [privacy-protection-tools/anti-AD#234]
域名:

```
#北京基调网络股份有限公司(听云)
apmcon.cn
cntingyun.com
networkbench.com
tingyun.com
#广州市动景计算机科技有限公司(UC)
appchaoshi.cn
appsmall.mobi
babybubble.cn
babymoment.net
blovestorm.com
coolppa.cn
dayu.com
effirst.cn
effirst.com
hdyzx.cn
minippa.cn
myquark.cn
open-uc.cn
qingzhou.biz
qingzhou.ltd
qingzhou.pro
quark.cn
tinya1.cn
tinyap2.cn
tinypap.cn
tinyppa.cn
u-mob.cn
ubibibi.com
uc.cn
uc123.com
ucdesk.cn
ucfly.com
ucweb.cn
ucweb.com
ucweb.com.cn
uflowx.com
xiaomengquan.cn
xmq123.cn
yun.cn
zjbuc.cn
zjbuc.com
zjbuc.com.cn
```

补充说明：8.26的anti-AD。

- 听云：tingyun.com域名已有，另外三个没有（只有dc1.networkbench.com，但除了dc1还有其他三级域名会被应用访问）。
- 广州市动景计算机科技有限公司（UC）：这个有些麻烦，个人是全拉黑名单的，也没出问题，不过作为过滤列表似乎不能全拉黑名单。可以拉黑的：uflowx.com、ubibibi.com（优量平台，似乎是广告营销平台），effirst.com、effirst.cn（岳鹰——移动应用全景监控，洞析用户真实体感）。其他域名没有确实证据说明其有害性（岳鹰这个产品已经说明了这家公司的尿性），但是可以全加自定义列表，只要不用UC和夸克浏览器问题不大，换火狐即可。

**Comment by gentlyxu** [comment]
感谢提供，已部分收录，具体在 76c5feb2cb924452e771fafbbfc78acabdb35042
