### ISSUE TITLE
[误杀] api.kwaizt.com

### ISSUE THREAD

**Issue by 3gZ2jA** [privacy-protection-tools/anti-AD#235]
域名：api.kwaizt.com
发生时间：2020年08月27日
使用的列表： https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt
问题描述：
在acfun app中无法打开up的个人页面，查看adgurad home日志发现是api.kwaizt.com被拦截。放行api.kwaizt.com后可以正常打开up的个人页面

**Comment by gentlyxu** [comment]
实测没有发现acfun app有请求这个域名。 `api.kwaizt.com` 看资料是快手的

**Comment by 3gZ2jA** [comment]
![WeChat Image_20200831112505](https://user-images.githubusercontent.com/14199554/91680056-a8483d00-eb7c-11ea-843b-357248e47109.jpg)
我这边看是有请求这个域名。acfun是是快手的，有请求快手的域名也正常。

**Comment by gentlyxu** [comment]
能抓包看看`api.kwaizt.com`请求了什么内容吗？ 多个过滤列表都屏蔽了 `api.kwaizt.com`

**Comment by 3gZ2jA** [comment]
这两天更了版本，发现没有请求这么域名了😂。
