### ISSUE TITLE
[新增拦截]p2pchunk-tx.douyucdn.cn

### ISSUE THREAD

**Issue by wastelandx** [privacy-protection-tools/anti-AD#237]
域名:p2pchunk-tx.douyucdn.cn
出现场景：斗鱼
补充说明：看了会比赛，adg里面出现大量的dns请求，感觉是斗鱼拿来做P2P的。

**Comment by gentlyxu** [comment]
根据之前虎牙的反馈，封杀p2p域名会造成有些网络下观看直播卡顿，而有些宽带网络下会占满上传带宽，为了更好的体验，还是不加入公共封杀列表了，请自行决定是否封杀之
