### ISSUE TITLE
[误杀]规则: /^[1-3]\\.[0-9a-z\\.\\-]+\\.(com|cn|net|org|cc|me)$/

### ISSUE THREAD

**Issue by Mosney** [privacy-protection-tools/anti-AD#24]
`2.android.pool.ntp.org`会命中此规则

**Comment by gentlyxu** [comment]
感谢反馈，确实存在这个问题，已经加白了ntp.org

**Comment by kr513268** [comment]
> 感谢反馈，确实存在这个问题，已经加白了ntp.org

2.openwrt.pool.ntp.org
同样也被屏蔽了

**Comment by kr513268** [comment]
> 感谢反馈，确实存在这个问题，已经加白了ntp.org

@@/ntp.*/$important adguardhome手动添加后可以解除拦截，但是不排除其它非ntp服务的域名中含有ntp字样。

**Comment by gentlyxu** [comment]
我在回复前已经修复了问题，直接更新最新的规则即可
________________________________
发件人: #0xf <notifications@github.com>
发送时间: 星期六, 二月 1, 2020 23:22
收件人: privacy-protection-tools/anti-AD
主题: Re: [privacy-protection-tools/anti-AD] [误杀]规则: /^[1-3]\\.[0-9a-z\\.\\-]+\\.(com|cn|net|org|cc|me)$/ (#24)


感谢反馈，确实存在这个问题，已经加白了ntp.org

@@/ntp.*/$important adguardhome手动添加后可以解除拦截，但是不排除其它非ntp服务的域名中含有ntp字样。

―

**Comment by gentlyxu** [comment]
我在回复前已经修复了问题，直接更新最新的规则即可
@kr513268
