### ISSUE TITLE
[新增拦截]BAN了老毛桃全家

### ISSUE THREAD

**Issue by qpzr** [privacy-protection-tools/anti-AD#240]
详情请看火绒的 装机工具老毛桃携带木马病毒 卸载安全软件进行恶意推广
https://www.huorong.cn/info/1598957552515.html

BAN了老毛桃全家 还有文章里溯源分析的域名

**Comment by gentlyxu** [comment]
图我存一下，这些系统工具权限非常大，如此无底线！！！
![e83c6518e250f5c1043fa9a3265621ff](https://user-images.githubusercontent.com/1243610/92293996-73f8c600-ef5a-11ea-87e9-4dd801b65a7a.png)
