### ISSUE TITLE
whitelist  ouo.io

### ISSUE THREAD

**Issue by 3xploiton3** [privacy-protection-tools/anti-AD#241]
![image](https://user-images.githubusercontent.com/19517680/92270075-96192680-ef0f-11ea-9e07-218aca416609.png)

example:
https://ouo.io/qs/pRqHNWPK?s=https://usersdrive.com/dakjcpl6geha.html

**Comment by gentlyxu** [comment]
Why? This domain will track user behavior. And, it's a breach of privacy.

**Comment by 3xploiton3** [comment]
its like shorten link, 

ex:
bit.ly
etc

**Comment by gentlyxu** [comment]
no, the `ouo.io` can "**earn money**", not just a URL Shortener service. it's an advertisement, it's a user behavior tracker. don't add it to the whitelist. use `bit.ly` or `goo.gl` instead

**Comment by krystian3w** [comment]
I suppose this is not link created by that user, link open cracked software and webmaster / owner "`m-a-z-t-e-r-i-z-e`" newer read this theard.
