### ISSUE TITLE
[误杀] slashdot.org

### ISSUE THREAD

**Issue by proletarius101** [privacy-protection-tools/anti-AD#242]
域名：slashdot.org  
发生时间：2020年9月23日  
使用的列表： https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt  
问题描述：Slashdot是一個資訊科技網站，每天以部落格的形式在主頁發表科技資訊，所有的新聞都源於網友投稿，經編輯篩選後發表，文中會附上源新聞的連結。并不是广告网站。

**Comment by gentlyxu** [comment]
修复了，请更新

**Comment by proletarius101** [comment]
Thanks!
