### ISSUE TITLE
[误杀]ename.com.cn、ename.net

### ISSUE THREAD

**Issue by godwasdog** [privacy-protection-tools/anti-AD#246]
域名：ename.com.cn、ename.net
发生时间：2020年9月27日
使用的列表： anti-ad-easylist.txt、anti-ad-smartdns.conf
问题描述：易名的官方网站无法登录管理域名了。

**Comment by gentlyxu** [comment]
你好，`ename.com.cn`的网站描述是
```
域名联盟为易名科技旗下网站，致力于域名推广和域名展示页等服务，联盟的宗旨是打造域名界的生态闭环，流量变现，凸显域名的价值。
```

所以无法为你放行，若确有需要，请自行加白
