### ISSUE TITLE
[误杀]api.iplay.163.com

### ISSUE THREAD

**Issue by A-Cepheus** [privacy-protection-tools/anti-AD#247]
域名：api.iplay.163.com
发生时间：2020年9月28日
使用的列表： anti-ad-easylist.txt
问题描述：影响网易云APP的直播内容，无法观看任何直播

**Comment by gentlyxu** [comment]
1085e960c3e96475e28804c734eebf553b5c18c6 ,我已经在最新版本中将`api.iplay.163.com` ,请在确认问题解决了之后关闭issue
