### ISSUE TITLE
[误杀]sock158-mt1.pusher.com， ws-mt1.pusher.com

### ISSUE THREAD

**Issue by Calvin-LL** [privacy-protection-tools/anti-AD#248]
域名：sock158-mt1.pusher.com， ws-mt1.pusher.com
发生时间：2020年09月29日
使用的列表：anti-ad-domains.txt
问题描述：pusher.com只用stats.pusher.com 来收集用户信息，sock158-mt1.pusher.com和其他服务器只是用来连接websocket的

**Comment by gentlyxu** [comment]
经过调查，情况属实，目前已将 `pusher.com`加入白名单，只屏蔽了 `stats.pusher.com` ，请确认没有问题后关闭issue
