### ISSUE TITLE
[误杀] bukalapak.go2cloud.org

### ISSUE THREAD

**Issue by 3xploiton3** [privacy-protection-tools/anti-AD#250]
![image](https://user-images.githubusercontent.com/19517680/95067939-bdd9f500-072e-11eb-86b1-f23e6dd318a6.png)

marketplace website
bukalapak.go2cloud.org

from https://www.priceza.co.id/search?productdataname=10750h

**Comment by gentlyxu** [comment]
opening the link you shared, I didn't find **any** request for `go2cloud.org`.
![go2cloud-not-found](https://user-images.githubusercontent.com/1243610/95073860-22ea1680-0740-11eb-9126-6565b77be1ff.png)

You can refer to https://blog.malwarebytes.com/detections/go2cloud-org/ , `go2cloud.org` is a hijacking type of domain.
