### ISSUE TITLE
[新增拦截] 恶意域名/勒索网站

### ISSUE THREAD

**Issue by xx10n31y** [privacy-protection-tools/anti-AD#253]
域名: c4frc.info/jtuzd.rdtk.io
出现场景：出现在本人的Google voice收件箱中, 使用curl对其进行请求, 发现这是一个多重跳转的短链接, ~~`https://c4frc.info/Ss8RBPxvXj`~~, 最后跳转到Google首页但跟随一些不明参数.
补充说明：将该域名在Google搜索发现早已是被标志为 **malware website**, 请求加上该域名以防止可能使用Google voice用户有概率受害, 以下是几个在线扫描网站对该域名的扫描. **建议打开过的立即修改Google账号密码**
[rdtk.io-Malwarebytes Labs](https://blog.malwarebytes.com/detections/rdtk-io/)
[VirusTotal](https://www.virustotal.com/gui/url/e3613d798ab39c870f8d6573b832ab824b5d1db26e3df4d5eadd551b91a8067d/detection)
[VirusTotal2](https://www.virustotal.com/gui/url/21d39a4c607c50a2ed7d2c313c5fa79bf07dfedd9a5bc1d5e4323cd8e322e1ab/detection)
[VirusTotal3](https://www.virustotal.com/gui/url/f601da49a3e1f49886570998ccef2df95ab3e765f5602c70ac462bd9910bc6ef/detection)

**Comment by gentlyxu** [comment]
`rdtk.io` 已经有上游收录了，我加了`jtuzd.rdtk.io`，`c4frc.info` 黑名单

**Comment by xx10n31y** [comment]
> `rdtk.io` 已经有上游收录了，我加了`jtuzd.rdtk.io`，`c4frc.info` 黑名单

感谢
