### ISSUE TITLE
[误杀]虎牙、斗鱼有些直播间由于拦截，打开会很慢

### ISSUE THREAD

**Issue by Faramitas** [privacy-protection-tools/anti-AD#254]
域名：douyu huya
发生时间：xxx年xx月xx日
使用的列表： anti-ad-easylist.txt（具体的文件，例如/anti-ad-easylist.txt, /dist/anti-ad-surge-full.txt等等）
问题描述：虎牙、斗鱼有些直播间由于拦截，打开会很慢，这应该不属于误杀，就是由于拦截打开速度会很慢
ylog.huya.com、msg.douyu.com、statwup.huya.com，可能是这些。

**Comment by Carlos920** [comment]
是的虎牙经过我查找发现是  migu-bd.p2p.huya.com/huyalive  这个被拦截导致的，拦截后会导致视频无法正常播放；斗鱼我这儿没有问题所以不知道是啥原因

**Comment by Faramitas** [comment]
> 是的虎牙经过我查找发现是 migu-bd.p2p.huya.com/huyalive 这个被拦截导致的，拦截后会导致视频无法正常播放；斗鱼我这儿没有问题所以不知道是啥原因

解决了。。。。
@@||p2p.huya.com^
@@||*p2p*douyucdn.cn^把这两个放行了

**Comment by Faramitas** [comment]
> 是的虎牙经过我查找发现是 migu-bd.p2p.huya.com/huyalive 这个被拦截导致的，拦截后会导致视频无法正常播放；斗鱼我这儿没有问题所以不知道是啥原因

douyu有些直播间没有P2P商户，所以是可以直接打开的，huya同理

**Comment by Carlos920** [comment]
> > 是的虎牙经过我查找发现是 migu-bd.p2p.huya.com/huyalive 这个被拦截导致的，拦截后会导致视频无法正常播放；斗鱼我这儿没有问题所以不知道是啥原因
> 
> douyu有些直播间没有P2P商户，所以是可以直接打开的，huya同理

虎牙我所有打开的都是这样哈哈😂

**Comment by Carlos920** [comment]
> Thank you for opening your first issue in this repo. It’s people like you who make anti-AD better!

建议将注释部分的=号改成 : 号这样Adguard好自动识别🤣，有点强迫症

**Comment by gentlyxu** [comment]
啊呀，老生常谈的话题了。p2p域名放行有可能导致CPU飙高， 见之前的讨论 #134   #228  ，这个需要大家自行决定了

**Comment by Faramitas** [comment]
> 啊呀，老生常谈的话题了。p2p域名放行有可能导致CPU飙高， 见之前的讨论 #134 #228 ，这个需要大家自行决定了

好的！这个我倒是无所谓，反正都是给软路由挂着，CPU够用
谢谢大佬！！！

**Comment by gentlyxu** [comment]
>
> 建议将注释部分的=号改成 : 号这样Adguard好自动识别🤣，有点强迫症

这个说法有官方参考文档吗？如果是冒号分隔符自动识别的话，那`https://` 中的冒号怎么处理的？

**Comment by Carlos920** [comment]
> > 建议将注释部分的=号改成 : 号这样Adguard好自动识别🤣，有点强迫症
> 
> 这个说法有官方参考文档吗？如果是冒号分隔符自动识别的话，那`https://` 中的冒号怎么处理的？

我是参考别人能正确显示的规则的，下载本地改了如图所示的两个后导入adguard即可识别标题和版本号
![Uploading 1.png…]()
![Uploading 2.png…]()

**Comment by gentlyxu** [comment]
> > > 建议将注释部分的=号改成 : 号这样Adguard好自动识别🤣，有点强迫症
> > 
> > 
> > 这个说法有官方参考文档吗？如果是冒号分隔符自动识别的话，那`https://` 中的冒号怎么处理的？
> 
> 我是参考别人能正确显示的规则的，下载本地改了如图所示的两个后导入adguard即可识别标题和版本号
> ....

转到 #255 讨论这个话题
