### ISSUE TITLE
建议将注释部分的=号改成 : 号这样Adguard好自动识别🤣，有点强迫症

### ISSUE THREAD

**Issue by gentlyxu** [privacy-protection-tools/anti-AD#255]
> > 建议将注释部分的=号改成 : 号这样Adguard好自动识别🤣，有点强迫症
> 
> 这个说法有官方参考文档吗？如果是冒号分隔符自动识别的话，那`https://` 中的冒号怎么处理的？

我是参考别人能正确显示的规则的，下载本地改了如图所示的两个后导入adguard即可识别标题和版本号
![1](https://user-images.githubusercontent.com/32257015/96008837-8b3ca480-0e72-11eb-8d59-0bcc33d9898b.png)
![2](https://user-images.githubusercontent.com/32257015/96008860-94c60c80-0e72-11eb-9a04-286e722465b8.png)

_Originally posted by @Carlos920 in https://github.com/privacy-protection-tools/anti-AD/issue_comments/708467846_

**Comment by gentlyxu** [comment]
开个新的issue到这里.找到个可能算是靠谱的参考： https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/filter_15_DnsFilter/filter.txt ，照着改了一下

@Carlos920 , 你看看

**Comment by Carlos920** [comment]
> 开个新的issue到这里.找到个可能算是靠谱的参考： https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/filter_15_DnsFilter/filter.txt ，照着改了一下
> 
> @Carlos920 , 你看看

可以了，感谢
![Snipaste_2020-10-15_19-10-13](https://user-images.githubusercontent.com/32257015/96115795-1624aa00-0f1a-11eb-9cd5-53b1cb01aa83.png)
