### ISSUE TITLE
[误杀]pdc.micloud.xiaomi.net

### ISSUE THREAD

**Issue by tianiue** [privacy-protection-tools/anti-AD#256]
域名：pdc.micloud.xiaomi.net
发生时间：2020年10月15日
使用的列表：anti-ad-easylist.txt
问题描述：小米手机云服务不能同步，需要加入白名单

**Comment by gentlyxu** [comment]
该规则来自上游neohosts， 同样的反馈 https://github.com/neoFelhz/neohosts/issues/95

待我修复之
