### ISSUE TITLE
[误杀]酷喵无法看视频

### ISSUE THREAD

**Issue by kiolou** [privacy-protection-tools/anti-AD#257]
域名：valf.atm.cp31.ott.cibntv.net
发生时间：2020年10月19日
使用的列表： https://anti-ad.net/easylist.txt
问题描述：
TV端酷喵APP无法看视频，去掉列表正常，疑似不放广告不能播。。。。

**Comment by 1mogude1** [comment]
能播，等广告时间过了黑屏结束就行了
