### ISSUE TITLE
[误杀]sf1-ttcdn-tos.pstatp.com

### ISSUE THREAD

**Issue by wxf26054** [privacy-protection-tools/anti-AD#258]
域名：sf1-ttcdn-tos.pstatp.com
发生时间：2020年10月20日
使用的列表： （具体的文件，https://anti-ad.net/domains.txt、ADGuardHome拦截规则文件
）
问题描述：屏蔽此域名回导致部分页面无法正常打开

**Comment by gentlyxu** [comment]
“部分页面”具体是什么？

**Comment by wxf26054** [comment]
影响了某些页面的正常图片展示, 比如我之前去_飞书官网_下载_飞书_时, 有些官网展示的图片看不到.
![image](https://user-images.githubusercontent.com/22016320/96683778-2ff83e00-13ad-11eb-90f0-1fdc4d7640c7.png)
