### ISSUE TITLE
[误杀]www.ucweb.com

### ISSUE THREAD

**Issue by 3xploiton3** [privacy-protection-tools/anti-AD#259]
whitelist www.ucweb.com

just regular website,

**Comment by gentlyxu** [comment]
Nope.This browser collects a lot of personal information and the content sites under its domain are of low quality.Highly discouraged on whitelist.

**Comment by 3xploiton3** [comment]
> Nope.This browser collects a lot of personal information and the content sites under its domain are of low quality.Highly discouraged on whitelist.

ok thx for advice
