### ISSUE TITLE
被gfw强了

### ISSUE THREAD

**Issue by yiguihai** [privacy-protection-tools/anti-AD#26]
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused

**Comment by gentlyxu** [comment]
这，纯属误会啊。。。

两个方案：

1. 通过jsdelivr的CDN加速，有大约1～3天的缓存，用法见[README的加速段落](https://github.com/privacy-protection-tools/anti-AD#jsdelivr%E9%95%9C%E5%83%8F%E5%8A%A0%E9%80%9F)
2. 专有域名 https://anti-ad.win ，还在建设中，后续过滤列表会保持同步更新，国内测速发现移动是个渣渣 (-;
