### ISSUE TITLE
[误杀]NGA

### ISSUE THREAD

**Issue by HsuXwAsTe** [privacy-protection-tools/anti-AD#260]
域名：bbs.nga.cn
发生时间：2020年10月21日
使用的列表： https://anti-ad.net/easylist.txt
问题描述：当网页端每次点开一个主题时都会卡住无法显示，需要刷新一下才会正常打开。
在adguard home后台看到当时是拦截了 <bdtj.tagtic.cn>，手动放行了就可以正常浏览帖子，不需要正常刷新了。检查过滤后，发现是anti-ad屏蔽了tagtic.cn整个域名。我手动放行这个域名后，其他的广告都是正常过滤的，包括但不限于PC端广告，APP端开屏广告，帖子与帖子之间的信息流广告。所以个人可能觉得是应该是一个误杀。
查找了论坛的帖子之后，发现也有用户反馈过给NGA的管理人员，管理人员答复说<bdtj.tagtic.cn>这个网页是他们的一个统计代码。https://bbs.nga.cn/read.php?tid=18820581 （14楼）

也不知道这个统计代表是否会涉及隐私之类的东西，所以先提交这个误杀。

**Comment by gentlyxu** [comment]
首先，感谢你这么详细的描述问题。 统计是肯定要收集隐私的，它会记录用户的行为习惯，设备特征，唯一识别码，IP地址等相关联信息，是本项目要屏蔽的一类域名。

经过反复体验，好像放行域名`g1.tagtic.cn`就可以正常浏览，不会出现卡住的现象，但是，查看该域名加载的文件
```javascript
(function () {
  var bg_data = [{"pid":"715","hiturl":"https://g1.tagtic.cn/don/cl?encode_nyg=cmVxaWQ9ZENLR0p3ZGtfanZxS3VIVFpfejMyJmNvbz1kNzcyMTgwZGE5ZGEyOWFhOWI2ODEwYjEzNjc4NjJhNDRmYjhhZjgzNDAwNDJlNTQ2OWM2NWVjMTQwNWMzMTkzJm9zPTMmcmVmPWh0dHBzJTNBJTJGJTJGYmJzLm5nYS5jbiUyRiZhZHZlcnVzZXJpZD02MzQmb3JkZXJpZD01ODMzJmFpZD04NTg5JnByb3ZpbmNlSWQ9OCZwYXltZW50PWNwdCZhZF9mcm9tPTAmbWlkPTg1ODkxJmdyb3VwX2lkPTg1ODkxJnBvc2l0aW9uPTY2NCZ3PTEyMCZoPTI0MCZjb3N0PTEwMCZjb2VmZmljaWVudD0xJnNsb3RCaW5kaW5nPXNpbmdsZSZjb21wYXJlX2J1Y2tldF9pZD1hJnRyYWZmaWNfYnVja2V0X2lkPXAzMzIxMiZpc1VuaW9uPTEmbmV4dHVybD1odHRwcyUzQSUyRiUyRmdhbWUuc3RhcmdhbWUuY29tJTJGQlNZRFhD&v_y=1c68ae6cb060a75c8bc439ed2ecbfe00a5656945dc074103f60ce2a6b8ab50e5","wnUrl":"https://g1.tagtic.cn/don/wn?encode_nyg=cmVxaWQ9ZENLR0p3ZGtfanZxS3VIVFpfejMyJmNvbz1kNzcyMTgwZGE5ZGEyOWFhOWI2ODEwYjEzNjc4NjJhNDRmYjhhZjgzNDAwNDJlNTQ2OWM2NWVjMTQwNWMzMTkzJm9zPTMmcmVmPWh0dHBzJTNBJTJGJTJGYmJzLm5nYS5jbiUyRiZhZHZlcnVzZXJpZD02MzQmb3JkZXJpZD01ODMzJmFpZD04NTg5JnByb3ZpbmNlSWQ9OCZwYXltZW50PWNwdCZhZF9mcm9tPTAmbWlkPTg1ODkxJmdyb3VwX2lkPTg1ODkxJnBvc2l0aW9uPTY2NCZ3PTEyMCZoPTI0MCZjb3N0PTEwMCZjb2VmZmljaWVudD0xJnNsb3RCaW5kaW5nPXNpbmdsZSZjb21wYXJlX2J1Y2tldF9pZD1hJnRyYWZmaWNfYnVja2V0X2lkPXAzMzIxMiZpc1VuaW9uPTE&v_y=5e8cb5263d774dc42f591d18cbe7f91d73f79a5208122e802cda071120c2000c&","box":"https://ad-static-xg.tagtic.cn/ad-material/images/dzfOdJlchfsJqTsXLF5vgVC07JiAW1HHRXfd3mHk.png","txt":"","tid":1,"width":120,"height":240,"weight":1007.265625,"time":10,"IsUnion":1,"type":0}];
  if (bg_data.length > 0) {
    var ref = bg_data[0].box.substring(bg_data[0].box.lastIndexOf('/'), bg_data[0].box.lastIndexOf('.'));
    ngaAds.push({
      "id": "bbs_ads24",
      "isUnion": "" + bg_data[0].IsUnion + "",
      "file": "" + bg_data[0].box + "",
      "url": "" + bg_data[0].hiturl + "",
      "title": "",
      "width": "" + bg_data[0].width + "",
      "height": "" + bg_data[0].height + "",
      "date": "all",
      "rate": "100",
      "nolog": "1",
      "type": "" + bg_data[0].type + "",
      "sgid": bg_data[0].pid,
      "refreshid": "" + ref + "",
      "onload": function () {
        var x = document.createElement("script");
        x.src = bg_data[0].wnUrl;
        document.getElementsByTagName("head")[0].appendChild(x);
      }
    });
  }
})();

```
没看错的话，用来插入广告的，这样的话，我是不建议放行域名的

**Comment by HsuXwAsTe** [comment]
> 首先，感谢你这么详细的描述问题。 统计是肯定要收集隐私的，它会记录用户的行为习惯，设备特征，唯一识别码，IP地址等相关联信息，是本项目要屏蔽的一类域名。
> 
> 经过反复体验，好像放行域名`g1.tagtic.cn`就可以正常浏览，不会出现卡住的现象，但是，查看该域名加载的文件
> 
> ```js
> (function () {
>   var bg_data = [{"pid":"715","hiturl":"https://g1.tagtic.cn/don/cl?encode_nyg=cmVxaWQ9ZENLR0p3ZGtfanZxS3VIVFpfejMyJmNvbz1kNzcyMTgwZGE5ZGEyOWFhOWI2ODEwYjEzNjc4NjJhNDRmYjhhZjgzNDAwNDJlNTQ2OWM2NWVjMTQwNWMzMTkzJm9zPTMmcmVmPWh0dHBzJTNBJTJGJTJGYmJzLm5nYS5jbiUyRiZhZHZlcnVzZXJpZD02MzQmb3JkZXJpZD01ODMzJmFpZD04NTg5JnByb3ZpbmNlSWQ9OCZwYXltZW50PWNwdCZhZF9mcm9tPTAmbWlkPTg1ODkxJmdyb3VwX2lkPTg1ODkxJnBvc2l0aW9uPTY2NCZ3PTEyMCZoPTI0MCZjb3N0PTEwMCZjb2VmZmljaWVudD0xJnNsb3RCaW5kaW5nPXNpbmdsZSZjb21wYXJlX2J1Y2tldF9pZD1hJnRyYWZmaWNfYnVja2V0X2lkPXAzMzIxMiZpc1VuaW9uPTEmbmV4dHVybD1odHRwcyUzQSUyRiUyRmdhbWUuc3RhcmdhbWUuY29tJTJGQlNZRFhD&v_y=1c68ae6cb060a75c8bc439ed2ecbfe00a5656945dc074103f60ce2a6b8ab50e5","wnUrl":"https://g1.tagtic.cn/don/wn?encode_nyg=cmVxaWQ9ZENLR0p3ZGtfanZxS3VIVFpfejMyJmNvbz1kNzcyMTgwZGE5ZGEyOWFhOWI2ODEwYjEzNjc4NjJhNDRmYjhhZjgzNDAwNDJlNTQ2OWM2NWVjMTQwNWMzMTkzJm9zPTMmcmVmPWh0dHBzJTNBJTJGJTJGYmJzLm5nYS5jbiUyRiZhZHZlcnVzZXJpZD02MzQmb3JkZXJpZD01ODMzJmFpZD04NTg5JnByb3ZpbmNlSWQ9OCZwYXltZW50PWNwdCZhZF9mcm9tPTAmbWlkPTg1ODkxJmdyb3VwX2lkPTg1ODkxJnBvc2l0aW9uPTY2NCZ3PTEyMCZoPTI0MCZjb3N0PTEwMCZjb2VmZmljaWVudD0xJnNsb3RCaW5kaW5nPXNpbmdsZSZjb21wYXJlX2J1Y2tldF9pZD1hJnRyYWZmaWNfYnVja2V0X2lkPXAzMzIxMiZpc1VuaW9uPTE&v_y=5e8cb5263d774dc42f591d18cbe7f91d73f79a5208122e802cda071120c2000c&","box":"https://ad-static-xg.tagtic.cn/ad-material/images/dzfOdJlchfsJqTsXLF5vgVC07JiAW1HHRXfd3mHk.png","txt":"","tid":1,"width":120,"height":240,"weight":1007.265625,"time":10,"IsUnion":1,"type":0}];
>   if (bg_data.length > 0) {
>     var ref = bg_data[0].box.substring(bg_data[0].box.lastIndexOf('/'), bg_data[0].box.lastIndexOf('.'));
>     ngaAds.push({
>       "id": "bbs_ads24",
>       "isUnion": "" + bg_data[0].IsUnion + "",
>       "file": "" + bg_data[0].box + "",
>       "url": "" + bg_data[0].hiturl + "",
>       "title": "",
>       "width": "" + bg_data[0].width + "",
>       "height": "" + bg_data[0].height + "",
>       "date": "all",
>       "rate": "100",
>       "nolog": "1",
>       "type": "" + bg_data[0].type + "",
>       "sgid": bg_data[0].pid,
>       "refreshid": "" + ref + "",
>       "onload": function () {
>         var x = document.createElement("script");
>         x.src = bg_data[0].wnUrl;
>         document.getElementsByTagName("head")[0].appendChild(x);
>       }
>     });
>   }
> })();
> ```
> 
> 没看错的话，用来插入广告的，这样的话，我是不建议放行域名的

好的 十分感谢。

**Comment by ameyukisora** [comment]
个人试了一下，应该还是bdtj.tagtic.cn这个域名的问题，查询了一下常用的广告屏蔽列表，包括AdguardFilters、Easylist、cjxlist、lhie1均无收录，估计是考虑到了和网站功能冲突的问题，放行可能会更好
