### ISSUE TITLE
[误杀] 微信小程序 饿了么

### ISSUE THREAD

**Issue by Frankcjn** [privacy-protection-tools/anti-AD#261]
域名：wgo.mmstat.com
发生时间：2020年10月23日
使用的列表： /anti-ad-easylist.txt
问题描述：微信小程序 饿了么 无法添加购物车

**Comment by gentlyxu** [comment]
实测，没有重现，可以添加购物车和付款

**Comment by Frankcjn** [comment]
我今天测试了一下确实可以，😓
