### ISSUE TITLE
[误杀]bbs.nga.cn

### ISSUE THREAD

**Issue by ameyukisora** [privacy-protection-tools/anti-AD#266]
域名：bbs.nga.cn
发生时间：2020年10月27日
使用的列表： https://anti-ad.net/easylist.txt
问题描述：同[https://github.com/privacy-protection-tools/anti-AD/issues/260](url)
试了一下，应该还是bdtj.tagtic.cn这个域名的问题，考虑到与网站功能体验冲突这一点，个人建议放行可能会更好

**Comment by gentlyxu** [comment]
请提供详细的测试方法和测试步骤

**Comment by ameyukisora** [comment]
> 请提供详细的测试方法和测试步骤

感谢您的回复。使用到的工具：
`1.Microsoft Edge 86.0.622.56
2.Clash for Windows 0.13.0`
Clash用作系统代理。每次测试均在版块[漩涡书院](https://bbs.nga.cn/thread.php?fid=524)内点击版头公告[关于涉及盗版阅读发言的公告](https://bbs.nga.cn/read.php?tid=23853330)，使用Edge的DevTools监控页面加载时间。

第一次测试：
不拦截bdtj.tagtic.cn与g1.tagtic.cn：
不会卡住，页面中出现广告。清空缓存硬刷新页面完全加载时间约2400毫秒。

第二次测试：
清除浏览器缓存，Clash中添加规则
`- DOMAIN-SUFFIX,bdtj.tagtic.cn,REJECT #拦截bdtj.tagtic.cn`
不会卡住，页面中出现广告。清空缓存硬刷新页面完全加载时间约2400毫秒。

第三次测试：
清除浏览器缓存，Clash删除第二次测试的规则并添加规则
`- DOMAIN-SUFFIX,g1.tagtic.cn,REJECT #拦截g1.tagtic.cn`
不会卡住，页面中广告消失。清空缓存硬刷新页面完全加载时间约800毫秒。

第四次测试：
清除浏览器缓存，Clash中删除第三次测试的规则并添加规则
`- DOMAIN-SUFFIX,bdtj.tagtic.cn,REJECT #拦截bdtj.tagtic.cn`
`- DOMAIN-SUFFIX,g1.tagtic.cn,REJECT #拦截g1.tagtic.cn`
在点击主题帖时会完全卡住，刷新后正常且无广告。清空缓存硬刷新页面完全加载时间约800毫秒。

额外测试：
在第四次测试的基础上，删除
`- DOMAIN-SUFFIX,bdtj.tagtic.cn,REJECT #拦截bdtj.tagtic.cn`
不清除浏览器缓存，再次点击，不会卡住且页面中无广告。
清除缓存后点击，不会卡住且页面中无广告。

至此，可以发现，此情况出现于bdtj.tagtic.cn与g1.tagtic.cn同时被拦截时。考虑到g1.tagtic.cn用于插入大块的页面内广告，参考nga管理人员的说法，放行bdtj.tagtic.cn会是更好的选择。

查看AdguardFilters、EasylistChina后，我觉得将bdtj.tagtic.cn加入白名单或者把tagtic.cn规则细化为g1.tagtic.cn，二者均能即拦截了广告也不破坏浏览体验

**Comment by gentlyxu** [comment]
非常感谢你的详细测试。经查看，是`tagtic.cn` 整个被拦截了。目前已放行，请更新列表。
