### ISSUE TITLE
[误杀]settings-win.data.microsoft.com

### ISSUE THREAD

**Issue by Clackz** [privacy-protection-tools/anti-AD#268]
域名：settings-win.data.microsoft.com
发生时间：2020年10月30日
使用的列表： https://anti-ad.net/easylist.txt
问题描述：拦截这个域名会导致windows预览体验计划的连接失败
https://docs.microsoft.com/zh-cn/windows/privacy/windows-endpoints-2004-non-enterprise-editions
在微软的上述文档中可以查询到该域名的作用

**Comment by gentlyxu** [comment]
感谢反馈，已修复
