### ISSUE TITLE
增加RouterOS专用版本

### ISSUE THREAD

**Issue by rinho1239104** [privacy-protection-tools/anti-AD#269]
在anti-ad-domains.txt的数据基础上修改
例:
/ip dns static
add address=240.0.0.1 name=00-gov.cn
add address=240.0.0.1 name=kwcdn.000dn.com

最后保存为rsc文件,在ros上通过脚本自动更新

**Comment by gentlyxu** [comment]
官方暂无增加新的格式支持的计划，总是增加新的格式，一方面运算压力骤增，一方面容易分散精力去维护各种各样的生成格式。

不过，你这个需求既然要用到脚本，那么很容易满足需求，只需脚本要加一行代码，用sed替换就可以了，例如

```
curl -s -o - https://anti-ad.net/anti-ad-for-dnsmasq.conf | sed 's#^address=/\(.\+\?\)/#add address=240.0.0.1 name=\1#g'
```

**Comment by rinho1239104** [comment]
好的.谢谢
