### ISSUE TITLE
[误杀] 沪江网校网课

### ISSUE THREAD

**Issue by fgprodigal** [privacy-protection-tools/anti-AD#271]
域名：mc.hujiang.com
发生时间：2020年10月31日
使用的列表： adblock-for-dnsmasq
问题描述：沪江网校网课Role play card

**Comment by gentlyxu** [comment]
没看懂，到底影响了什么

**Comment by fgprodigal** [comment]
上网课的时候，role play card环节显示不出来，无法正常上网课，并且这是人家沪江网校的官网地址

**Comment by gentlyxu** [comment]
怎么确定是这个域名引起的？能提供详细一些的资料吗

**Comment by fgprodigal** [comment]
算了，我这边本地处理一下吧，你把人沪江网校官网直接干掉又是为啥呢

**Comment by gentlyxu** [comment]
首先，这个域名不是我干掉的。这条规则来自上游 
 https://github.com/vokins/yhosts/blob/017fa57a29532ec11163d2aa18691f7b2a170ff9/hosts.txt#L5980 ，请不要用这种质问的语气来问我，我开源出来的项目，一直是一个负责任的态度在做，来一个人就说某个域名是误杀，去广告还能有效果吗？

其次，我能搜到这个mc.hujiang.com 的域名下的广告widget 

```
https://mc.hujiang.com/ec/quan/600004
```

所以我需要更详细的资料判断是否为误杀？

有什么问题？

**Comment by fgprodigal** [comment]
你发的这个所谓的广告链接是人家自己的网校业务啊，那难不成qq官网上做个宣传会员的widget也叫广告了直接把qq.com扔名单里吗。日志的话，等哪天我老婆有网课了我想办法抓包吧。

**Comment by gentlyxu** [comment]
前面一段话，逻辑混乱，不知所云。BTW，沪江网校的官网应该是 `https://www.hujiang.com/` 。

关于日志抓包，谢了，等你的好消息

**Comment by fgprodigal** [comment]
不必了
