### ISSUE TITLE
軟件下載被阻止

### ISSUE THREAD

**Issue by gistsy** [privacy-protection-tools/anti-AD#273]
域名：`isdspeed.qq.com`, `c.gj.qq.com` (one or all)
问题描述：Go to https://guanjia.qq.com and download the software then run QQPCDownload1600.exe

**Comment by gentlyxu** [comment]
I'm sorry, my windows computer will not install this "security" software. Can you please describe the specific problem more clearly? what happens when these domains are blocked..,And, attached is a screenshot, thanks

**Comment by gistsy** [comment]
1. I use your ad-block list
2. Go to https://guanjia.qq.com and download the software then run QQPCDownload1600.exe setup. it's a online installer. 
(You can test on virtualmachine)

>I'm sorry, my windows computer will not install this "security" software

I use ubuntu then testing on windows vm.

3. You can be see below

![image](https://user-images.githubusercontent.com/73447325/98083423-ec252e80-1eac-11eb-8ea4-4c22416232ba.png)


@gentlyxu make sure to not block local softwares or services. eg: about 'security' software then you know there're other intelligence antivirus tools similar avast etc that depend on users data. (compared to those, guanjia not that bad). when you block local services next people start to use foreign companies. you know the meanings
