### ISSUE TITLE
[误杀]中国互联网中心被拦截

### ISSUE THREAD

**Issue by woboo110** [privacy-protection-tools/anti-AD#274]
域名：www.cnnic.net.cn/
发生时间：2020年11月03日
使用的列表： anti-ad-easylist.txt
问题描述：中国互联网中心被拦截了，这个不属于广告域名吧？？

**Comment by gentlyxu** [comment]
这个不属于广告域名，属于可能的隐私泄漏域名。anti-AD不予放行，请自行搜索相关内容了解详细

**Comment by gentlyxu** [comment]
感谢反馈，经过仔细搜索和验证，发现 证书事件 已经是过去式，当前封锁的域名下亦未发现有收集隐私的情形存在。其官网还有定期发布的互联网行业相关报告，有一定的数据参考价值。

综上，已对cnnic相关域名加白了
