### ISSUE TITLE
[误杀]51y5.net

### ISSUE THREAD

**Issue by AzurLab** [privacy-protection-tools/anti-AD#276]
域名：51y5.net
发生时间：2020年11月07日
使用的列表： anti-ad-surge.txt
问题描述：
屏蔽后，Wifi大师无法查询数据，取消屏蔽后正常

**Comment by gentlyxu** [comment]
搜索了一下 `51y5.net`域名在多个上游列表中均有屏蔽，再搜索WiFi大师
> WiFi 大师是最好用的智能手机免费畅连wifi管理工具。所有热点信息基于云端数据库，内置全球可免费连接热点，随时随地轻松接入无线网络，最大化使用各种联网移动服务，扫除无网断网状态，尤其适合商务、移动人群和重度网虫。

似乎是一个共享Wi-Fi密码的工具，既然是共享，那么它也会上传手机连接过的Wi-Fi密码，这种行为已经超越了隐私，可以称之为毒瘤了吧？

**Comment by AzurLab** [comment]
> 搜索了一下 `51y5.net`域名在多个上游列表中均有屏蔽，再搜索WiFi大师
> 
> > WiFi 大师是最好用的智能手机免费畅连wifi管理工具。所有热点信息基于云端数据库，内置全球可免费连接热点，随时随地轻松接入无线网络，最大化使用各种联网移动服务，扫除无网断网状态，尤其适合商务、移动人群和重度网虫。
> 
> 似乎是一个共享Wi-Fi密码的工具，既然是共享，那么它也会上传手机连接过的Wi-Fi密码，这种行为已经超越了隐私，可以称之为毒瘤了吧？

我个人使用的修改精简版
