### ISSUE TITLE
[误杀]www.similarweb.com

### ISSUE THREAD

**Issue by wuyinghao1** [privacy-protection-tools/anti-AD#277]
域名：www.similarweb.com
发生时间：2020年11月10日
使用的列表： anti-ad-easylist.txt
问题描述：||similarweb.com^ 规则误杀了www.similarweb.com

**Comment by gentlyxu** [comment]
你好，需要进一步的信息。从内容上看，这个域名归属于一个统计分析网站。众所周知，统计是典型的收集用户行为和隐私信息的。

请告知为什么属于误杀

**Comment by wuyinghao1** [comment]
> 你好，需要进一步的信息。从内容上看，这个域名归属于一个统计分析网站。众所周知，统计是典型的收集用户行为和隐私信息的。
> 
> 请告知为什么属于误杀

www.similarweb.com是一个统计分析网站, 具体是否涉及收集隐私我个人也无法鉴定, 根据日志确实有收集隐私的analytics.similarweb.com 域名, 对于统计分析网站屏蔽它确实是好的选择, 感谢回复.
