### ISSUE TITLE
[新增拦截]gdp.gsgsr.xyz

### ISSUE THREAD

**Issue by so1ar** [privacy-protection-tools/anti-AD#278]
域名:gdp.gsgsr.xyz
出现场景：钓鱼网址，冒充政府网站。
补充说明：

**Comment by CalmLong** [comment]
复制的政府的备案号，[点击这里](https://icp.chinaz.com/%E7%B2%A4ICP%E5%A4%8705028606%E5%8F%B7)查看原备案域名

![image](https://user-images.githubusercontent.com/37164399/98778769-ca3c2680-242d-11eb-9393-7a8724a24078.png)

测试尝试提交任意内容都可以

![J5KAA`JRR$(N @9O4_8~KK2](https://user-images.githubusercontent.com/37164399/98778923-0a9ba480-242e-11eb-8ae6-974376300d1d.png)

然后并返回错误

![P0J9L47{0V6GW3S`QKZSFL8](https://user-images.githubusercontent.com/37164399/98778946-112a1c00-242e-11eb-8066-a137d9f82a53.png)
