### ISSUE TITLE
[误杀] widget.intercom.io

### ISSUE THREAD

**Issue by chicheng** [privacy-protection-tools/anti-AD#280]
域名：widget.intercom.io
发生时间：2020年11月13日
使用的列表： https://anti-ad.net/easylist.txt
规则：`/^(\S+\.)?widgets?\./`
问题描述：Intercom 有访客营销功能，但最主要的功能是提供客服在线聊天工具: https://www.intercom.com/customer-support-software

主要在商业网站应用：https://whotracks.me/trackers/intercom.html

**Comment by gentlyxu** [comment]
封杀了会影响什么？可以请你说详细一点么？

**Comment by chicheng** [comment]
使用这个服务的网站的在线客服聊天功能被屏蔽了。
