### ISSUE TITLE
[误杀]京东快递无法下单

### ISSUE THREAD

**Issue by ShureCool** [privacy-protection-tools/anti-AD#284]
域名：https://logistics-mrd.jd.com
发生时间：2020年11月27日
使用的列表： anti-ad-for-smartdns.conf
问题描述：
京东APP里面，点击寄件服务--寄快递 和 寄重货，都无法点进去，smartdns设置不过滤之后就可以了，用浏览器访问京东快递的手机端网址https://logistics-mrd.jd.com一样无法点进去

**Comment by gentlyxu** [comment]
并未发现anti-AD 有拦截 `logistics-mrd.jd.com` ，请确认一下

**Comment by ShureCool** [comment]
这几天没空，今天抽空验证了，问题和pingjs.qq.com有关，放行之后网页访问https://logistics-mrd.jd.com/express/#可以正常下单，京东APP里面也OK，将pingjs.qq.com屏蔽后问题复现

**Comment by sr093906** [comment]
I want to clarify this issue.

Blocking this domain breaks JD app's package delivery services. But THIS DOESN'T MEAN IT COLLECTS ONLY LIMITED INFO AS THE LIST MAINTAINER COMMENTED IN

https://github.com/privacy-protection-tools/anti-AD/commit/a98869d51bcd24a9e9bab450f5545a005c66067c.

Have a look at https://mta.qq.com/docs/h5_advance_access.html, an official page that is related to pingjs.qq.com. 

By integrating MTA, service provider can have a knowledge of 

> 实时数据、历史趋势、实时访客、新老访客比、**访客画像、地域信息、运营商、终端信息**、页面排行、**性能监控、访问深度**、外部链接、入口页面、离开页面

This is just what Tencent called the 'Basic Function'...

> （1）基础功能包括

I therefore suggest privacy-conscious users blocking this domain unless YOU HAVE TO USE SOME SERVICES THAT FORCE USERS TO LET IT GO TO REMAIN FUNCTIONAL.  

The case is quite similar to graph.facebook.com. Blocking it will break apps but it doesn't mean it is harmless or less harmful.

https://github.com/jerryn70/GoodbyeAds

> We block graph.facebook.com. The reason is that **this domain serves many of the ads**. So, in order to use Facebook, you should consider to whitelist either facebook's main app, or whitelist graph.facebook.com in your ad blocker — **otherwise the Facebook app will not work** (there are no problems with facebook lite app and other facebook client apps).
