### ISSUE TITLE
[误杀]百度云无法下载

### ISSUE THREAD

**Issue by chinnkarahoi** [privacy-protection-tools/anti-AD#285]
域名：issuecdn.baidupcs.com
发生时间：2020年11月30日
使用的列表： anti-ad-domains.txt
问题描述： [百度云客户端](https://pan.baidu.com/download)无法下载

**Comment by gentlyxu** [comment]
你好！能提供更详细一些的描述么？比如屏蔽了这个域名，具体的现象是怎么样的？无法下载是无法添加任务？没有下载速度？点击无响应？还是什么，因为这个域名是包含广告的，轻易放行不太合适
