### ISSUE TITLE
[误杀]酷狗音乐概念版

### ISSUE THREAD

**Issue by yfue** [privacy-protection-tools/anti-AD#286]
域名：
.mobilelog.kugou.com
.msg.mobile.kugou.com
.bssdlbig.kugou.com
.bssdl.kugou.com
发生时间：20年11月30日
使用的列表： https://anti-ad.net/surge2.txt
问题描述：
这几个屏蔽会导致酷狗音乐概念版音乐云盘存储的歌曲不能播放和下载

**Comment by gentlyxu** [comment]
必须放行列出的所有域名，还是其中一部分，希望兄弟能提供实验过程和结论，若有刚好路过的兄弟，又对酷狗音乐概念版 颇有研究，也特别欢迎指导

**Comment by yfue** [comment]
不好意思，我没弄清楚。
.mobilelog.kugou.com
.bssdlbig.kugou.com
这两个需要放行的，麻烦了
