### ISSUE TITLE
请求新增Hosts格式

### ISSUE THREAD

**Issue by GalaxyAlpha** [privacy-protection-tools/anti-AD#287]
你好，在使用AdAway导入现有的hosts格式的时候，发现都没法识别出域名，如果可以希望可以增加类似于0.0.0.0 12724.xyz这样的格式，谢谢。

**Comment by gentlyxu** [comment]
推荐我们的上游项目 [neoFelhz/neohosts](https://github.com/neoFelhz/neohosts) - 自由·负责·克制 去广告 Hosts 项目 。很nice的作者，很权威、很著名的hosts项目。

我们不推出hosts格式的原因是该格式非常臃肿，非常“写实”，例如 要屏蔽 `0024aadd.com`全站 ，需要把它下面的所有的子域名全部列出，而anti-AD从一开始就是希望精简规则的，合并了easylist格式之后，再去维护hosts格式将额外花费非常多的精力，且收益不成正比，还请兄弟理解

**Comment by GalaxyAlpha** [comment]
> 推荐我们的上游项目 [neoFelhz/neohosts](https://github.com/neoFelhz/neohosts) - 自由·负责·克制 去广告 Hosts 项目 。很nice的作者，很权威、很著名的hosts项目。
> 
> 我们不推出hosts格式的原因是该格式非常臃肿，非常“写实”，例如 要屏蔽 `0024aadd.com`全站 ，需要把它下面的所有的子域名全部列出，而anti-AD从一开始就是希望精简规则的，合并了easylist格式之后，再去维护hosts格式将额外花费非常多的精力，且收益不成正比，还请兄弟理解

没事，这种格式的确太臃肿不便，不适合拿来作为拦截规则使用，奈何AdAway的开发者似乎不太愿意支持其他格式=_=
