### ISSUE TITLE
[误杀]self.events.data.microsoft.com

### ISSUE THREAD

**Issue by tanglueyi** [privacy-protection-tools/anti-AD#288]
域名：http://self.events.data.microsoft.com/OneCollector/1.0/

使用的列表：adgurad
问题描述：edge浏览器发出的请求，每隔几秒就被拦截一次，这域名到底是干啥的？有什么办法让edge不发出这个请求吗？

**Comment by gentlyxu** [comment]
微软官方： https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1903-non-enterprise-editions

参考： https://news.ycombinator.com/item?id=20426970

这个域名用于office的遥测，是要违规收集用户信息的，不属于误杀
