### ISSUE TITLE
考虑输出 Surge list 么?

### ISSUE THREAD

**Issue by xlighting2017** [privacy-protection-tools/anti-AD#29]
目前是 surge conf, 比较难和 其他的规则共存

目前的Surge支持 list, 只需要在现有 conf基础上稍作改动, 就可以

稍作 = 去掉 [Rule] 一行 +  去掉下面每一行末尾的 ,REJECT

提供一行代码:
`tail -n +4 anti-ad-surge.txt | sed "s|,REJECT||" > surge.list`

**Comment by gentlyxu** [comment]
必须支持！当前提供的这个格式，是我自用的，不过现在也用不上了，一直没改格式。刚刚我按照你说的改了，兄弟帮忙测试测试 https://anti-ad.win/surge.txt

**Comment by xlighting2017** [comment]
测试可用, issue 关掉~

**Comment by liuyudongxiao** [comment]
也可以增加 Quantumult X的适配，这个用户量非常庞大
