### ISSUE TITLE
Clarifying Issue 284

### ISSUE THREAD

**Issue by sr093906** [privacy-protection-tools/anti-AD#291]
I want to clarify this issue.

Blocking this domain breaks JD app's package delivery services. But THIS DOESN'T MEAN IT COLLECTS ONLY LIMITED INFO. 

In short: If you do value privacy, please find another service provider 

Have a look at https://mta.qq.com/docs/h5_advance_access.html, an official page that is related to pingjs.qq.com.

By integrating MTA, service provider can have a knowledge of

> 实时数据、历史趋势、实时访客、新老访客比、**访客画像、地域信息、运营商、终端信息**、页面排行、**性能监控、访问深度**、外部链接、入口页面、离开页面

This is just what Tencent called the '_Basic Function_'...

> （1）基础功能包括

I therefore suggest privacy-conscious users blocking this domain unless YOU HAVE TO USE SOME SERVICES THAT FORCE USERS TO WHITELIST THE DOMAIN TO MAKE IT FUNCTIONAL. Even so, I am not surprised if someone tells me such kind of act is totally legal as the users have read and agreed to the terms of use and privacy policy. Haha. 

The case is quite similar to graph.facebook.com. Blocking it will break apps but it doesn't mean it is harmless or less harmful.

https://github.com/jerryn70/GoodbyeAds

> We block graph.facebook.com. The reason is that **this domain serves many of the ads**. So, in order to use Facebook, you should consider to whitelist either facebook's main app, or whitelist graph.facebook.com in your ad blocker — **otherwise the Facebook app will not work** (there are no problems with facebook lite app and other facebook client apps).

**Comment by sr093906** [comment]
This issue just serves as a reminder. I will close it sometime on Dec. 6.

**Comment by gentlyxu** [comment]
感谢关注，看commit记录可以知道我在`pingjs.qq.com`这个域名是否加白上进行了几次变动。最近我仔细的阅读了他的代码，也就是`http://pingjs.qq.com/h5/stats.js?v2.0.4`，这个sdk当然会上报用户的各种行为，但请注意！这些行为上报的域名都是`pingtas.qq.com`，而`pingjs.qq.com`域名下，只是加载sdk，加载sdk也会暴露用户的浏览器user-agent等基本信息，这就是我说的**收集信息有限**，比起多个页面因为屏蔽了`pingjs.qq.com`导致js报错，进而页面不能使用来说，放行`pingjs.qq.com`是不是更合适？

**Comment by sr093906** [comment]
@gentlyxu

A casual user's basic info also include referrer, screen size, color depth,  system language, domainLookupTime, connectTime, timezone ...

`	}

	function A() {
		var a = v(document.referrer),
			c = v();
		return {
			rdm: a.host,
			rurl: a.path,
			rarg: encodeURIComponent(a.search ||
				"").substr(0, 512),
			adt: c.param.ADTAG || c.param.adtag || c.param.CKTAG || c.param.cktag || c.param.PTAG || c.param.ptag || c.adtag
		}
	}

	function y() {
		try {
			var a = navigator,
				c = screen || {
					width: "",
					height: "",
					colorDepth: ""
				},
				e = {
					scr: c.width + "x" + c.height,
					scl: c.colorDepth + "-bit",
					lg: (a.language || a.userLanguage).toLowerCase(),
					tz: (new Date).getTimezoneOffset() / 60
				}
		} catch (b) {
			return {}
		}
		return e
	}`

**Comment by sr093906** [comment]
BTW, there are more such shit under pingjs.qq.com.

Just some of them:
https://pingjs.qq.com/tcss.ping.https.js
https://pingjs.qq.com/h5/hotclick.js
https://pingjs.qq.com/ping.js

**Comment by gentlyxu** [comment]
> BTW, there are more such shit under pingjs.qq.com.
> 
> Just some of them:
> https://pingjs.qq.com/tcss.ping.https.js
> https://pingjs.qq.com/h5/hotclick.js
> https://pingjs.qq.com/ping.js

我没有注意到下面这些js文件，然后还有可能不止这些。。。。那么这个域名的危害就不能确定了，好了，长时间的纠结到此为止。`pingjs.qq.com`将继续回到屏蔽列表中

**Comment by sr093906** [comment]
@gentlyxu 

Thanks for the reply.

As I said earlier, this issue serves as a reminder. This means I just want to let other users have a clearer picture. Whether to block the domain or not is totally up to their judgments.
