### ISSUE TITLE
[误杀]贴吧一键签到异常

### ISSUE THREAD

**Issue by yfue** [privacy-protection-tools/anti-AD#292]
域名：nlog.baidu.com发生时间：12月6日列表使用：https://anti-ad.net/surge2.txt
问题描述：屏蔽此域名会导致贴吧一键签到打不开，直接正常

**Comment by gentlyxu** [comment]
`nlog.baidu.com` 主要是收集诸多客户端行为log，不建议放行。

**Comment by yfue** [comment]
收到👌
