### ISSUE TITLE
[误杀]腾讯应用宝网页被误杀

### ISSUE THREAD

**Issue by terrytw** [privacy-protection-tools/anti-AD#294]
域名：img1.sj.qq.com
发生时间：2020年12月12日
使用的列表： anti-ad-domains.txt
问题描述：
此规则导致腾讯应用宝网站显示不正常，且无法使用搜索功能
![捕获](https://user-images.githubusercontent.com/24227628/87506326-9af2f400-c69d-11ea-817e-70feab4e03c9.PNG)
去除规则后，一切正常

此规则估计来自neofelhz的上游，我已经向那边提了issue，可是那边似乎3月份之后就没有commit了，估计项目暂时没人打理

**Comment by gentlyxu** [comment]
没有重现你描述的问题，再确认一下？
<img width="1172" alt="Jietu20201229-162339@2x" src="https://user-images.githubusercontent.com/1243610/103270438-dfc3da80-49f2-11eb-89ad-9311e14c3617.png">

**Comment by terrytw** [comment]
![1](https://user-images.githubusercontent.com/24227628/103280333-1d346200-4a0b-11eb-94c0-b56042209f78.png)

神奇啊，我这边是很明显的

**Comment by gentlyxu** [comment]
重现了。我的测试环境有问题，一会儿修复
