### ISSUE TITLE
好像翻车了

### ISSUE THREAD

**Issue by qpzr** [privacy-protection-tools/anti-AD#295]
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /home/runner/work/AGH-diy/AGH-diy/anti-AD/scripts/tools/easylist-extend.php on line 273
Error: Process completed with exit code 255.
检查一下为

**Comment by gentlyxu** [comment]
感谢告知，年底非常忙。看到你关闭我才想起来这个事，所有actions全挂了

吐槽一下：php这版本进化，真是一言难尽啊，这么优秀又怪诞还彰显技术底蕴的语法居然也淘汰

**Comment by qpzr** [comment]
> 感谢告知，年底非常忙。看到你关闭我才想起来这个事，所有actions全挂了
> 
> 吐槽一下：php这版本进化，真是一言难尽啊，这么优秀又怪诞还彰显技术底蕴的语法居然也淘汰

我也是因为昨晚LOL停机维护，没事干研究了一下才发现是PHP升级到8.0翻车的，所以自行关闭问题了

**Comment by qpzr** [comment]
> 感谢告知，年底非常忙。看到你关闭我才想起来这个事，所有actions全挂了
> 
> 吐槽一下：php这版本进化，真是一言难尽啊，这么优秀又怪诞还彰显技术底蕴的语法居然也淘汰

开始下载 dead-hosts0...
开始下载 dead-hosts1...

Error: Process completed with exit code 255.

还是没改对PHP8的格式 所以没运行直接报错了

action 里 默认PHP7.4
sudo update-alternatives --set php /usr/bin/php7.4 
直接正常 看来我还是继续这个昨晚找到的方法好了

**Comment by gentlyxu** [comment]
我加一下试试

**Comment by gentlyxu** [comment]
加上这句
```
sudo update-alternatives --set php /usr/bin/php7.4
```
恢复正常了
