### ISSUE TITLE
[误杀] issuecdn.baidupcs.com

### ISSUE THREAD

**Issue by terrytw** [privacy-protection-tools/anti-AD#298]
域名：issuecdn.baidupcs.com
发生时间：2020年12月20日
使用的列表： anti-ad-domains.txt
问题描述：
百度网盘官网上(https://pan.baidu.com/download) 下载客户端基本上都是连接 issuecdn.baidupcs.com
把这个域名封了之后，不能下载客户端

从网址上来看，感觉是百度网盘的cdn节点，不知道为何进入了封锁列表

**Comment by gentlyxu** [comment]
是百度云管家的推广用域名，如果只是影响下载客户端，那不建议放行

**Comment by terrytw** [comment]
好吧，作者的意图是较为严格的过滤，对于一定的误杀是持肯定态度。
