### ISSUE TITLE
[新增拦截] 人人影视客户端跟踪器

### ISSUE THREAD

**Issue by groundcat** [privacy-protection-tools/anti-AD#299]
域名:

file.apicvn.com

tracker1.zmzfile.com
tracker2.zmzfile.com
tracker3.zmzfile.com
tracker4.zmzfile.com
tracker5.zmzfile.com
...

htracker1.zmzfile.com
htracker2.zmzfile.com
htracker3.zmzfile.com
htracker4.zmzfile.com
htracker5.zmzfile.com
...

出现场景：
人人影视客户端

补充说明：
- 由于是泛域名解析到同一个IP地址，启动app时子域名会随机变动，可以屏蔽 *.zmzfile.com 根域名。
- 经测试，屏蔽上述域名后，不影响客户端正常使用。

**Comment by gentlyxu** [comment]
请再确认一下这个跟踪器到底上传了什么样的内容。 `*.zmzfile.com` 有没有涉及到在线字幕的加载？直接屏蔽了除了你说的不影响客户端正常使用，会不会影响其他播放器在线加载字幕呢？

**Comment by groundcat** [comment]
使用 Wireshark 嗅探发现，向 `htracker*.zmzfile.com` 和 `htracker*.zmzfile.com` 上传的数据包被加密，因此我们无从得知这个跟踪器到底上传了什么样的内容。但是因域名名为 tracker，非常有可能其用途是采集用户信息。为避免误杀，可以只屏蔽 `htracker*.zmzfile.com` 和 `htracker*.zmzfile.com`。

另外，Wireshark 嗅探发现客户端也连接了另一个疑似跟踪器域名 `tj.playcvn.com`，“tj”可能意为“统计”。

在本地将上述域名指向`0.0.0.0`，并刷新本机DNS缓存后，测试客户端的影片浏览、影片下载、在线播放、聊天室功能，均没有出现问题。

人人影视都是嵌入字幕后压制渲染影片，因此不存在在线字幕挂载的问题。

**Comment by gentlyxu** [comment]
感谢详细测试
