### ISSUE TITLE
[误杀]不知道算不算误杀

### ISSUE THREAD

**Issue by exLuLu** [privacy-protection-tools/anti-AD#300]
域名：httpdns.n.netease.com
发生时间：2020年12月25日
使用的列表： adblock-for-dnsmasq.conf
问题描述：OpenWrt开启AdByByPLUS，里面只添加了adblock-for-dnsmasq.conf这个规则，开启网抑云解锁灰色插件失败，关闭AdByByPLUS则能正常开启网抑云插件
网抑云插件日志：
Fri, 25 Dec 2020 10:54:15 +0800 # Start UnblockNeteaseMusic
Fri, 25 Dec 2020 10:54:15 +0800 # UnblockNeteaseMusic Nodejs Version (http:5200, https:5201)
Error: getaddrinfo ENOTFOUND httpdns.n.netease.com
--
  syscall: 'getaddrinfo',
  hostname: 'httpdns.n.netease.com'
}
Error: getaddrinfo ENOTFOUND httpdns.n.netease.com
--
  syscall: 'getaddrinfo',
  hostname: 'httpdns.n.netease.com'

**Comment by e703** [comment]
软路由添加的ADGuardHome 最新的版本。加载后。网抑云插件不能工作。日志如下：
--
2020/12/27 23:43:02 http.Client.Do fail:Post "http://clientlog.music.163.com/api/feedback/client/log": dial tcp: lookup clientlog.music.163.com on 127.0.0.1:53: no such host
2020/12/27 23:43:10 http.Client.Do fail:Post "http://clientlog.music.163.com/api/feedback/client/log": dial tcp: lookup clientlog.music.163.com on 127.0.0.1:53: no such host
--
2020/12/27 23:43:11 {"Id":"25790009","Size":34605162,"Br":999000,"Url":"http://other.player.rc03.sycdn.kuwo.cn/87a8657ac782c1bfd02b6047c1370c7e/5fe8ab8f/resource/s3/4/84/3961059070.flac","Md5":"","Name":"怀念战友","Artist":"刀郎","AlbumName":"北方的天空下","MatchScore":1,"Source":"kuwo"}
2020/12/27 23:43:32 http.Client.Do fail:Post "http://clientlog.music.163.com/api/feedback/client/log": dial tcp: lookup clientlog.music.163.com on 127.0.0.1:53: no such host
2020/12/27 23:44:02 http.Client.Do fail:Post "http://clientlog.music.163.com/api/feedback/client/log": dial tcp: lookup clientlog.music.163.com on 127.0.0.1:53: no such host

**Comment by gentlyxu** [comment]
先手动把下面域名加入adgh的白名单，看看问题是否解决
```
httpdns.n.netease.com
clientlog.music.163.com
```

**Comment by e703** [comment]
添加了还是不行
