### ISSUE TITLE
[误杀] ||tracking*.*^ 本行阻止了几乎世界上所有物流跟踪网站凡使用 Tracking 作为关键字的跟踪页面.

### ISSUE THREAD

**Issue by amosnet** [privacy-protection-tools/anti-AD#301]
域名：dpd / dhl / ups / speedy / any postal services in Europe
发生时间：2020年12月28日
使用的列表： https://anti-ad.net/easylist.txt
问题描述：几乎世界上所有物流跟踪网站凡使用 Tracking 作为关键字的跟踪页面被封锁.

||tracking*.*^

**Comment by gentlyxu** [comment]
事实上拦住各种广告跟踪的域名更多

**Comment by amosnet** [comment]
好，我明白甄别平衡的侧重了。
