### ISSUE TITLE
[误杀]极光推送 jiguang.cn / jpush.cn

### ISSUE THREAD

**Issue by PMExtra** [privacy-protection-tools/anti-AD#304]
域名：jiguang.cn / jpush.cn
发生时间：2021年1月3日
使用的列表： /anti-ad-easylist.txt
问题描述：
https://www.jiguang.cn/
https://www.jpush.cn/

极光推送是一个通用的App推送平台，是App开发者常用的一个服务。
据观察，该屏蔽规则不影响使用极光SDK的App正常收到推送，但是影响开发者登录极光后台和浏览开发文档。
建议删除 jiguang.cn 和 jpush.cn 这两条规则。
如果目的是屏蔽极光的跟踪服务，应该更精确的匹配极光跟踪相关的域名，而不是直接对根域名一棒子打死。

**Comment by gentlyxu** [comment]
1. 十分不推荐在工作环境中部署anti-AD；
2. 没有"如果"，100%的跟踪和用户唯一识别；
3. 你可以自行加白；

**Comment by PMExtra** [comment]
@gentlyxu 不知道为什么从你的回复中感觉到一丝不友善，不知道是我的描述哪里惹到你了，还是你对极光有什么看法。

如果我没看错，anti-AD 项目的描述是「实现**精确**的广告屏蔽和隐私保护。」，因为极光有跟踪业务，你就封禁整个极光。那么你是不是要把 qq.com 和 taobao.com 也都给封了？

我在项目描述中也没有看到任何关于「不推荐在工作环境中部署anti-AD」的声明。

我能来这里提出问题，自然是已经自己加白了，纯粹是为了分享和贡献。如果所有的规则都由我自行维护，那么 anti-AD 存在的意义是什么，还望解答。

**Comment by gentlyxu** [comment]
感谢回复
嗯，完全没有不友善。不推荐在工作环境中部署去广告我认为是众所周知的常识，工作环境中屏蔽任何域名都有可能出现问题而导致时间浪费，这种就没有必要专门声明了吧？就像卖菜刀的没有必要声明“菜刀不推荐用来刮胡须”，如果非要试试也不是不行。

说回域名屏蔽的事情，屏蔽一级域名通常是为了极致的缩短屏蔽规则，预见性的屏蔽其未来新增的子域名，而对于大多数普通用户这种屏蔽没有影响，才会有这样的规则；

关于自行维护：是有必要的，每个人都有个性化的需求，比如我自己用的就屏蔽了360.cn，2345，hao123等一大批的一级域名，而这些直接加到anti-AD势必影响到很多普通用户。一样的道理，你是极光开发者，需要自行维护一部分自己的黑名单和白名单，如果因为你是极光开发者，anti-AD就得放行极光，那下次来个广告开发者，需要放行所有广告？

`qq.com`和`taobao.com`的例子举的非常好，你可以搜索一下anti-AD的列表里有多少关于他们的子域名，这不恰恰说明了“精确”（相对来说，并没有多精确）屏蔽吗？精确是本项目一直追求的目标。屏蔽这两个一级域名的影响和屏蔽极光是完全不一样的，试问全国人民有多少人每天必须要上极光的网站？

anti-AD的存在并没有多大意义，我也没有赋予它什么了不起的意义，只是我自己用了很长一段时间之后，觉得可能有用，开源出来大家共享，同时大家一起报告问题，一起完善。

我本人仍然是anti-AD的首个忠实使用者，希望anti-AD早日实现【成为中文区命中率最高的广告过滤列表】的目标

**Comment by PMExtra** [comment]
我还是无法认同工作环境中就不应该去广告。正因为是工作环境，才更需要集中注意力，避免有限的时间和精力浪费在没有意义的广告上。菜刀不用来刮胡须是因为众所周知有剃须刀。而目前并没有一个公知的【工作环境中去广告】的产品，自然也不存在公认的不应该将anti-AD用在工作环境中。而且经过这个案例，我知道了anti-AD可能会对广告无关的业务造成误杀之后，下次遇到问题我第一时间就会排查DNS日志，更换网络环境来确认是不是anti-AD对我的工作产生了影响，这并不会导致多少时间浪费。

作为缩短评比规则，预见性的屏蔽未来新增的子域名这一点考虑，我觉得有道理，如果这一规则针对的是广告联盟、推广平台一类的网站，我认为无可厚非。事实上也是如此，对于因为anti-AD导致访问异常的淘宝联盟等网站，我就是自己维护白名单来保障使用，因为我认为淘宝联盟本身属于AD范畴。
但是极光不同，极光并不是一个广告平台，也不像CNZZ之类以跟踪作为主要业务。仅仅因为旗下有一小块数据跟踪的业务，就屏蔽整个一级域名，这让我难以接受。以广告开发者要放行所有广告作为例子就是偷换概念了，我要求放行极光，是因为我认为极光本身并不是AD，不应该属于被anti的范围。如果按照【有涉及广告和数据跟踪业务，且普通用户不常用】这一标准来对一级域名做过滤，那么包括 aliyun.com 在内的一众云服务厂商也都应该要被过滤了。

emmm，我刚发现作为同行的，友盟 umeng.com ，个推 getui.com 等平台也都是同样的被 anti-AD 屏蔽一级域名。。。

行吧，算我get到了anti-AD的一个原则。

放过这个case，我提一个 feature request，把 anti-AD 拆成几个列表，让用户自由组合。

至少拆成广告一个列表，隐私一个列表，然后每个列表中还可以进行分级。比如非常明确的是广告内容专用的域名定一级，涉及广告业务但是并不一定是广告内容的（例如广告平台）定二级这样。然后通过脚本预先把各种组合生成好列表，用户可以通过自己的需求选择是否开启某一类的过滤，开到什么等级。

这样可以实现更加精确的过滤，也可以将你所说的 2345, hao123, 360 之类的对于某一类用户普遍希望屏蔽的【垃圾网站】维护在一个列表之中了。

这样，可以大大减少用户自行维护的例外规则。

**Comment by MUSIBII** [comment]
https://firxworx.com/blog/it-devops/sysadmin/using-dnsmasq-on-macos-to-setup-a-local-domain-for-development/

**Comment by PMExtra** [comment]
@MUSIBII 你想表达什么？用dnsmasq来组合多个列表？组合列表的方法太多了，我提出的主要的点不在「组合」上，而在于「拆分」上，首先希望anti-AD能够对数据进行分类和分级。然后这个组合，由anti-AD来做或者由用户自己做都可以。之所以提出由anti-AD来提供一些预设组合，仅仅是为了兼容现有用户，让它们能够不必改变目前的使用习惯和工具

**Comment by gentlyxu** [comment]
> 我还是无法认同工作环境中就不应该去广告。正因为是工作环境，才更需要集中注意力，....

这一大段话我不知道该说啥。。。行吧，你爱怎么用就怎么用吧

**Comment by sioxe823** [comment]
> @gentlyxu 不知道为什么从你的回复中感觉到一丝不友善，不知道是我的描述哪里惹到你了，还是你对极光有什么看法。
> 
> 无意引战，首先感谢anti-AD以及所有为anti-AD做出贡献的人们。
> 我的所有描述都是从客观角度想要解决问题希望anti-AD更好，而非指责。
> 
> 如果我没看错，anti-AD 项目的描述是「实现**精确**的广告屏蔽和隐私保护。」，因为极光有跟踪业务，你就封禁整个极光。那么你是不是要把 qq.com 和 taobao.com 也都给封了？
> 
> 我在项目描述中也没有看到任何关于「不推荐在工作环境中部署anti-AD」的声明。
> 
> 我能来这里提出问题，自然是已经自己加白了，纯粹是为了分享和贡献。如果所有的规则都由我自行维护，那么 anti-AD 存在的意义是什么，还望解答。

"不知道为什么从你的回复中感觉到一丝不友善，不知道是我的描述哪里惹到你了" 这句真的笑死

看這里 "而不是直接对根域名一棒子打死" 這是对名單維護者的

**Comment by c2xusnpq6** [comment]
而且這份列表是基於域名的黑名單 所以如果他是數據分析為主的一間公司的話 就必須要 必須要整個域名封鎖 因此我不明白那裏有不妥

除非你能讓那間數據分析公司另外開一個子域名用於設置管理sdk的東西

希望你下次發言以前多想一想 因為這裏始終是~~連接~~牆外的世界 感謝你!

**Comment by sioxe823** [comment]
而且這份列表是基於域名的黑名單 所以如果他是數據分析為主的一間公司的話 就必須要 必須要整個域名封鎖 因此我不明白那裏有不妥

除非你能讓那間數據分析公司另外開一個子域名用於設置管理sdk的東西

希望你下次發言以前多想一想 因為這裏始終是連接牆外的世界 感謝你!

**Comment by c2xusnpq6** [comment]
或者維護者可以嘗試另外推出一款it從業員也可以使用的版本? 也就是放寬一點 但可能會因此而被追蹤的版本

**Comment by sioxe823** [comment]
或者維護者可以嘗試另外推出一款it從業員也可以使用的版本? 也就是放寬一點 但可能會因此而被追蹤的版本

**Comment by c2xusnpq6** [comment]
@PMExtra 如果是這樣的話我建議您使用easylist china, adguard chinese 這兩個穩定很多 而且知道的人更多 用的人更多 若果真的誤殺了的話 也比較快修補好

配合nextdns使用更佳 (他內置的黑名單好像還可以)

**Comment by sioxe823** [comment]
@PMExtra 如果是這樣的話我建議您使用easylist china, adguard chinese 這兩個穩定很多 而且知道的人更多 用的人更多 若果真的誤殺了的話 也比較快修補好

配合nextdns使用更佳 (他內置的黑名單好像還可以)

**Comment by PMExtra** [comment]
@sioxe823 首先，感谢你提供的宝贵建议。但我仍然对于前面几段话有不同意见。
请问你从哪里得出的结论 “极光是以数据分析为主的一间公司” ？极光旗下有 极光推送（JPush）、极光IM（JMessage）、极光短信（JSMS）、极光统计（JAnalytics）等大量业务，明显存在数据采集的只有极光统计。
诚然，极光可能也会从其它业务上产生一些用户数据用于数据分析，但是这样算起来，淘宝、微信、QQ、抖音等几乎所有面向C端用户的互联网产品，都会采集用户数据，那是否我们应该认为阿里巴巴、腾讯、字节跳动，这些公司，全都是“以数据分析为主的一间公司”，从而封禁他们的根域名？
将根域名一棒子打死，我认为只是阐述一个客观事实，并非是对维护者的侮辱。就像是我们不会因为腾讯采集用户数据而屏蔽 weixin.com 和 qq.com ，那么为什么因为 JAnalytics 的存在就要屏蔽 jiguang.cn 呢？

最后的最后，我已经接受了 anti-AD 的【宁愿误杀一千，绝不放过一个】基本定位，此处没有贬义，有这么一个严格的策略，是对用户隐私最强有力的保护。之前是因为我没有理解到 anti-AD 的定位，因此产生了这一问题，后来我也主动 close 了这一问题，因为我理解了这是有意为之而不是误杀。问题已经close，我认为没必要继续讨论了。

**Comment by sioxe823** [comment]
@PMExtra 你说你公司有在用jpush? 方便给一下apk档么? 我跑一下 分析一下 `jiguang.cn`可能不需要封锁

**Comment by sioxe823** [comment]
刚好找到一个
```
ali-stats.jpush.cn
sis.jpush.io
gd-stats.jpush.cn
s.jpush.cn
tsis.jpush.cn
stats.jpush.cn
```

**Comment by chacha20** [comment]
> 域名：jiguang.cn / jpush.cn 发生时间：2021年1月3日 使用的列表： /anti-ad-easylist.txt 问题描述： https://www.jiguang.cn/ https://www.jpush.cn/
> 
> 极光推送是一个通用的App推送平台，是App开发者常用的一个服务。 据观察，该屏蔽规则不影响使用极光SDK的App正常收到推送，但是影响开发者登录极光后台和浏览开发文档。 建议删除 jiguang.cn 和 jpush.cn 这两条规则。 如果目的是屏蔽极光的跟踪服务，应该更精确的匹配极光跟踪相关的域名，而不是直接对根域名一棒子打死。

极光、友盟在一些地方是禁止使用的，所以一刀切，屏蔽jpush.cn，而且是屏蔽了jpushcloud.cn。
