### ISSUE TITLE
[误杀]一系列

### ISSUE THREAD

**Issue by sayhello023** [privacy-protection-tools/anti-AD#306]
域名：hpplay.cn
发生时间：很早了
使用的列表：/anti-ad-easylist.txt
问题描述：乐播投屏如果直接屏蔽主域名会导致某些应用无法投屏，比如ios上的韩剧tv app。还有一个是芒果tv的开启广告。还有一个爱奇艺的收藏夹域名，屏蔽后收藏夹无法加载。这些用了半年了，没什么问题。来看下有没有更新，发现没更新。
添加
||h5.hpplay.com.cn^
||hpplay.cdn.cibn.cc^
||imdns.hpplay.cn^
||vipauth.hpplay.cn^
||sl.hpplay.cn^
||519332DA.rtc.youme.im^
||hotupgrade.hpplay.cn^
||tvapp.hpplay.cn^
||image.hpplay.cn^
||gslb.hpplay.cn^
||cdn.hpplay.com.cn^
||adeng.hpplay.cn^
||conf.hpplay.cn^
||adcdn.hpplay.cn^
||pin.hpplay.cn^
||rp.hpplay.cn^
||video.da.mgtv.com^

删除
||hpplay.cn^
||subscription.iqiyi.com^

**Comment by gentlyxu** [comment]
感谢提供，晚些时候处理

**Comment by gentlyxu** [comment]
收录了，有反馈再继续更新
