### ISSUE TITLE
[新增拦截] xiaomi miui

### ISSUE THREAD

**Issue by c2xusnpq6** [privacy-protection-tools/anti-AD#308]
域名:
出现场景：
补充说明：

https://gist.github.com/unknownFalleN/3f38e2daa8a98caff1b0d965c2b89b25
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Xiaomi-Extension.txt
https://gist.github.com/eboye/ef2f8c3e9e3b32c0980ff1a226770b1c

**Comment by gentlyxu** [comment]
有点多，误杀情况不好控制，等有时间慢慢消化

**Comment by c2xusnpq6** [comment]
ok~

> 
> 
> 有点多，误杀情况不好控制，等有时间慢慢消化

**Comment by c2xusnpq6** [comment]
刪除這個 https://gist.github.com/unknownFalleN/3f38e2daa8a98caff1b0d965c2b89b25#file-xiaomi_dns_block-lst-L149

**Comment by gentlyxu** [comment]
https://gist.github.com/unknownFalleN/3f38e2daa8a98caff1b0d965c2b89b25 列表中，
```
miui.com
miui.net
...
```
和
```
xiaomi.com
xiaomi.net
```

赫然在列，这个列表的权威性和国人的引用情况到底如何？

**Comment by c2xusnpq6** [comment]
> 
> 
> https://gist.github.com/unknownFalleN/3f38e2daa8a98caff1b0d965c2b89b25 列表中，
> 
> ```
> miui.com
> miui.net
> ...
> ```
> 
> 和
> 
> ```
> xiaomi.com
> xiaomi.net
> ```
> 
> 赫然在列，这个列表的权威性和国人的引用情况到底如何？

那這个先略過吧

**Comment by gentlyxu** [comment]
我的意思是这个列表是否经过验证，是否可信？连根域名都屏蔽了。这些规则暂不加入anti-AD了

**Comment by c2xusnpq6** [comment]
> 我的意思是这个列表是否经过验证，是否可信？连根域名都屏蔽了。这些规则暂不加入anti-AD了

因為那個列表可能是給...買了小米手機 卻不想要小米的任何(癰腫)東西的人吧~

**Comment by gentlyxu** [comment]
OK，不能引入这种通用性太低的列表

**Comment by c2xusnpq6** [comment]
> 
> 
> OK，不能引入这种通用性太低的列表

那其余的加了么?...
