### ISSUE TITLE
[误杀] software-download.microsoft.com

### ISSUE THREAD

**Issue by princepjamie06832** [privacy-protection-tools/anti-AD#309]
域名：software-download.microsoft.com
发生时间：2021年1月7日 
使用的列表： https://anti-ad.net/easylist.txt
问题描述：我需要下载Microsoft产品。 您能否删除此域。 此域不应在此列表中。

**Comment by gentlyxu** [comment]
尝试修复了，下面这个域名
```
||azureedge.net^
```
导致的cname被杀
