### ISSUE TITLE
[新增拦截] https://mercury.jd.com/log.gif

### ISSUE THREAD

**Issue by c2xusnpq6** [privacy-protection-tools/anti-AD#310]
域名: jd.com, jd.hk, tw.jd.com
出现场景：
补充说明：

https://github.com/privacy-protection-tools/anti-AD/issues/124

https://blog.csdn.net/weixin_37490221/article/details/80894827
https://github.com/Advanced-Frontend/Daily-Interview-Question/issues/87
http://stozen.net/40.html

**Comment by gentlyxu** [comment]
已经拦截了
```
||mercury.jd.com^
```
dns层无法实现url拦截，只能屏蔽域名
