### ISSUE TITLE
[新增拦截] Windows相关分析追踪等域名

### ISSUE THREAD

**Issue by Lonelier** [privacy-protection-tools/anti-AD#311]
域名:activity.windows.com  settings-win.data.microsoft.com  cs.dds.microsoft.com  continuum.dds.microsoft.com edge.activity.windows.com  weus2watcab01.blob.core.windows.net
出现场景：Windows 10使用当中
补充说明：域名来自WindowsSpyBlocker (Spy)及NextDNS深度跟踪保护（Windows）

**Comment by gentlyxu** [comment]
能否提供一下规则的原地址，感谢

**Comment by Lonelier** [comment]
https://github.com/nextdns/metadata/blob/master/privacy/native/windows
https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/hosts/spy.txt

**Comment by Lonelier** [comment]
> 
> 
> 能否提供一下规则的原地址，感谢

https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/hosts/spy.txt
https://github.com/nextdns/metadata/blob/master/privacy/native/windows

**Comment by gentlyxu** [comment]
https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/hosts/spy.txt 已加入上游列表，正观察误杀情况，若可用，将稳定运行

**Comment by gentlyxu** [comment]
为了方便观察，暂时不要关闭此issue

**Comment by haygcao** [comment]
用了这个your phone 不能使用

**Comment by haygcao** [comment]
> 情况是这样的，我电脑上安装的your phone 5天前突然让不饿能使用了，我一直在排查，后来去拦截路由器广告那里看发现了，your phone 的所有数据链接都被拦截了，我就顺着找过来了，我不知道有没有其他人也遇到过这个类似的情况。具体哪个域名我没看，但是我已停用anti ad 就能连接了，麻烦您筛查一下。

@@||mobile.pipe.aria.microsoft.com^$important
@@||continuum.dds.microsoft.com^$important
@@||vortex.data.microsoft.com^$important
@@||v10.events.data.microsoft.com^$important
@@||settings-win.data.microsoft.com^$important   第一条应该最重要

**Comment by Lonelier** [comment]
> 
> 
> > 情况是这样的，我电脑上安装的your phone 5天前突然让不饿能使用了，我一直在排查，后来去拦截路由器广告那里看发现了，your phone 的所有数据链接都被拦截了，我就顺着找过来了，我不知道有没有其他人也遇到过这个类似的情况。具体哪个域名我没看，但是我已停用anti ad 就能连接了，麻烦您筛查一下。
> 
> @@||mobile.pipe.aria.microsoft.com^$important
> @@||continuum.dds.microsoft.com^$important
> @@||vortex.data.microsoft.com^$important
> @@||v10.events.data.microsoft.com^$important
> @@||settings-win.data.microsoft.com^$important 第一条应该最重要

朋友，你可以加白名单测试一下吗？

**Comment by haygcao** [comment]
> > > 情况是这样的，我电脑上安装的your phone 5天前突然让不饿能使用了，我一直在排查，后来去拦截路由器广告那里看发现了，your phone 的所有数据链接都被拦截了，我就顺着找过来了，我不知道有没有其他人也遇到过这个类似的情况。具体哪个域名我没看，但是我已停用anti ad 就能连接了，麻烦您筛查一下。
> > 
> > 
> > @@||mobile.pipe.aria.microsoft.com^$important
> > @@||continuum.dds.microsoft.com^$important
> > @@||vortex.data.microsoft.com^$important
> > @@||v10.events.data.microsoft.com^$important
> > @@||settings-win.data.microsoft.com^$important 第一条应该最重要
> 
> 朋友，你可以加白名单测试一下吗？

嗯嗯我家白名单了，但是应该还有一条我没找出来上面这个不知道有没有多的

**Comment by Lonelier** [comment]
> 
> 
> > > > 情况是这样的，我电脑上安装的your phone 5天前突然让不饿能使用了，我一直在排查，后来去拦截路由器广告那里看发现了，your phone 的所有数据链接都被拦截了，我就顺着找过来了，我不知道有没有其他人也遇到过这个类似的情况。具体哪个域名我没看，但是我已停用anti ad 就能连接了，麻烦您筛查一下。
> > > 
> > > 
> > > @@||mobile.pipe.aria.microsoft.com^$important
> > > @@||continuum.dds.microsoft.com^$important
> > > @@||vortex.data.microsoft.com^$important
> > > @@||v10.events.data.microsoft.com^$important
> > > @@||settings-win.data.microsoft.com^$important 第一条应该最重要
> > 
> > 
> > 朋友，你可以加白名单测试一下吗？
> 
> 嗯嗯我家白名单了，但是应该还有一条我没找出来上面这个不知道有没有多的。主要是我就一个小白哈哈，电脑同时发出的microsoft 有点多，我就一条条的在dns 的屏蔽了找的

没事，我也小白。你说的your phone不能使用是哪一方面啊？主要这玩意我不用我不知道怎么帮你筛选啊

**Comment by haygcao** [comment]
> > > > > 情况是这样的，我电脑上安装的your phone 5天前突然让不饿能使用了，我一直在排查，后来去拦截路由器广告那里看发现了，your phone 的所有数据链接都被拦截了，我就顺着找过来了，我不知道有没有其他人也遇到过这个类似的情况。具体哪个域名我没看，但是我已停用anti ad 就能连接了，麻烦您筛查一下。
> > > > 
> > > > 
> > > > @@||mobile.pipe.aria.microsoft.com^$important
> > > > @@||continuum.dds.microsoft.com^$important
> > > > @@||vortex.data.microsoft.com^$important
> > > > @@||v10.events.data.microsoft.com^$important
> > > > @@||settings-win.data.microsoft.com^$important 第一条应该最重要
> > > 
> > > 
> > > 朋友，你可以加白名单测试一下吗？
> > 
> > 
> > 嗯嗯我家白名单了，但是应该还有一条我没找出来上面这个不知道有没有多的。主要是我就一个小白哈哈，电脑同时发出的microsoft 有点多，我就一条条的在dns 的屏蔽了找的
> 
> 没事，我也小白。你说的your phone不能使用是哪一方面啊？主要这玩意我不用我不知道怎么帮你筛选啊

your phone 就是在登录账户和手机链接的时候，电脑上发出的链接申请都被拦截了，完全没法和手机连，就是第一条 mobile 那条。 他会卡在60%的位置，就是数据没发出去的状态

**Comment by Lonelier** [comment]
@haygcao 你说的同屏卡住是手机电脑链接成功之后还是没有链接成功

**Comment by Lonelier** [comment]
@haygcao 我添加了mobile.pipe.aria.microsoft.com，continuum.dds.microsoft.com两条规则后，电脑端进度条100%，但显示遇到连接问题，是不是你说的情况？

**Comment by haygcao** [comment]
> @haygcao 我添加了mobile.pipe.aria.microsoft.com，continuum.dds.microsoft.com两条规则后，电脑端进度条100%，但显示遇到连接问题，是不是你说的情况？

对的，你这还能100% 我在没加白名单的时候60%romeccs.microsoft.com cdpcs.microsoft.com

**Comment by Lonelier** [comment]
> 
> 
> > @haygcao 我添加了mobile.pipe.aria.microsoft.com，continuum.dds.microsoft.com两条规则后，电脑端进度条100%，但显示遇到连接问题，是不是你说的情况？
> 
> 对的，你这还能100% 我在没加白名单的时候60%romeccs.microsoft.com cdpcs.microsoft.com

你是双端拦截吗？还是只有手机或电脑

**Comment by haygcao** [comment]
> > > @haygcao 我添加了mobile.pipe.aria.microsoft.com，continuum.dds.microsoft.com两条规则后，电脑端进度条100%，但显示遇到连接问题，是不是你说的情况？
> > 
> > 
> > 对的，你这还能100% 我在没加白名单的时候60%romeccs.microsoft.com cdpcs.microsoft.com
> 
> 你是双端拦截吗？还是只有手机或电脑

没有我就在路由器的adguard home 上拦截的。现在正常了

**Comment by gentlyxu** [comment]
> 情况是这样的，我电脑上安装的your phone 5天前突然让不饿能使用了，我一直在排查，后来去拦截路由器广告那里看发现了，your phone 的所有数据链接都被拦截了，我就顺着找过来了，我不知道有没有其他人也遇到过这个类似的情况。具体哪个域名我没看，但是我已停用anti ad 就能连接了，麻烦您筛查一下。


继续讨论，兄弟们。我没有重现这个问题，有可能是我电脑的问题，还需要懂行的兄弟继续测试

**Comment by hue715** [comment]
上游issue也提出了类似问题
https://github.com/crazy-max/WindowsSpyBlocker/issues/300
