### ISSUE TITLE
[热烈讨论]再提这个问题：建议 retcode.taobao.com 放行

### ISSUE THREAD

**Issue by luzhaohui** [privacy-protection-tools/anti-AD#312]
再提这个问题：
1、h-adashx.ut.taobao.com，问题不大，杀掉也不影响使用。
2、retcode.taobao.com，这个真的影响使用，尤其是钉钉，一进入办公审批流程就卡住了；我觉得不应该只有我个人遇到了这个问题，虽然我自己是放行了，但还是觉得应该提出来。

_Originally posted by @luzhaohui in https://github.com/privacy-protection-tools/anti-AD/issues/181#issuecomment-723562359_

**Comment by gentlyxu** [comment]
来波投票（用+1，-1），看看多少人遇到

**Comment by luzhaohui** [comment]
> 来波投票（用+1，-1），看看多少人遇到

haha，我肯定是 +1

**Comment by luzhaohui** [comment]
> 来波投票（用+1，-1），看看多少人遇到

我自己做了一个排查，把常用的拦截规则按如下顺序写在 Surge 的规则里，发现只有 anti-AD 在拦截 retcode.taobao.com，关键是拦截这个地址后，造成了钉钉无法使用审批流程，只能自己放行这个地址。
所以，这真的是一个误杀（至少我认为是误杀，因为已经影响到了正常使用）。

DOMAIN-SET,https://cdn.jsdelivr.net/gh/geekdada/surge-list/domain-set/dns-filter.txt,REJECT // DNS filter
DOMAIN-SET,https://cdn.jsdelivr.net/gh/geekdada/surge-list/domain-set/chinese-filter.txt,REJECT // Chinese filter
DOMAIN-SET,https://cdn.jsdelivr.net/gh/geekdada/surge-list/domain-set/adaway.txt,REJECT // AdAway

RULE-SET,https://cdn.jsdelivr.net/gh/lhie1/Rules@master/Surge/Surge%203/Provider/Reject.list,REJECT

RULE-SET,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Advertising.list,REJECT
RULE-SET,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Privacy.list,REJECT
RULE-SET,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Hijacking.list,REJECT

**DOMAIN-SET,https://cdn.jsdelivr.net/gh/privacy-protection-tools/anti-AD@master/anti-ad-surge2.txt,REJECT // anti-AD**

**Comment by gentlyxu** [comment]
我之前捕获到的示例URL `http://retcode.taobao.com/r.png?uid=4e6642cf-3988-4931-b843-1b308f2930e6&userNick=&times=1&_t=-15698432473&tag=&api=articleDetailService&issucess=true&delay=437&msg=success&detail=&type=retcode&sampling=1&spm=a2700.8293689,alibaba.com` ，实际上这种传参方式可以上报任何的隐私数据。

**Comment by gentlyxu** [comment]
这个域名是不太明确是否归为误杀，每个人的需求也是千差万别的

**Comment by luzhaohui** [comment]
> 我之前捕获到的示例URL `http://retcode.taobao.com/r.png?uid=4e6642cf-3988-4931-b843-1b308f2930e6&userNick=&times=1&_t=-15698432473&tag=&api=articleDetailService&issucess=true&delay=437&msg=success&detail=&type=retcode&sampling=1&spm=a2700.8293689,alibaba.com` ，实际上这种传参方式可以上报任何的隐私数据。

我也查到了类似的信息，但似乎都没有说明这个域名存在窃取隐私的行为。

**Comment by gentlyxu** [comment]
是的。我也只是怀疑这种上报方式，没有明确的证据证明

这么多天过去，就我们俩在讨论，我希望投票决定的方式又行不通了。至2021-01-31 23:00:00，如果仍然无人问津，我就把`retcode.taobao.com`加入白名单，请 @luzhaohui 兄弟再耐心等等了，我想把更多选择权交给社区，真正发挥开源的力量。

**Comment by luzhaohui** [comment]
> 是的。我也只是怀疑这种上报方式，没有明确的证据证明
> 
> 这么多天过去，就我们俩在讨论，我希望投票决定的方式又行不通了。至2021-01-31 23:00:00，如果仍然无人问津，我就把`retcode.taobao.com`加入白名单，请 @luzhaohui 兄弟再耐心等等了，我想把更多选择权交给社区，真正发挥开源的力量。

好的，这个耐心肯定是有的。我是自己加入了白名单放行，只是觉得这是一个完全可以复现且会造成问题的“误杀”，并且这个域名还没有发现违规行为，才再次提出这个问题。

**Comment by PikuZheng** [comment]
我投+1（但不用钉钉

**Comment by qwerttvv** [comment]
+1

另外我希望这个列表的原则的话，最好是最小伤害为第一准则：）

比如1条规则命中10个evil，但是杀了1个正常的，那我觉得这条规则就应该废弃
