### ISSUE TITLE
[误杀]mobile.pipe.aria.microsoft.com

### ISSUE THREAD

**Issue by e703** [privacy-protection-tools/anti-AD#315]
域名：mobile.pipe.aria.microsoft.com
发生时间：2021年01月12日
使用的列表： （具体的文件，例如/anti-ad-easylist.txt）
问题描述：这个是微软官方针对安全认证的API地址，封堵的话无法开启手机二次验证功能

**Comment by gentlyxu** [comment]
请提供进一步的详细信息。经测试，使用microsoft Authenticator 的批准功能完全正常，“无法开启手机二次验证功能”是指的什么？

**Comment by PikuZheng** [comment]
难道是这个项目使用的人太少
顺便说一下 Microsoft Authenticator 的五位字符批准一直是正常的，但是三选一的数字批准总是显示服务器通讯出错。这个问题和 issue 提到的域名无关

**Comment by PikuZheng** [comment]
> issue 里提到的域名是微软著名的遥测域名，各大广告屏蔽都有它。数字批准通讯出错你不用屏蔽广告的大概也会出错 （：我每次恢复数据就会通讯出错，清除数据重新登录就好了

Autherticator 清除数据重新登陆吗？三选一数字批准（免密码登陆）能好用一阵子？

**Comment by MoonBegonia** [comment]
> > issue 里提到的域名是微软著名的遥测域名，各大广告屏蔽都有它。数字批准通讯出错你不用屏蔽广告的大概也会出错 （：我每次恢复数据就会通讯出错，清除数据重新登录就好了
> 
> Autherticator 清除数据重新登陆吗？三选一数字批准（免密码登陆）能好用一阵子？

![image](https://user-images.githubusercontent.com/26798347/105433891-75225980-5c95-11eb-95d6-4ac8d45cf3f1.png)

我只有恢复过 authenticator 数据才会出现这种问题，其余时候并无此种情况出现，不知道清除数据是否可以解决，你可以按照我画的图走一遍看看 : )

**Comment by PikuZheng** [comment]
我可以肯定三选一和广告屏蔽、国内访问无关。
刚试了清除 Autherticator 数据然后重新登陆的确可以三选一了。这就很玄学。
感谢提供信息 @MoonBegonia 
------
不过这个 issue 可以 close 了 @gentlyxu
