### ISSUE TITLE
可否将Surge的做成Module

### ISSUE THREAD

**Issue by cyjahappy** [privacy-protection-tools/anti-AD#318]

**Comment by gentlyxu** [comment]
我确实不懂Module是什么样子的，一时间也还没有抽空来学习，所以还回答不了，能或不能。。。你是否可以提供一下相关说明，我再来判断

**Comment by TPCTPCTPC** [comment]
Module非常简单，自己写一个也行，好处就是可以做一个anti-AD的快捷开关。参见：https://github.com/TPCTPCTPC/Adblock-gist

**Comment by cyjahappy** [comment]
Thanks> Module非常简单，自己写一个也行，好处就是可以做一个anti-AD的快捷开关。参见：https://github.com/TPCTPCTPC/Adblock-gist
