### ISSUE TITLE
[误杀]app-measurement.com

### ISSUE THREAD

**Issue by PikuZheng** [privacy-protection-tools/anti-AD#319]
域名：app-measurement.com
发生时间：2021年01月18日
使用的列表： anti-ad-for-smartdns.conf
问题描述：
app-measurement.com 用于 firebase 消息推送组件的网络检查，等同于 connectivitycheck.gstatic.com。
某些 app （如 Tiktok）屏蔽此域名后直接报告网络不通，并拒绝连接尝试

**Comment by gentlyxu** [comment]
自测在屏蔽了此域名的环境中，安卓版 tiktok能正常使用，没有复现网络不通的情况，请再次确认

**Comment by PikuZheng** [comment]
求测tiktok（with music.ly）有没有刷8个视频然后报网络不稳定的情况

**Comment by Aikatsui** [comment]
Such type of domain doesn't need to unblock and additionally its blocked by many adblock lists not only @gentlyxu's list
