### ISSUE TITLE
[误杀]analytics-api.smzdm.com

### ISSUE THREAD

**Issue by 3136083906** [privacy-protection-tools/anti-AD#321]
域名：analytics-api.smzdm.com
wxsnsdy.wxs.qq.com
iotapi.adups.com
发生时间：2020年1月1日至今
使用的文件：https://anti-ad.net/easylist.txt
问题描述：严格来讲应该不是规则的问题，而是App的问题，比如第一条是什么值得买的一条规则，如果不放行的话，app会非常卡顿耗电严重。第二条规则确实是广告，但是他是微信和京东的一个看视频任务，没办法只能放行。第三条是电视盒子的系统升级文件规则。后面两条其实不是特别重要。最重要的是第一条什么值得买的那个规则。那个要是不放行的话，这个App基本用不了了，太卡顿了。

**Comment by gentlyxu** [comment]
> 比如第一条是什么值得买的一条规则，如果不放行的话，app会非常卡顿耗电严重。

“app会非常卡顿耗电严重” 是怎么定位到这个域名的？能详细讲一讲复现过程吗

**Comment by 3136083906** [comment]
应该是这个App反复要求这个权限，

**Comment by gentlyxu** [comment]
> 第二条规则确实是广告，但是他是微信和京东的一个看视频任务，没办法只能放行。
是广告就没有必要报误杀啦～顺便说一句：如果确有看广告的需求，比如看广告赚钱、看广告完成任务一类的，不建议拦截统计和隐私上报，否则可能会被广告系统判定为作弊而引起麻烦

**Comment by gentlyxu** [comment]
> 应该是这个App反复要求这个权限，

![image](https://user-images.githubusercontent.com/1243610/105619094-22c67180-5e2a-11eb-8d3e-a233d89fbde3.png)

从时间上来看，并不会反复请求这个域名，我一直开着这个app

**Comment by 3136083906** [comment]
可是确实是我把这个域名放行之后App就流畅了，耗电也没那么严重了。关键是adguardhome 可以逐条放行规则。其他的屏蔽广告软件没有日志系统，这就难办了。

**Comment by gentlyxu** [comment]
咦～～似乎是每隔12秒会自动重试一次

**Comment by gentlyxu** [comment]
确实有反复尝试解析`analytics-api.smzdm.com`，但并没有重现你说的卡顿和耗电严重的问题。iOS和安卓都有打开

**Comment by MoonBegonia** [comment]
很多域名屏蔽后都是重试很多次的，造成卡顿，加载慢没有办法，只能自行取舍了 😶
