### ISSUE TITLE
[误杀] jwpcdn.com

### ISSUE THREAD

**Issue by ghost** [privacy-protection-tools/anti-AD#322]
域名：jwpcdn.com
发生时间 2020年1月25日
使用的列表： NextDNS 使用此屏蔽列表，经确认列表中存在 jwpcdn.com
问题描述：DW 使用了 jwplayer 播放器，jwplayer 的一些 js 文件托管在这个域上面，禁止会导致播放器无法加载

存在视频播放问题的页面：

https://www.dw.com/zh/%E5%8F%91%E5%B1%95%E6%96%B0%E8%83%BD%E6%BA%90-%E4%B8%AD%E5%9B%BD%E6%8E%80%E8%B5%B7%E9%A3%8E%E7%94%B5%E6%8A%A2%E8%A3%85%E6%BD%AE/a-56312851

**Comment by ygsk10** [comment]
使用 jwplayer 官方网站上的这个播放器 demo 也可以复现问题

https://www.jwplayer.com/developers/web-player-demos/live-streaming/

<img width="1323" alt="Screen Shot 2021-01-27 at 00 57 47" src="https://user-images.githubusercontent.com/77837107/105877223-b3739c00-603a-11eb-8342-482762ef6d49.png">

**Comment by ygsk10** [comment]
git blame 确认此规则最早出现在 

https://github.com/privacy-protection-tools/anti-AD/blob/65ef3eaeb8154fa16fba193c49c9b203333abe77/origin-files/easylist4.txt

上游的 initial commit 就包含了这一条
https://github.com/banbendalao/ADgk/commit/2a7f0cae2e85755b0117c2d0f9cd549f3c678e84
message 是 **仓库转移**，但是找不到之前的历史了

**Comment by ygsk10** [comment]
源文件对于 `p.jwpcdn.com` （存放 js 文件的域）有一个白名单的处理 

https://github.com/privacy-protection-tools/anti-AD/blob/65ef3eaeb8154fa16fba193c49c9b203333abe77/origin-files/easylist4.txt#L692

自动合并时没有处理这一条
