### ISSUE TITLE
[误杀]serverlist.fgcq.3975.com

### ISSUE THREAD

**Issue by lerry** [privacy-protection-tools/anti-AD#326]
域名：serverlist.fgcq.3975.com
发生时间：2021年2月1日
使用的列表： https://anti-ad.net/easylist.txt
问题描述：
3975的手游打不开了，无法获取服务器列表。3975.com 是游戏，不是广告

**Comment by gentlyxu** [comment]
感谢告知，这条规则来自上游，可能是该游戏厂商用这个域名投放广告了，导致主域被误杀
