### ISSUE TITLE
[误杀]针对miui的误杀(?)

### ISSUE THREAD

**Issue by PussAzuki** [privacy-protection-tools/anti-AD#328]
域名：`api.sec.miui.com` `api.miui.security.xiaomi.com` `sec.resource.xiaomi.net`
发生时间：2021年2月2日
使用的列表：https://anti-ad.net/easylist.txt
问题描述：前两个拦截了会导致miui手机管家无法更新“骚扰拦截”功能所需要的数据库
最后一个拦截了会导致小米应用商店无法领取每日红包

**Comment by gentlyxu** [comment]
其中的多个域名并不存在于anti-AD的拦截列表中，请再仔细甄别，更为严谨的提出问题

**Comment by PussAzuki** [comment]
现在看了下，前两个确实不在列表中，而是再ADGuard的filter中，我忘了检查了，只是一股脑把自定义规则里的方形部分复制过来

所以第三个应该是你们这列表里的吧
