### ISSUE TITLE
[误杀] 解鎖百度 :/

### ISSUE THREAD

**Issue by Aikatsui** [privacy-protection-tools/anti-AD#329]
域名：share.baidu.com 
问题描述：gitee

![download](https://user-images.githubusercontent.com/63988538/106622349-110d6880-65a6-11eb-9309-a8e9fe93f716.png)

**Comment by gentlyxu** [comment]
不是很推荐放行该域名。多个上游列表同时拦截了这个域名，应该不是简单的误杀。进一步说加载这个域名下的js后，会收集隐私。

**Comment by Aikatsui** [comment]
> 不是很推荐放行该域名。多个上游列表同时拦截了这个域名，应该不是简单的误杀。进一步说加载这个域名下的js后，会收集隐私。

@gentlyxu but this's a important part on gitee platform and that's what have as good local service while google drive, onedrive and others collect more privacy data seriously but they're smart enough to gather them indirectly

Can't you find any way to whitelist that? maybe you can s.share.baidu.com (affected domain) instead share.baidu.com

**Comment by Aikatsui** [comment]
(not related to this request)
@gentlyxu I also want to know what other lists block this subdomain `share.baidu.com` that leads for affect to `s.share.baidu.com`
