### ISSUE TITLE
[误杀]规则: ||file.market.xiaomi.com^

### ISSUE THREAD

**Issue by Mosney** [privacy-protection-tools/anti-AD#33]
小米应用商店的应用图标使用此域名，例如
http://file.market.xiaomi.com/thumbnail/PNG/l114/AppStore/0a21605a012a34b741d85cbecf50bf5b4db0d9146

**Comment by gentlyxu** [comment]
感谢反馈，已于最新版本中修复 8265ad698772d7d91245363cd0a79e9e699bcd30
