### ISSUE TITLE
来自用户的小请求

### ISSUE THREAD

**Issue by Karmylr** [privacy-protection-tools/anti-AD#336]
anti-ad规则非常好用，但是目前能屏蔽https协议的广告的koolproxy/koolproxyr没法识别anti-ad规则。可以出个koolproxy版的anti-ad吗？

**Comment by gentlyxu** [comment]
从原理上，在kpr中应用anti-AD的规则，是对kpr的大材小用

**Comment by Karmylr** [comment]
> 从原理上，在kpr中应用anti-AD的规则，是对kpr的大材小用

我是想用koolproxyr去广告的同时还能放追踪之类的。

**Comment by gentlyxu** [comment]
kpr是一个基于内容的过滤工具，anti-ad的规则只涉及域名，根本达不到kpr的粒度，这么说你能明白吗？
