### ISSUE TITLE
[误杀]gitlab无法正常运作

### ISSUE THREAD

**Issue by c2xusnpq6** [privacy-protection-tools/anti-AD#337]
域名：
https://assets.gitlab-static.net/
使用的列表： `/^(\S+\.)?analytics(\-|\.)/`
问题描述：gitlab无法正常运作
https://assets.gitlab-static.net/assets/webpack/commons-pages.admin.audit_logs-pages.admin.impersonation_tokens-pages.analytics.productivity_analyti-0cf84cb4.189cbab7.chunk.js

![image](https://user-images.githubusercontent.com/75058881/107457726-8de3a800-6b8d-11eb-8edd-385c75f5d237.png)

![image](https://user-images.githubusercontent.com/75058881/107457768-a2c03b80-6b8d-11eb-9bfc-2c857a852a23.png)

**Comment by c2xusnpq6** [comment]
雖然這是`anti-ad-easylist.txt` 但過份easy的規則 比如這个`analytics`跟`counter`这些易误杀的可以分开放么谢 (很明显的 比如`baidu_counter`除外?

**Comment by gentlyxu** [comment]
我晚点再想想办法，anti-ad规则起初的设计是只涉及域名的，没有要匹配整个url的意思

**Comment by gentlyxu** [comment]
> 雖然這是`anti-ad-easylist.txt` 但過份easy的規則 比如這个`analytics`跟`counter`这些易误杀的可以分开放么谢 (很明显的 比如`xiaomianalytics` `baidu_counter`除外?

没有get到你的意思，小米和百度的数据分析和统计就是误杀吗？

**Comment by gentlyxu** [comment]
研究了一番，为了兼容市面上其他的、甚至未知的过滤工具，让正则表达式只匹配域名的话，会使得表达式变得臃肿不堪，放弃了。建议还是将anti-ad用在readme中推荐的地方

**Comment by c2xusnpq6** [comment]
👍🏼

**Comment by c2xusnpq6** [comment]
> 研究了一番，为了兼容市面上其他的、甚至未知的过滤工具，让正则表达式只匹配域名的话，会使得表达式变得臃肿不堪，放弃了。建议还是将anti-ad用在readme中推荐的地方

可以分开2个版本么 一个是穩定版 一个是比较激进一点的(现在这个...)

我想要穩定.... T.T 555555555
