### ISSUE TITLE
[误杀]微博第三方客户端share点赞验证

### ISSUE THREAD

**Issue by uh00095** [privacy-protection-tools/anti-AD#339]
域名：
`monitor.geetext.com`
`static.geetext.com`
`api.geetext.com`
发生时间：2021年2月11日
使用的列表： Anti-AD.txt
问题描述：微博第三方客户端share点赞验证无法显示

**Comment by gentlyxu** [comment]
这些域名并不在anti-ad的屏蔽列表中，请再次确认
