### ISSUE TITLE
[误杀] main.m.taobao.com

### ISSUE THREAD

**Issue by c2xusnpq6** [privacy-protection-tools/anti-AD#342]
域名：main.m.taobao.com
问题描述：无法正常瀏覽
https://main.m.taobao.com/cart/index.html?cartFrom=taobao_client

**Comment by gentlyxu** [comment]
打开你提供的url，是一个登录页面，具体无法正常浏览是指的什么？

![image](https://user-images.githubusercontent.com/1243610/108615917-9cf70f80-7443-11eb-9443-7c3bb80d48df.png)
