### ISSUE TITLE
[误杀]虎牙p2p.huya.com

### ISSUE THREAD

**Issue by liuluping0106** [privacy-protection-tools/anti-AD#345]
域名：p2p.huya.com
发生时间：xxx年xx月xx日
使用的列表： https://anti-ad.net/anti-ad-for-dnsmasq.conf
问题描述：这个域名是虎牙数据流传输的地址，拦截会是直播加载异常

**Comment by gentlyxu** [comment]
这个域名之前讨论过多次，我自己以及一些朋友一起测试过

#228 #254 

> 首先说明一下，这条规则是从上游源继承过来的。查了一些资料和之前反馈的issues，这个p2p.huya.com应该是个p2p共享流量的东东，被屏蔽的最可能的原因是网友看不惯虎牙偷偷上传流量，不屏蔽可能会将上传带宽跑满和CPU居高不下（有相关讨论贴）。你的带宽略小，大概还是放行会体验更好。


结论就是造成直播卡顿不是必现的，而大多数网友是认为这个域名偷偷占用带宽上传流量（可google搜索相关讨论），所以仍然还是屏蔽这个域名
