### ISSUE TITLE
[误杀]v.qq.com

### ISSUE THREAD

**Issue by lindong629** [privacy-protection-tools/anti-AD#351]
域名：ppp.net
发生时间：xxx年xx月xx日
使用的列表： （具体的文件，例如/anti-ad-easylist.txt, /dist/anti-ad-surge-full.txt等等）
问题描述：
v.qq.com 在游览器播放视频的时候阻断这两个URL导致无法播放,

vd.l.qq.com    VIP视频无法播放
btrace.video.qq.com    普通视频无法播放

**Comment by gentlyxu** [comment]
没能重现你说的现象，腾讯视频的所有视频都能正常播放
