### ISSUE TITLE
[误杀] NGA论坛里部分帖子用到的图床

### ISSUE THREAD

**Issue by PussAzuki** [privacy-protection-tools/anti-AD#353]
域名：ftp.bmp.ovh
发生时间：2021年2月22日
使用的列表： https://anti-ad.net/easylist.txt
问题描述：如题 目前发现这个地址是有被当做图床来使用的...

**Comment by gentlyxu** [comment]
确实有屏蔽这个根域名。`bmp.ovh`，规则来源于 `https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt` ，你说的图床，有没有示例的帖子，提供一些看看

**Comment by PussAzuki** [comment]
https://ngabbs.com/read.php?tid=25609445 看乐子用的...

**Comment by PussAzuki** [comment]
https://imgurl.org/
