### ISSUE TITLE
[误杀] Taobao Orders Page, can't go to next page

### ISSUE THREAD

**Issue by xenstar** [privacy-protection-tools/anti-AD#355]
域名：https://buyertrade.taobao.com/trade/itemlist/list_bought_items.htm
发生时间：25年02月21日
使用的列表：https://anti-ad.net/easylist.txt
问题描述：Cannot go to the second page of buying list in Taobao. Something is blocking by the adguard home server. 

![doesnt work](https://user-images.githubusercontent.com/55502651/109115581-3db63980-777a-11eb-9728-268b6277e54b.png)

**Comment by gentlyxu** [comment]
你好，我登录taobao.com，然后点击你提供的URL，然后点击第二页，第三页……均能正常打开，没能重现你的问题。
