### ISSUE TITLE
[误杀] 拦截chtbl.com导致部分播客无法播放

### ISSUE THREAD

**Issue by TPCTPCTPC** [privacy-protection-tools/anti-AD#358]
域名：chtbl.com
发生时间：2021年03月03日
使用的列表：surge2.txt
问题描述：如题，在使用微信小程序播放播客“迟早更新”时无法加载（直接搜索 迟早更新 播客 进入的小程序），将chtbl.com放行后解决。在reddit上也看到[类似案例](https://amp.reddit.com/r/pihole/comments/kspwsh/apple_podcasts_fail_when_they_cant_connect_to/)，拦截此域名导致部分Apple podcast无法播放。上面说这个网站是心跳检测的作用，确实存在隐私追踪的问题，请大佬权衡下是否需要放行。

**Comment by gentlyxu** [comment]
我正准备编辑一个anti-ad的使用文档，讲明放行和屏蔽的利害关系，对于某些域名，由用户选择是否放行，类似此issue提及的域名，官方不予放行，但影响正常使用时，可临时加入白名单

**Comment by TPCTPCTPC** [comment]
好的了解。
