### ISSUE TITLE
[误杀]skydrivesync.policies.live.net

### ISSUE THREAD

**Issue by tjr57** [privacy-protection-tools/anti-AD#359]
域名：skydrivesync.policies.live.net
发生时间：2021年03月07日
使用的列表： anti-ad-easylist.txt
问题描述：导致onedrive程序无法联网同步

**Comment by gentlyxu** [comment]
没有啊
```
dig skydrivesync.policies.live.net

; <<>> DiG 9.10.6 <<>> skydrivesync.policies.live.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33399
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;skydrivesync.policies.live.net.	IN	A

;; ANSWER SECTION:
skydrivesync.policies.live.net.	22 IN	CNAME	common-geo.ha.1drv.com.
common-geo.ha.1drv.com.	22	IN	CNAME	common-us.onedrive.akadns.net.
common-us.onedrive.akadns.net. 22 IN	A	157.55.109.224

;; Query time: 37 msec
;; SERVER: 10.1.1.1#53(10.1.1.1)
;; WHEN: Sun Mar 07 21:39:50 CST 2021
;; MSG SIZE  rcvd: 140

```

**Comment by tjr57** [comment]
这个很玄学，一般情况下也不会登录不上，但是偶尔就会因为这个地址拦截就登录不上，一旦加入了白名单之后就能登录，然后从白名单移除之后一段时间居然也没事，然后过了一段时间在某个时刻又会登录不上……从年前到现在我反复加入白名单和移除白名单三次，三次都是指向这个地址。具体的我没法分析，只能表述我使用的感受。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "privacy-protection-tools/anti-AD"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月7日(星期天) 晚上9:41
收件人:&nbsp;"privacy-protection-tools/anti-AD"<anti-AD@noreply.github.com&gt;;
抄送:&nbsp;"谭竣仁"<287250552@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [privacy-protection-tools/anti-AD] [误杀]skydrivesync.policies.live.net (#359)





 
没有啊
 dig skydrivesync.policies.live.net ; <<&gt;&gt; DiG 9.10.6 <<&gt;&gt; skydrivesync.policies.live.net ;; global options: +cmd ;; Got answer: ;; -&gt;&gt;HEADER<<- opcode: QUERY, status: NOERROR, id: 33399 ;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0 ;; QUESTION SECTION: ;skydrivesync.policies.live.net.	IN	A ;; ANSWER SECTION: skydrivesync.policies.live.net.	22 IN	CNAME	common-geo.ha.1drv.com. common-geo.ha.1drv.com.	22	IN	CNAME	common-us.onedrive.akadns.net. common-us.onedrive.akadns.net. 22 IN	A	157.55.109.224 ;; Query time: 37 msec ;; SERVER: 10.1.1.1#53(10.1.1.1) ;; WHEN: Sun Mar 07 21:39:50 CST 2021 ;; MSG SIZE  rcvd: 140
