### ISSUE TITLE
Breakage due to ccmp.eu

### ISSUE THREAD

**Issue by crssi** [privacy-protection-tools/anti-AD#365]
Listed `ccmp.eu`  is used as a CNAME for online catalogues.
Working sample from affiliated email: `https://l.newsletter.lidl.com/rts/go2.aspx?h=35714&tp=i-1NGB-D6-pM-cMSp-1c-Qgk-1c-cHqo-l5nj5aAaDA-WBYSD&x=3184%7c9142819`

Would you be so kind and remove `ccmp.eu` ?

Thank you ❤️

**Comment by crssi** [comment]
I don't know why `wontfix` label has been assigned?

**Comment by crssi** [comment]
Thank you.

**Comment by gentlyxu** [comment]
> Thank you.

Haha, happy to help!
