### ISSUE TITLE
[误杀] 统计学相关域名 www.stats.ox.ac.uk

### ISSUE THREAD

**Issue by doabell** [privacy-protection-tools/anti-AD#366]
域名：http://www.stats.ox.ac.uk/
发生时间：2020年03月14日
使用的列表：https://anti-ad.net/easylist.txt
问题描述：一些和统计学相关的域名
规则：`/^(\S+\.)?(web)?stats?\./`

更多域名：
https://stats.stackexchange.com/
https://stats.idre.ucla.edu/
https://www.stats.govt.nz/
以及 Google 搜索 `site:stats.*.*`

![image](https://user-images.githubusercontent.com/35297086/111068057-08dc0d80-8502-11eb-91ab-4560f9e4e314.png)

**Comment by gentlyxu** [comment]
都是stats是吧，那我修正一下

**Comment by gentlyxu** [comment]
@doabell ，请更新到最新规则看看是否ok

**Comment by doabell** [comment]
测了几个域名都没问题了，非常感谢

**Comment by doabell** [comment]
还有一些域名是 stat 的
规则：`/^(\S+\.)?(stat|webstats?|swebstats?|mywebstats?)\./`
```
https://www.stat.cmu.edu/
https://www.stat.ubc.ca/
https://stat.ethz.ch/
https://www.stat.org.uk/
```

加一个  .edu 的白名单可以过滤掉一部分大学
不过这其实不算中文区了……加一句“统计学用户谨慎选择”?

**Comment by gentlyxu** [comment]
😓，这条规则初衷是为了归纳规则列表中的用户行为统计域名（不过也误杀过统计局网站），再次修改了一下，你测测

**Comment by GeQi** [comment]
同样的还有 http://ads.harvard.edu/
实话实说这样写 list 实在是有点好笑。

**Comment by doabell** [comment]
https://www.stat.go.jp/ 或许给日本的统计局加个白名单?
剩下的就很小众了 比如
https://stat.memberclicks.net/ Science Teachers Association of Texas
http://stat.gibdd.ru/ 俄交通局
http://www.stat.or.kr/ Korea Statistics Promotion Institute

**Comment by gentlyxu** [comment]
彻底删除了这个`stat`这个关键字的正则，再试试看

**Comment by doabell** [comment]
删除后测试正常
哇，三次下来300多条更改，辛苦了
