### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by l20f111164** [privacy-protection-tools/anti-AD#369]
域名：dig.*.net  , dig.*.cn
发生时间：2021年03月18日
使用的列表： （具体的文件，/anti-ad-easylist.txt）
问题描述：
抖音直播间商品列表信息无法打开，也就是抖音直播间的购物车图标无法点击查看对应商品列表，从而无法购物，添加排除如下域名之后恢复正常。

@@||dig.*.net^$important
@@||dig.*.cn^$important

**Comment by gentlyxu** [comment]
没有弄懂你的意思。这两个都不是域名
