### ISSUE TITLE
[误杀]Mediawiki搜索页面显示不完整

### ISSUE THREAD

**Issue by Lehmaning** [privacy-protection-tools/anti-AD#373]
域名：zh.wikipedia.org（所有Mediawiki实例）
使用的列表：/anti-ad-easylist.txt
问题描述：列表中的规则 `/^(\S+\.)?widgets?\./` 导致维基百科搜索页面显示不完整。
希望能将`@@/mediawiki\.widgets\./`这条白名单规则加入列表。

**Comment by gentlyxu** [comment]
没太看明白，具体涉及什么域名啊？`zh.wikipedia.org` 这个域名不会触发`/^(\S+\.)?widgets?\./` 这条规则

还有，你把anti-AD的规则用在了什么地方？

**Comment by Lehmaning** [comment]
好吧，原来正则是用来匹配域名的。
