### ISSUE TITLE
[误杀] pcgamingwiki 编辑界面 js

### ISSUE THREAD

**Issue by GeQi** [privacy-protection-tools/anti-AD#374]
域名：https://www.pcgamingwiki.com/w/index.php?title=Doom_Eternal&action=edit&section=1
问题描述
![image](https://user-images.githubusercontent.com/4011632/111921887-a1234680-8a5c-11eb-9d7b-9244e590794d.png)

**Comment by gentlyxu** [comment]
用错地方了，兄弟。 仅维护readme页面说明的使用场景

**Comment by GeQi** [comment]
没有用错地方，况且正则不论他用在哪里都是正则。

**Comment by GeQi** [comment]
See also https://github.com/privacy-protection-tools/anti-AD/issues/373

**Comment by gentlyxu** [comment]
> 没有用错地方，用 Adguard 也是一样的。况且正则不论他用在哪里都是正则。

这么肯定吗？你能弄清楚域名和URL的区别吗？ 还有AdGuardHome与AdGuard的区别？

anti-AD最初的设计是针对域名进行拦截过滤的，写的正则也是。正则到哪里都是正则这句话没错，但是原先设计的正则只用来匹配域名，而不是用来匹配整个URL的

顺便说一句，针对域名和内容进行过滤的规则，颗粒度是精细得多的。

**Comment by gentlyxu** [comment]
所以，之前也有人提过一样的问题，我想过优化正则只匹配域名，好像根本没有意义，因为那些已经能匹配到URL的过滤工具，肯定能更精细的过滤广告，非得优化只能重现为它们维护一套另外的规则，个人精力完全罩不住

**Comment by GeQi** [comment]
明白了，感谢维护。
