### ISSUE TITLE
[误杀]profile.se.360.cn

### ISSUE THREAD

**Issue by lzqd** [privacy-protection-tools/anti-AD#381]
域名：profile.se.360.cn
发生时间：21年4月4日
使用的列表： https://anti-ad.net/easylist.txt
问题描述：域名被拦截导致360极速浏览器收藏夹同步失败。

**Comment by gentlyxu** [comment]
没有发现这个域名被拦截，请将屏蔽列表更新到最新再试

**Comment by lzqd** [comment]
> 没有发现这个域名被拦截，请将屏蔽列表更新到最新再试

- [ ] **这跟确实是在你的拦截规则里的。
![QQ截图20210415125854](https://user-images.githubusercontent.com/68813588/114816330-84bfc300-9dea-11eb-9307-439419d4d992.png)
![QQ截图20210415125927](https://user-images.githubusercontent.com/68813588/114816336-87bab380-9dea-11eb-84b6-36f7078630de.png)
