### ISSUE TITLE
[误杀]2345网页误拦

### ISSUE THREAD

**Issue by lzqd** [privacy-protection-tools/anti-AD#382]
域名：www.2345.com，tv.2345.com
发生时间：21年3月12日
使用的列表： https://anti-ad.net/easylist.txt
问题描述：家里有人使用2345影视看电视剧，添加该过滤规则后2345网址导航和2345影视都打不开了，目前已经添加排除。希望尽快优化过滤列表。

**Comment by gentlyxu** [comment]
不建议放行

**Comment by lzqd** [comment]
> 不建议放行

家人习惯了这个2345影视所以我单独添加例外也没什么

**Comment by gentlyxu** [comment]
ok.谢谢支持
