### ISSUE TITLE
[误杀] metrics.brightcove.com

### ISSUE THREAD

**Issue by kousyougi** [privacy-protection-tools/anti-AD#386]
域名：metrics.brightcove.com
发生时间：2021年04月10日
使用的列表： 全部
问题描述：
看tver.jp的时会出现 地域外ERROR
移除之后就正常了

**Comment by gentlyxu** [comment]
这个就是用户行为统计的吧？放行的理由是啥？

**Comment by kousyougi** [comment]
我刚刚加回去测，没有这个错误。应该是我搞错了
