### ISSUE TITLE
[误杀] ddos-guard

### ISSUE THREAD

**Issue by GeQi** [privacy-protection-tools/anti-AD#388]
域名：check.ddos-guard.net
发生时间：04-11
使用的列表：https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt

**Comment by gentlyxu** [comment]
这条规则来自`https://easylist.to/easylist/easyprivacy.txt` ，理论上有收集隐私的问题，请补充说明影响
