### ISSUE TITLE
[误杀]手机浏览器使用百度搜索的问题

### ISSUE THREAD

**Issue by foxconndmd** [privacy-protection-tools/anti-AD#389]
域名：boxer.baidu.com
使用的列表： https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-smartdns.conf
问题描述：手机浏览器用百度搜索打开目标链接时使用boxer.baidu.com跳转，导致不能打开搜索结果的目标链接。

**Comment by gentlyxu** [comment]
自测没有发现你描述的跳转到`boxer.baidu.com`的情况

**Comment by foxconndmd** [comment]
有点奇怪，有时跳转有时不跳转，我自己在客户端处理吧。

**Comment by protectedMan** [comment]
同样发现此问题,有时候百度搜索点击搜索结果会跳转到boxer.baidu.com

**Comment by coderbean** [comment]
同样遇到了这个问题，百度网页版必须弹窗，然后点击取消后才会进入搜索结果。
中间跳转页 是 boxer.baidu.com 的。
[测试连接（要在手机端打开）](https://boxer.baidu.com/scheme?scheme=baiduboxapp%3A%2F%2Fv1%2Fbrowser%2Fopen%3Furl%3Dhttps%253A%252F%252Fwww.baidu.com%252Ffrom%253D844b%252Fs%253Fword%253D%2525E7%25259F%2525B3%2525E6%2525B2%2525B3%2525E5%2525AD%252590%2525E5%2525A4%2525A7%2525E5%2525AD%2525A6%2526ts%253D0%2526t_kt%253D0%2526ie%253Dutf-8%2526fm_kl%253D021394be2f%2526rsv_iqid%253D3884180707%2526rsv_t%253D6cd48HZ%2525252Bbn5oCOcC1AsRk2VJkR5mYRkhstASbMZOox9skNVDUYCFBVOA%2525252FQ%2526sa%253Dihr_4_d%2526ms%253D1%2526rsv_pq%253D3884180707%2526tj%253D1%2526rsv_sug4%253D1635863037604%2526ss%253D011%2526rqid%253D3884180707%2526rfrom%253D1024093s%2526rchannel%253D1024099c%26newwindow%3D0%26simple%3D1%26fromwise%3D1%26needlog%3D1%26logargs%3D%257B%2522source%2522%253A%25221024093s%2522%252C%2522from%2522%253A%2522openbox%2522%252C%2522page%2522%253A%2522safari%2522%252C%2522type%2522%253A%2522%2522%252C%2522value%2522%253A%2522%2522%252C%2522channel%2522%253A%25221024099c%2522%252C%2522extlog%2522%253A%257B%2522ext_content%2522%253A%257B%2522from%2522%253A%2522844b%2522%252C%2522browserid%2522%253A%252225%2522%252C%2522qid%2522%253A%25223884180707%2522%252C%2522sids%2522%253A%2522107311_110085_127969_175667_176398_178384_178629_179350_179451_181485_181588_182248_182273_182530_183035_183329_183982_184012_184198_184794_184893_184893_185215_185651_185880_186319_186596_186635_186716_186743_186841_186898_187061_187084_187201_187292_187356_187421_187433_187449_187529_187669_187726_187815_187929_188031_188182_188426_188453_188463_188469_188553_188730_188846_188933_189058_189097_189233_189255_189326_189346_189391_189412_189431_189448_189679_189731_189755_189756_189926_190035_190155_190210_190474_190515_190621_190679_190751_190780_190790_191030_191117_191242_191415_191427_191501_191527_191533_191598_191797%2522%252C%2522timestamp%2522%253A1635863046386%252C%2522invokeId%2522%253A%25223884180707_1635863046381%2522%257D%257D%252C%2522baiduId%2522%253A%2522CCADD99B5FEBE009F2A9E197E60AB888%253AFG%253D1%2522%252C%2522app_now%2522%253A%2522safari_1635863046388_3255127961%2522%257D&source=1024093s&channel=1024099c&target=https%3A%2F%2Fwww.baidu.com%2Ffrom%3D844b%2Fs%3Fword%3D%25E7%259F%25B3%25E6%25B2%25B3%25E5%25AD%2590%25E5%25A4%25A7%25E5%25AD%25A6%26ts%3D0%26t_kt%3D0%26ie%3Dutf-8%26fm_kl%3D021394be2f%26rsv_iqid%3D3884180707%26rsv_t%3D6cd48HZ%25252Bbn5oCOcC1AsRk2VJkR5mYRkhstASbMZOox9skNVDUYCFBVOA%25252FQ%26sa%3Dihr_4%26ms%3D1%26rsv_pq%3D3884180707%26tj%3D1%26rsv_sug4%3D1635863037604%26ss%3D011&token=&ts=&appid=&tokenData=%7B%22url%22%3A%22https%3A%2F%2Fwww.baidu.com%2Ffrom%3D844b%2Fs%3Fword%3D%25E7%259F%25B3%25E6%25B2%25B3%25E5%25AD%2590%25E5%25A4%25A7%25E5%25AD%25A6%26ts%3D0%26t_kt%3D0%26ie%3Dutf-8%26fm_kl%3D021394be2f%26rsv_iqid%3D3884180707%26rsv_t%3D6cd48HZ%25252Bbn5oCOcC1AsRk2VJkR5mYRkhstASbMZOox9skNVDUYCFBVOA%25252FQ%26sa%3Dihr_4_d%26ms%3D1%26rsv_pq%3D3884180707%26tj%3D1%26rsv_sug4%3D1635863037604%26ss%3D011%26rqid%3D3884180707%26rfrom%3D1024093s%26rchannel%3D1024099c%26ivk_p2%3D844b%22%2C%22activity_id%22%3A220%7D)

我的解决办法是放弃百度了，中文搜索用Bing吧
