### ISSUE TITLE
[误杀]网页版闲鱼2.taobao.com被误杀

### ISSUE THREAD

**Issue by garypang13** [privacy-protection-tools/anti-AD#39]
规则: /^[1-2]\\.[0-9a-z\\.\\-]+\\.(com|cn|net|cc|me)$/    导致2.taobao.com被误杀.

**Comment by garypang13** [comment]
这条规则会不会威力太大了点,感觉会误杀很多网站.

**Comment by gentlyxu** [comment]
> 这条规则会不会威力太大了点,感觉会误杀很多网站.

已经调整了多次，从列表对比，命中广告和垃圾域名的多，误杀的少。因为命中了没有人提issue。“幸存者偏差”
