### ISSUE TITLE
【误杀】chtbl.com会被匹配成REJECT，导致声动活泼旗下的所有播客均无法正常播放

### ISSUE THREAD

**Issue by xieft** [privacy-protection-tools/anti-AD#390]
如图，关闭规则后恢复正常

![photo_2021-04-14_10-31-50](https://user-images.githubusercontent.com/35829258/114646258-85365c00-9d0d-11eb-86a3-1c84f43e1e8e.jpg)
![photo_2021-04-14_10-31-49](https://user-images.githubusercontent.com/35829258/114646262-87001f80-9d0d-11eb-96ac-47a658885c3a.jpg)

**Comment by gentlyxu** [comment]
放行该域名是否就可以播放了呢？

**Comment by xieft** [comment]
是的
2021年4月14日 +0800 22:15 gentlyxu ***@***.***>，写道：
