### ISSUE TITLE
[误杀] 10086相关

### ISSUE THREAD

**Issue by Befod** [privacy-protection-tools/anti-AD#393]
域名：www.10086.cn.baidu.cdn.yiwk.com
发生时间：xxx年xx月xx日
使用的列表： anti-ad-domains.txt
问题描述：这个域名在anti-ad-easylist.txt等其它几个文件中是没有的，会造成10086的一些页面出现问题

**Comment by gentlyxu** [comment]
可能性不大，这个域名指向的是个`美女图库`， 和10086的关系是？

**Comment by Befod** [comment]
那可能是我的问题，其它文件中没有这个域名，也许是我误会了
