### ISSUE TITLE
使用的padavan固件没有dnsmasq.d路径

### ISSUE THREAD

**Issue by lon91ong** [privacy-protection-tools/anti-AD#394]
没有找到`dnsmasq.d`路径, 所以自己新建了一个放置下载的`anti-ad-for-dnsmasq.conf`
不清楚这么操作对不对
![路径问题](https://user-images.githubusercontent.com/16462258/115145383-d2a32800-a083-11eb-854f-813c7ceface5.png)

**Comment by gentlyxu** [comment]
有关工具使用和配置的问题，建议多Google、百度

**Comment by lon91ong** [comment]
> 有关工具使用和配置的问题，建议多Google、百度

搜索结果太凌乱, 主要参考了[恩山的结果](https://www.right.com.cn/forum/thread-217335-1-1.html), 单好像并没有用到anti-AD, 而且效果验证的结果也不好, PC端查看cnBeta页面似乎完全没过滤
