### ISSUE TITLE
[新增拦截] 勾正数据（创维智能电视监视上报所有连网设备）

### ISSUE THREAD

**Issue by groundcat** [privacy-protection-tools/anti-AD#402]
域名: 
gz-data.com
gzads.com
gozendata.com

出现场景：创维智能电视 勾正数据服务

补充说明：
抓包记录见以下V2EX帖子《我家电视机正在监视所有连网设备》https://www.v2ex.com/t/772523
备份：https://web.archive.org/web/*/https://www.v2ex.com/t/772523

**Comment by kr513268** [comment]
gzads.com
gozendata.com
还有这两个
