### ISSUE TITLE
[误杀]火萤视频壁纸官网huoying666.com

### ISSUE THREAD

**Issue by 547555909** [privacy-protection-tools/anti-AD#405]
火萤视频壁纸官网
huoying666.com
是一个视频壁纸APP，不是广告网站

**Comment by gentlyxu** [comment]
主域名已放行，仍有
```
s2.huoying666.com
u.huoying666.com
```
在屏蔽列表中

请帮忙确认一下这两个域名是否误杀

**Comment by 547555909** [comment]
> u.huoying666.com

也是误杀，请一起放行下。

**Comment by gentlyxu** [comment]
> > u.huoying666.com
> 
> 也是误杀，请一起放行下。

能具体说说这个域名是干什么的吗？ 举例被误杀的URL

**Comment by 547555909** [comment]
> > > u.huoying666.com
> > 
> > 
> > 也是误杀，请一起放行下。
> 
> 能具体说说这个域名是干什么的吗？ 举例被误杀的URL

火萤APP在使用的域名，应该是这样的
