### ISSUE TITLE
[误杀] tracking-protection.cdn.mozilla.net

### ISSUE THREAD

**Issue by xiao-mantou** [privacy-protection-tools/anti-AD#407]
域名：tracking-protection.cdn.mozilla.net
发生时间：2021年4月26日
使用的列表： anti-ad-easylist.txt
问题描述：
应该是Firefox用来同步已知跟踪器的
另外windows10针对得有点严重啊,推送,系统设置同步(?),不知道是不是有意为之.

**Comment by gentlyxu** [comment]
Windows的屏蔽规则主要是来自 https://github.com/crazy-max/WindowsSpyBlocker/

不是有意为之，而是之前有网友推荐此列表。其他的问题可以搜搜本issues区

**Comment by xiao-mantou** [comment]
> 
> 
> Windows的屏蔽规则主要是来自 https://github.com/crazy-max/WindowsSpyBlocker/

用spy.txt就好, 用extra.txt太过了, 可以在readme中详细推荐, 我自认为您的过滤器不应如此匿名化, 说真的如果"误杀"严重的话有些人会觉得保护隐私和屏蔽广告鸡肋, 保护隐私不应成为小众人的癖好.
