### ISSUE TITLE
[新增拦截] 某中國互聯網電視 tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [privacy-protection-tools/anti-AD#408]
域名: gz-data.com (100% sure)
gzdata.com.cn (not sure)
gozendata.com
出现场景：创维电视?
补充说明：

請參考文章「我家电视机正在监视所有连网设备」:
https://www.v2ex.com/t/772523

还有这些:
https://gitee.com/bigdataleaveme/dontcollectme/raw/master/dontcollectme.txt

**Comment by gentlyxu** [comment]
前面已经有朋友提交过了。 #402  #403

**Comment by gentlyxu** [comment]
不要重复提交
