### ISSUE TITLE
[误杀] OneDrive Windows 客户端卡登录

### ISSUE THREAD

**Issue by robertying** [privacy-protection-tools/anti-AD#409]
域名：skydrivesync.policies.live.net
发生时间：2021年4月29日
使用的列表： anti-ad-easylist.txt
问题描述：（猜测）

1. `skydrivesync.policies.live.net` 解析为了：
   CNAME: i-snz04p-cor002.api.p001.1drv.com. (ttl=2902)
   A: 104.44.88.24 (ttl=2902)
2. `i-snz04p-cor002.api.p001.1drv.com` 被规则 `||*-cor0*.api.p001.1drv.com^` 拦截
3. OneDrive 卡在“登录中”

**Comment by gentlyxu** [comment]
别猜测啊！！你把域名放到白名单里，看看onedrive是否正常登录。

**Comment by robertying** [comment]
写了猜测，是因为 onedrive 客户端并不是每次启动都会连接这个域名，可能是存在一定程度的结果缓存（测试时 DNS 缓存每次都手动清空了）

1. anti-ad 开启，onedrive 无法登录；
2. 将此域名白名单，onedrive 可以登录；
3. 关闭 onedrive，将此域名从白名单移除，onedrive 再次启动时依旧正常登录。

域名误杀是确凿的。看这个域名也像是功能性的。
