### ISSUE TITLE
[误杀]千牛客户端使用异常[淘宝天猫卖家pc客户端]

### ISSUE THREAD

**Issue by EnnawYang** [privacy-protection-tools/anti-AD#41]
域名：taobao.com，tmall.com，etc...（主要为千牛客户端）
发生时间：2020-02-19，2020-02-20
使用的列表： anti-ad-easylist.txt
问题描述：放入路由器全局拦截之后千牛登录出现异常，具体症状例如无法正常加载团队列表，挂起状态，千牛首页模块等等，关闭广告拦截或者更换其它规则之后恢复正常，其它地方还没发现什么异常
![Snipaste_2020-02-20_09-58-41](https://user-images.githubusercontent.com/6705663/74898304-79cef580-53d4-11ea-8ed4-112b3db5eeb9.png)
![Snipaste_2020-02-20_09-59-03](https://user-images.githubusercontent.com/6705663/74898306-7b002280-53d4-11ea-85bc-f4e52557ad4f.png)

**Comment by gentlyxu** [comment]
请查询一下拦截日志，看看具体是哪个（些）域名被误杀了

**Comment by gentlyxu** [comment]
还有不明白的，欢迎加下qq群 716981535

**Comment by EnnawYang** [comment]
路由器没有日志，但win端又是正常的（

我再观察下，issue先关闭了
