### ISSUE TITLE
[误杀]腾讯视频首页有部分图片加载不出来

### ISSUE THREAD

**Issue by Karmylr** [privacy-protection-tools/anti-AD#411]
域名：v.qq.com
发生时间：2021年4月29日
使用的列表：/anti-ad-easylist.txt （具体的文件，例如/anti-ad-easylist.txt, /dist/anti-ad-surge-full.txt等等）
问题描述：腾讯视频主页的图片加载不出来。测试后认为是anti-ad误杀了。

**Comment by gentlyxu** [comment]
自测没有发现该问题。请补充一下，加载不出来的图片域名是哪个？

**Comment by Karmylr** [comment]
![Uploading Screenshot_20210503_205612_com.tencent.qqlive.jpg…]()

**Comment by Karmylr** [comment]
![Screenshot_20210503_205739_com android chrome](https://user-images.githubusercontent.com/69903376/116878743-5c412100-ac52-11eb-83a1-2d3f8bf751b7.jpg)
![Screenshot_20210503_205739_com android chrome](https://user-images.githubusercontent.com/69903376/116878759-5f3c1180-ac52-11eb-97fc-a006f454fa2d.jpg)

![Screenshot_20210503_205612_com tencent qqlive](https://user-images.githubusercontent.com/69903376/116878725-577c6d00-ac52-11eb-8877-4b2e58d1f3b9.jpg)
![Screenshot_20210503_205647_com android chrome](https://user-images.githubusercontent.com/69903376/116878737-5a775d80-ac52-11eb-8936-3b75096a4cdb.jpg)

**Comment by Karmylr** [comment]
> 自测没有发现该问题。请补充一下，加载不出来的图片域名是其中？

请问为什么毛线都不说就直接关了?

**Comment by Karmylr** [comment]
发现了，是从别人那复制来的自定义规则误杀了。抱歉添麻烦了
