### ISSUE TITLE
[误杀]quark.sm.cn

### ISSUE THREAD

**Issue by SakuraAkino** [privacy-protection-tools/anti-AD#412]
域名：quark.sm.cn
发生时间：2021年05月01日
使用的列表：/anti-ad-easylist.txt
问题描述：
触发规则 
/^(\S+\.)?advert/$dnstype=~CNAME
原始响应
CNAME: ai.advertisement.alibabacorp.sm.cn. (ttl=300)
CNAME: zb-443-wagbridge.advertisement.alibaba-inc.com. (ttl=300)
CNAME: zb-443-wagbridge.advertisement.alibaba-inc.com.gds.alibabadns.com. (ttl=194)

**Comment by gentlyxu** [comment]
#412
