### ISSUE TITLE
關於誤殺問題

### ISSUE THREAD

**Issue by c2xusnpq6** [privacy-protection-tools/anti-AD#413]
請問您知道您的這個廣告黑名單被nextdns收錄了嗎

這是一個基於dns的廣告&追蹤器攔截dns服務

但是我之前有跟您反映說 那些tracker tracking analyze analysis 這些字眼的匹配範圍過大 令到我原本已經選用了您的這份列表 但後來想了又想 最後只能忍痛把他關掉

希望你可以推出一個誤殺率更低的黑名單  反正我也只會在nextdns用 不用擔心我的電腦 或者手機 或者電視的效能降低
因為這些負擔都在nextdns他們那邊 
期待那一天的到來 謝謝

**Comment by c2xusnpq6** [comment]
因為我不想拖慢 或過度佔用移動設備 例如手機 以及智能電視的效能 (好幾年前的款了 有點慢)
所以我才打算使用nextdns

手機及電腦的話 我是nextdns配合adguard使用

**Comment by c2xusnpq6** [comment]
還是說... 你可以把tracker analysis這些 限定那些大型企業或者廣告公司的域名 (如果是adguard的話 可以使用
比如知名的阿里雲 Facebook Google umeng

**Comment by c2xusnpq6** [comment]
如何創建自己的廣告過濾器 (adguard):
https://kb.adguard.com/zh/general/how-to-create-your-own-ad-filters

DNS過濾規則語法 (adguard):
https://kb.adguard.com/zh/general/dns-filtering-syntax

```
/^(\S+\.)?counter(\-|\.)/  --->
/^(\S+\.)?counter(\-|\.)/$domain=umengcloud.com
/^(\S+\.)?counter(\-|\.)/$domain=umeng.com
```
![image](https://user-images.githubusercontent.com/75058881/116795447-b1bce700-ab07-11eb-9b87-f657a9d9bb78.png)

![image](https://user-images.githubusercontent.com/75058881/116795423-6dc9e200-ab07-11eb-9e62-76c7403acba8.png)

另外 下面這些可以被收录 ^^
```
# ||umengcloud.com.gds.alibabadns.com^
# ||umeng.com.gds.alibabadns.com^
||umeng*.*.alibabadns.com^
||umeng*.alibabadns.com^
# ||umengjmacs.m.taobao.com^
# ||umengacs.m.taobao.com^
||umeng*.taobao.com^
||umeng*.*.taobao.com^
```

**Comment by gentlyxu** [comment]
误杀率并不高，只是当前不支持adguard

精力有限，短期不会添加对adguard的支持，可以试试adguard home版加载easylist格式

**Comment by gentlyxu** [comment]
> 請問您知道您的這個廣告黑名單被nextdns收錄了嗎
> 

它们使用的列表是anti-ad-domains.txt，不会有通配符或正则表达式匹配而导致误杀的问题

**Comment by c2xusnpq6** [comment]
> > 請問您知道您的這個廣告黑名單被nextdns收錄了嗎
> 
> 它们使用的列表是anti-ad-domains.txt，不会有通配符或正则表达式匹配而导致误杀的问题

我android手機之前就是在adguard用的easylist版本.......

**Comment by gentlyxu** [comment]
我说的是nextdns，你能明白我上面说的是什么吗？
