### ISSUE TITLE
[新增拦截]虎牙新使用的p2p域名

### ISSUE THREAD

**Issue by onebest1** [privacy-protection-tools/anti-AD#415]
域名:pp.io
ppio.cloud
出现场景：虎牙新使用的p2p域名
补充说明：

**Comment by gentlyxu** [comment]
https://ppio.cloud/about.html ，这是个cdn服务商吧？

> PPIO是由PPTV创始人姚欣及王闻宇于2018年发起的分布式云计算项目，目标是打造一个去中心化的分布式云服务，使命是汇聚全球计算资源，并为全人类提供服务。PPIO基于共享经济的商业模式，结合大数据、云原生、分布式计算技术，汇聚网络边端侧的专业服务器资源，构建出首个覆盖全国所有省市区县的分布式云服务，为下一代低时延、高带宽、可靠安全的边缘计算场景服务。目前已成为国内外多家一线音视频互联网巨头、云计算公司、独角兽创业企业的分布式云服务的主要提供商。目前在全中国2000多个城市及地区设有微数据中心机房和分布式算力资源，可以提供全国范围内在网络边缘侧部署的裸金属云、容器云服务，以及基于分布式云原生架构的CDN分发、音视频直播及转码、应用性能监控、AI计算推理、云游戏渲染等边缘计算服务。公司核心团队成员均有超过十年以上的科技及互联网领域创业及管理经验，两位联合创始人曾经研发的PPTV网络电视，是曾拥有4.5亿用户的P2P分布式网络流媒体应用。创始团队坚持『价值创造、商业落地、全球普适』的观念，希望在新一轮分布式云计算创新的浪潮中，将边缘计算从概念推进到落地，有效连接云，边，端的算力资源，为下一代应用提供分布式云基础设施，并希望能通过开源建立边缘计算的行业标准，用技术让我们的生活更美好！
