### ISSUE TITLE
新增屏蔽

### ISSUE THREAD

**Issue by 18140135973** [privacy-protection-tools/anti-AD#416]
盗版steam（百度任何3a游戏几乎都会出现的广告，兜售共享账号而已，坑害无数小白）
域名：steam.dadagame.net
player.ebwii.com
game.99box.com
vip.99box.com
youxi.99box.com
www.99box.com
youxi.tuiplay.com

**Comment by gentlyxu** [comment]
共享账号会有什么危害？是否涉及广告，隐私泄漏或是病毒木马？

如果是盗版侵权，建议向受害方举报，向国家版权局等有关部门举报该网站

**Comment by 18140135973** [comment]
唔，可以说是诈骗网站了，毕竟是花钱买盗版。
问题是举报了国家根本没怎么实质性管过..这些网站还是堂而皇之的摆在那里。
