### ISSUE TITLE
[误杀]Apple Muisc播放服务被拦截

### ISSUE THREAD

**Issue by EndDream** [privacy-protection-tools/anti-AD#417]
域名：aod.itunes.g.aaplimg.com
发生时间：2021年5月4日
使用的列表：https://anti-ad.net/easylist.txt
问题描述：Apple Muisc无法播放，查询adguard home日志后发现触发anti-ad规则，自定义放行该域名后便可以播放

**Comment by gentlyxu** [comment]
过滤列表是否更新到最新了？
具体是哪条规则拦截的？请发一下截图。我在AdGuard Home中没有重现这个问题

**Comment by EndDream** [comment]
> 过滤列表是否更新到最新了？
> 具体是哪条规则拦截的？请发一下截图。我在AdGuard Home中没有重现这个问题

我的失误，看错拦截文件了，是adgk的拦截，抱歉

**Comment by gentlyxu** [comment]
OK
