### ISSUE TITLE
[新增拦截] 网易云音乐App无用域名

### ISSUE THREAD

**Issue by PussAzuki** [privacy-protection-tools/anti-AD#421]
域名:：nstool.ntes53.netease.com p2cdn.com nstool.netease.com
出现场景：网易云音乐安卓APP播放音乐时
补充说明：上述域名(包括CNAME) 是软件运行时完全不需要使用的 但是却一直在用来反查不知用途的域名且**增加点击播放后实际开始播放的时间** 禁用后暂无观察到明显的副作用

**Comment by CalmLong** [comment]
`nstool.netease.com` 似乎是一个检测网络的，不太建议拦截

**Comment by PussAzuki** [comment]
但是你抓包会发现，app一直在请求该网址下的一个脚本，然后返回一堆302的结果而且不会停下来，最后严重拖慢速度和滥用手机性能

**Comment by gentlyxu** [comment]
我们还是多聚焦在去广告和保护隐私上

**Comment by PussAzuki** [comment]
emmmm 这个域名显著的降低了性能也不行吗...

**Comment by gentlyxu** [comment]
且不说导致性能下降的原因是啥，请思考一下用这种方式来解决性能问题是不是正确的方向？

然后，显然anti-AD的发展方向不是万金油，什么都插一脚，最终会变成什么模样？`致力于成为中文区命中率最高的广告过滤列表，实现精确的广告屏蔽和隐私保护`这样的愿景还有可能达到或接近吗？

**Comment by PussAzuki** [comment]
只要能抓包都能发现这个域名是该app在播放前反复询问此域名下的一个脚本并302跳转到一些奇怪的域名上进行奇怪的反查且上述提到的第二个就是其反查的cname名字。

什么叫都插一脚？你是否有去花费几分钟的时间验证下我说的到底是不是对的？我是仅在体验中体验到了严重的问题才来反馈的好吧，我可没吃饱了没事做，瞎提交域名。

什么叫隐私保护？ 真要隐私保护我还要把额外一个上传log的域名名字也贴上来是吗？log内容我解不来所以我把其他与音乐播放无关的域名贴这了怎么就影响风气了？

更上面的说是能检查dns，然而使用了局域网内套的dns后，这个检查就离谱的很了，没有啥实际意义了

**Comment by PussAzuki** [comment]
不是很懂我都说了为什么会造成性能下降还会来一句且不论造成性能下降定位原因，我真要是暴躁老哥你这早被挂到名人堂了。

**Comment by gentlyxu** [comment]
看到这些回复，我都给你整气笑了。我上一条那么清晰的回复你看不懂啊？那我就再补充一点：app播放导致性能下降，**正确的方向应该是向app开发者反馈，而不是跟去广告项目反馈屏蔽他的域名来解决问题**，这不是解决性能下降问题的正确思路。

我说的“什么都插一脚”，根据小学语文知识，结合上下文，大概指的是anti-AD不希望什么都插一脚，导致自己面目全非，忘了自己的愿景。

我没有说过隐私保护会影响风气！

最终结论：anti-AD不会因为这个性能下降原因屏蔽你提供的这些域名

**Comment by PussAzuki** [comment]
1.你觉得养猪场会因为我的意见而去改掉这个“feature”吗？

2.为什么你会认为他们会在这边查dns的请求里不放置追踪参数？

3.你自己有抓包看过屏蔽前后对正常功能有影响吗？
