### ISSUE TITLE
[误杀]ddos-guard.net

### ISSUE THREAD

**Issue by exLuLu** [privacy-protection-tools/anti-AD#422]
域名：ddos-guard.net
发生时间：2021年5月9日
使用的列表： （具体的文件，例如/anti-ad-easylist.txt, /dist/anti-ad-surge-full.txt等等）
https://anti-ad.net/easylist.txt
问题描述：
AdGuard Home 只添加【https://anti-ad.net/easylist.txt】拦截列表，打开使用了ddos-guard.net这个服务的网站过不了，一直转圈圈（如图）

![123](https://user-images.githubusercontent.com/35789196/117575017-8c853580-b112-11eb-8f5f-09db090c0084.PNG)

**Comment by gentlyxu** [comment]
https://github.com/privacy-protection-tools/anti-AD/issues/388#issuecomment-819555637

这条规则来自`https://easylist.to/easylist/easyprivacy.txt` ，理论上有收集隐私的问题，请补充说明影响

**Comment by exLuLu** [comment]
> [#388 (comment)](https://github.com/privacy-protection-tools/anti-AD/issues/388#issuecomment-819555637)
> 
> 这条规则来自`https://easylist.to/easylist/easyprivacy.txt` ，理论上有收集隐私的问题，请补充说明影响

打开这个网站 https://fitgirl-repacks.site/ 就会先出现如图的页面，如没有添加ddos-guard.net白名单，则一直在这个页面无限刷新，进入不了目标网站（ https://fitgirl-repacks.site/）

**Comment by gentlyxu** [comment]
我建议你手动添加一下，官方暂时不放行这个域名
