### ISSUE TITLE
[新增拦截] 同盾科技 同盾指纹

### ISSUE THREAD

**Issue by c2xusnpq6** [privacy-protection-tools/anti-AD#424]
域名: tongdun.com.cn tongdun.net yourip.cn tongdun.cn fraudmetrix.cn tongdun.me
出现场景：android app
补充说明：
tracker?

**Comment by c2xusnpq6** [comment]
浙ICP备12036190号
同盾科技有限公司

**Comment by CalmLong** [comment]
得有一些使用场景吧

**Comment by gentlyxu** [comment]
这些域名有什么证据或者url表明他们有广告或者收集隐私么？

**Comment by c2xusnpq6** [comment]
分析某个app找到的 但忘了 那么先放着吧
