### ISSUE TITLE
[新增拦截] "Growing" tracker 

### ISSUE THREAD

**Issue by c2xusnpq6** [privacy-protection-tools/anti-AD#425]
域名: growingio.com  gio.ren  datayi.cn growingio.cn giocdn.com growin.cn
出现场景：
补充说明：
![image](https://user-images.githubusercontent.com/75058881/117937740-e8310800-b338-11eb-9065-0ba7763505c9.png)
![image](https://user-images.githubusercontent.com/75058881/117937837-fbdc6e80-b338-11eb-83a5-fbbf8c8ef1c1.png)
![image](https://user-images.githubusercontent.com/75058881/117938364-891fc300-b339-11eb-907b-a714e858b4ca.png)

**Comment by gentlyxu** [comment]
这个待验证，得空继续跟进

**Comment by c2xusnpq6** [comment]
給您參考 

https://github.com/easylist/easylist/commit/185622149331e16d6bb3f88ba890304d7e12b507

https://github.com/easylist/easylist/commit/728aa1422feca07b06304356eee6959ecf33b491

**Comment by gentlyxu** [comment]
经检查早已收录
