### ISSUE TITLE
[误杀] Microsoft域名相关很多都被拦截

### ISSUE THREAD

**Issue by WhiteCoffee9834** [privacy-protection-tools/anti-AD#426]
域名：
+ settings-win.data.microsoft.com
+ vortex.data.microsoft.com
+ self.events.data.microsoft.com
发生时间：21年5月14日
使用的列表：https://anti-ad.net/easylist.txt
问题描述：已经使用这个规则一周的时间,我发现这三个被拦截的次数累计加起来已经达到将近8K次.很多微软官方的服务都会有影响,望作者能修复或者解释拦截这个的原因.

**Comment by gentlyxu** [comment]
感谢反馈。微软一批的域名屏蔽规则主要来自于[WindowsSpyBlocker](https://crazymax.dev/WindowsSpyBlocker/)，规则相对是比较权威全面的。当然，前面也遇到过微软服务受影响的情况，我们经过了很长的一个讨论，见 #330 
回答你后面的问题：`我发现这三个被拦截的次数累计加起来已经达到将近8K次` 这个通常是域名被屏蔽了不断重试导致的，不能作为应该放行的依据。`很多微软官方的服务都会有影响`这句过于笼统，不方便我或者路过的朋友进行验证，希望可以有更详细的描述

**Comment by WhiteCoffee9834** [comment]
> 很多微软官方的服务都会有影响

指的是,我在试图加入windows预览体验计划时无法连接到服务器,经过测试,发现是被规则拦截.  
虽说影响没有很大吧,但我感觉这毕竟是把正常的服务给屏蔽了,多少还是会影响体验的.

**Comment by WhiteCoffee9834** [comment]
今天找了个时间排查了一下.
阻挠我加入windows预览计划的规则是
## insideruser.microsoft.com
这一条.

经过两周的使用,我目前把微软的被拦截的最狠的几个服务都放进了白名单中.
目前看来没什么影响

**Comment by wesley800** [comment]
@gentlyxu https://github.com/privacy-protection-tools/anti-AD/commit/a8ff8c07b1a3861999ab6b1c5c7ac9f04ff27451 的修改导致把 #288 里的域名放出来了，是否需要修复一下？
