### ISSUE TITLE
[误杀] eset防毒軟體

### ISSUE THREAD

**Issue by c2xusnpq6** [privacy-protection-tools/anti-AD#427]
域名: 
使用的列表： 
问题描述：這是來自歐盟成員國的知名防毒軟體eset的手機版

這是故意的嗎? 這是追蹤器嗎? 謝謝

![IMG_20210515_214632.jpg](https://user-images.githubusercontent.com/75058881/118363549-7f12f400-b5c7-11eb-8586-984caea6c5c3.jpg)

**Comment by gentlyxu** [comment]
这个看起来是软件匹配有问题，anti-AD规则屏蔽的域名是`play.es`，那个软件把`play.eset.com`给干掉了。

请将anti-AD的规则仅用于DNS屏蔽，匹配整个URL应该不行

**Comment by gentlyxu** [comment]
新开了一个专门的adguard规则： https://anti-ad.net/adguard.txt  ，你可以试试～

@c2xusnpq6
