### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by kyo64** [privacy-protection-tools/anti-AD#430]
域名：moapyr.fandom.com
发生时间：2021年5月20日
使用的列表： anti-ad-easylist.txt
问题描述：
拦截了css导致页面完全错乱
https://i.imgur.com/vIgftnr.png

**Comment by gentlyxu** [comment]
adguard的话，请试试专门规则:

https://anti-ad.net/adguard.txt

easylist.txt是针对adguardhome优化过的
