### ISSUE TITLE
[新增拦截] Telegram山寨官网, 存在恶意行为

### ISSUE THREAD

**Issue by GizmoOAO** [privacy-protection-tools/anti-AD#431]
域名: telegram-vip.com telegramcn.org telegrcn.org telegramsvip.com telegram-cn.org
出现场景：搜索引擎搜索后这些网站排名普遍都比较靠前
补充说明：
山寨的Telegram官网, 上面下载的修改过的Telegram存在恶意行为.
[小心虚假Telegram携带远控木马，个人隐私被窥探！](https://www.ijinshan.com/info/202011101133.shtml)

**Comment by WhiteCoffee9834** [comment]
telegramcn可还行.
偷国永远走在山寨的最前沿,又赢了,五个域名,赢五遍.
