### ISSUE TITLE
[误杀]activity.windows.com

### ISSUE THREAD

**Issue by chelly233** [privacy-protection-tools/anti-AD#432]
域名：activity.windows.com
发生时间：2021年5月22日
使用的列表： adblock-for-dnsmasq.conf
问题描述：误杀Microsoft Edge的同步服务
![image](https://user-images.githubusercontent.com/30742960/119212037-9468b080-bae8-11eb-9f5b-0d4cf6cca7d5.png)

**Comment by gentlyxu** [comment]
`activity.windows.com` 这个域名实际上是上传windows的历史记录，属于明确的隐私泄漏。

不过在`anti-ad-easylist.txt`列表中，单独为edge同步开了白名单，dnsmasq并不支持白名单，暂无法针对性加白

**Comment by WhiteCoffee9834** [comment]
开发者幸苦了，最近一直有在关注这个项目的issue，发现有关微软的事情真的很多。
感谢你们。
