### ISSUE TITLE
Is this still an open-source project in strict sense?

### ISSUE THREAD

**Issue by sr093906** [privacy-protection-tools/anti-AD#435]
First, thanks for the long-time contribution to the project. Let's go straight to the point though. 

You encoded plain php files used to generate the final results and removed the [all address of source file](https://github.com/privacy-protection-tools/anti-AD/compare/privacy-protection-tools:f7cc332...privacy-protection-tools:ae7cde4#diff-bc7312940f85e4fa33623ae64828368e2347108c2ef232bd14a069286ff0955a) yesterday in 

https://github.com/privacy-protection-tools/anti-AD/compare/privacy-protection-tools:f7cc332...privacy-protection-tools:ae7cde4

Tip: Fanboy is missing in the 'Special Thanks to' section.

Today, you go further and just wiped the whole script dir, which contains entries of customized whitelist and blacklist (black_domain_list.php and white_domain_list.php)

https://github.com/privacy-protection-tools/anti-AD/compare/privacy-protection-tools:9afb999...privacy-protection-tools:13a157e

The commits have no impacts to end users who just want to subscribe to the files and use. But with such moves, I cannot stop raising an unpopular question: Is this still an open-source project ? 

This is what you said in README.md:

> 项目一直坚持每一行代码开源！anti-AD 过滤列表的所有规则均来自上游列表和网友提交的 issues，欢迎各界朋友审阅。

Now, the sentence becomes somewhat irony...

I have no interest in the php files and not even a user. I avoid using consolidated hosts because to be frank, the value of hosts aggregation project mostly lies in the users' contributions, i.e. the missing block rules and false positives in the sources they use. 

Sadly, it seems none of them report these entries back to the upstream sources they benefit from. Despite that, most of such project still at least keep the custom black/white entries they adopt as open-source projects in a sense.

Several examples are:

Energized Protection's whitelist
https://github.com/EnergizedProtection/unblock

notracking's whitelists and dead domains (Reminder: It benefits your project.)
https://github.com/notracking/hosts-blocklists-scripts

AdGuardDNS's exclusion list
https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/Filters/exclusions.txt

GoodbyeAds' core entries
https://github.com/jerryn70/GoodbyeAds/blob/master/Core/GoodbyeAds-Database.txt

CombinedPrivacy's supplementary hosts and whitelists
https://github.com/bongochong/CombinedPrivacyBlockLists/blob/master/NoFormatting/AdditionalSupplementaryHosts.txt
https://github.com/bongochong/CombinedPrivacyBlockLists/blob/master/NoFormatting/WhitelistedDomains.txt

Blockconvert's whitelist
https://github.com/mkb2091/blockconvert/blob/master/output/whitelist_domains.txt

Blahdns's blacklist and whitelist
https://github.com/ookangzheng/blahdns/blob/master/hosts/blacklist.txt
https://github.com/ookangzheng/blahdns/blob/master/hosts/whitelist.txt

and more ...

So, could you explain it a bit?

**Comment by gentlyxu** [comment]
Absolutely still.

Before the irony, learn what git branch is?

**Comment by gentlyxu** [comment]
> Tip: Fanboy is missing in the 'Special Thanks to' section.

got it. i'll add it

**Comment by sr093906** [comment]
@gentlyxu 

My apology. I didn't notice there is an ad-list maker branch here. :(

**Comment by gentlyxu** [comment]
it doesn't matter. thank you for your attention and supervision. 🤝
