### ISSUE TITLE
[误杀]edge-enterprise.activity.windows.com

### ISSUE THREAD

**Issue by tonyk520** [privacy-protection-tools/anti-AD#437]
域名：https://edge-enterprise.activity.windows.com
https://edge.activity.windows.com
发生时间：2021年05月31日
使用的列表：anti-ad-easylist.txt
问题描述：列表会拦截Edge浏览器同步网址，使得Edge浏览器无法同步

**Comment by gentlyxu** [comment]
https://github.com/privacy-protection-tools/anti-AD/blob/25bfdd541bbf62c581d08b5da262c7697d5dbc28/anti-ad-easylist.txt#L39-L40

这两条都早已放在了白名单中，你是如何被拦截的？使用的工具不支持白名单`@@`吗？
