### ISSUE TITLE
[新增拦截] 流氓app廣告

### ISSUE THREAD

**Issue by c2xusnpq6** [privacy-protection-tools/anti-AD#438]
你看看有什麼可以拿來用~

![Screenshot_20210601-065305_Trebuchet~2.png](https://user-images.githubusercontent.com/75058881/120247562-7fd5a680-c2a6-11eb-8337-8c08e3207afc.png)

**Comment by gentlyxu** [comment]
参考意义有限。图中的大多都已经被拦截了
