### ISSUE TITLE
[误杀]s.click.tmall.com

### ISSUE THREAD

**Issue by EuropeanWithSSR** [privacy-protection-tools/anti-AD#445]
域名：s.click.tmall.com
发生时间：2021年06月16日
使用的列表： anti-ad-easylist.txt
问题描述：adguard home 使用该规则，打开淘口令后能正常打开领券页面，但是无法点击进入商品页面。在 easylist 里没找到 s.click.tmall.com 这一条，但的确被拦截了，不知道触发的是哪条。
被拦截的链接举例：
https://s.click.tmall.com/g?et=xm3F5gh1F0MdFTLpYyQYarGIoKIl5zsF&tar=https%3A%2F%2Fdetail.m.tmall.com%2Fitem.htm%3Fid%3D621225910885%26ali_trackid%3D2%3Amm_803470146_1193650416_109893750297%3A1623773337_134_1439920037%26union_lens%3DlensId%3AOPT%401623773318%402108854a_07df_17a106e8e5a_9343%40022spusfSBVxR3jCNnHUs1Rk%3Brecoveryid%3AX%2FwCxwdWbe8DAPJYaf0BS2BD_1623772579328_501091779_21783927%3Bprepvid%3A201_11.170.86.128_1667976_1623773334872%26spm%3Da2e3n.13006421.0.0%26pvid%3Dnull%26scm%3Dnull%26e%3D3vM4ag6cOdRfRHk7Z7SOODjVyht4XtN3AyPcvAARusjKEoRA6vYIJHmicciG9WdMrDcKgEEvRa-eAyET6uaVma8Knxd2Ixr4D1AnWI_MR-Kk5p0rGwjhAQMWLZS8IIOB5rs5ww7qESw_0uUmhS7Rzicofsuytu4aXhLxzJOGEAJyIZAzamnlUu6kJXQIThZ5JfzwM_Yu7clIyO1H4CkeYpZ1vM5s24-6UD-4jMAahepIyO1H4CkeYrNT66rKRBjRAnFOXpwDk-eV7pN9Kqj1HzgNH1BeJ8w7DsiKeFmL4_Q4VK-vmIV9JF8ph7QOEB9cjCMTKw-EunHSmCe5s8N8ZLOOzylU0lJe199_Jos6fPEDRb1Etzp3Lw%26type%3D2%26tk_cps_param%3D803470146%26tkFlag%3D0%26tk_cps_ut%3D2%26bxsign%3DtbkTbhM2VectbQXo1UgAShyMythmUW0%2FC4HJFAADeh0%2BBahfYTUXp%2FUQvlvmun3U%2FGqYmnVPwb%2FpgzNOQ4zFLVlGUqI1odz2rJ79zRAS3TGy4w%3D&mb=e%3D3vM4ag6cOdRfRHk7Z7SOODjVyht4XtN3AyPcvAARusjKEoRA6vYIJHmicciG9WdMrDcKgEEvRa-eAyET6uaVma8Knxd2Ixr4D1AnWI_MR-Kk5p0rGwjhAQMWLZS8IIOB5rs5ww7qESw_0uUmhS7Rzicofsuytu4aXhLxzJOGEAJyIZAzamnlUu6kJXQIThZ5JfzwM_Yu7clIyO1H4CkeYpZ1vM5s24-6UD-4jMAahepIyO1H4CkeYrNT66rKRBjRAnFOXpwDk-eV7pN9Kqj1HzgNH1BeJ8w7DsiKeFmL4_Q4VK-vmIV9JF8ph7QOEB9cjCMTKw-EunHSmCe5s8N8ZLOOzylU0lJe199_Jos6fPEDRb1Etzp3Lw%26iv%3D0%26et%3D1623773337%26tk_cps_param%3D803470146%26tkFlag%3D0%26tk_cps_ut%3D2

**Comment by gentlyxu** [comment]
在easylist的开头部分有这样一段话
```
!!!note! If you are using "AdGuard", please load https://anti-ad.net/adguard.txt
!!!This list only applies to "AdGuard Home".
```

adguard需加载专用规则 `https://anti-ad.net/adguard.txt`

**Comment by gentlyxu** [comment]
请补充说清楚你用的是Adguard还是AdGuard Home

**Comment by EuropeanWithSSR** [comment]
> 请补充说清楚你用的是Adguard还是AdGuard Home

不好意思，是 AdGuard Home，没有说清楚。

**Comment by gentlyxu** [comment]
ok,修复了

**Comment by EuropeanWithSSR** [comment]
> ok,修复了

感谢！
