### ISSUE TITLE
[误杀] 屏蔽所有带有track的域名有点激进了吧？

### ISSUE THREAD

**Issue by t0ny-peng** [privacy-protection-tools/anti-AD#446]
域名：ppp.net
发生时间：2021年6月18日
使用的列表： （具体的文件，例如/anti-ad-easylist.txt, /dist/anti-ad-surge-full.txt等等）
问题描述：

`track.aliexpress.com`被以下规则屏蔽了
```
/^(\S+\.)?track(ing)?\./
```

似乎是有点激进了吧？比如上述URL只是一个物流追踪站点。谢谢

**Comment by terrytw** [comment]
https://github.com/privacy-protection-tools/anti-AD/issues/301

我的建议是你fork一个，自己加一个commit，然后用https://github.com/wei/pull自动同步

**Comment by jiayouba233** [comment]
这样配置的话，请问Trakcer服务器(Bt的)会被屏蔽吗？

**Comment by terrytw** [comment]
正则我不太看得懂，此规则好像只会屏蔽track.*以及tracking.*吧，不必配tracker.*

**Comment by gentlyxu** [comment]
不会屏蔽`tracker.*`的域名， 正如我在 #301 里回复的，拦住`track.*`和 `tracking.*`是更多的，使用正则的额外好处是没有收录的广告跟踪域名也会被屏蔽，当然缺点就是会误杀，如果能最大程度的避免误杀，就会是一个好规则了

**Comment by gentlyxu** [comment]
各位如果觉得此项规则误杀影响很大，欢迎提交所有涉及物流跟踪或其他被误杀的域名，我一并加白

**Comment by left4taco** [comment]
@gentlyxu thx 我的话只有一个域名 `track.aliexpress.com`，太少就不提PR了。等收集一些别人的反馈请一起更新吧，谢谢。

**Comment by gentlyxu** [comment]
在https://github.com/privacy-protection-tools/anti-AD/commit/1b525626925c77fe738fef4fa5d95f3091f132c9 中，我已经加白了`track.aliexpress.com`

过去7天一直没有新的反馈，故关闭此issue
