### ISSUE TITLE
[误杀] 抖音直播间购物小黄车，商品列表无法正常显示。

### ISSUE THREAD

**Issue by gee1k** [privacy-protection-tools/anti-AD#448]
域名：lianmengapi-hl.snssdk.com
发生时间 2021年06月20日
使用的列表： /anti-ad-easylist.txt
问题描述：抖音直播间购物小黄车，商品列表无法请求不到数据。经 AdGuard Home 后台 排查发现是 lianmengapi-hl.snssdk.com 域名被拦截，拦截后商品列表就无法正常出现，实测放行 lianmengapi-hl.snssdk.com 域名即可。

![image](https://user-images.githubusercontent.com/12059800/122650331-df67f900-d164-11eb-93e6-50dba798c250.png)

![IMG_3490](https://user-images.githubusercontent.com/12059800/122650345-ed1d7e80-d164-11eb-80df-803c32796438.PNG)

**Comment by gentlyxu** [comment]
无法复现
