### ISSUE TITLE
開設telegram群組

### ISSUE THREAD

**Issue by c2xusnpq6** [privacy-protection-tools/anti-AD#449]
這個廣告黑名單repo也有開 您可以參考一下

https://github.com/banbendalao/ADgk

> 反馈交流群
QQ群①:875865300
QQ群②:723295076
TG群:https://t.me/ADgk_list

**Comment by gentlyxu** [comment]
啊，QQ群都快经营不下去了，tg就完全没有必要。有要反馈的来issues区即可
