### ISSUE TITLE
[误杀]优酷不能播放

### ISSUE THREAD

**Issue by RodmanWang** [privacy-protection-tools/anti-AD#45]
域名：youku.com 
发生时间：2020年02月24日
使用的列表： https://gitee.com/privacy-protection-tools/anti-ad/raw/master/easylist.txt
问题描述：优酷可以打开不能播放，显示禁用COOKIE，如果关闭使用上述列表马上就可以播放了。
![QQ截图20200224005757](https://user-images.githubusercontent.com/19368219/75116216-f72e8a80-56a0-11ea-9aef-834d4f5ce83f.png)

**Comment by gentlyxu** [comment]
你好，请更新规则看看问题是否已解决

**Comment by RodmanWang** [comment]
确实好了，感谢。
