### ISSUE TITLE
小米电视广告近日开始无法拦截

### ISSUE THREAD

**Issue by protectedMan** [privacy-protection-tools/anti-AD#450]
不知道具体是什么情况，是小米升级了广告策略了嘛？有没有懂的？

**Comment by terrytw** [comment]
我教你：把你家所有其他联网的设备全部断网或者关机。
然后打开你的广告电视，在你用的去广告设备上（adguard home或者openwrt）看dns记录
如果是openwrt的话，你可以在dhcp和dns设置里打开日志，然后用winscp登录上路由器看那个日志的内容
具体怎么做可以搜索
把可能是广告的域名记下来
然后发到这里

这样才有可能有人帮你解决问题

**Comment by protectedMan** [comment]
> 我教你：把你家所有其他联网的设备全部断网或者关机。
> 
> 然后打开你的广告电视，在你用的去广告设备上（adguard home或者openwrt）看dns记录
> 
> 如果是openwrt的话，你可以在dhcp和dns设置里打开日志，然后用winscp登录上路由器看那个日志的内容
> 
> 具体怎么做可以搜索
> 
> 把可能是广告的域名记下来
> 
> 然后发到这里
> 
> 
> 
> 这样才有可能有人帮你解决问题

我只是在问问有没有跟我一样情况的用户

**Comment by terrytw** [comment]
https://github.com/privacy-protection-tools/anti-AD/issues/146

> # **以下几类issue可能会被直接关闭**
> 以“为什么屏蔽XXX”，“凭什么屏蔽X....”，“怎么连XXX都屏蔽了”等质问语气提交的issue，并且不说明目的的。这里解释一下：anti-AD的所有屏蔽规则均来自上游和网友提交，这些在代码和closed issues中均有记录；
> **不说明具体被误杀的域名，也不提供具体APP名称，只有类似于“我的xx视频看不了”，“XX app打开又有广告了” 这类简单描述**；
> anti-AD的过滤列表从原理上就做不到的，例如基于ip地址的广告投放，网页中的元素广告，视频中的某些嵌入广告，已经拍摄进视频内的广告等；
> 工具配置相关的，通过搜索引擎就能解决的；
> 意图左右anti-AD屏蔽公平性而影响大多数人的，例如“我不喜欢xxx，建议屏蔽了它”，“我觉得xx视频里有点广告很好，建议加白”，等等

**Comment by gentlyxu** [comment]
讨论问题的话，请加QQ群 716981535 ，当然也不保证100%解决问题
