### ISSUE TITLE
[误杀] activity.windows.com

### ISSUE THREAD

**Issue by leonwahy** [privacy-protection-tools/anti-AD#452]
域名：activity.windows.com
发生时间：2021年06月27日
使用的列表：https://anti-ad.net/anti-ad-for-smartdns.conf
问题描述：
建议取消此域名拦截，这个拦截导致无法实现微软及edge同步服务。谢谢！！

**Comment by terrytw** [comment]
提issue之前好歹搜一下有没有重复的嘛
https://github.com/privacy-protection-tools/anti-AD/issues/349

**Comment by gentlyxu** [comment]
参考 #349 。edge的同步服务加白以下两个域名
```
@@||edge-enterprise.activity.windows.com^
@@||edge.activity.windows.com^
```

smartDNS是否支持白名单，本人未细究

**Comment by leonwahy** [comment]
有浏览之前的问题，但目前smartdns规则没有更新，所以希望能完善，谢谢！ 
smartdns支持的白名单规则应该是： 
address /pass.ad.com/- 
与屏蔽规则稍微不同 
address /ad.com/# 
因为定期都会自动更新您提供的规则文件，如果能帮忙完善，非常感谢，这样就不用每次更新后自己再修改。 感谢！

**Comment by gentlyxu** [comment]
> 有浏览之前的问题，但目前smartdns规则没有更新，所以希望能完善，谢谢！
> smartdns支持的白名单规则应该是：
> address /pass.ad.com/-
> 与屏蔽规则稍微不同
> address /ad.com/#
> 因为定期都会自动更新您提供的规则文件，如果能帮忙完善，非常感谢，这样就不用每次更新后自己再修改。 感谢！

感谢！我们本身有输出白名单列表，`https://github.com/privacy-protection-tools/dead-horse/blob/master/anti-ad-white-list.txt`，你看看提交个smartdns格式白名单的PR到此处，做好测试，我完善php脚本，以后就自动生成smartDNS的白名单

**Comment by leonwahy** [comment]
**谢谢！我试了一下无法提交PR，请原谅我的蠢。
以下是我在smartDNS设置说明中找到的相关说明：**

如何屏蔽广告
smartdns具备高性能域名匹配算法，通过域名方式过滤广告非常高效，如要屏蔽广告，只需要配置类似如下记录即可，如，屏蔽*.ad.com，则配置：
address /ad.com/#
域名的后缀模式，过滤*.ad.com，#表示返回SOA，使屏蔽广告更加高效，如果要单独屏蔽IPV4， 或IPV6， 在#后面增加数字，如#4表示对IPV4生效。若想忽略特定子域名的屏蔽，可配置如下，如忽略pass.ad.com，可配置如下：
address /pass.ad.com/-

**Comment by gentlyxu** [comment]
https://github.com/privacy-protection-tools/dead-horse/blob/master/anti-ad-white-for-smartdns.txt

@leonwahy

**Comment by leonwahy** [comment]
谢谢，一万个赞。:)
