### ISSUE TITLE
[误杀] 露天拍賣網頁顯示不完整

### ISSUE THREAD

**Issue by timlu85** [privacy-protection-tools/anti-AD#453]
域名：ahd.ruten.com.tw
发生时间：110年06月28日
使用的列表：anti-ad.net/easylist.txt
问题描述：該網域阻擋之後網頁內容顯示不完全
將域名加入白名單後會正常 (@@||ahd.ruten.com.tw^$important)
![image](https://user-images.githubusercontent.com/11910660/123552880-e9b07580-d7aa-11eb-8953-4d3b1618ab78.png)

**Comment by gentlyxu** [comment]
你的说法似乎不对。
```
_xhref='https://ahd.ruten.com.tw/delivery/ck.php?oaparams=2__bannerid=203497__zoneid=49__source=home__cb=cc05bf5eae__maxdest=https%3A%2F%2Fwww.ruten.com.tw%2Ffind%2F%3Farea%3D0%26isauth%3D1%26q%3D%25E7%25A7%25BB%25E5%258B%2595%25E5%25BC%258F%25E5%2586%25B7%25E6%25B0%25A3'
```
`ahd.ruten.com.tw`域名都是用在这样的自定义属性中，目的应该是用来跟踪点击，统计用户浏览行为的。屏蔽此域名，并不会影响图片加载或页面结构，请再次确认

**Comment by timlu85** [comment]
thx for reply 
剛剛有再測試了一下 在未有任何插件的瀏覽器下開啟 [露天拍賣首頁](https://www.ruten.com.tw/)
AdGuard Home 只有阻擋這四項，進行各別解除封鎖測試，只有將ahd.ruten.com.tw解除封鎖才會有正常的首頁內容
![image](https://user-images.githubusercontent.com/11910660/123674145-db7a5c00-d873-11eb-9def-0501e8a1f4a1.png)
正常樣式
![image](https://user-images.githubusercontent.com/11910660/123674856-ac181f00-d874-11eb-9c14-a6b278a7d7e3.png)

**Comment by gentlyxu** [comment]
已删除域名`ahd.ruten.com.tw`
