### ISSUE TITLE
求助：合并smartDNS屏蔽清单及白名单

### ISSUE THREAD

**Issue by leonwahy** [privacy-protection-tools/anti-AD#455]
您好！非常感谢您解决了smartDNS的白名单问题，
https://github.com/privacy-protection-tools/dead-horse/blob/master/anti-ad-white-for-smartdns.txt
经这两天试用，目前smartDNS设置对IP白名单有单独配制文件，而域名白名单与屏蔽名单属于一个配置项；
目前不便于域名白名单自动更新，暂是将白名单拷贝到路由器，然后定期更新屏蔽文件后，将白名单列表合并到屏蔽文件内。

建议将smartDNS白名单自动追加/添加到 anti-ad-smartdns.conf 文件里面更便于更新及屏蔽。致谢！

**Comment by gentlyxu** [comment]
smartDNS支持引入多个配置文件的吧？
为什么要合并？
