### ISSUE TITLE
[误杀] can not download M$ edge installer

### ISSUE THREAD

**Issue by What-Zit-Tooya** [privacy-protection-tools/anti-AD#456]
域名：msedge.sf.dl.delivery.mp.microsoft.com
发生时间：2021/07/02
使用的列表： https://anti-ad.net/easylist.txt
问题描述：Can not download `M$ Edge` from site `https://www.microsoft.com/en-us/edge/business/download` 
Blocked by wildcard rule: `/^(\S+\.)?ad(s?[\d]+|m|s)?\./`

**Comment by gentlyxu** [comment]
which one is you using??  "AdGuard" or "AdGuard Home" ?

**Comment by What-Zit-Tooya** [comment]
> 
> 
> which one is you using?? "AdGuard" or "AdGuard Home" ?

AdGuard Home.

**Comment by gentlyxu** [comment]
OK. it's fixed
