### ISSUE TITLE
[误杀]导致虎牙直播性能出现问题

### ISSUE THREAD

**Issue by Smiliny** [privacy-protection-tools/anti-AD#457]
域名：huya.com
发生时间：2021.6开始使用本规则就开始出现，一直至今天
使用的列表： https://anti-ad.net/easylist.txt
问题描述：win10使用ublock origin插件，360极速浏览器
具体问题是虎牙所有直播加载慢，处在正在加载页面5秒左右才加载出来直播视频流。
去掉本规则，只使用halflife规则则恢复正常，直播视频瞬间加载

还有一个问题是只用halflife规则时，虎牙直播ublock显示拦截数量11，且稳定不再变化。而同时用上easylist时，一开始总拦截数40左右，后来随着时间推移，拦截数不断上升，达到一两百条以至更多

直播加载慢的问题一开始我还以为是网络或路由的问题，弄了很久很久，结果今天，茅塞顿开

**Comment by Smiliny** [comment]
对了，也测试了只用easylist的效果，同样会导致虎牙直播加载慢。所以确定了原因

**Comment by gentlyxu** [comment]
🤦‍♂️，特地在`https://anti-ad.net/easylist.txt`加了一段说明(加了很久了)
```
!!!note! If you are using "AdGuard", please load https://anti-ad.net/adguard.txt
!!!This list only applies to "AdGuard Home".
```

你这么用，anti-AD无法保证效果或误杀

**Comment by Smiliny** [comment]
...确实是从这篇介绍adguard的文章里面，得知的anti-AD：https://sspai.com/post/63088
看来只适合dns 路由层里面用，浏览器插件没法用anti-AD了对吧

**Comment by Smiliny** [comment]
...确实是从这篇介绍adguard的文章里面，得知的anti-AD：https://sspai.com/post/63088
看来只适合dns 路由层里面用，浏览器插件没法用anti-AD了对吧

**Comment by gentlyxu** [comment]
是的。同时也没有必要在浏览器插件中加载anti-AD
