### ISSUE TITLE
变更给gitee源dnsmasq配置文件的文件名

### ISSUE THREAD

**Issue by Leisuredpootle** [privacy-protection-tools/anti-AD#46]
请问可以尝试变更gitee端文件名和GitHub源一致吗？这样可以便于本地dnsmasq直接下载使用

**Comment by gentlyxu** [comment]
没弄懂你的意思，为啥文件名会影响到你本地使用？
如果是curl,可以使用`curl -o `保存成你要的文件名
如果是wget，可以使用 `wget -O` 保存成你要的文件名

和我在源端使用什么文件名有啥关联？

**Comment by Leisuredpootle** [comment]
啊 不是 本人会使用curl和wget 意思就是源端更改的话可以免去-o，仅仅是个小小的建议。

**Comment by gentlyxu** [comment]
感谢建议。
哈，我说下背景故事，因为最早的时候anti-ad只支持dnsmasq，现在支持的服务更多了，就规范了一下命名，原来的名字为了兼容老用户，也就不动了。gitee用了新的命名规范。

**Comment by Leisuredpootle** [comment]
原来如此，谢谢您的付出
