### ISSUE TITLE
[新增拦截] sunlogin.oray.com

### ISSUE THREAD

**Issue by xenstar** [privacy-protection-tools/anti-AD#464]
域名：
tk.oray.com
pgy.oray.com
pgy-api.oray.com
sl-tk.oray.com
sl-log.oray.net
7moor-fs1.com
7moor.com

出现场景：
补充说明：
没有任何跟踪域阻止 sunlogin。 他们有很多链接，跟踪。 请管理员查看，并将域添加到反广告列表中。

**Comment by gentlyxu** [comment]
已收录。感谢提交

**Comment by xenstar** [comment]
pubsub02.oray.net

也包括这个
