### ISSUE TITLE
[误杀]饿了么核心服务域名误杀

### ISSUE THREAD

**Issue by Nesxc** [privacy-protection-tools/anti-AD#466]
域名：alsc-buy2.ele.me   |    nt2.ele.me
发生时间：2021年7月16日
使用的列表： https://anti-ad.net/easylist.txt
问题描述：这两个域名被屏蔽后饿了么无法使用。图片无法加载，购物车无法加载下单等。

**Comment by gentlyxu** [comment]
没有发现这两个域名被拦截。请提供AdGuard Home 拦截这些域名的对应日志。并确认规则是来自anti-AD
