### ISSUE TITLE
[误杀] 拦截了ubisoft account的跳转

### ISSUE THREAD

**Issue by EndDream** [privacy-protection-tools/anti-AD#467]
域名：2mcmg31d.r.us-east-1.awstrack.me
发生时间：2021年7月17日
使用的列表：/anti-ad-easylist.txt
问题描述：今天重置育碧的帐号时，点击育碧邮件里的重置链接发现触发了anti-ad里面的||awstrack.me^规则，放行该域名后得以继续

**Comment by gentlyxu** [comment]
这个是 营销邮件中的效果追踪链接，不推荐放行。针对邮件追踪通常有两种方法应对：

1. 有提供正常URL，但其超链接加了追踪跳转。这种只需要把url复制到浏览器打开即可；
2. 提供的URL直接是追踪链接的，可以使用网络上提供的网址还原服务。但不适用你这种重置密码等的涉及信息安全的情况，可临时放行域名来解决问题
