### ISSUE TITLE
[误杀] 被反屏蔽前端识别

### ISSUE THREAD

**Issue by JunTsao** [privacy-protection-tools/anti-AD#468]
域名：www.zhenbuka2.com
发生时间：2021年7月8日
使用的列表： anti-ad-easylist.txt
问题描述：

首先非常感谢作者辛勤维护规则。
从6月份开始，此视频网站加入了前端反广告屏蔽，
此网站一个广告域名2785.dlads.cn匹配到了anti-AD,导致被识别出使用广告屏蔽软件。

第一次提交此类issue，不太清楚提交规则，还请作者海涵

**Comment by gentlyxu** [comment]
这个除了你自行放行广告域名。anti-AD无法解决这个问题
