### ISSUE TITLE
[误杀] (Possible) False Positives 

### ISSUE THREAD

**Issue by sr093906** [privacy-protection-tools/anti-AD#470]
Following domains are (possible) FPs found by comparing https://github.com/privacy-protection-tools/anti-AD/blob/master/anti-ad-domains.txt and oisd's whitelist using GNU comm. You can see details by clicking links on https://oisd.nl/excludes.php

2cnt.net
2mdn.net
2o7.net
4dsply.com
888poker.com
a-mo.net
a.baidu.com
a2.xinhuanet.com
aan.amazon.com
aax-us-iad.amazon.com
activity.windows.com
actonservice.com
ad.atdmt.com
ad.doubleclick.net
adash.man.aliyuncs.com
adashx.m.taobao.com
adcell.com
adcolo.com
addthis.com
adfoc.us
adform.net
adjust.com
adjust.io
adlandpro.com
adm3.autoimg.cn
admitad.com
adnxs.com
adocean.pl
adregain.com
ads.google.com
ads.twitter.com
adsafeprotected.com
adsafety.net
adservice.google.co.jp
adservice.google.com
adservice.google.com.hk
adservicemedia.dk
adsp.xunlei.com
adswizz.com
adtech.de
adtraction.com
adups.com
advcash.com
advertising.com
affex.org
affiliatefuture.com
agkn.com
ai.yimg.jp
aimatch.com
airbrake.io
alb.reddit.com
alimama.com
alitems.com
amazon-adsystem.com
amdc.m.taobao.com
amplitude.com
an.yandex.ru
analytics.edgekey.net
analytics.twitter.com
android.bugly.qq.com
anrdoezrs.net
anura.io
apester.com
api-secure.solvemedia.com
api.branch.io
api.groupon.com
api.traq.li
apmebf.com
aporasal.net
app.chat.xiaomi.net
appbrain.com
appcast.io
appmetrica.yandex.com
appsflyer.com
arms-retcode.aliyuncs.com
as.baidu.com
asadcdn.com
asimov-win.settings.data.microsoft.com.akadns.net
at-o.net
atconnect.npo.nl
atdmt.com
audid-api.taobao.com
autolinkmaker.itunes.apple.com
autopilothq.com
avantlink.com
awaps.yandex.ru
awemwh.com
awin1.com
azabu-u.ac.jp
b.hatena.ne.jp
b.koodomobile.com
b.scorecardresearch.com
bam-x.com
baremetrics.com
batch.com
bc.marfeelcache.com
bc0a.com
beacon.errorception.com
betrad.com
bfast.com
bigdata.ssp.samsung.com
blogcatalog.com
blogtopsites.com
blueconic.net
bluecore.com
bluetoad.com
bm23.com
bn5x.net
bongacams.com
bp01.net
branch.io
bridgetrack.com
brightedge.com
bronto.com
browser.pipe.aria.microsoft.com
bs.serving-sys.com
bs.yandex.ru
bsv.atm.youku.com
budurl.com
bufferapp.com
bugly.qq.com
bugsnag.com
burnside.dtcn.com
bxczchdxynw.com
byside.com
c.live.com
c.msn.com
c.paypal.com
c.yes.youku.com
cbox.ws
cbs.wondershare.com
cc-dt.com
cdn-net.com
cdn.branch.io
cdn.flurry.com
cdn.krxd.net
cdn.mxpnl.com
cdn.onesignal.com
cdn.segment.com
cdn.segment.io
cdn.yimg.com
cedexis.com
ceuswatcab01.blob.core.windows.net
ceuswatcab02.blob.core.windows.net
ch0p.darty.com
channeladvisor.com
chartbeat.com
check.ddos-guard.net
choice.microsoft.com
choices.truste.com
cint.com
cintnetworks.com
clearbit.com
cleverpush.com
click-url.com
click.aliexpress.com
click.redditmail.com
click.simba.taobao.com
clickcease.com
clickdimensions.com
clickmeter.com
clicktale.net
clicktime.symantec.com
clientservices.googleapis.com
clk.boulanger.com
cloudflareinsights.com
cloudfront-labs.amazonaws.com
cmp.nextday.media
cmstool.youku.com
cohesionapps.com
comet.yahoo.com
commander1.com
commission-junction.com
conduit-services.com
confirmit.com
connect.zebra.com
consensu.org
consent.faz.net
consent.truste.com
consentmanager.mgr.consensu.org
contentexchange.me
cookie.vrt.be
cookiebot.com
cookielaw.org
cookies.nos.nl
corp.sts.microsoft.com
corpext.msitadfs.glbdns2.microsoft.com
cpt.itv.com
cptrack.de
cquotient.com
crashlytics.com
crl.microsoft.com
crowdtwist.com
cs1.wpc.v0cdn.net
cse3.chausport.com
ct.pinterest.com
cts.businesswire.com
curalate.com
custom.plausible.io
customer.io
cws.conviva.com
cxense.com
d.agkn.com
d.toutiao.com
d10lpsik1i8c69.cloudfront.net
d1z2jf7jlzjs58.cloudfront.net
d1zgderxoe1a.cloudfront.net
d2na2p72vtqyok.cloudfront.net
d2r1yp2w7bby2u.cloudfront.net
d2wy8f7a9ursnm.cloudfront.net
d31qbv1cthcecs.cloudfront.net
d35u1vg1q28b3w.cloudfront.net
d3tglifpd8whs6.cloudfront.net
d3tsytm1wtjqo2.cloudfront.net
d5nxst8fruw4z.cloudfront.net
da.netease.com
data.mistat.intl.xiaomi.com
data.mistat.xiaomi.com
data.ubi.com
datacaciques.com
datadoghq-browser-agent.com
db5.vortex.data.microsoft.com.akadns.net
dcms.1688.com
dcs.audi.com
deals.macupdate.com
demdex.net
developermedia.com
diagnostics.support.microsoft.com
digidip.net
digitaladvisor.dk
directtrack.com
districtm.ca
dnn506yrbagrg.cloudfront.net
dnsseed.bitcoin.dashjr.org
dnsseed.bluematt.me
do-not-tracker.org
dolphincdn.xyz
dotomi.com
doubleclick.net
down.360safe.com
downmobile.kugou.com
dp.im.weibo.cn
dpbolvw.net
dpm.demdex.net
ds-aksb-a.akamaihd.net
dw-online.ksosoft.com
dw.cbsi.com
dw.com.com
dynamicyield.com
e.kc-education.com
ea.galerieslafayette.com
eaus2watcab01.blob.core.windows.net
eaus2watcab02.blob.core.windows.net
edgecast-vod.yahoo.net
edigitalsurvey.com
edrone.me
ekg.riotgames.com
eloqua.com
emjcd.com
ensighten.com
entitlements.jwplayer.com
epl.paypal-communication.com
epsilon.com
err.taobao.com
error.fc2.com
et.nytimes.com
etracker.de
eulerian.brandalley.fr
eultech.fnac.com
events.apester.com
events.gfe.nvidia.com
events.jotform.com
events.launchdarkly.com
events.mapbox.com
events.split.io
everesttech.net
eviltracker.net
evyy.net
exactag.com
exacttarget.com
exchange4media.com
exosrv.com
experience.jcu.edu.au
extole.io
extreme-ip-lookup.com
ezoic.net
f-log-at.grammarly.io
faktor.io
fc.vodafone.de
fccinteractive.com
feature.fm
feedblitz.com
fili.cc
firebaselogging-pa.googleapis.com
flipp.com
flx1.com
forter.com
fourier.taobao.com
freegeoip.net
ftpcontent.worldnow.com
ftr2.external.xerox.com
fwmrm.net
game.weibo.com
gc.zgo.at
gekko.spiceworks.com
gemius.pl
geo.nbcsports.com
geo.ngtv.io
geo.vortex.data.microsoft.com.akadns.net
geo2.adobe.com
geoip-db.com
geoip.hmageo.com
georiot.com
getblueshift.com
glancecdn.net
gleam.io
gm.mmstat.com
go.pardot.com
go.theregister.com
go2cloud.org
go2jump.org
goatcounter.com
google-analytics.com
googleadservices.com
googletagmanager.com
googletagservices.com
gopjn.com
gravityrd-services.com
gtrk.s3.amazonaws.com
hawk.pcgamer.com
hitmarkerjobs.com
host-tracker.com
hostip.info
hotelscombined.com.au
hotkeys.com
howsmyssl.com
huangye.miui.com
hugedomains.com
humanpresence.app
hypestat.com
idealmedia.io
ieonlinews.microsoft.com
iesnare.com
images.sohu.com
imasdk.googleapis.com
img2.user.kanimg.com
impactradius.com
imrworldwide.com
in.appcenter.ms
indexww.com
inetinteractive.com
info.seek.com
informer.yandex.ru
informz.net
infos.anz.com
infos.telstra.com.au
inmoment.com
inside-graph.com
insideruser.trafficmanager.net
insight.rapid7.com
insightexpress.com
insightexpressai.com
insitez.blob.core.windows.net
intelliad.de
intellimize.co
intergi.com
investingchannel.com
invoca.net
involve.asia
ip-adress.com
ip-api.com
ipapi.co
ipinfodb.com
ipstack.com
ironbeast.io
isgprivacy.cbsi.com
ist-track.com
iubenda.com
izooto.com
jdoqocy.com
jimdo.com
jivox.com
journity.com
js-agent.newrelic.com
justanswer.com
k.cocooncenter.com
kampyle.com
kaxsdc.com
kisshentai.net
komoona.com
kqzyfj.com
krxd.net
l.betrad.com
leadpages.net
leanplum.com
linkev.com
linksynergy.com
litix.io
livejasmin.com
liveupdate.mac.sandai.net
loginfra.com
logs.amap.com
m2.nsimg.net
m365log.com
mackeeper.com
mailerlite.com
mairdumont.com
marfeel.com
marinsm.com
mark.isbank.com.tr
maropost.com
mc.yandex.ru
md-nx.com
mds.yandex.net
media01.eu
mediafuse.com
mediagra.com
mediametrics.ru
mediaplex.com
mediav.com
medrx.telstra.com.au
meebo.com
messengerpeople.com
met2.hp.com
metok.sys.miui.com
micpn.com
mindtake.com
mistat.xiaomi.com
mixi.media
mkt51.net
mmtro.com
mobile.pipe.aria.microsoft.com
mobilityware.com
moengage.com
moneroocean.stream
monitis.com
monitor.azure.com
movable-ink-397.com
mparticle.com
mplxtms.com
mr.da.netease.com
mrzikj.com
msedge.net
mx.technolutions.net
mxpnl.com
mybloglog.com
myvisualiq.net
nabbr.com
nanigans.com
nanovisor.io
naytev.com
neobux.com
netcore.co.in
netupdater.info
networkedblogs.com
newrelic.com
news.smi2.ru
newsletter.bdnews24.com
newsletters.nationalgeographic.com
nexus.ensighten.com
nexus.officeapps.live.com
nexusrules.officeapps.live.com
nr-data.net
nsm.dell.com
nsstatic.com
nsstatic.net
ntv.io
ntvcld-a.akamaihd.net
nui.media
o2o.api.xiaomi.com
odc.weather.com
oimagea2.ydstatic.com
ojrq.net
om.symantec.com
oms.expedia.com
omtrdc.net
onecollector.cloudapp.aria.akadns.net
onelink.me
onenetworkdirect.net
onesignal.com
onetrust.com
online-metrix.net
opinionstage.com
ops.bpost.be
optanon.blob.core.windows.net
optimizely.com
otf.msn.com
p.tanx.com
p.typekit.net
p.yotpo.com
pagead46.l.doubleclick.net
parkingcrew.net
parklogic.com
partner-ads.com
partycasino.com
peerius.com
pendo.io
pepper.com
pepperjamnetwork.com
perfdrive.com
perimeterx.net
perr.h-cdn.com
phs.tanx.com
ping.cloud.tencent.com
pings.conviva.com
pjatr.com
pjtra.com
platform.linkedin.com
platform.tumblr.com
plausible.eurostocks.nl
plusone.google.com
pm0.net
pntra.com
pntrac.com
pntrs.com
postclickmarketing.com
ppcprotect.com
ppro.de
ppurifier.game.xiaomi.com
prism.app-us1.com
privacy-center.org
privacy-policy.truste.com
productsup.com
promos.fling.com
publicidees.com
pulsar.ebay.com
push.api.bbci.co.uk
pushauction.com
pushengage.com
pusherapp.com
pushwelcome.com
pv.sohu.com
px.spiceworks.com
pxf.io
qksrv.net
quantcast.mgr.consensu.org
quantummetric.com
questionpro.com
r.bbci.co.uk
r.mail.ru
r42tag.com
radeant.com
ramp.purch.com
rayli.com.cn
rd.rakuten.co.jp
rdstation.com.br
realsrv.com
recruitics.com
redirect-ads.com
refer.ccbill.com
referrer.disqus.com
refersion.com
relevant-digital.com
res-x.com
researchintel.com
resolver.gslb.mi-idc.com
responsys.net
rezync.com
rlcdn.com
rollbar.com
rutrk.org
s7.addthis.com
sail-horizon.com
salesmanago.pl
sanalytics.disneyplus.com
sb.scorecardresearch.com
sc-static.net
scanverify.com
sci.intuit.com
scoop.it
scorecardresearch.com
scrippsnetworks.com
seal.digicert.com
seal.godaddy.com
seal.verisign.com
sealserver.trustwave.com
search.twitter.com
secure-us.imrworldwide.com
secure.trust-guard.com
securemetrics.apple.com
sedoparking.com
seed.bitcoin.sipa.be
seed.bitcoinstats.com
segment.com
segment.io
sematext.com
sendpulse.com
sendsay.ru
sensic.net
services.zam.com
serving-sys.com
sessionstack.com
settingsfd-geo.trafficmanager.net
shareaholic.com
shareasale.com
sharethis.com
shopperapproved.com
sickrage.ca
sift.com
siftscience.com
simplyhired.com
siteplug.com
sitetracker.com
skimresources.com
smartasset.com
smartclip.net
smartredirect.de
smi2.ru
smljmp.com
snap.com
society6.com
socket.streamable.com
sourcepoint.mgr.consensu.org
sp-mms.weather.com
springmetrics.com
srvtrck.com
sstats.adobe.com
stat.download.xunlei.com
stat24.com
statcounter.com
static.adsafeprotected.com
static.chartbeat.com
static.mediav.com
static.parsely.com
staticxx.facebook.com
stats.adobe.com
stats.pusher.com
streamplay.to
swa.bol.com
sy.ameblo.jp
syndication.exosrv.com
syndication.twitter.com
szlong.weixin.qq.com
t.indeed.com
t.paydirekt.de
t.paypal.com
tacticalrepublic.com
tag.aticdn.net
tag.shopping-feed.com
tagcommander.com
tagger.opecloud.com
tags.news.com.au
tamedia.ch
tamgrt.com
taplytics.com
tawk.to
tce.alicdn.com
techlab-cdn.com
telecommand.telemetry.microsoft.com
telemetry.microsoft.com
tiqcdn.com
tkqlhce.com
tm.tradetracker.net
tmearn.com
todhamilton.pro
torimochi.line-apps.com
touclick.com
tr.info.mango-mobilites.fr
tracemyip.org
track.adform.net
track.effiliation.com
track.omgpl.com
track.webgains.com
trackcmp.net
trackersimulator.org
tracking.lengow.com
tracking.s24.com
tradedoubler.com
tradetracker.net
trafficguard.ai
trafficjunky.net
trafic.ro
traq.li
trk.email.dynect.net
trk.pinterest.com
trust.zone
trustarc.com
trustarc.mgr.consensu.org
uarating.com
ucweb.com
uim.tifbs.net
umwatsonc.events.data.microsoft.com
uniregistry.com
up.cm.ksmobile.com
update.360safe.com
upgrade.xl9.xunlei.com
urbanairship.com
usabilla.com
useinsider.com
usercentrics.eu
v.fwmrm.net
v10-win.vortex.data.microsoft.com.akadns.net
v2html.atm.youku.com
vcrypt.net
vd.l.qq.com
vectorstock.com
velaro.com
verify.authorize.net
vi-serve.com
videoplayerhub.com
videoplaza.tv
vidtech.cbsinteractive.com
viglink.com
vilynx.com
visualwebsiteoptimizer.com
vizury.com
voodoo.com
vortex-win.data.microsoft.com
vortex.data.glbdns2.microsoft.com
vortex.data.microsoft.com
vortex.hulu.com
vz-cdn.trafficjunky.net
w88.espn.com
watson.telemetry.microsoft.com
way2traffic.com
webgains.com
webmasterplan.com
websecurity.norton.com
weheartit.com
weus2watcab01.blob.core.windows.net
weus2watcab02.blob.core.windows.net
whoami.akamai.net
widget.trustpilot.com
widgets.getpocket.com
widgets.trustedshops.com
wifi.com
win10.ipv6.microsoft.com
win1710.ipv6.microsoft.com
win8.ipv6.microsoft.com
wmflabs.org
woocall.sina.com.cn
woodpecker.uc.cn
wootric.com
worldssl.net
wt-eu02.net
wumii.com
www-google-analytics.l.google.com
xg4ken.com
xlmc.sandai.net
ynuf.aliapp.org
youvisit.com
zanox.com
zdbb.net
ziffdavis.com
ztd.dds.microsoft.com

**Comment by People-11** [comment]
Agree, I mainly use ipapi.co to check my network status. I think ipapi.co has no relatively to ADS.

**Comment by prologic** [comment]
Came here to report that `plausible.io` is also a false positive. This is an open source analytics software (_alternative to Google analytics_). Can we get this removed from the list? 🙏

> Rule(s)
> ||plausible.io^
> CHN: anti-AD
