### ISSUE TITLE
[误杀] gleam 被误杀

### ISSUE THREAD

**Issue by muchqs** [privacy-protection-tools/anti-AD#472]
您好，
域名：gleam.io    gleamjs.io
发生时间：2021-07-29
使用的列表： 使用在 AdGuard Home 上的 https://anti-ad.net/easylist.txt
问题描述：gleam 是参加抽奖，网络活动等等的网站，广泛运用。比如 Intel 网站上申请游戏测试号（beta key) 等等活动表都需要 gleam。之前一直没有问题啊。可刚刚发现被拦截了。不知何时开始的。

**Comment by gentlyxu** [comment]
`gleam.io`已加入白名单。另拦截规则里只看到`widget.gleamjs.io`，请确认是否该域名误杀

**Comment by muchqs** [comment]
是的，也是误杀。 widget.gleamjs.io 如果不加白，表格也全显示不了。
谢谢。
