### ISSUE TITLE
Please support shadowrocket rules

### ISSUE THREAD

**Issue by Alphabet1226** [privacy-protection-tools/anti-AD#474]
As you already support surge and clash, why not support one more shadowrocket?

**Comment by gentlyxu** [comment]
already supported long ago.
u must try moreee...

**Comment by Alphabet1226** [comment]
Sorry I only see these, I don't know which of these rules are universal with shadowrocket, I tried to import the rules of surge, but shadowrocket gives me an error
![image](https://user-images.githubusercontent.com/51783873/128962115-549482b6-9839-47dc-b621-4e54ad024ce0.png)

**Comment by gentlyxu** [comment]
JUST FOR [REFERENCE](https://github.com/privacy-protection-tools/anti-ad.github.io/blob/master/docs/r.conf)

Because the configuration of shdowrocket is personalized.

anti-AD doesn't provide full configuration.

that's all
