### ISSUE TITLE
[误杀]OneDrive 部分功能不可用

### ISSUE THREAD

**Issue by cyy911** [privacy-protection-tools/anti-AD#477]
域名：skyapi.live.net
发生时间：2021年08月17日
使用的列表：anti-ad-easylist.txt
问题描述：||*-cor0*.api.p001.1drv.com^，这条规则导致 skyapi.live.net CANME解析被屏蔽，OneDrive 部分功能不可用，例如我测试出来安卓版无法下载。

**Comment by gentlyxu** [comment]
我缺少设备。你可以把问题描述的更详细一些吗？
比如你说的 `||-cor0.api.p001.1drv.com^` 这条anti-AD并无这条规则。**希望能提供AdGuard Home原始的拦截日志**，CNAME在每个地区的解析不完全相同，我也无法重现你描述的问题

**Comment by cyy911** [comment]
抱歉，因为这个是 11 天之前的issues，我刚刚测试无法复现，如果下次出现了我会直接提供日志。感谢回复。

**Comment by gentlyxu** [comment]
ok
