### ISSUE TITLE
[误杀] Minecraft 官方启动器

### ISSUE THREAD

**Issue by TheAceBlock** [privacy-protection-tools/anti-AD#478]
域名：`launchercontent.mojang.com`
发生时间：2021年08月18日
使用的列表：`anti-ad-easylist.txt`
问题描述：
使用 OpenWRT 上的 AdGuardHome 进行广告拦截，订阅 anti-AD 后 Minecraft 官方启动器无法使用。经查为 `||msedge.net^` 这条规则导致 `launchercontent.mojang.com` 被误杀。
AdGuardHome 原始日志：
```
Response details
Status: Blocked by CNAME or IP
DNS server: [some DNS server]:53
Elapsed: 473 ms
Response code: NOERROR
Rule(s): ||msedge.net^ (CHN: anti-AD)

Response
A: 0.0.0.0 (ttl=10)
Original response
CNAME: launchercontent.azureedge.net. (ttl=210)
CNAME: launchercontent.afd.azureedge.net. (ttl=1710)
CNAME: global-geo-afdthirdparty-unicast.trafficmanager.net. (ttl=60)
CNAME: osa30r3a.msedge.net. (ttl=60)
A: 104.212.68.19 (ttl=3600) 
```

**Comment by TheAceBlock** [comment]
刚才翻了一下之前的 issue，发现这个规则很可能是从 [WindowsSpyBlocker](https://github.com/crazy-max/WindowsSpyBlocker) 处理出来的。
我又去翻了一下 WindowsSpyBlocker 具体的规则，发现[这个规则](https://github.com/crazy-max/WindowsSpyBlocker/blob/3b283182db21e96075ebea7d80f8898bd314a1a2/data/proxifier/spy/domains.txt#L303)原本仅屏蔽了 `msedge.net` 这个根域名，而不像其中[某些规则](https://github.com/crazy-max/WindowsSpyBlocker/blob/3b283182db21e96075ebea7d80f8898bd314a1a2/data/proxifier/spy/domains.txt#L1)同时屏蔽了子域名。
再回来看看本项目中对应的规则，好像都没有考虑这个问题，而是直接将包含对应内容的域名通杀。
对于该列表中的绝大部分域名而言，因为基本上都是很长的子域名，所以没出现太多的误报。但是也有这一个看起来很像微软 CDN 的域名就被拦截了。**并且 AdGuradHome 会对 CNAME 的所有返回内容进行检查，有一个符合规则即被拦截**，但原项目只检查直接访问的域名是否符合规则，所以不存在此问题。
希望能修复这个问题。

**Comment by gentlyxu** [comment]
已修复
