### ISSUE TITLE
[误杀]Koolshare 网站登陆无法实现，应该是某些js被屏蔽了

### ISSUE THREAD

**Issue by yingqiangyu** [privacy-protection-tools/anti-AD#480]
域名：https://koolshare.cn/portal.php
发生时间：2021年08月21日
使用的列表： anti-ad-easylist.txt, adguard.txt
问题描述：koolshare论坛无法登陆，验证popup无法弹出.

**Comment by gentlyxu** [comment]
是同盾的验证码服务，遭到CNAME拦截，我先删除规则`||fraudmetrix.cn^`
