### ISSUE TITLE
[误杀] dfcfw.com 东方财富网

### ISSUE THREAD

**Issue by zoi50a6j** [privacy-protection-tools/anti-AD#482]
域名：dfcfw.com
发生时间：2021年8月23日
使用的列表： AdGuard Home 上的 https://anti-ad.net/easylist.txt
问题描述：dfcfw.com 应该是东方财富网分发静态文件的域名，屏蔽后影响网页使用。例子： [股吧](https://guba.eastmoney.com/)

首次添加在 8月20日 https://github.com/privacy-protection-tools/anti-AD/blob/aaeb2b865188e20528c7139c31e0233c3ff7c105/anti-ad-easylist.txt#L11890

**Comment by gentlyxu** [comment]
OK.已修复
