### ISSUE TITLE
easylist格式的`domains.txt`

### ISSUE THREAD

**Issue by c2xusnpq6** [privacy-protection-tools/anti-AD#483]
現在的這個easylist格式有一點太積極了... 
你可以弄一個easylist格式的`domains.txt`嗎? 😁

**Comment by gentlyxu** [comment]
如果是adguard home，他是有支持domains.txt这个格式的。

再重复弄一个格式完全没有必要

**Comment by c2xusnpq6** [comment]
因為我想把他放在adguard的網址過濾器那裏 而不是域名過濾器 因為現在已經有想到辦法繞過了... 例如阿里巴巴這個是用了自己的doh查詢被阻擋的域名的ip..

所以放在網址過濾器那裏會比較適合? 而且我不想用現在那個easylist格式的anti-ad 誤殺有點多... 我不想那麼麻煩...😅

![Screenshot](https://user-images.githubusercontent.com/75058881/132094987-3016b6fc-f54e-4401-979a-2187a647c959.png)

**Comment by c2xusnpq6** [comment]
![Screenshot_20210908-004130_Trebuchet~2.png](https://user-images.githubusercontent.com/75058881/132381262-74ba601e-b81c-4e88-8d69-884f45dfb31c.png)
