### ISSUE TITLE
[新增拦截] 动漫之家侵入性广告

### ISSUE THREAD

**Issue by PussAzuki** [privacy-protection-tools/anti-AD#487]
域名: yoke.jyhlo0.com sp.chemacid.cn wof.hnltcw.com
出现场景：tachiyomi安卓app，使用动漫之家插件，然后在任意漫画里点击webview进入网页版动漫之家查看时会出现浏览器版本过旧的广告
补充说明：
动漫之家网页版的其他部分广告域名已被拦截，上述的是漏网之鱼

**Comment by PussAzuki** [comment]
稳定复现的方法：
先确保访问的是移动端网页，然后打开任意漫画，此时有概率就会跳转到广告
根据chrome的F12下的network查看拦截结果发现是网页自带的垃圾脚本...
[搜索结果](https://i.loli.net/2021/09/11/eoiEWA67pjPbcwL.png)

访问的网址分别是 xopf.lhy1.xyz 和 abc.kfyg.xyz
上面的域名貌似是后续跳转的域名

**Comment by gentlyxu** [comment]
已全部加入
