### ISSUE TITLE
[误杀]腾讯网迷你版打不开

### ISSUE THREAD

**Issue by mjyhj** [privacy-protection-tools/anti-AD#49]
域名：qq
发生时间：2020年3月3日
使用的列表：大雕的SSR PLUS里 https://gitee.com/privacy-protection-tools/anti-ad/raw/master/easylist.txt
问题描述：打开WIN的QQ，点击腾讯网迷你版 会打不开
![ Image Text] https://s2.ax1x.com/2020/03/03/3fJwWR.png

**Comment by gentlyxu** [comment]
是否有拦截日志可以提供？光从描述无法判断是哪个域名或者哪些域名被误杀了

**Comment by mjyhj** [comment]
> 是否有拦截日志可以提供？光从描述无法判断是哪个域名或者哪些域名被误杀了

没有拦截日志，我也不知道哪个域名，就是QQ客户端上的，看不到域名
原来是这样的
![1](https://user-images.githubusercontent.com/22577418/75749401-b0095f00-5d5c-11ea-8889-8362465fa76e.png)

**Comment by mjyhj** [comment]
百度了一下，是这个应该是mini.qq.com
但是今天看了一下规则并没有这个域名在
而且我现在也正常访问了，不知道是不是你这边更新过了

**Comment by gentlyxu** [comment]
实事求是的说，最近一周没有更新qq相关域名的屏蔽规则。

`alimama.com`是在anti-AD中是确有屏蔽掉的，它的预期效果是alimama.com及其所有子域名全部被封杀

你说的3W多条这段。。。，我竟然没有看懂啥意思

**Comment by mjyhj** [comment]
我意思是这个规则有3W多条，导入到SSR PLUS里，全部变成了host屏蔽，所以会出现误杀情况比较严重。alimama，taobao，qq 好多都上不了

**Comment by gentlyxu** [comment]
> 我意思是这个规则有3W多条，导入到SSR PLUS里，全部变成了host屏蔽，所以会出现误杀情况比较严重。alimama，taobao，qq 好多都上不了

我还不了解ssr plus的屏蔽方式，不过真如你所说的方式的话，不太可能出现误杀。我们的过滤列表已经存在5年时间，期间不断自我修正，理论上不会出现大面积误杀的情况。

我个人推荐你试试adguardhome，加载anti-ad过滤列表来检查过滤效果

**Comment by mjyhj** [comment]
就是单纯的把规则内的所有域名，改成host屏蔽
![1](https://user-images.githubusercontent.com/22577418/75785489-c506e200-5d9e-11ea-9a1a-282fadd65387.png)

**Comment by moxuanyuan** [comment]
> 我意思是这个规则有3W多条，导入到SSR PLUS里，全部变成了host屏蔽，所以会出现误杀情况比较严重。alimama，taobao，qq 好多都上不了

用了anti-AD后alimama就打不开，看规则里果然有，然后上来看看issues，就看这里。误杀太严重了
