### ISSUE TITLE
[误杀]minexmr.com

### ISSUE THREAD

**Issue by SODAGARY** [privacy-protection-tools/anti-AD#490]
域名：minexmr.com   和  supportxmr.com
发生时间：2021年9月5日
使用的列表： https://anti-ad.net/anti-ad-for-dnsmasq.conf
问题描述：
在ssrp+里开的广告屏蔽用的这个列表，然而目前发现这两个站被杀了

**Comment by armin19900** [comment]
在DNSFilter使用，alimama.com被误杀了。打不开了
