### ISSUE TITLE
[误杀] macOS系统更新&天气小组件无法正常工作

### ISSUE THREAD

**Issue by ron159** [privacy-protection-tools/anti-AD#492]
域名：目前未知
发生时间：2021年9月1日
使用的列表：adblock-for-dnsmasq.conf
问题描述：
macOS的系统更新显示 **无法更新，请确定你已经连接到互联网**，天气小组件则显示空白。
关闭广告拦截后上述两个功能正常工作。
目前尚不清楚是何拦截了哪个域名导致的问题，后续发现后会进行补充。

**Comment by gentlyxu** [comment]
天气？ 你是说小组件里的 “天气”吗？

**Comment by ron159** [comment]
> 天气？ 你是说小组件里的 “天气”吗？

你好，是的，不好意思，没有描述清楚，已更改。

**Comment by gentlyxu** [comment]
晚点我看看能不能找到日志。

**Comment by ron159** [comment]
> 晚点我看看能不能找到日志。

麻烦了，我这边有更多信息也会尽快补充

**Comment by gentlyxu** [comment]
经过很长时间的测试观察，“天气小组件”无法工作的问题都没有出现，那么关闭此issue

**Comment by ron159** [comment]
确认了一下是因为dns造成的，和本项目无关，如有任何困扰，还请见谅~
