### ISSUE TITLE
[新增拦截]pglstatp-toutiao.com

### ISSUE THREAD

**Issue by Karmylr** [privacy-protection-tools/anti-AD#494]
域名:http://v6-be-pack.pglstatp-toutiao.com/988e4957a146272604639173059abe0f/614fbba7/video/tos/cn/tos-cn-v-0000c002/80da5c8e157b4248b12e671360a2afbc/toutiao.mp4
出现场景：网速管家app
补充说明：||pglstatp-toutiao.com^

**Comment by Karmylr** [comment]
不好意思 还抓到了http://v3-be-pack.pglstatp-toutiao.com/4c9051189bf2adc25f33343151d64643/614fb8b3/video/tos/cn/tos-cn-v-0000/684209d204ea420a859a5b195990654a/toutiao.mp4

**Comment by Karmylr** [comment]
!网速管家(adguard规则)
|http://*.pglstatp-toutiao.com/*/*/video/tos/cn/tos-cn-*-*/*/toutiao.mp4$media,redirect=noopmp4-1s
|http://adsmind.ugdtimg.com/ads_svp_video__*.f40.mp4?*$media,redirect=noopmp4-1s

**Comment by Karmylr** [comment]
what's up
以为真的更新这么频繁
结果是auto renew

**Comment by gentlyxu** [comment]
所以呢？😄
