### ISSUE TITLE
question:网页的过滤规则转换为host规则的转换方法

### ISSUE THREAD

**Issue by rufengsuixing** [privacy-protection-tools/anti-AD#5]
不懂php代码
希望能举例说明一下转换的方法，我想评判一下是否会有规则误伤

**Comment by rufengsuixing** [comment]
'/^\|\|([0-9a-z\-\.]+[a-z]+)\^(\$([^=]+?,)?(image|third-party|script)(,[^=]+)?)?$/'
找到了emmm

**Comment by rufengsuixing** [comment]
我不知道是不是贪婪匹配，如果是的话
[0-9a-z\-\.]+[a-z]+ 可能匹配到的是 www.baidu.co 和m 同样可以匹配不带.的规则

**Comment by rufengsuixing** [comment]
(\$([^=]+?,)?这部分没有看懂  为什么最后有个问号

**Comment by rufengsuixing** [comment]
@@||ad.kazakinfo.com^
有一些白名单可以考虑为adguard加入么

**Comment by rufengsuixing** [comment]
||koyi.pub/wp-content/plugins/dh-anti-adblocker/
误匹配？

**Comment by gentlyxu** [comment]
> @@||ad.kazakinfo.com^
> 有一些白名单可以考虑为adguard加入么

当前列表是精确匹配的黑名单，因此不需要额外声明白名单，需要白名单的域名直接不加入即可。
但，在本项目引入easylist的模糊匹配之后，白名单@@也是必须一并引入的，你知道为什么的。模糊匹配模式正在开发和自测当中，晚些时候上传

**Comment by gentlyxu** [comment]
> ||koyi.pub/wp-content/plugins/dh-anti-adblocker/
> ||ks.js.cn*/yytf/$object,script
> 误匹配？

这个你再细看看。😅

**Comment by rufengsuixing** [comment]
是我的匹配出了问题，取了多行的，检查了一下没什么问题，可以将你的项目加入我的项目https://github.com/rufengsuixing/luci-app-adguardhome的默认列表么

**Comment by gentlyxu** [comment]
> 是我的匹配出了问题，取了多行的，检查了一下没什么问题，可以将你的项目加入我的项目https://github.com/rufengsuixing/luci-app-adguardhome 的默认列表么

当然可以。也欢迎有任何建议或意见随时给我提issues
