### ISSUE TITLE
[新增拦截] 手机游戏中的广告与追踪域名

### ISSUE THREAD

**Issue by Mosney** [privacy-protection-tools/anti-AD#50]
最近从历史记录发现几个手机游戏中的看起来应该是广告相关的域名
config.unityads.unitychina.cn
ads-sdk-cn.upltv.com

**Comment by gentlyxu** [comment]
收到。晚些时候确认

**Comment by gentlyxu** [comment]
已确认，更新进黑名单了。 同时添加了几条近期监测到的新域名，欢迎继续关注
