### ISSUE TITLE
[误杀] Possible Problematic Domains Block Rules

### ISSUE THREAD

**Issue by sr093906** [privacy-protection-tools/anti-AD#503]
Following domains are found in https://anti-ad.net/domains.txt. Some of the domains are controversial on Chinese mainland but I think blocking them may be too aggressive. For others, I am totally baffled why they are added to blocklist at first...

118114.cn
rayli.com.cn
198game.com
iyoowi.com
2345.cn
2345.com
3600.com
37.com
55.la
ads.org.cn
aizhigu.com.cn
aliapp.org
alios.cn
azabu-u.ac.jp
baixing.com
bitbucket.io
clarins.com.cn
e.lianwangtech.com
ename.com.cn
gm99.com
group-ib.ru
hao222.com
internetdefenseleague.org
jav321.com
knet.cn
pepsico.com.cn
qhupdate.com
s11.cn
snap.com
sxhjty.com
nejmqianyan.cn
threatbook.cn
idgdmgroup.com.cn
u88.cn
uc123.com
ucweb.com
vnet.cn
w8.com.cn
watchtimes.com.cn
whhd.gov.cn
wifi.com
xifuquan.com
xj-n-tax.gov.cn
zazhipu.com
ztgame.com

**Comment by gentlyxu** [comment]
same as you. some entries I'm confused about tooooo.. 

You can refer [here](https://github.com/privacy-protection-tools/anti-AD/tree/adlist-maker/scripts/origin-files), These are the upstream of this project

In general, the current list of ad filters for Chinese regions is maintained by personalities

**Comment by gentlyxu** [comment]
```
In general, the current list of ad filters for Chinese regions is maintained by personalities
```
我的意思是说目前都是个人在维护，缺少专业的组织或机构

**Comment by sr093906** [comment]
@gentlyxu So, as the maintainer could you move some of/all these domains to whitelist as the issue is labeled as 'false positive/bug' ?

**Comment by gentlyxu** [comment]
Yes, do my best within my ability.

But these must pay very much time and may be very slow in progress

**Comment by gentlyxu** [comment]
added to whitelist

```php
    'bitbucket.io' => 0, #503
    'ename.com.cn' => 0, #503
    'baixing.com' => 0, #503
    'aizhigu.com.cn' => 0, #503
    'clarins.com.cn' => 0, #503
    'jav321.com' => 0, #503
    'knet.cn' => 0, #503
    'pepsico.com.cn' => 0, #503
    's11.cn' => 0, #503
    'snap.com' => 0, #503
    'nejmqianyan.cn' => 0, #503
    'w8.com.cn' => 0, #503
    'watchtimes.com.cn' => 0, #503
    'whhd.gov.cn' => 0, #503
    'xifuquan.com' => 0, #503
    'xj-n-tax.gov.cn' => 0, #503
    'zazhipu.com' => 0, #503
    'ztgame.com' => 0, #503
```


Some domains have been fixed by the upstream list

**Comment by sr093906** [comment]
Thanks.
