### ISSUE TITLE
[误杀]ads.privacy.qq.com

### ISSUE THREAD

**Issue by MkQtS** [privacy-protection-tools/anti-AD#505]
域名：`ads.privacy.qq.com`
发生时间：2021年10月30日
使用的列表： anti-ad-easylist.txt
问题描述：`https://ads.privacy.qq.com/ads/optout.html`是管理QQ、微信个性化广告的页面，可以关闭关闭一段时间的腾讯个性化广告，anti-ad-easylist中的`/^(\S+\.)?ad(s?[\d]+|m|s)?\./$denyallow=nucdn.net|azureedge.net|alibabacorp.com|alibabadns.com`这一条会拦截`ads.privacy.qq.com`

**Comment by gentlyxu** [comment]
已修复。感谢你清晰的描述，帮助快速的定位问题。
