### ISSUE TITLE
[新增拦截]vali-g1.cp31.ott.cibntv.net

### ISSUE THREAD

**Issue by Karmylr** [privacy-protection-tools/anti-AD#507]
域名:vali-g1.cp31.ott.cibntv.net
出现场景：优酷视频APP
补充说明：
http://vali-g1.cp31.ott.cibntv.net/youku/677426c6e3e4c72080d8368da/03000B01006172A0BA5B5259FBC61AA9B76927-398A-4891-B000-F9CEBC1E63CB.mp4?sid=163594462700010009149_00_Bc4ce282eb13f91eb294d1d857f6a95c9&sign=b04eecf326e059f1a69257d775dcdd8c&ctype=50&si=183&psid=8003983770197ac1bef1fbaae2cbd57343346&ykVideoShowType=2
http://vali-g1.cp31.ott.cibntv.net/youku/657245c0ac14171bbc745414d/03000B0100613200ADC956F07891337DC92CFA-B9D0-4931-8BB6-6B15B9D7EC10.mp4?sid=163594468900010001239_00_B3411f26ed37688ea52c7823d856dd073&sign=31cca4ac6c0f9f0c449b6d2d587f2b5a&ctype=50&si=183&psid=9fe53e1e418b0b269c69a04cc0118ed643346&ykVideoShowType=2

**Comment by Karmylr** [comment]
e

**Comment by gentlyxu** [comment]
此次是批量提交的。close 点早了，抱歉！
