### ISSUE TITLE
应用内置dns拦截[新增拦截]

### ISSUE THREAD

**Issue by mcnk328** [privacy-protection-tools/anti-AD#509]
域名:doh.iqiyi.com,doh.ptqy.gitv.tv
出现场景：两个域名都是查找解析日志中发现的，第一个域名请求出现爱奇艺的ios客户端中，目前已经屏蔽，屏蔽后也能正常使用播放，第二个在盒子上奇异果出现的请求，同样已经屏蔽，但是暂未测试是否有不可用的情况
补充说明：

**Comment by mcnk328** [comment]
第二个域名也已经测试，盒子奇异果屏蔽后也能正常使用

**Comment by gentlyxu** [comment]
对这类域名的屏蔽还是要慎重。
如果有确切证据证明，拦截这几个域名后，能屏蔽广告或拦截隐私收集，那是可以加入过滤列表的；
如果只是屏蔽了，发现并不影响正常使用，那我建议还是再考察一下。

这类域名通常有抗dns劫持，cdn优化等作用
