### ISSUE TITLE
dnsmasq格式建议

### ISSUE THREAD

**Issue by hcym** [privacy-protection-tools/anti-AD#51]
项目链接
https://github.com/notracking/hosts-blocklists
随便举例啊
他的dnsmasq格式
address=/unity3d.com/0.0.0.0
贵项目
address=/data-optout-service.uca.cloud.unity3d.com/0.0.0.0
其实这个直接放hosts比较好吧
只是建议，大佬看看吧，再次感谢

**Comment by gentlyxu** [comment]
感谢你的建议。 anti-AD项目就是为了合并域名减少长度而生的，我一开始就考虑到你提到的这种情况，例如`cnzz.com`，在hosts列表中，是非常长的一堆，弄到dnsmasq列表之后就只有一条。

至于有很多没有封杀根域名，那显然是因为不能这么干啊～。

**Comment by hcym** [comment]
谢谢啦，因为我封的偏激，用你的就要改，用他的不用改，就是太大，绝大部分不会去的网站。😂

**Comment by gentlyxu** [comment]
客气。偏激一些倒是无妨，只是anti-AD已经需要照顾更多的用户，每一个黑名单都需要非常慎重。

顺便问下，你这样的封杀效果主要增强了哪些地方？希望能具体讲讲

**Comment by hcym** [comment]
基本都是国内，别人恐怕不能用，cnzz新浪和微博，全部视频网站，搜狐搜狗uc等等等等，除了百度的网盘，微信和微信视频，基本封光了🤭

**Comment by qpzr** [comment]
想个性化还是抄一份start-ci.sh和输出格式php吧，想加什么规则表就加，想要 什么输出格式就改，最后开个私人项目把那两文件放上去，action调好点★图标就开车回传码云还是github这里的yml，一切云端操作。哈哈哈

**Comment by hcym** [comment]
不是个性化，觉得dns的应该是根域名，子域名还是hosts，多少有效率高低的好处

**Comment by gentlyxu** [comment]
> 基本都是国内，别人恐怕不能用，cnzz新浪和微博，全部视频网站，搜狐搜狗uc等等等等，除了百度的网盘，微信和微信视频，基本封光了🤭

这。。。。。请问你家为什么需要宽带？

**Comment by hcym** [comment]
没影响了，两个频道，一个接iptv公网没有任何广告屏蔽，家里人用，他们喜欢花花绿绿的广告，一个科学网，接了个盒子看YouTube和腾讯视频，就是烦手机电脑不停转圈才下的重手🤭

**Comment by CalmLong** [comment]
https://github.com/CalmLong/domain-parse  @hcym

**Comment by hcym** [comment]
感谢感谢，认码就是方便
