### ISSUE TITLE
s1.wp.com [break wordpress.org]

### ISSUE THREAD

**Issue by 3xploiton3** [privacy-protection-tools/anti-AD#510]
![image](https://user-images.githubusercontent.com/19517680/142001280-abbd5794-504a-402f-9246-c734c0e87aed.png)
![image](https://user-images.githubusercontent.com/19517680/142001302-88e1adfb-f996-408d-b49e-2453214ca6c6.png)

**Comment by gentlyxu** [comment]
fixed
