### ISSUE TITLE
[误杀] Microsoft Edge 浏览器同步服务

### ISSUE THREAD

**Issue by Moxicu** [privacy-protection-tools/anti-AD#511]
域名：https://edge-enterprise.activity.windows.com
           https://edge.activity.windows.com
发生时间：2021年11月23日
使用的列表： anti-ad-surge2.txt
问题描述：上述两个域名为Edge浏览器的同步域名（https://docs.microsoft.com/en-us/deployedge/microsoft-edge-troubleshoot-enterprise-sync ），使用“anti-ad-surge2.txt”规则列表后被拒绝访问，导致Edge浏览器无法开启同步。

**Comment by gentlyxu** [comment]
这倒是个新情况：域名`activity.windows.com`是被屏蔽的，但本项目实际上加白了`edge-enterprise.activity.windows.com`和`edge.activity.windows.com`，白名单地址是https://github.com/privacy-protection-tools/dead-horse/blob/master/anti-ad-white-list.txt

 我想知道surge是如何支持白名单的，有路过的知道的朋友，丢个链接或是说明

**Comment by Moxicu** [comment]
经过研究，将以下内容安装为“.sgmodule模块”可以解决白名单问题：

#!name=anti-AD
#!desc=https://github.com/privacy-protection-tools/anti-AD

[Rule]
DOMAIN-SET,https://raw.githubusercontent.com/privacy-protection-tools/dead-horse/master/anti-ad-white-list.txt,DIRECT
DOMAIN-SET,https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge2.txt,REJECT

**Comment by gentlyxu** [comment]
好的
