### ISSUE TITLE
[误杀] instant.page

### ISSUE THREAD

**Issue by mochaaP** [privacy-protection-tools/anti-AD#514]
域名：instant.page
发生时间：2021年11月28日
使用的列表： anti-ad-easylist.txt

**Comment by gentlyxu** [comment]
这个为啥是误杀？影响是什么？

**Comment by mochaaP** [comment]
instant.page 是一个用于在链接上 hover 一段时长后时自动 prefetch 以增强用户体验的 JavaScript 库，我不觉得这是一个 ad。
