### ISSUE TITLE
[误杀]https://my.jia.360.cn/web/

### ISSUE THREAD

**Issue by xiaoxulol** [privacy-protection-tools/anti-AD#515]
域名：https://my.jia.360.cn/web/
发生时间：2021年11月27日
使用的列表： ShadowSocksR Plus+自带的anti-AD规则
问题描述：开启ShadowSocksR Plus+自带的anti-AD规则后登录框消失

**Comment by gentlyxu** [comment]
额。。。具体用的是哪个规则列表？
<img width="665" alt="圖片" src="https://user-images.githubusercontent.com/1243610/143808428-504ecf06-2632-487c-b5c0-fded04285b66.png">

**Comment by xiaoxulol** [comment]
第一个，dnsmasq



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月29日(周一) 中午12:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [privacy-protection-tools/anti-AD] [误杀]https://my.jia.360.cn/web/ (Issue #515)




 
额。。。具体用的是哪个规则列表？
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
