### ISSUE TITLE
是否可以考虑增加Quantmult X、Shadowrocket 格式

### ISSUE THREAD

**Issue by yt1988** [privacy-protection-tools/anti-AD#518]
如题，现在 Quantmult X、Shadowrocket 使用率很高，用户量不少，除了iOS用户还包括 M1 Mac用户。

建议是不是anti-AD是不是可以考虑支持一下这两款软件的格式，或者是已经有其它可转换的工具来支持使用？

再次谢谢作者的辛勤维护

**Comment by gentlyxu** [comment]
可以自己制作规则，引入类似如下语句
```
RULE-SET,https://anti-ad.net/surge.txt,REJECT
```
