### ISSUE TITLE
[误杀]service.signalr.net

### ISSUE THREAD

**Issue by xlionjuan** [privacy-protection-tools/anti-AD#519]
域名：||service.signalr.net^
发生时间：2021年12月9日
使用的列表：https://anti-ad.net/easylist.txt
问题描述：這條規則會導致微軟的「您的手機」功能無法運作
經查閱log後發現此規則封鎖了下面兩條網域導致此事情的發生
signalr-relayhub-prod-as02-4.service.signalr.net
signalr-pairing-prod-as02-1.service.signalr.net

**Comment by wft44maqb** [comment]
@gentlyxu `signalr-pairing-prod-as02-1.service.signalr.net`

```
@@||signalr-pairing-prod-as02-1.service.signalr.net^
```
