### ISSUE TITLE
[误杀]gofile.io文件分享的网站误杀

### ISSUE THREAD

**Issue by hue715** [privacy-protection-tools/anti-AD#525]
域名：gofile.io
发生时间：2021年12月13日
使用的列表： （anti-ad-easylist.txt）
问题描述：
### **打开gofile.io的文件分享链接，被拦截**
![image](https://user-images.githubusercontent.com/22958922/145816359-a109f823-1675-4665-83d8-492814e21c50.png)
### **gofile.io是个文件分享的网站**
![image](https://user-images.githubusercontent.com/22958922/145816707-528e694a-ceeb-43b5-bb67-81a98fa21e46.png)

**Comment by gentlyxu** [comment]
已修复
