### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by Shsy** [privacy-protection-tools/anti-AD#528]
域名：https://auth.cloud.alipay.com/
发生时间：2021年12月16日
使用的列表：/anti-ad-easylist.txt
问题描述：这是支付宝旗下蚂蚁连的登陆页面，账号密码登陆时，页面不跳转。关闭规则后可以登陆。没有筛查出具体是哪个域名被屏蔽，希望大佬帮忙看看。

**Comment by gentlyxu** [comment]
我没有找到具体是什么域名造成的误杀
