### ISSUE TITLE
[新增拦截]把2345全家都给BAN了吧

### ISSUE THREAD

**Issue by qpzr** [privacy-protection-tools/anti-AD#53]
火绒安全实验室最新消息日前上市公司 2345 旗下多特软件站正在通过所谓的高速下载传播木马程序劫持用户
具体请看https://zhuanlan.zhihu.com/p/111435102
BAN了2345全家  曾经的多特 到它手里彻底凉凉了

**Comment by gentlyxu** [comment]
经核实，确实存在恶意弹窗广告，已将相关域名加黑，感谢反馈
