### ISSUE TITLE
[新增拦截]B站的广告横幅

### ISSUE THREAD

**Issue by ForestL18** [privacy-protection-tools/anti-AD#531]
(作者大大先别关这个issue，我再找找有没有别的广告)
域名:www.bilibili.com
出现场景：
B站首页的广告横幅
bilibili.com##.banner-card
bilibili.com##.video-card-common:has(>.card-pic>a[href*="cm.bilibili.com"][data-target-url])
bilibili.com##a[href*="cm.bilibili.com"][data-target-url]:not([data-target-url*=".bili"])

B站播放页侧边栏广告
bilibili.com###slide_ad + .ad-report

知乎侧边广告
||zhihu.com/commercial_api/banners_

**Comment by gentlyxu** [comment]
这个加不了

**Comment by gentlyxu** [comment]
anti-AD是只针对域名拦截

**Comment by ForestL18** [comment]
只针对域名的话，很多广告是去处不了的，效果会大大折扣
