### ISSUE TITLE
[误杀]淘宝滑动验证 cf.aliyun.com

### ISSUE THREAD

**Issue by Ivy-2501** [privacy-protection-tools/anti-AD#533]
域名：cf.aliyun.com
发生时间：2021年12月21日
使用的列表： 全部
问题描述：在访问 http://tingshen.court.gov.cn 时遇到淘宝滑动验证码无法通过，解除拦截后正常。
![F3C9DF17-E91C-4E8C-B4DE-A6D81F371A9C](https://user-images.githubusercontent.com/43741453/146909586-6bed29ec-7b08-453f-b879-5647756ce382.jpeg)
![23886249-618D-4813-8E23-D44675465A7E](https://user-images.githubusercontent.com/43741453/146909596-3495a15f-db3d-48b5-b44e-5ecca237722d.jpeg)

**Comment by gentlyxu** [comment]
已经被上游修复了？我没有找到`cf.aliyun.com`
