### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by Karmylr** [privacy-protection-tools/anti-AD#538]
域名：p-l.play.aiseet.atianqi.com,news-l.play.aiseet.atianqi.com
发生时间：2021年12月25日
使用的列表： anti-ad-easylist.txt
问题描述：
用adguard home/smartdns/pi hole这些dns过滤器运行anti-ad-easylist.txt是不会遇到问题的。因为云视听极光内置dns，可以绕过dns过滤器的过滤。用clash过滤p-l.play.aiseet.atianqi.com和news-l.play.aiseet.atianqi.com就会发现云视听极光的视频无法播放。

**Comment by Karmylr** [comment]
还有p-l.play.aiseet.atianqi.com。一样的

**Comment by gentlyxu** [comment]
放行这两个域名是否可以播放视频？

**Comment by Karmylr** [comment]
> 放行这两个域名是否可以播放视频？

可以
