### ISSUE TITLE
[误杀]storage.live.com

### ISSUE THREAD

**Issue by onec526** [privacy-protection-tools/anti-AD#539]
域名：storage.live.com
发生时间：有时候登入web OneDrive
使用的列表： anti-ad-easylist.txt-AdGuardHome（DNS过滤）
问题描述：拦截后，会导致web OneDrive 的 "My files"无法正常显示。需要一直刷新，但是还是无济于事。当 "My files"正常显示后，再拦截storage.live.com，开始能正常显示，但隔一天后web OneDrive 的 "My files"又无法正常显示。

**Comment by gentlyxu** [comment]
没有发现这个域名被拦截，请再次确认，并提供拦截日志
