### ISSUE TITLE
[误杀]/^(\S+\.)?(?!xn--)[^\.]{40,}\.[a-z]+(\.cn)?$/

### ISSUE THREAD

**Issue by Moexin** [privacy-protection-tools/anti-AD#54]
域名：https://github.com/privacy-protection-tools/anti-AD
发生时间：2020年3月8日
使用的列表： anti-ad-easylist.txt
问题描述：/^(\S+\.)?(?!xn--)[^\.]{40,}\.[a-z]+(\.cn)?$/
这条规则误杀太严重了，好多网站的css直接都被拦截了，包括anti-AD的官方GitHub都被拦了，我当时人都傻了。
![TIM截图20200308113959.png](https://i.loli.net/2020/03/08/Y6e5wJV4S1lrUId.png)

**Comment by gentlyxu** [comment]
首先，感谢你的积极反馈～
其次，anti-AD项目从一开始就是针对dns层面的广告拦截，你把规则用在了adguard上，这条正则表达式匹配了整个url，导致大面积误杀，属于官方未测试的应用场景。

现在，这条正则表达式已经修复了，请更新
