### ISSUE TITLE
[误杀] OneDrive被误杀

### ISSUE THREAD

**Issue by sjtuross** [privacy-protection-tools/anti-AD#540]
域名：api.onedrive.com, *.files.1drv.com, skyapi.live.net
发生时间：2021年12月25日
使用的列表：https://cdn.jsdelivr.net/gh/privacy-protection-tools/anti-AD@master/anti-ad-easylist.txt
问题描述：OneDrive一直处在同步状态，我在AdGuard Home里面手工加了以下允许规则后，恢复正常。根据AdGuard Home的Query Log来看，感觉是收到了某个IP或CNAME的牵连。

@@||api.onedrive.com^$important
@@||files.1drv.com^$important
@@||skyapi.live.net^$important

![image](https://user-images.githubusercontent.com/940110/147519564-78304477-58e6-4e50-aaad-962f99006948.png)

**Comment by gentlyxu** [comment]
截图是只有关于 `api.onedrive.com`

**Comment by sjtuross** [comment]
其他几个暂时找不到了，但是拦截原因是一样的

**Comment by sjtuross** [comment]
![image](https://user-images.githubusercontent.com/940110/147622526-1cd3976d-a12b-4095-a7dc-54f025a9ef0a.png)

**Comment by sjtuross** [comment]
*.files.1drv.com

这个有的会block有的不会，要看具体连接的是哪个cdn服务器，估计跟解析到的IP有关

**Comment by sjtuross** [comment]
![image](https://user-images.githubusercontent.com/940110/148044569-6a3d55d9-48bd-4b3d-a4d2-1f30aef3c7f5.png)

**Comment by sjtuross** [comment]
@gentlyxu 截图都提供了

**Comment by gentlyxu** [comment]
好的。收到！晚些时候我来修复bug

**Comment by Jefffish09** [comment]
今天实测

*.files.1drv.com

这个还是会被误block，导致onedrive上的file会下载不下来。
