### ISSUE TITLE
能不能独立出个去除盒子电视跟app视频广告的规则

### ISSUE THREAD

**Issue by xgitl** [privacy-protection-tools/anti-AD#541]
添加规则实在是太卡了，希望能精简点，只需要去除盒子跟app视频的规则即可。

**Comment by terrytw** [comment]
你这儿一句太卡，作者增加多少工作量
不太现实哈

就本repo这点量，几十块钱的垃圾软路由应该都可以胜任

**Comment by gentlyxu** [comment]
可能没办法精简，如果你有兴趣，可以挑一下哪些域名，哪些规则属于盒子、电视相关的，我来制作脚本
