### ISSUE TITLE
[误杀]anti-ad-adguard中误拦截ads.privacy.qq.com

### ISSUE THREAD

**Issue by MkQtS** [privacy-protection-tools/anti-AD#546]
域名：ads.privacy.qq.com
发生时间：2022年1月7日
使用的列表： anti-ad-adguard.txt
问题描述：anti-ad-adguard.txt中存在`||ads.privacy.qq.com^`，这个域名是应该加白的。。。

**Comment by gentlyxu** [comment]
在 3efe796281250794cdef6e052633510bd0a06981 中修复了
