### ISSUE TITLE
[新增拦截] 运营商一键获取手机号API

### ISSUE THREAD

**Issue by terrytw** [privacy-protection-tools/anti-AD#547]
cmpassport.com
hmrz.wo.cn
e.189.cn
id6.me
opencloud.wostore.cn
auth.wosms.cn
id.mail.wo.cn

来源：https://softs.im/%E5%B1%8F%E8%94%BD%E8%BF%90%E8%90%A5%E5%95%86%E6%9C%AC%E6%9C%BA%E5%8F%B7%E7%A0%81%E8%87%AA%E5%8A%A8%E7%99%BB%E5%BD%95/

**Comment by mcnk328** [comment]
以及id.189.cn

**Comment by mcnk328** [comment]
e.189.cn不建议屏蔽吧

**Comment by gentlyxu** [comment]
```
cmpassport.com
auth.wosms.cn
e.189.cn
```
这仨都不能屏蔽，官方app登录要用的域名

**Comment by terrytw** [comment]
我都屏蔽了，但是“中国联通”（原联通营业厅）这个联通的官方app还是正常的
其他就不知道了，没有移动的app。电信都是网页登录的，没遇到问题

**Comment by gentlyxu** [comment]
移动和电信的都试试

**Comment by gentlyxu** [comment]
另外你用的屏蔽工具是哪个？

**Comment by terrytw** [comment]
Openwrt 劫持所有53端口流量到
https://github.com/IrineSistiana/mosdns

**Comment by gentlyxu** [comment]
好的。辛苦你的测试，晚些时候我来合并
