### ISSUE TITLE
和讯网站[误杀]

### ISSUE THREAD

**Issue by liuyuan29** [privacy-protection-tools/anti-AD#55]
域名：hexun.com
发生时间：2020年03月10日
使用的列表：https://gitee.com/privacy-protection-tools/anti-ad/raw/master/anti-ad-for-dnsmasq.conf
问题描述：
搞金融的，和讯网站上不了有点麻烦！

**Comment by gentlyxu** [comment]
感谢反馈，现在已经将其主域名移出了黑名单，从上游名单中新增了
```
address=/utrack.hexun.com/
address=/hxsame.hexun.com/
address=/itv.hexun.com/
```
请测试是否有异常
