### ISSUE TITLE
[新增拦截]云闪付广告

### ISSUE THREAD

**Issue by MkQtS** [privacy-protection-tools/anti-AD#552]
域名:`ads.95516.com`
出现场景：使用云闪付App时后台发现的网络请求

**Comment by cxw620** [comment]
ads.95516.com
/^(\S+\.)?ad(s?[\d]+|m|s)?\./$denyallow=nucdn.net|azureedge.net|alibabacorp.com|alibabadns.com
anti-AD
这个应该被拦截了吧

**Comment by MkQtS** [comment]
> ads.95516.com /^(\S+.)?ad(s?[\d]+|m|s)?./$denyallow=nucdn.net|azureedge.net|alibabacorp.com|alibabadns.com anti-AD 这个应该被拦截了吧

`anti-ad-adguard.txt`等列表中没有这样的正则匹配
