### ISSUE TITLE
activity.windows.com (false positive)

### ISSUE THREAD

**Issue by 3xploiton3** [privacy-protection-tools/anti-AD#553]
activity.windows.com

its blocking ms authenticator for backup

https://answers.microsoft.com/en-us/mobiledevices/forum/all/unable-to-backup-microsoft-authenticator-on/4a7ea3ed-eb08-41cd-8c9c-b5a0e29804e3?rtAction=1642216756104&page=1

**Comment by gentlyxu** [comment]
#330

**Comment by gentlyxu** [comment]
You must include whitelists to solve this problem
`https://raw.githubusercontent.com/privacy-protection-tools/dead-horse/master/anti-ad-white-list.txt`
