### ISSUE TITLE
小米云服务PC登录验证[误杀]

### ISSUE THREAD

**Issue by tianiue** [privacy-protection-tools/anti-AD#557]
域名：data.sec.miui.com
发生时间：22年1月18日
使用的列表： /anti-ad-easylist.txt
问题描述：登录到同意协议时无法通过，被阻止。小米云服务PC版1.3.3

**Comment by gentlyxu** [comment]
没有发现 `data.sec.miui.com` 被拦截，可能已经修复

**Comment by gentlyxu** [comment]
`cdn.cnbj1.fds.api.mi-img.com`  #556
