### ISSUE TITLE
[误杀]/^(\\S+\\.)?ad([\\d]|m|s)?\\./

### ISSUE THREAD

**Issue by lukemin** [privacy-protection-tools/anti-AD#56]
域名：https://portal.azure.com/
发生时间：2020年3月13日
使用的列表： https://anti-ad.win/easylist.txt
问题描述：
管理选项无法打开

**Comment by gentlyxu** [comment]
请提供具体被误杀的域名，提供的页面无法确认到底是什么域名误杀

**Comment by lukemin** [comment]
https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/Overview  会提示错误
