### ISSUE TITLE
[误杀] live-trace.bilibili.com b站直播获取免费礼物需要

### ISSUE THREAD

**Issue by zhibisora** [privacy-protection-tools/anti-AD#561]
域名：live-trace.bilibili.com
发生时间：2022/1/20
使用的列表：anti-ad-easylist.txt
问题描述：live-trace.bilibili.com 屏蔽后b站观看直播无法获得小心心，及赠送辣条等道具

该规则阻止  https://live-trace.bilibili.com/xlive/rdata-interface/v1/heartbeat/webHeartBeat 接口获取 web心跳数

web心跳数记录前端观看时长和观看记录，阻止其可能对直播观看历史记录产生影响
同时小心心的获取是每5分钟给予一次，阻止心跳数将会使得后端无法记录时间，从而不能给予小心心

如若认为获取观看时长是获取个人隐私，那么该接口确实应该屏蔽，但确实会影响b站部分功能的使用
希望有一定的讨论

鉴于我在ublock中同时发现该规则，且没有使用anti-AD，该规则可能来源于上游（可能来自 https://github.com/banbendalao/ADgk ）

同时在 #517 中该规则已被提到，但未解决

**Comment by shenzhiming88** [comment]
> 鉴于我在ublock中同时发现该规则

这个我记得在几个月前我就提交PR删除了

https://github.com/uBlockOrigin/uAssets/pull/10611

> 该规则可能来源于上游（已证实来自[ easylist/easylist#9291 ](https://github.com/easylist/easylist/pull/9291#issuecomment-981720429)）

这个PR是我提交的，但是并没有被合并到`EasyList`里面

**Comment by avatartw** [comment]
>该规则可能来源于上游（已证实来自[ easylist/easylist#9291 ](https://github.com/easylist/easylist/pull/9291#issuecomment-981720429)）

规则来自上游 https://github.com/banbendalao/ADgk

**Comment by Karmylr** [comment]
biibili app首页刷新会被影响

**Comment by gentlyxu** [comment]
ok, 已加白
