### ISSUE TITLE
[误杀]iufostworldcongress-singapore.com 被误杀

### ISSUE THREAD

**Issue by hhhkkk520** [privacy-protection-tools/anti-AD#563]
域名：iufostworldcongress-singapore.com
发生时间：2022年1月21日
使用的列表： （https://anti-ad.net/easylist.txt)
问题描述：
Adguard Home 显示拦截规则为:
````
iufostworldcongress-singapore.com
/^(\S+\.)?[0-9a-z\-]{26,}\.(com|net|cn)(\.cn)?$/
CHN: anti-AD
````

**Comment by gentlyxu** [comment]
.......， 竟有如此长的`正经`域名?? 这谁记得住啊..... 好吧，我修复它
