### ISSUE TITLE
[误杀] 微信红包封面

### ISSUE THREAD

**Issue by Steven52065** [privacy-protection-tools/anti-AD#564]
域名：wxs.qq.com
发生时间：2022年1月23日
使用的列表： easylist
问题描述：
使用adgrandhome进行广告过滤，添加了anti-AD的easylist。发现无法加载部分微信红包的封面。经抓包，发现加载部分微信红包封面的图需要wxsnsdy.wxs.qq.com，而anti-AD将wxs.qq.com全部列为了广告。手动放行后封面可以正常加载
另祝各位开发者新年快乐

**Comment by gentlyxu** [comment]
这些相关规则来自上游 https://github.com/jdlingyu/ad-wars/ ，还不清楚加入的原因，以及个人观察：最近的微信红包封面非常多都是品牌的广告

我不能确定是否应该将这些设为白名单
