### ISSUE TITLE
希望能够合并一个新的规则列表

### ISSUE THREAD

**Issue by MysteryMulberry** [privacy-protection-tools/anti-AD#570]
https://gitee.com/halflife/list/issues/I1CV06
这里面的规则不仅仅是整合那么简单，其作者还添加了许多有用的规则，例如当你在百度上查司法考试时 ta的规则能够屏蔽掉侧边广告，同样也能屏蔽必应/贴吧上的相关广告，而这些是anti-ad规则无法做到的~
另外，作者提供了许多版本的过滤规则，个人觉得 其中的https://halflife.coding.net/p/list/d/list/git/raw/master/ad.txt 这个规则的性价比是最高的~

**Comment by terrytw** [comment]
自己给自己点赞可行...
这些规则是用于去广告插件的，一般都是装在浏览器上的
这些插件可以直接访问页面元素，自然可以做到更彻底的去广告
anti-AD是DNS为基础的网关去广告，这些规则是没用的
好比说anti-AD是快递员，他可以决定哪个包裹给你还是不给你，但是他不能拆包裹
去广告插件就好比你妈，她拿到快递之后全拆开，看到少儿不宜的就全给你扔掉了
这两个人的权力是不同的

建议自己关闭issue，这个是完全不可能做到的
