### ISSUE TITLE
[误杀]show.re.taobao.com

### ISSUE THREAD

**Issue by LyntNy4n** [privacy-protection-tools/anti-AD#574]
域名：show.re.taobao.com
发生时间：2022年2月6日
使用的列表：anti-ad-easylist.txt （具体的文件，例如/anti-ad-easylist.txt, /dist/anti-ad-surge-full.txt等等）
问题描述：手机端淘宝 店铺的图片被拦截 adguard home中放行该链接后问题解决

**Comment by gentlyxu** [comment]
是否有重现步骤或重现方法？还有截图

我用手机淘宝，没有发现使用异常或是图片不显示
