### ISSUE TITLE
[新增拦截] 汇报几个在nextDNS中发现的追踪域名

### ISSUE THREAD

**Issue by Mosney** [privacy-protection-tools/anti-AD#58]
### NextDNS Recommended Ads & Trackers Blocklist：
open.oneplus.net
s.youtube.com
api.sec.intl.miui.com
data.sec.intl.miui.com
nexusrules.officeapps.live.com
nexus.officeapps.live.com
p.twitter.com
m2.nsimg.net
*.v.smtcdns.net
m2.nsimg.net

### adaway：
mobile.pipe.aria.microsoft.com

---

另外关于 app.adjust.com 这个域名似乎被广泛应用跳转链接，AdGuardSDNSFilter选择把它加入了白名单，相关链接：https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/186

---
最后，规则列表的顺序可以按照二级域名的字母顺序排列，更加方便查找同一域名下的相关子域。

**Comment by gentlyxu** [comment]
感谢提供。以下域名以添加
```
open.oneplus.net
nexusrules.officeapps.live.com
nexus.officeapps.live.com
p.twitter.com
m2.nsimg.net
mobile.pipe.aria.microsoft.com
```
`sec.*.miui.com`是MIUI安全相关的一批域名
`v.smtcdns.net`是腾讯视频的cdn，鉴于adgh会拦截CNAME解析，所以不能添加此域
`s.youtube.com` 这个域名notracking同学曾专门提议加白，他说市面上大多过滤列表都错了

`app.adjust.com` 已经加了白名单

已经按主域名排序了，相同主域的二级、三级域名等会集中在一起

**Comment by dampier2020** [comment]
gently <notifications@github.com>于2020年3月15日 周日下午5:29写道：

**Comment by Mosney** [comment]
看了一下log，我这 `v.smtcdns.net` 持续被 neoHost 规则拦截，目前没有发现TV端的腾讯视频出现问题，不过这个域名似乎也很少请求解析，只有零星几条昨天的log。

打开ytb点了一圈也没看到有`s.youtube.com`的资源，等以后碰到再看看吧
