### ISSUE TITLE
List without Whitelist

### ISSUE THREAD

**Issue by RicoHeat** [privacy-protection-tools/anti-AD#580]
Hello @gentlyxu .. First I would like to say that I appreciate your dedication to always updating this list.. Even though it's mainly for Chinese sites, your list is excellent all around for the average user.
 
I don't really have an issue.. I would like to just make a request..

Would it be possible to have an additional list for Adguard users but without any @@Whitelist^ entries? It would be greatly appreciated..

Thanks again for your excellent work.. Have a great day! 👍

**Comment by gentlyxu** [comment]
hello, see [this](https://github.com/privacy-protection-tools/dead-horse/blob/master/anti-ad-white-list.txt), may be what you want
