### ISSUE TITLE
[误杀]tracking.miui.com

### ISSUE THREAD

**Issue by KS-OTO** [privacy-protection-tools/anti-AD#582]
域名：http://tracking.miui.com/
发生时间：2022年2月13日
使用的列表：/anti-ad-easylist.txt,
问题描述：
小米有品APP，拦截该域名后将导致搜索功能无法使用、且从订单中前往商品详情页直接404

**Comment by Titlecan** [comment]
确实是误杀，但不知道是不是这个的误伤。
