### ISSUE TITLE
[误杀]e.189.cn

### ISSUE THREAD

**Issue by Funny-T** [privacy-protection-tools/anti-AD#594]
域名：e.189.cn
发生时间：2022年02月26日
使用的列表：anti-ad-easylist.txt
问题描述：该域名承载了电信的许多服务，例如其子域名open.e.189.cn运用于天翼云盘/定向流量等

**Comment by gentlyxu** [comment]
这条规则来自 #547

**Comment by gentlyxu** [comment]
已修复
