### ISSUE TITLE
不必push中间过程文件

### ISSUE THREAD

**Issue by Hubedge** [privacy-protection-tools/anti-AD#595]
这样可以减小repo大小、节约clone需要的时间，让本项目更加环保。如果现在这么做是出于debug的需要或者有其他考虑，也欢迎讨论

实现参考
192703260e007be389bd5be34f3cffa21a0a1977
77d2b977a8c380958e646f8e33608f595b0386c9

成功运行样例见
https://github.com/Hubedge/anti-AD/actions/runs/1906688715

**Comment by gentlyxu** [comment]
谢谢建议。你说的“中间过程文件”，大概是说的origin-files目录下的源文件。
把这些文件提交到版本库，有两方面考虑：
1. 方便找bug，某个源文件有bug，如果源又同时更新了，很难回溯问题；
2. 避免不必要的争议，每个版本的规则文件都能清清楚楚的看到是根据哪些源文件，走了哪些规则生成的；

当然这样做的坏处就是版本库很大

**Comment by Hubedge** [comment]
明白了，谢谢
