### ISSUE TITLE
此条规则会导致 edge.activity.windows.com 被 reject ，从而造成 iOS 端的 Edge 浏览器一直卡在「正在同步设置」的故障，希望能修复

### ISSUE THREAD

**Issue by kongdeqi** [privacy-protection-tools/anti-AD#596]
https://github.com/privacy-protection-tools/anti-AD/blob/b2aa22c912c5860338b86f1b08ab8b270cdc29eb/anti-ad-surge2.txt#L48279

**Comment by gentlyxu** [comment]
https://github.com/privacy-protection-tools/anti-AD/issues/511#issuecomment-1007490280
