### ISSUE TITLE
[误杀]中国移动免流验证接口

### ISSUE THREAD

**Issue by SakuraAkino** [privacy-protection-tools/anti-AD#598]
域名：wap.cmpassport.com
发生时间：2022年3月3日
使用的列表：/anti-ad-easylist.txt
问题描述：此域名为中国移动免流验证接口，拦截会导致免流服务不生效。

**Comment by SakuraAkino** [comment]
https://github.com/privacy-protection-tools/anti-AD/blob/175024601f936b9bd8abe672fddb13ea0644cd68/anti-ad-easylist.txt#L10880

**Comment by gentlyxu** [comment]
啊。。。又是来自 #547 ，当时那兄弟还仔细的测试了一波。这样看来只能忍痛删除了 @terrytw

**Comment by terrytw** [comment]
没事，毕竟当时只是测试了各大运营商的app而已，也不那么全面
项目就是靠大家一起反馈的才不断优化的嘛
