### ISSUE TITLE
https://zq2.leixjun.com/ms/d.js?b=100611!401849!100!1080!170!200&n=1157258&a=11018649]

### ISSUE THREAD

**Issue by xfmly** [privacy-protection-tools/anti-AD#60]
域名:
出现场景：近段时间，云南联通、云南电信宽带流量，访问网易跳转https://zq2.leixjun.com/ms/d.js?b=100611!401849!100!1080!170!200&n=1157258&a=11018649到https://xi9p.com/2019llq_5/mp.xi9p.com/1051.html，诱骗下载App
补充说明：

**Comment by gentlyxu** [comment]
感谢反馈，已经添加到黑名单中，xi9p.com已被Chrome列入诈骗网址了
