### ISSUE TITLE
[误杀]支付宝部分功能受到限制

### ISSUE THREAD

**Issue by BestTimerOne** [privacy-protection-tools/anti-AD#605]
域名：gm.mmstat.com
发生时间：2022年3月22日
使用的列表： /anti-ad-easylist.txt
问题描述：
财富页面里面只能通过这个域名才能正常显示

**Comment by xiaotianvm** [comment]
+1

**Comment by gentlyxu** [comment]
网页还是app？你用的哪个拦截工具？是否有截图可以提供一下？url是什么呢？

我开支付宝刷了很久没有发现问题

**Comment by gentlyxu** [comment]
而且我特地为此登录了一次网页支付宝，仍然没有找到你说的“财富页面”。 app中也只有 “理财”

由此可见，把问题描述清楚，对解决问题有多么大的帮助

**Comment by xiaotianvm** [comment]
随便进入一个财经大V的主页就能发现问题，比如理财页面搜索：群伟伟，进入他的主页你会发现主页的文章被屏蔽了 @gentlyxu

**Comment by pqopq** [comment]
屏蔽这个域名（gm.mmstat.com）会导致网商银行的可用余额打不开@gentlyxu
