### ISSUE TITLE
[误杀] 2mcmg31d.r.us-east-1.awstrack.me

### ISSUE THREAD

**Issue by IIIlllIIllIIIll** [privacy-protection-tools/anti-AD#606]
域名：2mcmg31d.r.us-east-1.awstrack.me
发生时间：2022年03月24日
使用的列表： anti-ad-easylist.txt
问题描述：ubisoft 发送的更改密码邮件使用此域名跳转. 屏蔽后无法更改密码.

**Comment by gentlyxu** [comment]
这类请自行加白。
