### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by tpishere** [privacy-protection-tools/anti-AD#61]
域名：hinet.net suo.im
发生时间：2020年03月17日
使用的列表：anti-ad-for-dnsmasq.conf
问题描述：hinet.net是台湾中华电信网站，且提供流媒体服务，被误杀。
suo.im是chinaz站长之家提供的短链接转换服务域名。

**Comment by gentlyxu** [comment]
感谢反馈，已将两域名加入白名单
