### ISSUE TITLE
建议：去除有关百度云客户端的提速模式的规则

### ISSUE THREAD

**Issue by ssrubsd** [privacy-protection-tools/anti-AD#612]
众所周知，百度云的下载速度在没有会员的情况下几乎等同于没有速度，而开启了提速模式在下载热门资源的时候速度会有极大的改善，建议剔除有关百度云提速模式的规则，不然在开启规则的情况下使用百度云下载一些大文件基本上不可能下得完

**Comment by CalmLong** [comment]
好主意，支持一下
