### ISSUE TITLE
[误杀]无法连接杀戮空间2仓库服务器

### ISSUE THREAD

**Issue by fenghuo0** [privacy-protection-tools/anti-AD#618]
域名：tripwireinteractive.com
发生时间：2022年3-4月
使用的列表： anti-ad-easylist.txt
使用的工具：AdGuard Home
问题描述：拦截此域名 steam杀戮空间2 无法连接仓库服务器

**Comment by gentlyxu** [comment]
没有拦截这个域名。请再次确认一下
