### ISSUE TITLE
[误杀]edge.activity.windows.com

### ISSUE THREAD

**Issue by YY-China** [privacy-protection-tools/anti-AD#619]
域名：**edge.activity.windows.com**
发生时间：2022年4月13日
使用的列表：**https://anti-ad.net/anti-ad-for-dnsmasq.conf**
使用的工具：**dnsmasq**
问题描述：
        微软Edge浏览器的同步服务域名为：edge.activity.windows.com。在Edge浏览器中输入"edge://sync-internals/"可查看同步服务网络连接是否正常。
        如图所示：由于误杀**edge.activity.windows.com**，导致Edge浏览器同步服务网络连接中断！
![msedge_qB9flgdpE3](https://user-images.githubusercontent.com/43245993/163174663-a3d65708-6306-47c3-b277-e7f765f4a942.png)

**Comment by YY-China** [comment]
目前已通过
**server=/edge.activity.windows.com/114.114.114.114**
解决

**Comment by gentlyxu** [comment]
#330 , #349
