### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by xuan880** [privacy-protection-tools/anti-AD#627]
域名：click.mz.simba.taobao.com
发生时间：2022年04月23日
使用的列表： anti-ad-clash.yaml
使用的工具：clash
问题描述：此规则会导致淘宝网主页的猜你喜欢下中的部分商品无法打开.
![Screenshot_20220423_003258](https://user-images.githubusercontent.com/2383369/164756787-0096e413-df88-43c6-85da-cbfa857682d3.png)

**Comment by yikexiaoyao** [comment]
抖音直播间小黄车页面打不开

**Comment by gentlyxu** [comment]
啊，这些本来就是广告追踪，请自行酌情处理
