### ISSUE TITLE
[误杀]  lnk0.com

### ISSUE THREAD

**Issue by ohyeah521** [privacy-protection-tools/anti-AD#634]
域名：lnk0.com
发生时间：20220507
使用的列表：  anti-ad-easylist.txt 
使用的工具： AdGuard Home 
问题描述：

误杀：
lnk0.com
![微信截图_20220507135622](https://user-images.githubusercontent.com/1449374/167240763-6df564f5-f81f-4942-bf7c-2b0798eeb468.png)

**Comment by ohyeah521** [comment]
> 搜了一下这个域名`lnk0.com`是广告追踪的啊。
> 
> ref: https://doc.talkingdata.com/posts/160

这是一个短网址平台而已，可能被坏人利用做广告了，你浏览器里面直接访问 lnk0.com就知道了
上面图中的二维码就是这个平台的短网址跳转

**Comment by gentlyxu** [comment]
啊？？？

你看下我发的地址。然后了解一下TalkingData是什么. `lnk0.com`的所有者是TalkingData。

你发的二维码，看起来是用来追踪app下载安装的

**Comment by ohyeah521** [comment]
> 下我发的地址。然后了解一下Tal

这个二维码是福特官网的下载二维码，要下载福特的app只能通过这个二维码

**Comment by gentlyxu** [comment]
刚好有空，把这个短网址还原了。

你看看这是什么
```
https://www.ford.com.cn/fordpass/get-app/
```

好了，综上，lnk0.com不属于误杀。

**Comment by ohyeah521** [comment]
如果拦截这个域名，那么福特的这个二维码就无法使用了，用户无法下载软件
