### ISSUE TITLE
[误杀]gw5.push.mcp.weibo.cn和gw6.push.mcp.weibo.cn是微博安卓客户端消息通知服务器域名

### ISSUE THREAD

**Issue by CtLl** [privacy-protection-tools/anti-AD#64]
域名：gw5.push.mcp.weibo.cn/gw6.push.mcp.weibo.cn
发生时间：xxx年xx月xx日
使用的列表： （具体的文件，例如/anti-ad-easylist.txt, /dist/anti-ad-surge-full.txt等等）
问题描述：
这2个域名是微博安卓客户端Push网关的域名，如果封禁，客户端会收不到消息通知，包括私信评论等。

**Comment by gentlyxu** [comment]
该规则来自上游。又因推送接口会收集大量隐私信息用于唯一标识设备，属anti-AD重点封杀对象。所以，这不属于误杀，况且推送常常夹带广告，防不胜防。以上种种，请自行斟酌是否放行
