### ISSUE TITLE
[误杀]小米浏览器搜索引擎联想词功能

### ISSUE THREAD

**Issue by catsimple** [privacy-protection-tools/anti-AD#651]
域名：`exp.sug.browser.miui.com`
`ssl-cdn.static.browser.mi-img.com`

发生时间：2022年6月8日
使用的列表： anti-ad-easylist.txt
使用的工具：AdGuard Home
问题描述：拦截上述域名后，在小米浏览器中输入搜索关键词没有相应的联想词出现

**Comment by MkQtS** [comment]
@gentlyxu `ssl-cdn.static.browser.mi-img.com`仍被拦截，这个问题依旧存在
