### ISSUE TITLE
[误杀] zconfig.alibabausercontent.com

### ISSUE THREAD

**Issue by scomper** [privacy-protection-tools/anti-AD#69]
域名： zconfig.alibabausercontent.com
发生时间：2020年03月21日
使用的列表： （具体的文件， /dist/anti-ad-surge-full.txt等等）
问题描述：拦截这个会导致阿里云 app 提示网络中断，无法刷新数据。

**Comment by gentlyxu** [comment]
我也有在使用阿里云app，你反馈的域名确实在屏蔽列表中，打开app也确有这条被屏蔽，但我的使用一切正常，建议你再确认一下。

**Comment by scomper** [comment]
打开不会有问题，是过一段时间这个域名不可访问验证就失效了，提示网络故障。

**Comment by gentlyxu** [comment]
好的。那我加白，你更新过滤列表试试

**Comment by scomper** [comment]
问题可能是阿里 45.116.154.0/22 IP 段使用了非标准 DNS，导致开启 Surge 时访问失败，和域名无关。

**Comment by fernvenue** [comment]
這個問題依然存在, 經過測試在 iPhone 使用 [surge](https://github.com/privacy-protection-tools/anti-AD/blob/master/anti-ad-surge.txt) 列表時如果不單獨放行該域名會導致無法與客服對話, 放行後即可恢覆正常.
