### ISSUE TITLE
[误杀]tdid.m.qq.com

### ISSUE THREAD

**Issue by Auron009** [privacy-protection-tools/anti-AD#691]
域名：tdid.m.qq.com
使用的列表： [anti-ad-for-dnsmasq.conf](https://anti-ad.net/anti-ad-for-dnsmasq.conf)
使用的工具：dns过滤器，adbyby-plus， AdGuardHome
问题描述：QQ安全中心（手机APP）账号无法登陆，tdid.m.qq.com白名单就可以登陆，但adbyby-plus无法添加白名单（有白名单，但无效）。

**Comment by CalmLong** [comment]
我在 iOS 平台测试的没这个问题

**Comment by gentlyxu** [comment]
我下载了iOS版qq安全中心，没有重现你的问题
