### ISSUE TITLE
[误杀]ads.95516.com

### ISSUE THREAD

**Issue by boeing77710x** [privacy-protection-tools/anti-AD#695]
域名：ads.95516.com
发生时间：8.30
使用的列表： (https://anti-ad.net/easylist.txt)
使用的工具：AdGuard Home
问题描述：云闪付APP，右上角切换标准版关爱版被拦截打不开

**Comment by CalmLong** [comment]
我在 iOS 上测试了下，这个域名被拦截的时候并不会出现无法切换关爱版的现象
云闪付版本：9.2.2

**Comment by gentlyxu** [comment]
请将anti-AD规则更新到最新再试。看看 #552

**Comment by CalmLong** [comment]
`anti-ad-domains.txt` 这个列表里还存在

**Comment by gentlyxu** [comment]
修复了
