### ISSUE TITLE
[误杀]mbd.baidu.com

### ISSUE THREAD

**Issue by BurningC4** [privacy-protection-tools/anti-AD#7]
域名：mbd.baidu.com
发生时间：2019年12月28日
使用的列表： adblock-for-dnsmasq.conf
问题描述：mbd.baidu.com是百家号在PC端使用的域名

**Comment by gentlyxu** [comment]
已排除该域名，您更新一下看看

**Comment by snakwu** [comment]
这个列表误杀非常严重，连qq浏览器的书签同步都给杀了

**Comment by gentlyxu** [comment]
> 这个列表误杀非常严重，连qq浏览器的书签同步都给杀了

兄弟能否给点具体信息，比如哪个端的qq浏览器书签不能同步？比如关闭了本屏蔽列表后功能即正常，而开启后即不能同步？

**Comment by snakwu** [comment]
我用adg，只加了你的列表，是pc的qq浏览器，然后我只能手动放行：
@@||stdl.qq.com^$important
@@||wup.imtt.qq.com^$important

**Comment by gentlyxu** [comment]
> 我用adg，只加了你的列表，是pc的qq浏览器，然后我只能手动放行：
> @@||stdl.qq.com^$important
> @@||wup.imtt.qq.com^$important

已经将这两个域名加入白名单，你更新过滤列表试试。如果还有任何问题欢迎继续交流。毕竟靠我一个人是没有办法全面测试的，大家都积极反馈问题的话，anti-AD过滤列表会更准确的。

**Comment by snakwu** [comment]
其实误杀不怪你，不竟大佬们的规则也有误杀，你只是努力的在做整合，优化，所以我在用你的规则之前都是用三两个主流的规则就好了

**Comment by gentlyxu** [comment]
是啊。本项目也很依赖上游规则的精准度，若上游的list存在误杀，在没有设置例外时，误杀规则就会被同步进来。这个我还在思考更好的解决方案

**Comment by kr513268** [comment]
> 是啊。本项目也很依赖上游规则的精准度，若上游的列表存在误杀，在没有设置例外时，误杀规则就会被同步进来。

请教下作者，anti-ad都整合了哪家规则？

**Comment by gentlyxu** [comment]
> 请教下作者，anti-ad都整合了哪家规则？

详细见wiki的常见问题部分
https://github.com/privacy-protection-tools/anti-AD/wiki
