### ISSUE TITLE
强烈建议增加国内app启动页广告拦截.

### ISSUE THREAD

**Issue by dampier2020** [privacy-protection-tools/anti-AD#70]
这个太重要了.特别是百度网盘.京东商城等等.每天每次打开一个app就要等5秒钟啊.每天得浪费多少时间.试过了好多规则都没有用.求大佬解决.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Mosney** [comment]
显然实现难度太大，给你几个方案
1.自己抓URL汇报
2.Android使用启动器创建活动绕过闪屏
3.弃用带闪屏的app

**Comment by garypang13** [comment]
启动页不是Hosts可以拦截的.

**Comment by Leisuredpootle** [comment]
启动页拦截不是dns拦截可以做到的，它仅仅能帮你不加载广告，但不能解除5秒限制

**Comment by YH0426** [comment]
> 启动页拦截不是dns拦截可以做到的，它仅仅能帮你不加载广告，但不能解除5秒限制

有些应用在无法加载广告的情况下会直接跳过启动页广告。

**Comment by mephisX** [comment]
Quantumult X/surge 这些中间人攻击，应该特容易吧。
类似的项目有：https://github.com/eHpo1/Rules
