### ISSUE TITLE
[误杀] geotrust.com 拦截。某些软件无法使用

### ISSUE THREAD

**Issue by muchqs** [privacy-protection-tools/anti-AD#701]
域名：geotrust.com
发生时间：2022-09-15
使用的列表：https://anti-ad.net/easylist.txt
使用的工具：AdGuard Home
问题描述：请问为什么这个域名被黑名单？应该是全球第二大证书签发公司吧。`||geotrust.com^` 拦截了后，Sony Vegas 视频编辑软件无法验证正版授权。试图使用该软件时会报错说 “该电脑没有合法的使用授权”。 把上面这个域名加白后，就没有问题了。
具体的链接为 `cdp.geotrust.com` 和 `status.geotrust.com`

**Comment by MkQtS** [comment]
上游EasyPrivacy拦截的 https://github.com/easylist/easylist/commit/70c6eafa7b2c1e74611f59170fa70f152b8f276f
