### ISSUE TITLE
XiaoHongshu Block List

### ISSUE THREAD

**Issue by xenstar** [privacy-protection-tools/anti-AD#704]
域名:XiaoHongshu

出现场景：
s.xiaohongshu.com
crash.xiaohongshu.com
apppush-sh5.xiaohongshu.com
flash.xiaohongshu.com
referee.xiaohongshu.com
edith.xiaohongshu.com
vi.xiaohongshu.com
v.xiaohongshu.com
ci.xiaohongshu.com
store.xiaohongshu.com
starry.xiaohongshu.com
apppush.xiaohongshu.com
st.todesk.com

Xiaohongshu has a lot of privacy-invading links and after blocking it, still works. I have tested it with Adguard Home. I think you should add to your global list.

**Comment by dfc643** [comment]
should 不合适，应该只是 suggestion
