### ISSUE TITLE
[误杀]天翼认证 id6.me

### ISSUE THREAD

**Issue by dfc643** [privacy-protection-tools/anti-AD#706]
域名：id6.me
发生时间：2022-9-30
使用的列表： adblock-for-dnsmasq.conf, anti-ad-adguard.txt
使用的工具：AdGuard Home, dnsmasq
问题描述：

所有涉及电信天翼账号/一键认证的业务均无法使用。影响范围：电信公众号、电信营业厅、电信小程序、电信客服小程序、翼支付、天翼云盘、天翼云电脑、小翼管家、天翼测速专家、天翼云会议、天翼生活、天翼智慧社区、天翼智慧校园、天翼智慧产业园、等100多天翼业务一键登录或本机验证受影响。

**Comment by dfc643** [comment]
除影响登录外，天翼在线复机功能亦受影响。

**Comment by gentlyxu** [comment]
id6.me这个域名属于 天翼认证，是电信的【本机号码一键登录】服务

这个问题属于值得深入探讨一下的范畴

这个域名主要是屏蔽其他app用到的运营商一键登录。而不是专门屏蔽电信营业厅等运营商服务的登录，因为运营商本身就知道咱们的手机号码。 一键登录无法使用，但短信验证码、微信登录，等方式仍然可以正常使用。

规则来源是 #547 ，也是经过测试的

【本机号码一键登录】这个功能三大运营商都有，理论上可以获取到手机号码，我的观点是这个方便的功能牺牲了部分的隐私，
小米也在miui 13中加入了针对这个一键登录方式的专门隐私防范

**Comment by dfc643** [comment]
的确影响电信业务系统了，因为我天天要用，所以我没办法用这个规则，不只是快捷登录 @gentlyxu

**Comment by dfc643** [comment]
如果硬要区分隐私，建议单独搞个列表，因为不是所有人都在乎隐私
