### ISSUE TITLE
[误杀]edith.xiaohongshu.com会导致小红书无网络

### ISSUE THREAD

**Issue by Vinetan** [privacy-protection-tools/anti-AD#708]
域名：edith.xiaohongshu.com
发生时间：2022年10月03日
使用的列表： https://anti-ad.net/easylist.txt
使用的工具：AdGuardHome Surge
问题描述：拦截edith.xiaohongshu.com会导致小红书无网络

**Comment by Vinetan** [comment]
似乎不是这个域名的问题 等我再测试下

**Comment by xinlhong** [comment]
同样遇到这个问题，麻烦更新下把这个删了

**Comment by gentlyxu** [comment]
已更新。 相关issue #704
