### ISSUE TITLE
[误杀]阿里妈妈淘宝客和PC：QQ-腾讯网迷你版 打不开

### ISSUE THREAD

**Issue by mjyhj** [privacy-protection-tools/anti-AD#710]
域名：alimama.com
发生时间：2022年10月8日
使用的列表： anti-ad-easylist.txt
使用的工具：AdGuard Home
登录不了阿里妈妈，淘宝客转换不了

域名：mini2015.qq.com
发生时间：2022年10月8日
使用的列表： anti-ad-easylist.txt
使用的工具：AdGuard Home
WIN版QQ，顶部的腾讯网迷你版打不开

**Comment by gentlyxu** [comment]
看看好了没有？

**Comment by mjyhj** [comment]
> 看看好了没有？

正常了
