### ISSUE TITLE
[误杀] salon.com

### ISSUE THREAD

**Issue by fouram** [privacy-protection-tools/anti-AD#711]
域名：salon.com
发生时间：2022-10-07 4:33PM EST
使用的列表： anti-ad-easylist.txt
使用的工具：AdGuard Home
问题描述：Salon.com is a news site. If there are trackers they may need to be targeted more specifically. (Sorry, I do not speak Chineese, using Google Translate) Salon.com 是一个新闻网站。如果有跟踪器，则可能需要更具体地定位它们。 （对不起，我不会说中文，使用谷歌翻译）

**Comment by gentlyxu** [comment]
ok, fixed
