### ISSUE TITLE
[新增拦截] 新的过滤规则列表

### ISSUE THREAD

**Issue by code-ZeroOne** [privacy-protection-tools/anti-AD#719]
视频过滤规则：https://github.com/xinggsf/Adblock-Plus-Rule/blob/master/mv.txt
通用过滤规则：https://github.com/xinggsf/Adblock-Plus-Rule/blob/master/rule.txt
如果可以请添加合并，谢谢

**Comment by gentlyxu** [comment]
路过的投票看看，要添加吗？

**Comment by xiaorong61** [comment]
建议先别，最近我 b 站网页视频老打不开，关掉 adguard 的 xinggsf 规则后有所缓解，可能是 xinggsf 有所关系。

**Comment by gentlyxu** [comment]
似乎没有人关心这个，关闭吧
