### ISSUE TITLE
[误杀]误杀OpenPGP的公钥服务器、海盗湾bt站

### ISSUE THREAD

**Issue by tecsar9000** [privacy-protection-tools/anti-AD#720]
域名：keysopenpgporg.report-uri.com thepiratebay.org www.thepiratebay.org
发生时间：2022年10月24日
使用的列表： anti-ad-easylist.txt
使用的工具：AdGuard Home
问题描述：OpenPGP官方的keys.openpgp.org公钥服务器被误杀，海盗湾疑似上游直接把thepiratebay.org这个域名给污染了

**Comment by gentlyxu** [comment]
`keysopenpgporg.report-uri.com` 是什么鬼公钥服务器.... 那`keys.openpgp.org`是谁？

**Comment by tecsar9000** [comment]
这个网址之前我在keys.openpgp.org搜索公钥的时候不主动放行的话无法正常搜索，你可以试试

**Comment by tecsar9000** [comment]
刚刚又试了一次，不加白名单点击搜索无反应，查询记录里出现好几个keysopenpgporg.report-uri.com被拦截提示，我手动添加白名单就好了，不知道这网址是干嘛的，不过之前百度过openpgp官方的一封邮件里提到了这个网址，虽然那里面也没说这网址是干嘛的

**Comment by gentlyxu** [comment]
那你应该在提交issue的时候把问题说清楚，把重现步骤说清楚，以及你放行哪些指定的域名后，问题得到解决。这样我才能验证和更快速的解决问题

看看你一开始的问题描述

> OpenPGP官方的keys.openpgp.org公钥服务器被误杀，海盗湾疑似上游直接把thepiratebay.org这个域名给污染了

我会怎样根据你这些描述来判断到底是什么问题？

**Comment by gentlyxu** [comment]
晚些时候，我再来看看具体是什么情况
