### ISSUE TITLE
[误杀]小红书app push和消息无连接

### ISSUE THREAD

**Issue by humsg** [privacy-protection-tools/anti-AD#721]
域名：apppush.xiaohongshu.com
发生时间：2022年10月22日
使用的列表： anti-ad-domains.txt
使用的工具：pihole
问题描述：小红书push不畅（不能实时收到push）以及消息无法发送和消息(无链接）。无链接这个用pihole暂时排查不出来但怀疑和push有关或和ali有关，不能100%确定。

**Comment by cloverzrg** [comment]
翻了下, 这域名是精准匹配的, 不是通配符的误杀, 这个域名一看就是推送用的, 我理解app推送相关的都不应该封, 他推送的并不全是广告, 还有评论、点赞、聊天消息等, 会影响正常使用
`https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt`
