### ISSUE TITLE
[误杀] pico视频：dig.bdurl.net

### ISSUE THREAD

**Issue by h2y** [privacy-protection-tools/anti-AD#726]
域名：dig.bdurl.net
发生时间：22-11-5
使用的列表： dnsmasq
使用的工具：dnsmasq
问题描述：

pico VR机无法登录、无法正常使用，打日志发现屏蔽了以下域名
![image](https://user-images.githubusercontent.com/12909077/200102027-b0ad2115-0a28-4163-8c08-6a3d6ae642d6.png)

移除dig.bdurl.net 域名后恢复可用

**Comment by gentlyxu** [comment]
已修复
