### ISSUE TITLE
[误杀]支付宝-我的快递\菜鸟页面打不开

### ISSUE THREAD

**Issue by boeing77710x** [privacy-protection-tools/anti-AD#733]
域名：wgo.mmstat.com
发生时间：2022年11月16日
使用的列表：https://anti-ad.net/easylist.txt
使用的工具：AdGuard Home
问题描述：支付宝小程序-我的快递/菜鸟打开白屏，切5G后打开正常

**Comment by boeing77710x** [comment]
域名：@@||s-gm.mmstat.com^$important 也有问题，也会阻拦打开页面

**Comment by gentlyxu** [comment]
已修复，更新规则

**Comment by gentlyxu** [comment]
#730
