### ISSUE TITLE
[误杀] 微信公众号文章下微信头像无法显示

### ISSUE THREAD

**Issue by winduser** [privacy-protection-tools/anti-AD#734]
域名：wx.qlogo.cn
发生时间：2022年11月21日
使用的列表： anti-ad-surge2.txt
使用的工具：Surge
问题描述：拦截wx.qlogo.cn，致使微信公众号文章下微信头像无法显示。

**Comment by gentlyxu** [comment]
据群友反馈已经修复了。应该是上游更新了，请将规则更新到最新再试试看

**Comment by winduser** [comment]
目前看已经没有问题了。谢谢回复。
