### ISSUE TITLE
[误杀] button.like.co

### ISSUE THREAD

**Issue by xlionjuan** [privacy-protection-tools/anti-AD#737]
域名：button.like.co
发生时间：2022/11/28
使用的列表：anti-ad-easylist.txt
使用的工具：AdGuard Home
问题描述：
封鎖了讚賞(LikeCoin)按鈕
該服務介紹：
https://docs.like.co/v/zh/user-guide/civic-liker

**Comment by gentlyxu** [comment]
已加白
