### ISSUE TITLE
新浪网[误杀]

### ISSUE THREAD

**Issue by wzy105** [privacy-protection-tools/anti-AD#738]
域名：ppp.net（极其重要，没有域名基本无法排查误杀，提交了也大概率无法解决你的问题）
发生时间：xxx年xx月xx日
使用的列表： （具体的文件，例如/anti-ad-domains.txt, /anti-ad-easylist.txt等等）
使用的工具：（例如AdGuard Home, dnsmasq, smartDNS,surge等）
问题描述：
https://tech.sina.com.cn/
2022.11.29
anti-ad-smartdns.txt
smartdns
![image](https://user-images.githubusercontent.com/117211092/204504541-85e6d3e7-4f54-49ca-9290-b9d282d7e08d.png)
![屏幕截图 2022-11-29 183543](https://user-images.githubusercontent.com/117211092/204507296-2aeb50c6-9101-464f-a855-6efd5938a7f1.png)

**Comment by gentlyxu** [comment]
提供具体被误杀的域名

**Comment by wzy105** [comment]
> 提供具体被误杀的域名

https://tech.sina.com.cn/

**Comment by xrh0905** [comment]
> > 提供具体被误杀的域名
> 
> https://tech.sina.com.cn/

那不是被误杀的域名 是有问题的域名
实际被误杀的域名是指获取不到的地址
