### ISSUE TITLE
[新增拦截]

### ISSUE THREAD

**Issue by Mosney** [privacy-protection-tools/anti-AD#74]
### https://github.com/badmojr/1Hosts PRO
rlog.video.qq.com
arms-retcode.aliyuncs.com
adash-c.ut.taobao.com
adash.ut.taobao.com
m-adash.ut.taobao.com
c-adash.ut.taobao.com
adse.wsa.ximalaya.com
linkeye.ximalaya.com
f-log-extension.grammarly.io
f-log-mobile-ios.grammarly.io
f-log-at.grammarly.io
flogextension.grammarly.io
xp.apple.com
adse.wsa.ximalaya.com
location.ximalaya.com
dp-discovery-na-ext.amazon.com
unagi-na.amazon.com
stun.services.mozilla.com
gfe.nvidia.com
a2z.com
events.data.microsoft.com
tags.tiqcdn.cn
wl.jd.com
footprints-pa.googleapis.com

### https://github.com/notracking/hosts-blocklists
tl88.net
use.typekit.net
wns.windows.com

### https://github.com/jerryn70/GoodbyeAds
starget.intel.com

**Comment by Mosney** [comment]
再加一个YY频道内广告页
web.yystatic.com

**Comment by gentlyxu** [comment]
感谢提供，晚些时候，再来确认合并
