### ISSUE TITLE
[新增拦截]log.mmstat.com

### ISSUE THREAD

**Issue by 964215963** [privacy-protection-tools/anti-AD#740]
域名:log.mmstat.com
出现场景：大部分的广告或跟踪器（淘宝等）
补充说明：https://github.com/privacy-protection-tools/anti-AD/issues/45
在拦截它后，优酷能正常播放，建议将它撤出白名单

<img width="1280" alt="屏幕截图 2022-12-08 112721" src="https://user-images.githubusercontent.com/102475890/206350288-9a746272-cfb0-4278-b3b2-699a5ba6fa83.png">

<img width="1280" alt="屏幕截图 2022-12-08 112857" src="https://user-images.githubusercontent.com/102475890/206350398-c2029f52-6616-4872-98f6-d6e37ee8c2b1.png">

**Comment by 964215963** [comment]
某个规则可能会导致播放不了，但至少不是这个，但单独拦截它并不影响播放效果。

**Comment by 8764zui** [comment]
拦截这个域名会导致qwen打不开

<img width="1644" height="150" alt="Image" src="https://github.com/user-attachments/assets/79bed57b-c970-432e-8aab-2782ab57f155" />
