### ISSUE TITLE
[误杀]规则 /^(\S+\.)?tongji\./ 误杀酷我音乐PC版音乐搜索没有结果，点专辑数据异常

### ISSUE THREAD

**Issue by qpzr** [privacy-protection-tools/anti-AD#742]
域名：
search.kuwo.cn
响应细节
状态
已拦截
DNS 服务器
202.103.224.68:53(由缓存提供)
耗时
6 毫秒
响应代码
NXDOMAIN
规则
/^(\S+\.)?tongji\./

newlyric.kuwo.cn
响应细节
状态
已拦截
DNS 服务器
202.103.225.68:53(由缓存提供)
耗时
1 毫秒
响应代码
NXDOMAIN
规则
/^(\S+\.)?tongji\./

artistpic.kwcdn.kuwo.cn
响应细节
状态
已拦截
DNS 服务器
202.103.224.68:53
耗时
33 毫秒
响应代码
NXDOMAIN
规则
/^(\S+\.)?tongji\./

tips.kuwo.cn
响应细节
状态
已拦截
DNS 服务器
202.103.225.68:53
耗时
17 毫秒
响应代码
NXDOMAIN
规则
/^(\S+\.)?tongji\./

发生时间：2022年12月15日02:29:24
使用的列表： /anti-ad-easylist.txt
使用的工具：AdGuard Home
问题描述：酷我音乐PC版V9.1.1.8音乐搜索没有结果，点专辑数据异常，播放的歌曲专辑封面图片不显示
--------------------------------------------------------------------------

确认是CNAME触发了 那个规则 大片误杀
<html>
<body>
<h2 class="title" style="box-sizing: border-box; font-family: 微软雅黑; font-weight: 500; line-height: 1.1; color: rgb(51, 51, 51); margin: 60px auto 30px; font-size: 30px; text-align: center; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(245, 245, 245); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">DNS在线解析</h2><div class="row" style="box-sizing: border-box; margin-right: -15px; margin-left: -15px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(245, 245, 245); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="col-md-4 text-right" style="box-sizing: border-box; text-align: right; position: relative; min-height: 1px; padding-right: 15px; padding-left: 15px; float: left; width: 330px; line-height: 35px;">域名：</div><div class="col-md-4" style="box-sizing: border-box; position: relative; min-height: 1px; padding-right: 15px; padding-left: 15px; float: left; width: 330px;"><input name="txtDomain" type="text" id="txtDomain" class="form-control" placeholder="search.kuwo.cn" value="www.baidu.com" style="box-sizing: border-box; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 14px; line-height: 1.42857; font-family: inherit; color: rgb(85, 85, 85); display: block; width: 300px; height: 34px; padding: 6px 12px; background-color: rgb(255, 255, 255); background-image: none; border: 1px solid rgb(204, 204, 204); border-radius: 4px; box-shadow: rgba(0, 0, 0, 0.075) 0px 1px 1px inset; transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;"></div><div class="col-md-4" style="box-sizing: border-box; position: relative; min-height: 1px; padding-right: 15px; padding-left: 15px; float: left; width: 330px;"><input type="button" value="　查　询　" class="btn btn-success" id="btnSearch" style="box-sizing: border-box; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: 1.42857; font-family: inherit; color: rgb(255, 255, 255); display: inline-block; padding: 6px 12px; text-align: center; white-space: nowrap; vertical-align: middle; touch-action: manipulation; cursor: pointer; user-select: none; background-image: none; border: 1px solid rgb(76, 174, 76); border-radius: 4px; background-color: rgb(92, 184, 92); appearance: button;"></div></div><div class="row" style="box-sizing: border-box; margin-right: -15px; margin-left: -15px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(245, 245, 245); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="col-md-4 text-right" style="box-sizing: border-box; text-align: right; position: relative; min-height: 1px; padding-right: 15px; padding-left: 15px; float: left; width: 330px; line-height: 35px;">DNS服务器IP：</div><div class="col-md-4" style="box-sizing: border-box; position: relative; min-height: 1px; padding-right: 15px; padding-left: 15px; float: left; width: 330px;"><input name="txtDns" type="text" id="txtDns" class="form-control" placeholder="如果需要指定DNS服务器IP，请填写此项" style="box-sizing: border-box; margin: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 14px; line-height: 1.42857; font-family: inherit; color: rgb(85, 85, 85); display: block; width: 300px; height: 34px; padding: 6px 12px; background-color: rgb(255, 255, 255); background-image: none; border: 1px solid rgb(204, 204, 204); border-radius: 4px; box-shadow: rgba(0, 0, 0, 0.075) 0px 1px 1px inset; transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;"></div></div><div class="row" style="box-sizing: border-box; margin-right: -15px; margin-left: -15px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(245, 245, 245); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="col-md-4 text-right" style="box-sizing: border-box; text-align: right; position: relative; min-height: 1px; padding-right: 15px; padding-left: 15px; float: left; width: 330px; line-height: 35px;">检测类型：</div><div class="col-md-4" style="box-sizing: border-box; position: relative; min-height: 1px; padding-right: 15px; padding-left: 15px; float: left; width: 330px;"><div class="ctype" style="box-sizing: border-box; line-height: 35px;"><input type="radio" id="radioA" name="ctype" value="A" checked="checked" style="box-sizing: border-box; margin: 4px 0px 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: normal; font-family: inherit; color: inherit; padding: 0px;"><span> </span><label for="radioA" style="box-sizing: border-box; display: inline-block; max-width: 100%; margin-bottom: 5px; font-weight: 500;">A记录</label><span> </span><input type="radio" id="radioCNAME" name="ctype" value="CNAME" style="box-sizing: border-box; margin: 4px 0px 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: normal; font-family: inherit; color: inherit; padding: 0px;"><span> </span><label for="radioCNAME" style="box-sizing: border-box; display: inline-block; max-width: 100%; margin-bottom: 5px; font-weight: 500;">CNAME记录</label></div></div></div>

DNS服务商 | 响应类型 | 响应IP | TTL值 | 赞助商
-- | -- | -- | -- | --
百度公共DNS | CNAME | tongji.koowo.cn. | 300 | -
阿里公共DNS(1) | CNAME | tongji.koowo.cn. | 196 | -
阿里公共DNS(2) | CNAME | tongji.koowo.cn. | 197 | -
DNSPod(腾讯) | CNAME | tongji.koowo.cn. | 300 | -
114 DNS | CNAME | tongji.koowo.cn. | 158 | -
Google Dns | CNAME | tongji.koowo.cn. | 109 | -
Open Dns | CNAME | tongji.koowo.cn. | 300 | -
Dyn DNS | CNAME | tongji.koowo.cn. | 300 | -
Comodo Secure | CNAME | tongji.koowo.cn. | 287 | -
Ultra DNS | CNAME | tongji.koowo.cn. | 289 | -
Dns派 | CNAME | tongji.koowo.cn. | 217 | -
SDNS | - | Timeout Error | - | -

</body>
</html>

**Comment by esme518** [comment]
kbangserver.kuwo.cn 也同样在AdGuard Home被误杀了 应该是排行榜信息

**Comment by qpzr** [comment]
> kbangserver.kuwo.cn 也同样在AdGuard Home被误杀了 应该是排行榜信息
没错也中标了
响应细节
状态
已拦截
DNS 服务器
202.103.224.68:53
耗时
48 毫秒
响应代码
NXDOMAIN
规则
/^(\S+\.)?tongji\./

**Comment by qpzr** [comment]
> kbangserver.kuwo.cn 也同样在AdGuard Home被误杀了 应该是排行榜信息

应该就是因为CNAME触发了那个规则
响应细节
状态
允许项
DNS 服务器
202.103.224.68:53(由缓存提供)
耗时
2 毫秒
响应代码
NOERROR
规则
@@||search.kuwo.cn^$important
自定义过滤器规则
响应
CNAME: tongji.koowo.cn. (ttl=83)
A: 220.181.59.56 (ttl=83)
A: 220.181.59.53 (ttl=83)
A: 220.181.59.54 (ttl=83)
A: 220.181.59.55 (ttl=83)
