### ISSUE TITLE
tracking* rule

### ISSUE THREAD

**Issue by vdias** [privacy-protection-tools/anti-AD#743]
**Rule:** 
_||tracking*.*^_

**Affected domain URL:** 
_https://tracking.alertran.com/?token=XXXXXXXXXX&&uuid=XXXXXXXXXX_

The "tracking.alertran.com" domain is used by Spanish delivery company for tracking package state.

**Comment by dingwen07** [comment]
The rule also blocked:

`trackingshipment.apple.com` and
`trackingshipment.isg-apple.com.akadns.net`

unexpectedly. Which is the domain for Apple device package shipment tracking service.
