### ISSUE TITLE
[误杀]www.oxfordlearnersdictionaries.com 被误杀

### ISSUE THREAD

**Issue by wuairc** [privacy-protection-tools/anti-AD#744]
域名：www.oxfordlearnersdictionaries.com
发生时间：2022年12月19日
使用的列表： （https://anti-ad.net/easylist.txt)
问题描述：
Adguard Home 显示拦截规则为:

```
/^(\S+\.)?[0-9a-z\-]{26,}\.(com|net|cn)(\.cn)?$/
```

这条规则的其他误杀： #563, #648 ，似乎外国人能接受完整单词拼写的域名，这个规则杀伤范围太大了

**Comment by gentlyxu** [comment]
这个规则确实有不妥之处，还是删除掉吧
