### ISSUE TITLE
Adguard专用规则不会自动更新

### ISSUE THREAD

**Issue by OliverChristian** [privacy-protection-tools/anti-AD#747]
发生时间：2022年12月29日
使用的列表：https://anti-ad.net/adguard.txt
使用的工具：Adguard 7.11.3
问题描述：adguard.txt 导入 Adguard 之后，后续检查过滤器更新的时候，其他过滤器规则可以正常更新，但anti-Ad的规则（Adguard专用规则）不会更新到最新版本，想知道是Adguard的问题，还是 adguard.txt 规则出现了不适配的问题？

**Comment by gentlyxu** [comment]
列表是有自动更新的最新版本是 `!Version: 20230104183756052795312`

工具不会自动更新，请检查工具

**Comment by avatartw** [comment]
Adguard、uBlock Origin、Adblock Plus会根据列表里面设置的Expires时间自动更新。
没有设Expires的列表uBlock Origin是每7天更新一次，Adguard可能也是。
https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/filters.txt
! Expires: 4 days

**Comment by gentlyxu** [comment]
ok，那咱们也加上
