### ISSUE TITLE
请问 adguard dns filter 和 anti-ad 要同时开吗？

### ISSUE THREAD

**Issue by xiaorong61** [privacy-protection-tools/anti-AD#748]
![image](https://user-images.githubusercontent.com/5251387/210124528-41faad3f-1911-49ac-a56a-9d8cdd53a571.png)

**Comment by gentlyxu** [comment]
不太建议同时开，可以参考这个 https://github.com/privacy-protection-tools/anti-AD/pull/526

重复的部分，anti-AD已经包含了
