### ISSUE TITLE
[误杀] analytics.twitter.com 被屏蔽后无法跳转

### ISSUE THREAD

**Issue by dingdangnao** [privacy-protection-tools/anti-AD#751]
域名：analytics.twitter.com
使用的列表： anti-ad-surge2.txt
使用的工具：surge
问题描述：地址被屏蔽后，在twitter中跳转时会卡在analytics.twitter.com 无法跳转到下一步链接，是否可以考虑把它放出来？

**Comment by terrytw** [comment]
手机和电脑浏览器都无法复现
