### ISSUE TITLE
[误杀]百度翻译网页版右侧翻译结果输出文本框被屏蔽

### ISSUE THREAD

**Issue by sjh057573** [privacy-protection-tools/anti-AD#773]
域名：https://fanyi.baidu.com/
发生时间：2023年3月17日
使用的列表：https://anti-ad.net/adguard.txt
使用的工具：adguard for windows
问题描述：
<img width="960" alt="屏幕截图 2023-03-17 180949" src="https://user-images.githubusercontent.com/73327333/225875844-03c0a226-3ad2-4038-8ef7-ab86c02a3a0b.png">

**Comment by terrytw** [comment]
无法复现
![image](https://user-images.githubusercontent.com/24227628/227697984-d5260be7-ccac-479d-9481-abd11ba28ce2.png)
