### ISSUE TITLE
[误杀]amdc.m.taobao.com

### ISSUE THREAD

**Issue by ghost** [privacy-protection-tools/anti-AD#778]
域名：amdc.m.taobao.com
发生时间：2023 年 03 月 31 日
使用的列表： /surge.txt
使用的工具：Loon/Quantumul X
问题描述：此域名拦截后会导致阿里系的应用，例如，重新安装淘宝之后，天猫超市，打开商品购买按钮，加入购物车按钮都不见了。

**Comment by ihciah** [comment]
+1。adguardhome 下开启该规则后盒马无法正常使用。

**Comment by lxm9357** [comment]
adguardhome 盒马无法正常使用+1。两台iPhone连入同一网络，一台盒马不正常，但另一台正常；不屏蔽该域名后两台就都正常了，很诡异。。

**Comment by kid-oh** [comment]
这个还会导致闲鱼连不上网络

**Comment by sususu98** [comment]
![image](https://user-images.githubusercontent.com/33882693/235453277-c7ef9f18-df43-4a2c-83a8-6635f04a467b.png)
![image](https://user-images.githubusercontent.com/33882693/235453279-9c9ca0d2-09f1-4629-93de-e83f715646de.png)
今日更新后还有类似问题，我目前盒马无法正常访问
