### ISSUE TITLE
[新增拦截]一些常见APP的广告，建议增加

### ISSUE THREAD

**Issue by wchqybs** [privacy-protection-tools/anti-AD#79]
域名列表：https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/BanProgramAD.list
出现场景：常见手机软件和ROM广告

**Comment by gentlyxu** [comment]
感谢建议，晚些时候我对比一下和anti-ad的重合度再决定

**Comment by gentlyxu** [comment]
加上了，增加了接近300条新屏蔽规则，自测没有发现问题

**Comment by huosenlin** [comment]
我测试了，没有优酷/腾讯的去广告。建议加上

**Comment by gentlyxu** [comment]
> 我测试了，没有优酷/腾讯的去广告。建议加上

哪个列表可以，你发我参考一下，我就能加上
