### ISSUE TITLE
[新增拦截] httpdns.gslb.yy.com

### ISSUE THREAD

**Issue by Mosney** [privacy-protection-tools/anti-AD#80]
YY开始使用 `httpdns.gslb.yy.com` 来查询DNS，会导致一切广告屏蔽域名失效
![image](https://user-images.githubusercontent.com/22477230/77542840-c761e500-6ee1-11ea-8a86-ec330f6b6764.png)

**Comment by Mosney** [comment]
以下是PC版YY客户端通过抓包得出的非必要域名以及部分出现URL，屏蔽后经过测试不影响YY核心语音功能使用。因为我用的YY本身就是绿色精简版，所以可能不全面。
```
yydl.duowan.com
apipubless.yy.com
clientad.yy.com
pcyy.yy.com
res.cont.yy.com
eggcenter.game.yy.com
gtips.game.yy.com
httpdns.gslb.yy.com
pm.honor.yy.com

```
http://res.cont.yy.com/json/pcyy/imSearchTips.json?
http://eggcenter.game.yy.com/flashLogoInfo/getFlashLogoInfo.do
http://gtips.game.yy.com/tipsConf/getTipsInfo.do
http://pcyy.yy.com/switch/cache/white/44577368/2708729204
http://pm.honor.yy.com/personmedal/getPersonMedalForPCYY?
http://res.cont.yy.com/json/pcyy/imSearchTips.json?

**Comment by gentlyxu** [comment]
httpdns 通常是用来对付运营商劫持，和细化网络调度的。在没有确凿证据证明其恶意之前，不能轻易封杀，此issue先关闭哈
