### ISSUE TITLE
[误杀]Your domains list causes photos broken which are inserted on GitHub when enabling DNS filtering in AG for Android.

### ISSUE THREAD

**Issue by lancelot-moon** [privacy-protection-tools/anti-AD#81]
Your **domains list** causes photos broken which are inserted on GitHub when **enabling DNS filtering in AG for Android**.
I tested on Android.
**Clear cache before the test.**
ex: Photos were broken on GitHub:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/8qyDC0o.jpg)
</details><br/>

No problem on PC.
(I also subscribed to your domains list in my router for DNS filtering.)

I tried your other formats list, ex: basic rule syntax, which is no problem.
https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt

The problem is only with your **domains list**.
https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt

Maybe something wrong between your domains list and AG for Android.

**Comment by lancelot-moon** [comment]
After checking, AG for iOS v4 beta with anti-AD domains list also has the problem of broken photos on GitHub.
With anti-AD basic rule syntax list, no problem.

**Comment by gentlyxu** [comment]
can you please provide some log about this problem?

**Comment by Leisuredpootle** [comment]
collector.githubapp.com
测试了一下，似乎是这个域名，但中国屏蔽了部分raw.githubusercontent.com的ip，无法完全确定

> can you please provide some log about this problem?

**Comment by lancelot-moon** [comment]
The now logic for only domain list in AG for Android/iOS causes the incorrect blocking.
githubusercontent.com is wrongly blocked by the domain rule, ntent.com, even if they're different domains.
I think AG team will redesign it.
https://github.com/AdguardTeam/DnsLibs/issues/66#issuecomment-605156082

It's not your domain list's problem.

**Comment by gentlyxu** [comment]
> 
> 
> collector.githubapp.com
> 
> 测试了一下，似乎是这个域名，但中国屏蔽了部分raw.githubusercontent.com的ip，无法完全确定
> 
> 
> 
> > can you please provide some log about this problem?
> 
> 
> 
> 

@Leisuredpootle 谢谢你的帮忙，现在问题清晰了，我也查了你提供的域名并不在屏蔽列表。

这个bug需要adguard官方去修复了
