### ISSUE TITLE
[探讨]smartdns下，加载过滤列表后，微信连接非常慢

### ISSUE THREAD

**Issue by Licolnlee** [privacy-protection-tools/anti-AD#82]
域名：ppp.net
发生时间：xxx年xx月xx日
使用的列表：anti-ad-smartdns.conf （具体的文件，例如/anti-ad-easylist.txt, /dist/anti-ad-surge-full.txt等等）
问题描述：iOS端WeChat无法正常解析或者解析速度很慢，没用配置文件之前不存在这个问题，用了之后出现iOS端WeChat加载过慢的问题，希望能够予以修正。谢谢。

**Comment by gentlyxu** [comment]
需要更详细的描述

**Comment by Leisuredpootle** [comment]
是否使用了dns over https/tls ，如果使用了请使用普通的dns，国内的网络环境使用https/tls会很慢

**Comment by Licolnlee** [comment]
> 需要更详细的描述。速度慢根本不是屏蔽列表的问题。打不开，具体是什么域名被屏蔽？现象虽然是开启屏蔽就微信有问题，是否排除了smartdns的配置问题？ btw：smart dns的配置非常复杂，并不适合新手使用

屏蔽名单3w多个域名，数目太多一个人很难确定。smdrtdns我暂时使用的是udp模式添加运营商和公共dns，原来打开没有超出异常的延迟，我是将smartdns专用的复制放入它内置的屏蔽列表中，放入后只有wechat会出现异常延迟或者解析失败，其他软件屏蔽效果正常。（我是老用户了，自己也是程序员，基本操作我还是会的…

**Comment by gentlyxu** [comment]
太好了。那debug一下了，smartdns有日志的，如果路由器上不方便操作，可以试试弄个Linux搭一个，然后追踪一下具体哪里卡住，或者哪个规则导致慢的，期待你的回复

**Comment by Licolnlee** [comment]
> 太好了。那debug一下了，smartdns有日志的，如果路由器上不方便操作，可以试试弄个Linux搭一个，然后追踪一下具体哪里卡住，或者哪个规则导致慢的，期待你的回复

测试了一下，好像是c.wechat.jx.cn这个域名造成的解析超时问题，我把这条注释了暂时用下来解析正常了。

**Comment by gentlyxu** [comment]
不太像。我们家一直都有用微信（你说都wechat是指的微信吧？），但我的dns服务器上从未出现过这个域名

**Comment by Licolnlee** [comment]
> 不太像。我们家一直都有用微信（你说的wechat是指的微信吧？），但我的dns服务器上从未出现过这个域名

貌似找到解决方案了...我的系统语言是英语，所以请求的是微信海外服务器，换成中文简体或者中文繁体请求国内的服务器就没问题了...
