### ISSUE TITLE
[误杀]zh.wikipediay

### ISSUE THREAD

**Issue by EarOfWheat** [privacy-protection-tools/anti-AD#840]
域名：https://zh.wikipedia.org/wiki/Wikipedia:%E9%A6%96%E9%A1%B5ppp.net
发生时间：2023年10月1日
使用的列表： https://anti-ad.net/adguard.txt
使用的工具：uBlock Origin 1.52.2
问题描述：
![image](https://github.com/privacy-protection-tools/anti-AD/assets/74401501/8d316c75-da0d-4c38-83d2-549a1730463b)

**Comment by terrytw** [comment]
你怎么会把anti-ad放到ublock里去用，肯定不正常啊
这个是dns的方案，放dnsmasq或者pihole里去
