### ISSUE TITLE
[新增拦截]请求能否整合这个adgk规则

### ISSUE THREAD

**Issue by kr513268** [privacy-protection-tools/anti-AD#85]
域名:https://gitee.com/banbendalao/adguard/raw/master/ADgk.txt
出现场景：手机
补充说明：规则用于过滤手机上软件的广告，过滤效果挺不错的

**Comment by gentlyxu** [comment]
好的，感谢提供，晚些时候我对比一下差异和验证误杀率

**Comment by kr513268** [comment]
> 好的，感谢提供，晚些时候我对比一下差异和验证误杀率

麻烦了

**Comment by gentlyxu** [comment]
https://gitee.com/banbendalao/adguard/raw/master/ADgk.txt ，这个列表加入了，测试有一定误杀，先跑一段时间看看

**Comment by kr513268** [comment]
> https://gitee.com/banbendalao/adguard/raw/master/ADgk.txt ，这个列表加入了，测试有一定误杀，先跑一段时间看看

好的，感谢
