### ISSUE TITLE
[误杀]

### ISSUE THREAD

**Issue by snakwu** [privacy-protection-tools/anti-AD#9]
域名：ppp.net
发生时间：xxx年xx月xx日
使用的列表： （具体的文件，例如/anti-ad-easylist.txt, /dist/anti-ad-surge-full.txt等等）
问题描述：
lapi.jd.com

**Comment by l123456789jy** [comment]
域名：cd.bendibao.com
发生时间：2020年1月3日
使用的列表： anti-ad-easylist.txt
问题描述：
本地宝误杀，
http://cd.bendibao.com/live/2017127/94420.shtm

**Comment by gentlyxu** [comment]
> 域名：cd.bendibao.com
> 发生时间：2020年1月3日
> 使用的列表： anti-ad-easylist.txt
> 问题描述：
> 本地宝误杀，
> http://cd.bendibao.com/live/2017127/94420.shtm

已删除该域名，请更新一下列表

**Comment by gentlyxu** [comment]
> lapi.jd.com

该域名并不在屏蔽列表中
