### ISSUE TITLE
爱奇艺投屏出问题

### ISSUE THREAD

**Issue by xyzcheese** [privacy-protection-tools/anti-AD#93]
域名：iqiyi
发生时间：2020年4月8日
使用的列表： adblock-for-dnsmasq.conf
问题描述：

我是用于路由器上的dnsmasq，固件是老毛子padavan。投屏是通过机顶盒中乐播app实现的。今天发现ipad爱奇艺HD投屏电视不成功，不过在ipad上看爱奇艺的视频没问题，很流畅也无广告。

点击投屏后，电视显示连接速度很低，就是10K左右，然后一会儿提示网络可能有问题之类的，接着投屏中断。反复多次，选择了多部电视剧和动漫，皆是如此。

其后测试用腾讯视频app投屏成功。这说明可能是爱奇艺被误杀过滤了。

一直都没问题，就今天发现有问题。不知别人是不是也这样。

**Comment by gentlyxu** [comment]
具体定位一下问题再继续吧，这段描述，无法确定到底是什么引起的。并且不能确定是否某个域名误杀导致的现象

**Comment by gentlyxu** [comment]
你试试删除 msg.video.qiyi.com这条规则，看看投屏是否正常

**Comment by xyzcheese** [comment]
> 
> 
> 你试试删除 msg.video.qiyi.com这条规则，看看投屏是否正常

这个我试了好像不行。这条规则应该不影响。

不过我过滤视频广告的规则还有一个来源https://dev.tencent.com/u/shaoxia1991/p/yhosts/git/blob/master/data/tvbox.txt，这个过滤爱奇艺没问题。（好像不能下载，不过好久未更新，我自己把tvbox.txt放到gitee上了方便下载）

我现在是路由器开启联网后，先自动下载adblock-for-dnsmasq.conf后执行命令删除有“iqiyi”字符串的所有行，然后继续下载tvbox.txt后执行命令转换成dnsmasq格式，两者再合并。测试正常。这几天都是这样弄的。

就先这样用了。

**Comment by gentlyxu** [comment]
群里有人反馈是`data.video.iqiyi.com` ，我已经加白名单了

**Comment by gentlyxu** [comment]
兄弟再看看问题解决了么

**Comment by hellkun** [comment]
我今天也遇到了类似的情况，但似乎不只是爱奇艺 会有问题。
在手机上尝试使用B站、百度云、爱奇艺投屏，都是只是十几KB/s的速度，关掉去广告服务后立刻就好了。
我这边的环境是openwrt+adbyby，订阅了大佬的dnsmasq规则

**Comment by gentlyxu** [comment]
> 我今天也遇到了类似的情况，但似乎不只是爱奇艺 会有问题。
> 在手机上尝试使用B站、百度云、爱奇艺投屏，都是只是十几KB/s的速度，关掉去广告服务后立刻就好了。
> 我这边的环境是openwrt+adbyby，订阅了大佬的dnsmasq规则

还需要更细致的排查，建议通过日志追踪一下到底是什么域名导致的
