### ISSUE TITLE
Surge 加载 anti-ad-surge.txt 之后频繁重连

### ISSUE THREAD

**Issue by luzhaohui** [privacy-protection-tools/anti-AD#94]
按这个格式加载 anti-ad-surge.txt 之后，Surge for iOS 就频繁重连，是方法不对吗？还是这个规则集太过庞大了？
RULE-SET,https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt,REJECT

**Comment by gentlyxu** [comment]
有可能的，有新的进展吗？

**Comment by luzhaohui** [comment]
> 有可能的，有新的进展吗？

我现在是把 REJECT 改成 REJECT-TINYGIF ，貌似有点改善，还在观察。

**Comment by luzhaohui** [comment]
Surge for iOS 的常见问题里面有一则[关于内存超限的文章](https://nssurge.zendesk.com/hc/zh-cn/articles/900000310366-Surge-iOS-版本内存超限问题的说明)，应该是因为 Anti-AD 的规则集太大了，导致内存超限。
我自己观察，将 REJECT 改成 REJECT-TINYGIF 可以大幅降低 Surge for iOS 重启的概率。

**Comment by luzhaohui** [comment]
经过长时间的跟踪，我想应该是找到问题所在了，根本原因与 Anti-AD 无关，而是由于某个脚本造成的，但 Anti-AD 的规则集太大，还是建议用 REJECT-TINYGIF 进行拦截。
