### ISSUE TITLE
误杀msg.video.qiyi.com

### ISSUE THREAD

**Issue by snakwu** [privacy-protection-tools/anti-AD#95]
msg.video.qiyi.com这个域名栏截后，引起英伟达安桌盒子的wifi状态显示为已连接，不能访问互联网

**Comment by gentlyxu** [comment]
这不科学。你的盒子是爱奇艺的系统吗？

**Comment by snakwu** [comment]
> 这不科学。你的盒子是爱奇艺的系统吗？况且是否能联网通常也是以IP检测为准的，啥时候靠域名了？

英伟达的盒子是和爱奇合作的，我只要在adg自定义规则里加上，@@||msg.video.qiyi.com^$important
网络状态就正常了，要不是显示网络已连接，无法访问互联网！！

**Comment by gentlyxu** [comment]
msg.video.qiyi.com 这个域名在多个上游源中均存在。而且就我自己的使用中也没有发现副作用。如果只是**提示**无法访问互联网，实际上一切正常的话，建议忽略盒子的提示

**Comment by snakwu** [comment]
> msg.video.qiyi.com 这个域名在多个上游源中均存在。而且就我自己的使用中也没有发现副作用。如果只是**提示**无法访问互联网，实际上一切正常的话，建议忽略盒子的提示

使用是正常使用,就怕有些未知副作用!

**Comment by gentlyxu** [comment]
你担心的什么样的副作用？

**Comment by snakwu** [comment]
> 你担心的什么样的副作用？

也没啥,能解决最好,不能也就用着再说!

**Comment by gentlyxu** [comment]
你不是解决了么？这条规则目前来看，官方不需要加白处理

通过 Outlook<https://aka.ms/qtex0l> for iOS
________________________________
发件人: SnakWu <notifications@github.com>
发送时间: Thursday, April 9, 2020 11:42:46 PM
收件人: privacy-protection-tools/anti-AD <anti-AD@noreply.github.com>
抄送: gently <gently@live.cn>; Comment <comment@noreply.github.com>
主题: Re: [privacy-protection-tools/anti-AD] 误杀msg.video.qiyi.com (#95)


你担心的什么样的副作用？

也没啥,能解决最好,不能也就用着再说!

―

**Comment by gentlyxu** [comment]
你不是解决了么？这条规则目前来看，官方不需要加白处理

**Comment by snakwu** [comment]
> 你不是解决了么？这条规则目前来看，官方不需要加白处理

好吧!你关了这个问题吧,谢谢了!
