### ISSUE TITLE
[误杀] 关于xyz域名的封禁规则

### ISSUE THREAD

**Issue by Zy143L** [privacy-protection-tools/anti-AD#980]
### 注意事项

- [X] 我做了简单验证，确定问题由 anti-AD 列表造成
- [X] 我近期更新过 anti-AD 列表，当前版本仍存在问题
- [X] 我将提供清晰明确的问题描述

### 使用的规则

anti-ad-easylist.txt

### 使用的拦截工具

AdGuardHome

### 误杀域名

/^(\S+\.)?[0-9a-z]{16,}\.xyz$/ AntiAD

### 问题描述

/^(\S+\.)?[0-9a-z]{16,}\.xyz$/
为什么要用一个这种16位的通杀匹配规则来限制xyz域名

**Comment by Zy143L** [comment]
> 你好，朋友。 这个通杀规则是根据上游规则，为了将非常多条规则，总结成一条规则，这个`{16,}`是16位以上的字符

我知道这个匹配 但是你是过滤广告的规则 我认为没必要跟进这个拦截方案吧..
因为我恰好有个tracker服务器符合这个拦截..然后被ban了

**Comment by Linho1219** [comment]
啊，不是哥们，你都说了是 tracker 了不该被 ban
吗🤔

**Comment by Zy143L** [comment]
> 啊，不是哥们，你都说了是 tracker 了不该被 ban 吗🤔

这个tracker是bt的tracker的啊

**Comment by Linho1219** [comment]
> > 啊，不是哥们，你都说了是 tracker 了不该被 ban 吗🤔
> 
> 这个tracker是bt的tracker的啊

当我没说（

**Comment by Zy143L** [comment]
> > > 你好，朋友。 这个通杀规则是根据上游规则，为了将非常多条规则，总结成一条规则，这个`{16,}`是16位以上的字符
> > 
> > 
> > 我知道这个匹配 但是你是过滤广告的规则 我认为没必要跟进这个拦截方案吧.. 因为我恰好有个tracker服务器符合这个拦截..然后被ban了
> 
> 让我来捋一下，因为这个规则ban了你的一个tracker，你就认为这个规则没有存在的必要。你说你_知道这个匹配_，那为了将几十条规则缩短为一条正则表达式，到你这里就只是轻飘飘的觉得没有必要？而这些只是为了解决“我恰好有个tracker服务器符合这个拦截..然后被ban了”，我的大量的不容易的正则编写、测试、总结工作，就这样被你否定了，且你完全不懂这条规则隐性的帮助我们屏蔽了多少潜在垃圾域名

首先很感激你的付出工作 其次这个正则刚好对应了一个用到的tracker服务器也是事实 而且也说道是跟进上游匹配规则 而且我也并没有认为这是轻飘飘毫无必要的 只是询问这个原因 因为更看重的这是一个广告过滤规则 而不是防范互联网未知垃圾域名

**Comment by Zy143L** [comment]
没啥可说的了.. 无意冒犯您了 抱歉!
